### ISSUE TITLE
AzureMachinePool nodes fail to join cluster after 15 mins

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1000]
/kind bug

**What steps did you take and what happened:**
Change the `MachinePool` K8s version, scale up, or scale down after infrastructure has been ready for 15 mins. The nodes of the `AzureMachinePool` do not successfully join the cluster. The `AzureMachinePool` stays stuck in `ProvisioningState = Updating`.

**What did you expect to happen:**
The nodes of the `AzureMachinePool` to join the cluster successfully.

**Anything else you would like to add:**
related: 
- https://github.com/kubernetes-sigs/cluster-api/issues/3359
- #983

**Comment by CecileRobertMichon** [comment]
/close

this will be fixed in CAPI v0.3.12
