### ISSUE TITLE
Azure Generation 2 VM support

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes-sigs/cluster-api-provider-azure#1003]
/kind feature

**Describe the solution you'd like**
CAPZ should enable me to create clusters with [Azure Generation 2 VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2).

**Anything else you would like to add:**
I can't think of a use case where mixed gen 1 and gen 2 VMs are needed

**Comment by craiglpeters** [comment]
This may require changes to packer

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/422

also requires checking the VM size supports gen2 

It would be nice if we could attempt to default gen2 over gen1 when possible similar to https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1012#discussion_r513845559 but doing so has all the current caveats about webhook vs. controller context.

**Comment by alexeldeib** [comment]
@CecileRobertMichon what is left to close this? An example maybe once we publish official gen2 images for the next k8s patch version?

**Comment by nader-ziada** [comment]
> @CecileRobertMichon what is left to close this? An example/docs maybe once we publish official gen2 images for the next k8s patch version?

I can work on this work if you don't have time @alexeldeib 

I think we still have to check if the machine size supports Gen2 and set that when creating the VM like you mentioned in the comment above

**Comment by alexeldeib** [comment]
oops, go for it! I finished the image builder changes but totally forgot we didn't already have the capability check. 

/unassign

**Comment by nader-ziada** [comment]
thanks, will submit a PR soon

/assign

**Comment by invidian** [comment]
Perhaps it would make sense to close this issue and create a new one for migrating GPU tests?

**Comment by CecileRobertMichon** [comment]
/reopen 
/remove-lifecycle rotten

@mboersma @willie-yao are we currently publishing gen 2 images or still gen 1? If not is the only remaining item to switch the GPU SKU?

**Comment by mboersma** [comment]
@CecileRobertMichon we are not yet publishing Gen2 images, but IDK specifically what the hitch is (if there is any). We would need to make small changes to the image-builder scripts, since `-gen1` is effectively hard-coded right now.

**Comment by mboersma** [comment]
Re-reading this thread, it would appear that switching GPU SKUs is the only known blocker, besides adjusting the publishing scripts.

**Comment by mboersma** [comment]
/close

This issue as stated is incorrect–gen2 Azure images will work fine in CAPZ, although we currently publish reference images only in gen1 format.
