### ISSUE TITLE
controller should not try to recreate VM if removed from azure api

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1008]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Cluster successfully deployed and running
- Virtual machine is deleted from the azure api (without deleting the related disk)
- controller tries to recreate the machine but fails because os disk already exists
```
controller.go:248] controller-runtime/controller “msg”=“Reconciler error” “error”=“failed to reconcile AzureMachine: failed to create virtual machine: failed to create VM cluster1-md-0-j6kjq in resource group cluster1: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\u003cnil\u003e Code=\“ConflictingUserInput\” Message=\“Disk cluster1-md-0-j6kjq_OSDisk already exists in resource group cluster1. Only CreateOption.Attach is supported.\” Target=\“/subscriptions/xxxxxx/resourceGroups/cluster1/providers/Microsoft.Compute/disks/cluster1-md-0-j6kjq_OSDisk\“” “controller”=“azuremachine” “name”=“cluster1-md-0-j6kjq” “namespace”=“default”
```

**What did you expect to happen:**
- Machine to get status of `Failed` and not try to recreate

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- if machine is deleted using `kubectl delete machine` azure machine will get recreated fine
- if azuremachine is deleted using `kubectl delete azuremachine` the machine will be marked as `failed` and no further action will happen

context in slack thread here: https://kubernetes.slack.com/archives/CEX9HENG7/p1603375311114600 

**Environment:**

- cluster-api-provider-azure version: v0.4.9
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Sort of related: at some point we need to remove the logic that deletes a VM if it's in failed state: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azuremachine_controller.go#L286 in favor of MachineHealthChecks (we kept it around to wait for KCP remediation).
