### ISSUE TITLE
Transient vs terminal error reconcile requeue

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1014]
/kind feature

**Describe the solution you'd like**
There are occasions within the controller when we don't want to retry an error because the error can not be resolved by a subsequent reconcile. One example is https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1012#issuecomment-718152814.

As described in the comment, we should return back to the controller a error which could inform the controller to retry or to just ignore the error.

**Anything else you would like to add:**
This error behavior could be useful for implementing asynchronous controllers. Asynchronous controllers don't wait for all of the resource to be built in Azure, but rather update the state of the K8s resources and then requeue the resource to continue processing at some later time when the controller expects Azure to have reached a terminal state with the resources the controller asked Azure to build.

**Comment by shysank** [comment]
@devigned I just took a look at this one. Just wanted to confirm the approach before proceeding. I'm thinking of something like this: 
```
type TerminalError error

func (r *AzureMachineReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error) {
...

ams := newAzureMachineService(machineScope, clusterScope)

	if err := ams.Reconcile(ctx); err != nil {
		if terr, ok := err.(TerminalError); ok {
			//log error
			//record event
			return reconcile.Result{}, nil
		}else{
			//proceed with the existing flow
		}
	}
...

}
``` 

wdyt?

**Comment by shysank** [comment]
Following discussions in [this](https://kubernetes.slack.com/archives/C8TSNPY4T/p1605026393254100) slack thread, should we scope this issue to only prevent re-queueing in case of terminal error, and create a separate one for handling conditions while the proposal is being finalized? @CecileRobertMichon @devigned @alexeldeib
