### ISSUE TITLE
Accelerated networking test should handle VMSS instances

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#1015]
/kind bug

**What steps did you take and what happened:**

The test spec in test/e2e/azure_accelnet.go only loops over VMs in the resource group, so it's not testing the accelerated networking property of any VMSS / MachinePool clusters. It should be expanded and added to cover the VMSS spec that's now in azure_test.go.

**What did you expect to happen:**

e2e tests validate the accelerated networking property on VMSS instances is set as expected (`true` if it's available for the SKU).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by surajrana93** [comment]
@mboersma @CecileRobertMichon 
Do you still need help on this? Want to give it a try as a first issue

**Comment by CecileRobertMichon** [comment]
@surajrana93 go for it. I saw you also commented on #497. Both of these are up for grabs. Make sure you comment `/assign` on whichever one you choose to pick up and let us know if you would like any pointers.
