### ISSUE TITLE
Control plane NSG is open to the internet

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#104]
/kind bug

ref: #92

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: v0.1.0-alpha.3
- Kubernetes version: (use `kubectl version`): 1.13.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by awesomenix** [comment]
Uses NSG with https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/139, bastion VM could be an alternative instead of default, closing this

/close

**Comment by alexeldeib** [comment]
What's the preferred resolution to this issue? Implementing a bastion (which I assume would be open to the internet?) or locking down the control plane NSG further? Seems a little difficult without user input to determine e.g. the desired ranges.

**Comment by alexeldeib** [comment]
Seems like this is going towards bastion VM, just saw https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/175

**Comment by justaugustus** [comment]
I'm not sure if this is still true, but re-opening to investigate.
/reopen
/remove-lifecycle rotten
/remove-priority critical-urgent

**Comment by CecileRobertMichon** [comment]
So I think what we need to do here is:
1) Change the default NSG rules so they are more restrictive, we don't want the NSG to ever be open to the whole internet
2) Look into Azure Bastion and maybe implement it as an optional feature.
@jadarsie would this issue be of interest to you?
