### ISSUE TITLE
Cannot ssh to the public IP of worker node 

### ISSUE THREAD

**Issue by jessehu** [kubernetes-sigs/cluster-api-provider-azure#1056]
/kind bug

**What steps did you take and what happened:**
I used CAPZ v0.4.8 to create a 1 master node and 1 worker node cluster in Azure. I'm able to ssh to the public IP of master node with the specified ssh public key, but **unable** to ssh to the public IP of worker node.

**What did you expect to happen:**
Be able to ssh to the public IP of worker node

**Anything else you would like to add:**
After adding an Inbound NAT rule for the public IP of load balancer, tcp port 22 and targeted to worker node VM, also the Inbound port rule for tcp port 22 for the worker node VM, I'm able to ssh to the worker node.

**Environment:**

- cluster-api-provider-azure version: v0.4.8
- Kubernetes version: (use `kubectl version`): v1.19.3
- OS (e.g. from `/etc/os-release`): 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by jessehu** [comment]
Inbound NAT rule:
![image](https://user-images.githubusercontent.com/10006/100491291-52743880-315d-11eb-980e-92282d4b6ed9.png)

Inbound port rule:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/10006/100491225-de399500-315c-11eb-8b91-31693b656c3e.png">

**Comment by CecileRobertMichon** [comment]
Hi @jessehu! By default, worker VMs will not have a public IP, only a private IP. 

You should be able to ssh to any worker node by first ssh'ing on the control plane and using agent forwarding to ssh to the worker node from there as follows (given that your worker VM is using the same ssh key as the control plane):

```
➜  cluster-api-provider-azure git:(master) ✗ eval $(ssh-agent)
Agent pid 5824
➜  cluster-api-provider-azure git:(master) ✗ ssh-add ~/.ssh/id_rsa
Identity added: /Users/cerobert/.ssh/id_rsa (cerobert@Ceciles-MBP)
➜  cluster-api-provider-azure git:(master) ✗ ssh -A capi@52.171.224.198
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1031-azure x86_64)
...
Last login: Mon Nov 30 17:06:26 2020 from 24.10.159.18
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

capi@my-cluster-control-plane-jh55z:~$ ssh my-cluster-md-0-dhcst
The authenticity of host 'my-cluster-md-0-dhcst (10.1.0.4)' can't be established.
ECDSA key fingerprint is SHA256:+SiRTdOMATyH8K84YdiSCxYe+DR/vEirgivNFsc8Q+M.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'my-cluster-md-0-dhcst,10.1.0.4' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1031-azure x86_64)
....
capi@my-cluster-md-0-dhcst:~$
```

You can also use the capz-ssh kubectl plugin as a convenience to SSH into the nodes: https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/hack/debugging#capz-ssh

**Comment by jessehu** [comment]
Thanks a lot @CecileRobertMichon. I followed your steps but got:
```
capi@gpucluster-control-plane-gfs2t:~$ ssh gpucluster-md-0-pvnqg
capi@gpucluster-md-0-pvnqg: Permission denied (publickey).
```
So SSH to master nodes is enabled on purpose, but disabled for worker nodes?

Another question: when deploying an application which uses NodePort, shall we manually add the NAT rule for the LoadBalancer for worker nodes (as shown in my screenshot) to map to the port of worker nodes?

**Comment by CecileRobertMichon** [comment]
`capi@gpucluster-md-0-pvnqg: Permission denied (publickey).`  means the private key does not match. Are you using the same key for btoh control plane and worker nodes? You can try resetting the ssh key for the worker VM in the Azure portal to make sure it is using your public key.

> Another question: when deploying an application which uses NodePort, shall we manually add the NAT rule for the LoadBalancer for worker nodes (as shown in my screenshot) to map to the port of worker nodes?

No, you shouldn't add anything manually to the resources. CAPZ and cloud provider might even overwrite any manual changes during reconcile.

**Comment by CecileRobertMichon** [comment]
I'm going to close this for now, feel free to reopen if needed.

/close
