### ISSUE TITLE
Rename exp.AzureMachineTemplate

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1060]
/kind feature

**Describe the solution you'd like**
Rename `AzureMachineTemplate` in the experimental folder to make moving `MachinePool` into the stable API easier and to minimize confusion with the v3alpaha `AzureMachineTemplate`.

For additional discussion see: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/575#issuecomment-735819680.

Perhaps, `AzureMachinePoolTemplate`. Not really sure what the right name is, but that's a good start.

**Comment by nader-ziada** [comment]
fixed as part of #1389 

/close
