### ISSUE TITLE
Align flag names with upstream Kubernetes components

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes-sigs/cluster-api-provider-azure#1066]
/kind feature

**Describe the solution you'd like**
cluster-api repo made these changes to the flag names: kubernetes-sigs/cluster-api#3934

CAPZ should adopt these here as well to be consistent with it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@kkeshavamurthy let's hold on this until we open the main branch for v1alpha4 breaking changes

/milestone v0.5.x

**Comment by nader-ziada** [comment]
I think this got done as part of the v1alpha4 PR #1144 as a side effect of aligning with core capi
