### ISSUE TITLE
Move Service interface outside of azure (cloud/ directory) package 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1075]
/kind cleanup

**Describe the solution you'd like**
We have the [service](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/interfaces.go#L28) interface which describes the behavior of a reconciliation capz service. There are two kinds of services:

1. Individual service that reconciles one specific azure component (eg. virtualmachines.Service which only cares about vm reconciliation). These live inside `cloud/services` directory.
2. Composite Service (aka reconcilers) that reconciles more than one individual components (eg. azuremachineReconciler which reconciles all services required for an azuremachine). These are mostly inside `controllers/`

Right now, the `Service` interface is defined inside `cloud/` directory which makes it awkward for services that are outside of `cloud/services` to implement.

We'd like to move `Service` interface outside of `cloud/` to a common package accessible for all implementors.

**Anything else you would like to add:**

More discussion on this topic [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1053#discussion_r540551787)

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by surajrana93** [comment]
@shysank 
Can i take this up if its unassigned?

**Comment by shysank** [comment]
Sure @surajrana93 , although I'm not entirely sure about where we want to move `Service` to?  Should we create a new package? 

/cc @CecileRobertMichon @devigned

**Comment by devigned** [comment]
Maybe we just rename `azure.Service` to `azure.Reconciler`. Thoughts?

Related to this, does anyone else find that the `cloud` directory contains the `azure` package a bit odd? Should it be the `azure` directory or the `cloud` package? I prefer the former.

**Comment by CecileRobertMichon** [comment]
> Maybe we just rename azure.Service to azure.Reconciler. Thoughts?

+1 for the rename

> Related to this, does anyone else find that the cloud directory contains the azure package a bit odd? Should it be the azure directory or the cloud package? I prefer the former.

Yep, I think this slipped into the v1alpha2 revamp and never got corrected. +1 for renaming the directory to `azure`

**Comment by shysank** [comment]
+1 for renaming both interface, and directory. I also noticed we have an `OldService` interface which is only used in machine pool. Not sure about the history here, but should we also migrate it to implement the new service interface?

**Comment by CecileRobertMichon** [comment]
>  I also noticed we have an OldService interface which is only used in machine pool. Not sure about the history here, but should we also migrate it to implement the new service interface?

Yep that's leftover TODO from https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/757

As soon as all the services have been refactored we can get rid of OldService

**Comment by surajrana93** [comment]
@CecileRobertMichon 
Please take a look when you get time https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1094
