### ISSUE TITLE
Reduce the amount of authentication requests

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1077]
/kind feature

**Describe the solution you'd like**
For every reconciliation, CAPZ will completely rebuild the cluster `Authorizer` and with it, cause a request to Azure Active Directory to procure a new JWT which will them be used to Authenticate to Azure. You can see the POST in the Jaeger output below.

![capz-auth-overhead](https://user-images.githubusercontent.com/386473/102229642-08f44f00-3eba-11eb-943d-528853335c15.png)

Azure Active Directory generally responds in about 80ms - 200ms, but this is overhead for _every_ reconcile cycle. It adds up. Also, it's not very friendly to Azure Active Directory.

I think we can use the work in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1067, specifically, the `Authorizer.Hash()` and the time to live least recently used cache to create a safe and efficient mechanism to reuse `Authorizers` across reconcile cycles.

**Comment by dtzar** [comment]
Is this still relevant after we move to ASO?

**Comment by dtzar** [comment]
@adriananeci - FYI potentially relevant to #3526

**Comment by dtzar** [comment]
@nojnhuh - Do you think this is still valid after all the refactoring we've done or not sure without more investigation?

**Comment by dtzar** [comment]
If this still happens with main branch today assuming workload identity, then something we should prioritize.

**Comment by nojnhuh** [comment]
Hopefully coming soon :eyes:

before/after
![before](https://github.com/user-attachments/assets/d55591b7-f8a0-4550-8896-e21a61734eed)
![after](https://github.com/user-attachments/assets/1dc9c9c7-93fe-4121-9277-092a437d3533)

/remove-lifecycle rotten
/milestone v1.18
/assign

**Comment by nojnhuh** [comment]
#5211 doesn't fix this, but it does lay some groundwork to be able to fix this.
