### ISSUE TITLE
[Flaky tests] pull-cluster-api-provider-azure-e2e 

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1095]
/kind bug

**What steps did you take and what happened:**

I have seen the following tests flaking on my PR but also happen in the periodic [jobs](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-capi-e2e-full).  This needs some further investigation and I have linked a few failures I've seen

- capz-e2e: Workload cluster creation With 3 control-plane nodes and 2 worker nodes:
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1036/pull-cluster-api-provider-azure-e2e/1340101528018489344
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1036/pull-cluster-api-provider-azure-e2e/1340122799942930432
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full/1340025518291947520
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full/1339481166377390080
- capz-e2e: Workload cluster creation Creating a ipv6 control-plane cluster With ipv6 worker node expand_more
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1036/pull-cluster-api-provider-azure-e2e/1340791520889933824
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full/1341114195642421248

Can find more recent flakes at https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-capi-e2e-full

**What did you expect to happen:**
Tests to pass more consistently 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

The job configs: https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
Good issue to dive into the internals of how things work.  

/help

**Comment by CecileRobertMichon** [comment]
Going to close this since we're opened more specific issues for failures since

/close
