### ISSUE TITLE
Adopt a Reconcile/Delete pattern for exported methods

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#110]
**Describe the solution you'd like**
The goals are two-fold here:
1. Adopt a consistent pattern/interface for retrieving/modifying/deleting Cluster/Machine/Azure resources
2. Minimize calls to Azure by storing more information in Cluster & Machine objects

For each actuator reconciler, we currently have Reconcile and Delete methods which operate over the lower-level Azure resources. 

Instead of handling implementation details in the top-level reconciler, we should scope them to the resources that they're operating over. As an example, a `SubnetSpec` should instead be generated/manipulated by a subnet reconciler:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0b7cf771058e2cef05e99b048138454afd12616e/pkg/cloud/azure/actuators/cluster/reconciler.go#L108-L113

As a concrete reference, see the [`ReconcileNetwork()`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c694a556e993c243326d63e38f09ee167dfdd6b8/pkg/cloud/aws/services/ec2/network.go#L23-L59) method for Cluster API Provider AWS.

A secondary problem is that in our current actuator reconciler model, we make a variety of Create/Update calls to the Azure API, in instances where a Get would suffice. This means we're attempting to modify a majority of the Azure resources we create on every round-trip of a reconciler.

Finally, we do not fully utilize the defined types in the capz API, instead accepting an [ambiguous spec](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0b7cf771058e2cef05e99b048138454afd12616e/pkg/cloud/azure/interfaces.go#L29-L30) and returning a loosely-defined interface, instead of a concrete type. 

This means that we are required to query Azure for cluster/machine information, instead of being able to reference the `ClusterSpec`, `ClusterStatus`, `MachineSpec`, and `MachineStatus` directly, which should be our sources of truth.

---

As a solution, we can:
- Redefine the `Service` interface to present only Reconcile and Delete methods
- Add a temporary interface (`GetterService`) to represent packages that don't adhere to the Reconcile/Delete model
- Refactor packages to adhere to Reconcile/Delete model, which will convert and store Azure resource information in the relevant Spec or Status
- Redefine package-level `CreateOrUpdate`/`Get`s as unexported methods (only to be used by the package-level Reconcile/Delete)
- Remove references to unexported methods from the top-level reconcilers
- Remove the temporary `GetterService` interface

The work to accomplish this has begun in #174.

ref: #92
/kind feature

**Comment by juan-lee** [comment]
Have we considered implementing our services as CRDs? @justaugustus

**Comment by CecileRobertMichon** [comment]
@juan-lee see #416 😃

**Comment by CecileRobertMichon** [comment]
@justaugustus is it okay if I help out with this?

**Comment by CecileRobertMichon** [comment]
/close

 in favor of #757
