### ISSUE TITLE
Add tests for scope structs

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1108]
/kind feature

The `scope` structs (machine, cluster etc.) look like they only have simple getters and setters, but some of them have some subtle logic which return different values based on the state of the cluster/machine. Eg. PublicIPSpecs. Since we mock this behavior in `services`, we don't actually test the behavior of scope methods.

**Describe the solution you'd like**
Unit tests for all the scope methods, at least for the ones that have conditional logic.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
This is slightly more complicated than a good first issue. But, it has low impact and would be a good way to get a feel of the codebase. I'd suggest opening a pr for one scope first, and then do it for the rest. Happy to pair or answer any questions on this.

**Comment by sonasingh46** [comment]
@shysank -- Would like to work in this issue. Thanks.

**Comment by jsturtevant** [comment]
this was fixed in #1649 
/close
