### ISSUE TITLE
E2E failure: cannot get remote client to workload cluster

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1114]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Seeing some more common flakes on PRs over the last few days. One of them is the following error in KCP logs which causes the 3rd control plane to not be created and the test to fail with:

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:216
Timed out after 1200.000s.
Expected
    <int>: 2
to equal
    <int>: 3
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.12/test/framework/controlplane_helpers.go:107
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1110/pull-cluster-api-provider-azure-e2e/1348678463292182528/artifacts/clusters/bootstrap/controllers/capi-kubeadm-control-plane-controller-manager/capi-kubeadm-control-plane-controller-manager-644cd47898-ggv5s/manager.log

```
I0109 09:21:04.850870       1 controller.go:419] controllers/KubeadmControlPlane "msg"="failed to reconcile conditions" "cluster"="capz-e2e-5dz6z4" "kubeadmControlPlane"="capz-e2e-5dz6z4-control-plane" "namespace"="create-workload-cluster-jzi2zy" "error"="cannot get remote client to workload cluster: create-workload-cluster-jzi2zy/capz-e2e-5dz6z4: Get https://capz-e2e-5dz6z4-1b33ab75.westus2.cloudapp.azure.com:6443/api?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The few repros I've seen were on the ipv6 spec but unsure whether that's a coincidence or if this failure is specific to ipv6 clusters.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
/reopen

Happened on #1640

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1640/pull-cluster-api-provider-azure-e2e/1443255955692195840
