### ISSUE TITLE
Cluster deletion stuck in continuous loop

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1118]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
copying issue from cluster-api repo since it is in the provider: https://github.com/kubernetes-sigs/cluster-api/issues/4065

**What did you expect to happen:**
I was expecting the cluster to be deleted and not shown in output of kubectl get cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
i believe there are similar threads but for aws provider.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
The resource group is 404 error probably affects more than just `AzureCluster`. I think it's pervasive in the controllers. If Azure gives us a 404 back for the resource group and the resource is being deleted, we should just delete the resource. I think we check for 404 in the non-delete case b/c we might have started reconciling a resource prior to the group being created.

The annoying part of this is that we don't setup the Scope until after we have built up all of the information needed to reconcile, and checking for the resource group is usually one of the first things we do.

**Comment by nader-ziada** [comment]
There is already a check in the groups service if the resource group doesn't exist and assumes it already deleted, but maybe the problem here is that the error is `Subscription not found` so the check is not working

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/groups/groups.go#L99-L103

**Comment by devigned** [comment]
Delete never gets called. The controller returns before the scope is created and delete is called: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/a3525d2d89821192dbaeef270f46eff09e4c4587/controllers/azurecluster_controller.go#L105-L115

**Comment by nader-ziada** [comment]
but when the original issue reported called delete, the error is `error deleting AzureCluster default/test-cluster-1: failed to delete resource group` which I think is coming from here https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azurecluster_reconciler.go#L151

**Comment by devigned** [comment]
I'm so sorry... You are right, @nader-ziada. I think it's coming from here where the 404 is returned and we only expect a wrapped error type in the caller.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/a3525d2d89821192dbaeef270f46eff09e4c4587/cloud/services/groups/groups.go#L88-L91

**Comment by nader-ziada** [comment]
i'll try to work on that, thanks for your help @devigned
