### ISSUE TITLE
Add Metrics server to clusters

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1125]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
After deploying a cluster the commands `kubectl top nodes` and `kubectl top pods` don't work because the [metric server](https://github.com/kubernetes-sigs/metrics-server) is missing.  Functionality like the [HPA will also require](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#before-you-begin) the metric server.  

```
 k top nodes
error: Metrics API not available
 k top pods
error: Metrics API not available
 k get pods -A
NAMESPACE     NAME                                                           READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-8f59968d4-v8clz                        1/1     Running   0          60m
kube-system   calico-node-clfb2                                              1/1     Running   0          60m
kube-system   calico-node-kdv67                                              1/1     Running   0          58m
kube-system   calico-node-n542l                                              1/1     Running   0          57m
kube-system   coredns-f9fd979d6-gf6hr                                        1/1     Running   0          60m
kube-system   coredns-f9fd979d6-h2m7m                                        1/1     Running   0          60m
kube-system   etcd-default-template-control-plane-9przl                      1/1     Running   0          60m
kube-system   kube-apiserver-default-template-control-plane-9przl            1/1     Running   0          60m
kube-system   kube-controller-manager-default-template-control-plane-9przl   1/1     Running   0          60m
kube-system   kube-proxy-4pb22                                               1/1     Running   0          60m
kube-system   kube-proxy-qf5v7                                               1/1     Running   0          57m
kube-system   kube-proxy-xqrvw                                               1/1     Running   0          58m
kube-system   kube-scheduler-default-template-control-plane-9przl            1/1     Running   0          60m
```

```
 kubectl describe hpa
Name:                                                  php-apache
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 15 Jan 2021 13:17:36 -0800
Reference:                                             Deployment/php-apache
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       14s (x4 over 60s)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  14s (x4 over 60s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This could be applied via [Custom Resource Sets](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200220-cluster-resource-set.md) similar to the way we do CNI's: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e7ebdf3bef11fcb5a6e001b2860ae8d6654e0202/Tiltfile#L199

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/templates/addons/calico-resource-set.yaml

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
We can do this easily on all dev clusters created by e2e and through the makefile, and document how to do this for workload clusters (either run `kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml` on each cluster or use a ClusterResourceSet to automatically apply it to every workload cluster). However, same as CNIs, it's up to the user to create the CRS. We can provide documentation and examples, but the CRS won't be created automatically by clusterctl.

**Comment by jackfrancis** [comment]
In my tests the vanilla metrics-server config doesn't work. I have gotten a v0.3.7 spec working correctly, using the `--kubelet-insecure-tls` and `--kubelet-preferred-address-types=InternalIP` command args, and using a `spec.insecureSkipTLSVerify: true` config to the `APIService` configuration.

**Comment by jsturtevant** [comment]
/reopen 

This is only partially fixed for e2e and the the insecure flag needs to be addressed via updates to capi or manually be a customer that wishes to deploy it.  See for more details https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1903#issuecomment-989350818

**Comment by jsturtevant** [comment]
/reopen

This is only partially fixed for e2e and the the insecure flag needs to be addressed via updates to capi or manually be a customer that wishes to deploy it. See for more details https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1903#issuecomment-989350818

**Comment by jackfrancis** [comment]
Does metrics-server have an official helm chart/repo?

**Comment by jsturtevant** [comment]
looks like it does: https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/README.md
