### ISSUE TITLE
Decouple Infrastructure resource from machine controller

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-azure#1129]
/kind feature

**Describe the solution you'd like**
As a CAPI consumer I'd like to plug-in my own ControlPlane and Infrastructure resources [1] while still still reusing the existing machine controller implementation.

Today this is not possible because the machine/machinePool controllers are tightly coupled with the regular AzureCluster kind [2].

A scenario where this is handy is one where there's a common vision for a controlPlane across providers e.g cluster-api-provider-nested and the infrastructure management can differ arbitrarily from the core implementations, e.g BYO.

[1] https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/cluster_types.go#L50-L58
[2] https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azuremachine_controller.go#L186-L204

**Anything else you would like to add:**
Analogous to AWS
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2125
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2124

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
As discussed in Slack, let's start with a proposal.

/milestone v0.5.x

**Comment by CecileRobertMichon** [comment]
/remove lifecycle-frozen

Proposal https://github.com/kubernetes-sigs/cluster-api/pull/4135

**Comment by CecileRobertMichon** [comment]
/close 

done in #1389
