### ISSUE TITLE
Containers still run as root due to non-numeric user in Docker image

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1133]
/kind bug

**What steps did you take and what happened:**
This is a duplicate of [capi non root user bug](https://github.com/kubernetes-sigs/cluster-api/issues/4046)

**What did you expect to happen:**
capz should not fail when psp for non root users is enabled

**Anything else you would like to add:**
[capi fix](https://github.com/kubernetes-sigs/cluster-api/pull/4064)

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
FYI https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1089#issuecomment-765721150
