### ISSUE TITLE
azure nodeOutbound loadbalancer reconcile fails after creating serviceType=LoadBalancer

### ISSUE THREAD

**Issue by sadysnaat** [kubernetes-sigs/cluster-api-provider-azure#1139]
/kind bug

**What steps did you take and what happened:**
Create a cluster using clusterctl 

```
clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.12", GitCommit:"9e1dd7e8e428e05bee406602952ae269d55bdbba", GitTreeState:"clean", BuildDate:"2020-12-15T16:42:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

```
clusterctl init --infrastructure=azure
Fetching providers
Installing cert-manager Version="v0.16.1"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.13" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.13" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.13" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-azure" Version="v0.4.10" TargetNamespace="capz-system"
```

Install cni
[cni.yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/5868627/cni.yaml.txt)

Install nginx controller 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/cloud/deploy.yaml`

and capz starts throwing error

**What did you expect to happen:**
Expect no reconcile error in capz
```
I0125 17:50:26.321627       1 azurecluster_controller.go:168] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="<cluster-name>" "cluster"="<cluster-name>" "namespace"="default" 
E0125 17:50:30.964200       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to reconcile load balancer: failed to create load balancer \"cluster-name\": network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidResourceReference\" Message=\"Resource /subscriptions/<subscriptionId>/resourceGroups/<cluster-name>/providers/Microsoft.Network/loadBalancers/ds-bet-1780/backendAddressPools/<cluster-name> referenced by resource /subscriptions/<subscriptionId>/resourceGroups/<cluster-name>/providers/Microsoft.Network/loadBalancers/<subscriptionId>/loadBalancingRules/a285df35053e544419fd8ecb70ac7218-TCP-80 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\" Details=[]" "controller"="azurecluster" "name"="<cluster-name>" "namespace"="default"
```

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: v0.4.10
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
`Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`

**Comment by CecileRobertMichon** [comment]
Hi @sadysnaat, we have identified a similar issue in our E2E tests (#1115) that has been root caused to a platform (Azure) issue. A fix is currently being rolled out.

Did you create/delete another LB /service before this happened by any chance? The repro steps we've observed so far are:
1) Create internal service (which triggers a create of an internal load balancer)
2) Delete internal service (which triggers a delete of the internal LB) 
3) Create an external service 
4) watch the external LB fail to create and the associated scale set go into failed state with error "internal-LB not found"

Also, could you please share the command you used to create the workload cluster (clusterctl config cluster)?

**Comment by sadysnaat** [comment]
> Did you create/delete another LB /service before this happened by any chance? The repro steps we've observed so far are:

No. First manifest I applied to cluster is nginx-ingress 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/cloud/deploy.yaml`

No deletion for internal service was performed as soon as Loadbalancer service got external IP, capz reconcile error started.



> Also, could you please share the command you used to create the workload cluster (clusterctl config cluster)?
```
clusterctl config cluster <cluster-name> \
  --kubernetes-version v1.18.8 \
  --control-plane-machine-count=1 \
  --worker-machine-count=1
```

**Comment by CecileRobertMichon** [comment]
Thanks @sadysnaat, I was able to repro. There seems to be a conflict between cloud provider setting LB rules and CAPZ trying to reconcile the LB.

/assign
