### ISSUE TITLE
Add AKS addon support

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-azure#1145]
/kind feature

**Describe the solution you'd like**
Add support for installing/managing AKS addons as part of the control plane reconciliation.

**Comment by devigned** [comment]
Azure API for addons: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#managedclusteraddonprofile

**Comment by surajrana93** [comment]
@CecileRobertMichon 
Can I help here?

**Comment by CecileRobertMichon** [comment]
@surajrana93 go for it. Let me or @alexeldeib know if you have any qestions.

/assign @surajrana93

**Comment by alexeldeib** [comment]
/remove-lifecycle stale

Required work:
- Add a field to AzureManagedControlPlane with a map/slice of addon configurations
- Update AzureManagedControlPlane reconciler to pass those fields to managedclusters service/client.
- Update managedclusters service/client to consume those fields and pass them to AKS
- Webhook validation on addon options? I'm not sure if there are any other restrictions like e.g. incompatible addons, addons you can't disable, etc. that's a TODO if you want to work on this :) 

addons are surprisingly poorly documented via anything other than the CLI: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_enable_addons

The code is simple enough: https://github.com/Azure/azure-cli-extensions/blob/fa207098b7bbe12c8e074b81e7fe55d6e028d49c/src/aks-preview/azext_aks_preview/_consts.py#L68-L79

[Here's an example](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-05-01/examples/ManagedClustersCreate_AzureKeyvaultSecretsProvider.json#L62-L69) of how it looks in the REST API. The addon names are well-known (see the CLI link), and as far as I know there is no dynamic way to list those (they don't change _too_ often). 

It ends up [here ](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-05-01/containerservice?utm_source=godoc#ManagedClusterAddonProfile)in the Go SDK.
