### ISSUE TITLE
Multi tenancy support for AKS/managed clusters

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-azure#1153]
/kind feature

**Describe the solution you'd like**
Multi tenancy support for AKS/managed clusters

**Anything else you would like to add:**
Similar to unamanged clusters as described here: https://capz.sigs.k8s.io/topics/multitenancy.html, I would like to request multi tenancy support for AKS/managed clusters as well.

**Comment by nader-ziada** [comment]
/unassign
didn't get a chance to work on it yet
