### ISSUE TITLE
Windows support for AKS clusters

### ISSUE THREAD

**Issue by nprokopic** [kubernetes-sigs/cluster-api-provider-azure#1176]
/kind feature

Currently managed clusters (AKS) only support Linux nodes, while AKS supports Windows nodes as well.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

New `OSType` field in `AzureManagedMachinePoolSpec`, which is then used to set the specified OS type in `ManagedClusterAgentPoolProfileProperties` when submitting request to Azure API.

**Anything else you would like to add:**

OS type `Linux` is currently hardcoded in the `ManagedClusterAgentPoolProfileProperties`.

**Comment by jackfrancis** [comment]
I think we can close this issue now that https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2410 has merged (included in 1.4.0 release of capz)

Thanks again @luthermonson!
