### ISSUE TITLE
Parallel reconciliation of azure resources

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1181]
/kind feature
/kind explore

**What steps did you take and what happened:**

We reconcile serially a bunch of resources in azurecluster and azuremachine reconcilers. Some of these resources have no dependency on each other, and can be reconciled simultaneously. Eg. After a vm is reconciled, vmextensions, tags and roleassignments can be reconciled simultaneously, and potentially save some time.

**Describe the solution you'd like**

Reconcile mutually exclusive services in parallel using goroutines and channels.

**Anything else you would like to add:**

This is more of an exploration than an actual requirement.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Another thing we should consider doing more of is #1067 for other resources. A lot of these create operations are long running and we don't need to be block everything else while the resource creates. We can start the create and then exit the controller loop right away and come back later to check if the operation is done. This also allows us to deal with a lot more objects concurrently (imagine you're trying to create 500 nodes, having the controller be able to kickstart the create and then circle back is a lot more efficient than having to wait for each one to be done before exiting the controller loop).

**Comment by shysank** [comment]
Yeah, the ideal solution is probably a combination of both. We could  use #1067 for long running operations (vm create), and go routines for relatively shorter ones.

Or another thing we can do is to just timeout all operations longer than 5 seconds (let's say), update future data, and return control. This will mean only the reconciliation during create will be async, the subsequent ones will mostly be synchronous.

**Comment by arschles** [comment]
@CecileRobertMichon great, thanks for letting me know! I'm gonna work to get #1575 done and then I'll drop in and see where this effort is, and how I can help 👍

**Comment by shysank** [comment]
@CecileRobertMichon now that we are following [async](#1541) pattern for reconcile/delete of services, can we close this one?
