### ISSUE TITLE
Forward port MachinePool FailureDomains to v1alpha4 types

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1193]
@nader-ziada let's forward port this to alpha4 once the types merge

_Originally posted by @CecileRobertMichon in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1180#issuecomment-784439609_

**Comment by nader-ziada** [comment]
applied as part of v1alpha4 PR #1144 

closing issue
