### ISSUE TITLE
Not all of the CI jobs use the same registry

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1195]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I logged into Azure Container Registry (capzci.azurecr.io), I saw there were images in two repositories, `ci-e2e/cluster-api-azure-controller-amd64` and `cluster-api-azure-controller-amd64`. I suspect we have some CI jobs not applying the `ci-e2e/` prefix when tagging images.

**What did you expect to happen:**
I'd expect to only use a single repository.

related: #1194

**Comment by CecileRobertMichon** [comment]
this was fixed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1334

/close
