### ISSUE TITLE
Cert manager tilt module needs to be updated

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1211]
Copy paste from https://github.com/kubernetes-sigs/cluster-api/issues/4256

Cert manager version was recently bumped to v1.1.0 in this [commit](https://github.com/kubernetes-sigs/cluster-api/pull/4225/files#diff-c2ee8653e1d6b85f0aadf87cd438a9250806c052877248442be4d434cbc52425) but the Tilt [module](https://github.com/kubernetes-sigs/cluster-api/blob/master/tilt_modules/cert_manager/Tiltfile) wasn't updated.

There are a few changes that should be made in the module:

- default version should be v1.1.0
- apiVersions in cert_manager_test_resources need to be updated to latest available ones
- the workaround for https://github.com/jetstack/cert-manager/issues/3121 can be removed since the issue is now fixed

 I might be missing some things, we should also audit [commit](https://github.com/kubernetes-sigs/cluster-api/pull/4225/files#diff-c2ee8653e1d6b85f0aadf87cd438a9250806c052877248442be4d434cbc52425) to make sure no other changes are needed.

**Comment by davideimola** [comment]
Hi @CecileRobertMichon, as the task in Cluster API has been done and replicated in the tilt module too it would be nicer if we commit the same thing here.

FYI @fabriziopandini

**Comment by CecileRobertMichon** [comment]
yes let's implement the same changes as https://github.com/kubernetes-sigs/cluster-api/pull/4274

@enyinna1234 let us know if you have any questions

**Comment by nader-ziada** [comment]
/close

fixed by #1234
