### ISSUE TITLE
Enable `metrics`-scraping

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cluster-api-provider-azure#1222]
/kind feature

**Describe the solution you'd like**
I created [PR 📖 document metrics scraping and enable metrics services via annotations](https://github.com/kubernetes-sigs/cluster-api/pull/4247) at CAPI and also some PRs on other infraproviders to document how to setup all the RBAC stuff together with `kube-rbac-proxy` and `prometheus` to scrape metrics from CAPI containers.

The annotation already exist at `capz` but was removed last year with [this commit](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/2cc75f4e6be222b7340139614adfc7b03f8cb612) in PR #1019 by @devigned 

Using the prometheus-operator is definitely a valid solution to bring some observability in a cluster, but imho using a "simple" `prometheus` deployment/statefulset with a very common config is also very proven in a k8s environment.

would you accept a PR, where i set some annotations on the `metrics`-service?

```yaml
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
``` 

- new PRs:
  - [CAPI](https://github.com/kubernetes-sigs/cluster-api/pull/4247)
  - [Packet](https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/231) - merged
  - [IBM Cloud](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/310) - merged
  - [DigitalOcean](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/240) - merged
- `annotation` already exist:
  - [AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/rbac/auth_proxy_service.yaml)
  - [Metal3](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/config/rbac/auth_proxy_service.yaml)
  - [GCP](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/config/rbac/auth_proxy_service.yaml)
  - [OpenStack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/rbac/auth_proxy_service.yaml)
  - [vSphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/config/rbac/auth_proxy_service.yaml)

**Comment by CecileRobertMichon** [comment]
> would you accept a PR, where i set some annotations on the metrics-service?

@bavarianbidi, yes please go ahead and open a PR to add it back
