### ISSUE TITLE
Move AZURE_ENVIRONMENT to AzureCluster spec

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1227]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Moving AZURE_ENVIRONMENT to AzureCluster spec will allow capz `infrastructure-components.yaml` to be deployed without requiring `envsubst` to set a default value

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
source: https://github.com/kubernetes-sigs/cluster-api/issues/3881#issuecomment-743370519 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nader-ziada** [comment]
The reason we used an env var for `AzureEnvironment` is that the azure sdk reads it from the environment and as far as I can see there is not func to pass this in. So even it we switch to a field on AzureCluster, we would need to set it as an env var before calling the sdk?

@CecileRobertMichon @devigned  wdyt?

**Comment by devigned** [comment]
@nader-ziada I think we can get around setting an env var. I'm happy to pair on this with you.

As for the idea of adding it to the `AzureCluster` spec and not needing `envsubst`, +1. Can you think of any other fields that would go with this? Just wondering if this should be part of a larger struct or is just top level on the spec.

**Comment by nader-ziada** [comment]
@devigned would be cool if there is a way to get around that with the sdk, can you share any tips here? happy to pair as well :)

I was thinking of just adding it to the AzureCluster Spec since would remove the need for envsubst on the mainfest. I don't think is anything else to add in a bigger struct

**Comment by devigned** [comment]
I think we can just override some of what is going on in go-autorest auth https://github.com/Azure/go-autorest/blob/c7f947c0610de1bc279f76e6d453353f95cd1bfa/autorest/azure/auth/auth.go#L107.
