### ISSUE TITLE
Machine actuator is unable to discover an existing machine

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#123]
/kind bug

**What steps did you take and what happened:**
This requires additional investigation, but I believe there is faulty logic in the `VMIfExists` and by extension, `CreateOrGetMachine` which is causing the controller to believe the machine has not already been created. This leads to additional calls to the Azure API (#110) which can be avoided.

/assign
/milestone mvp
/priority critical-urgent

**Comment by justaugustus** [comment]
(Updating the cluster actuator, machine actuator, and deployer code should resolve this.)

**Comment by awesomenix** [comment]
Fixed with PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/139, calls azure to check existence of the machine, since we reconcile every 10 minutes in future, its fine to call azure to check vm existence
