### ISSUE TITLE
clusterctl apiVersion in metadata.yaml

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-azure#1235]
/kind bug

**What steps did you take and what happened:**

I'm currently implementing v1alpha4 for CAPO and I saw that the [metadata.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/metadata.yaml) in CAPZ already has the apiVersion v1alpha4. I'm just wondering if this should be v1alpha3 or if there's someting I"m missing.

**Environment:**

- cluster-api-provider-azure version: master

**Comment by devigned** [comment]
I think this was intentional when the new v1alpha4 types were added. Is this causing a problem?

cc @nader-ziada

**Comment by sbueringer** [comment]
@devigned Just wondering because that's the only place where it's used and there is no v1alpha4 of this apiGroup clusterctl. Just was confused that the latest cluster-api (master) version of the test framework was not able to handle that (CAPZ e2e tests also use v1alpha3 in metadata.yaml)

**Comment by nader-ziada** [comment]
@sbueringer main branch is now for v1alpha4, are you wondering if this change should have only come when we release?

**Comment by sbueringer** [comment]
@nader-ziada No, that sounds fine to me. I just found out that when I use v1alpha4 in metadata.yaml the cluster-api test framework says that it doesn't know it. Which imho absolutely makes sense, because cluster-api on master revision (which is v1alpha4) does not have a v1alpha4 for the apiGroup: `clusterctl.cluster.x-k8s.io`.

I understand that all other resources are v1alpha4, I'm just pretty confused how it's possible to use  `clusterctl.cluster.x-k8s.io/v1alpha4` when it doesn't exist in the cluster-api repo. Or is this something which is already planned / or exists on a branch / PR of the cluster-api repo?

P.S. the CAPZ e2e tests also use v1alpha3: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/data/shared/v1alpha4_provider/metadata.yaml#L6

**Comment by nader-ziada** [comment]
oh I finally get what you are saying now, you are correct that this is wrong, it should be 
`apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3`

**Comment by sbueringer** [comment]
@nader-ziada Ah great :). Just wasn't sure if I"m missing something or if it's intended to keep this apiGroup on version v1alpha3.
