### ISSUE TITLE
Update golangci to v0.38.0

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1259]
Steps:

- bump golangci to v0.38.0 release https://github.com/golangci/golangci-lint/releases/tag/v1.38.0 
- deprecate `maligned` and enable govet `fieldalignment` https://github.com/golangci/golangci-lint/pull/1765
- handle/fix new detected lint issues in code

**Comment by mistikel** [comment]
I would like to take it
