### ISSUE TITLE
Support ipv6 dual stack

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1266]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

#646 added ipv6 single stack support. 

This issue is to track adding IPv6 dual-stack support (https://kubernetes.io/docs/concepts/services-networking/dual-stack/) and enabling e2e testing for dual-stack clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

for prior Azure + dual stack art, refer to https://github.com/Azure/aks-engine/pulls?q=is%3Apr+dual+stack+is%3Aclosed

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
cc @chewong @aramase

**Comment by aramase** [comment]
Had an offline conversation with @CecileRobertMichon 

We already support dual-stack host for the VM/VMSS provisioned with CAPZ as part of single stack IPv6 support. The required changes for dual-stack will be around the Kubernetes configuration for the control plane components:

1. Multiple pod cidr
2. Option to add multiple service cidr
3. Feature flags (< 1.20) as 1.21 it's on by default

**Comment by CecileRobertMichon** [comment]
some notes on IPv6 dual stack support with Calico: https://github.com/projectcalico/calico/pull/5313
