### ISSUE TITLE
Metrics are not being collected from Azure SDK client calls

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1272]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Following https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/hack/observability/prometheus I was unable to see any metrics in prometheus. 

**What did you expect to happen:**
I expect prometheus metrics to be scraped and visible following the directions referenced above.

**Comment by CecileRobertMichon** [comment]
I was able to repro this from the v0.4.10 tag, which is the tag for the first release that included metrics and tracing with tilt, so it doesn't look to be a recent regression. Either something in the environment changed, or we're testing it wrong.

**Comment by CecileRobertMichon** [comment]
Seems like it was the latter, I can see the metrics now 😃 the old UI makes it slightly easier to find what queries to use...

**Comment by devigned** [comment]
@CecileRobertMichon can you describe your query or add it to documentation so we don't forget again.

**Comment by CecileRobertMichon** [comment]
So there are many different queries. In the old UI they show up in a drop down so you can just click on the one you want, but in the new UI you have to start typing for it to autocomplete which makes it a bit harder to find if you don't know what you're looking for. I can add details to the doc later.
