### ISSUE TITLE
Log dumping script for Windows clusters

### ISSUE THREAD

**Issue by chewong** [kubernetes-sigs/cluster-api-provider-azure#1286]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Our log dumping script (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/hack/log/log-dump.sh) should support Linux as well as Windows clusters 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by jsturtevant** [comment]
took a look and we are collecting some windows logs such as kubeproxy and flannel cni logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1296/pull-cluster-api-provider-azure-e2e-windows/1387118255923007488/artifacts/clusters/capz-e2e-hy4mf8/kube-system/

there also seems to be some logs attempted to be collected but looks like assumptions were linux as most files are blank: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1296/pull-cluster-api-provider-azure-e2e-windows/1387118255923007488/artifacts/clusters/capz-e2e-hy4mf8/machines/capz-e2e-hy4mf8-md-win-8678b7dd8-5btwg/ 

These files are collected by https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_logcollector.go not the https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/hack/log/log-dump.sh which is only used in a few jobs where the e2e framework is not used (azure disk etc).  

Going to add Windows support to the `azure_logcollector.go`
