### ISSUE TITLE
Investigate using Kustomize 2.x

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#129]
There are some breaking changes from kustomize 1.x --> 2.x that would prevent us from simply bumping the version.

ref:
- https://github.com/kubernetes-sigs/kustomize/blob/master/docs/version2.0.0.md
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/126#discussion_r263607147
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/569
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/611

/kind feature
/priority important-longterm
/milestone baseline
/help

**Comment by serbrech** [comment]
related : https://github.com/kubernetes-sigs/kubebuilder/pull/614
Kubebuilder updated their scaffolding to match Kustomize v2 expectations.

**Comment by serbrech** [comment]
Instructions to fix structure : 
https://github.com/kubernetes-sigs/kubebuilder/issues/595#issuecomment-468471211

**Comment by serbrech** [comment]
Further investigations : 
the `secretGenerator` type has done away with `commands:` for security concerns.
it has has now plugins, which allow you to define where the secrets are pulled from.
Environment is one option that is easy to swap in.

**Comment by justaugustus** [comment]
No longer required as we've moved to kustomize 3.x in v1alpha2.
