### ISSUE TITLE
Windows Machine Naming

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes-sigs/cluster-api-provider-azure#1313]
/kind feature

**Describe the solution you'd like**

The name of the Azure Windows machines is currently derived from the cluster object name (first 10 chars) and the last 5 chars from the Azure machine object name. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/scope/machine.go#L280-L291

While this is fine, it would be slightly more functional in my case to have the machine name base (first 10 chars) derived from the Azure machine object name. This would allow a more consistent naming convention with the Linux machines, and allow for embedding some information about the machineDeployments into the machine name (with the caveat that there's only 10 chars available to do so).

For instance, my machineDeployments could be named `m6-wrk-p0-lin` and `m6-wrk-p0-win` to indicate worker nodes in pool 0 for cluster m6 which would then give me `m6-wrk-p0-lin-bea41bbfdc9f6361bfe6496608a03304-vnhz5` for Linux and `m6-wrk-p0-pbnl6` for Windows.

**Anything else you would like to add:**
 
Windows machine naming is restricted to 15 chars due to concerns about netbios.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
This looks reasonable to me and would allow you to map it back to your machine deployments in the case that your cluster name was different from your machine names.  I didn't notice this because by default we prefix our Flavor templates with the cluster name and truncation gives it the same name.

This could be a breaking change if we someone was upgrading but could be worked around by manually setting the names to the existing node names.

**Comment by CecileRobertMichon** [comment]
I can take this one

/assign

**Comment by CecileRobertMichon** [comment]
> This could be a breaking change if we someone was upgrading but could be worked around by manually setting the names to the existing node names.

@jsturtevant I'm not sure there's a good way to make this backward compatible for MachineDeployments that weren't using the cluster name as prefix previously... Since the code uses the VM name (which is different from the AzureMachine name) to fetch the existing VM and delete it, etc.

**Comment by CecileRobertMichon** [comment]
nevermind, I found a way https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1408, PTAL
