### ISSUE TITLE
Suggestion:   Use role other than contributor when creating Service Prin.

### ISSUE THREAD

**Issue by lastcoolnameleft** [kubernetes-sigs/cluster-api-provider-azure#1317]
/kind feature

**Describe the solution you'd like**
It would be helpful if there was either a specific role, or specific steps to create the role which has least-privileges instead of `contributor`.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/getting-started.md#setting-up-your-azure-environment

**Anything else you would like to add:**
Keep up the great work!

**Environment:**
N/A

**Comment by devigned** [comment]
Great idea! Perhaps, we can create a custom role with only the rights needed for the service principal.

/cc @mboersma this might be something really interesting for https://github.com/Azure/azure-capi-cli-extension
