### ISSUE TITLE
Add a user-agent'ish header to containerd

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1325]
/kind feature

**Describe the solution you'd like**
When pulling container images, we should identify ourselves to the container registry. I'm not 100% sure what format we should use, but https://github.com/Azure/acr/blob/main/docs/http-headers.md#azure-container-registry-http-headers describes the preferred format for ACR.

My preference would be simply identify using the same user-agent specified for HTTP interactions in the controller.

**Comment by CecileRobertMichon** [comment]
Wouldn't this be done in the image builder image configuration?

**Comment by devigned** [comment]
> Wouldn't this be done in the image builder image configuration?

It could be. If one were to include the "cloud" as is described in the ACR headers, it may need to be part of the bootstrapping of the VM. Perhaps, part of the custom script extension.
