### ISSUE TITLE
e2e tests for machinepool clusters are not collecting logs

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1352]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If you look at logs for a cluster that was VMSS on a CI run you will not find the logs for the VMSS ndes:

https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full/1387735706947817472/artifacts/clusters/capz-e2e-j51u3m/machines/

**What did you expect to happen:**
logs for the VMSS nodes to be collected.  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It looks like this is because the framework only looks for machines 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/2203c184b97eb8bd3e95bd9ac5ff099c6e235c04/test/e2e/e2e_suite_test.go#L117-L118

https://github.com/kubernetes-sigs/cluster-api/blob/45b6080c276453c2f30fae3e093679a15c7ccdfd/test/framework/cluster_proxy.go#L218-L219

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
fyi @devigned

**Comment by devigned** [comment]
I think this is an addition for CAPI in the longer term. For the short term, we should probably do it ourselves.

**Comment by CecileRobertMichon** [comment]
I think we need the CAPI framework helper to get MachinePools too https://github.com/kubernetes-sigs/cluster-api/blob/45b6080c276453c2f30fae3e093679a15c7ccdfd/test/framework/cluster_proxy.go#L218-L219
