### ISSUE TITLE
MTU for Linux Calico VXLAN deployments should be lowered to below 1400

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1353]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
As part of #1335 it was identified that Linux uses Calico's vxlan and the MTU is over 1400 (which is azure networks MTU).  This doesn't cause any direct issue but could cause throughput issues because the vxlan traffic will get fragmented.

**What did you expect to happen:**
Packets shouldn't get fragmented and throughput affected

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

the following should be lowered and validated that packets are not fragmented.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/2203c184b97eb8bd3e95bd9ac5ff099c6e235c04/templates/addons/calico.yaml#L13-L19

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
should the title say below 1400?

**Comment by CecileRobertMichon** [comment]
Do you have a recommendation for what the new value should be?

**Comment by jsturtevant** [comment]
I believe this could be set to 1392 which would give room for the encapsulation but it would be good to validate it.

**Comment by CecileRobertMichon** [comment]
/good-first-issue

the ask is to set the `veth_mtu` value to 1392. @jsturtevant do you have any guidance for validating that packets are not fragmented?
