### ISSUE TITLE
Cluster upgrade fails when capz is upgraded to version >= 04.9 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1357]
/kind bug

**What steps did you take and what happened:**

1. Deploy capz version < 0.4.9
2. Create cluster 
3. Upgrade capz to >=0.4.9
4. Upgrade cluster created previously

cluster fails to upgrade because it cant find the secret `azure.json`

**What did you expect to happen:**
Cluster should upgrade successfully

**Anything else you would like to add:**

#955 changed cloud config secret keys from `azure.json` to `control-plane-azure.json` and `worker-node-azure.json`.

slack thread: https://kubernetes.slack.com/archives/CEX9HENG7/p1619814825276400

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
In terms of forward porting this fix, we decided in office hours to deprecate it for 0.5.x, and remove it in 0.6.x while having documentation guiding the users with an upgrade path.
cc @nader-ziada @devigned

**Comment by nader-ziada** [comment]
@shysank does that mean we need to to cherry pick the fix from `release-0.4` to `main` for the first release of 0.5 and mark it as deprecated?

**Comment by shysank** [comment]
Yes, and maybe add some warning that it'll be removed in the subsequent release.
