### ISSUE TITLE
Add tests for conversion from previous API versions

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1365]
We should add similar tests for conversion webhooks than https://github.com/kubernetes-sigs/cluster-api/pull/4417 to make sure that v1alpha3 --> v1alpha4 conversion actually works for each CRD.

/help
/good-first-issue

**Comment by sonasingh46** [comment]
@CecileRobertMichon - I would like to work on this issue.

**Comment by nprokopic** [comment]
Slightly related, while working on https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1634, I added a unit test for `AzureClusterIdentity` conversion, since it was missing, and it failed, so I will also include `AzureClusterIdentity` conversion fix in #1634.

**Comment by willie-yao** [comment]
/close

This is no longer needed as v1alpha3 and v1alpha4 have been removed in #3393
