### ISSUE TITLE
Consolidate log collection scripts for e2e tests

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1372]
/kind cleanup

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The upstream tests collect logs in different ways.  

The conformance tests collect logs via the [e2e framework](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_logcollector.go).  An example output is: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/capz-conformance-master/1391754619595526144/artifacts/

The provider specific tests collect logs [via a script](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/hack/log/log-dump.sh). An example output is: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/capz-azure-file-machinepool-master/1391279987113332736/artifacts/

**What did you expect to happen:**
Logs to be collected in same format for easier debugging and consistent output.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I'm not sure there's a good way to plug in the framework AfterSuite() log collection for stuff that isn't actually running CAPI tests (eg. the AzureFile job above just calls the CAPZ script for dev cluster creation and then the tests are run from the azure-file repo). I don't think using the bash script for everything is what we want either since it's less complete and not shared with other providers. 

@chewong thoughts?

**Comment by chewong** [comment]
I agree that https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/hack/log/log-dump.sh is pretty outdated considering how the CAPI test framework has evolved over the past year. It'd be great if the CAPI test framework can help us manage the lifecycle of both management and workload cluster (and also unifying the logging experience) while allowing us to inject any arbitrary test to run against the workload cluster.

**Comment by marosset** [comment]
> We discussed that this is still an issue, fyi @marosset
> 
> /remove-lifecycle rotten

Ack - yes this is still an issue.
