### ISSUE TITLE
Cloud provider config customization - cloudProviderBackoff

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1382]
/kind feature

**Describe the solution you'd like**
#1373 allowed rate limits to be customized in cloud provider config. We also might want to do this for other properties. This issue tracks cloud provider backoff config that we want to override. specifically the following ones:

Name | Description | Remark
-- | -- | --
cloudProviderBackoff | Enable exponential backoff to manage resource request retries | Boolean value, default to false
cloudProviderBackoffRetries | Backoff retry limit | Integer value, valid if&nbsp;cloudProviderBackoff&nbsp;is true
cloudProviderBackoffExponent | Backoff exponent | Float value, valid if&nbsp;cloudProviderBackoff&nbsp;is true
cloudProviderBackoffDuration | Backoff duration | Integer value, valid if&nbsp;cloudProviderBackoff&nbsp;is true
cloudProviderBackoffJitter | Backoff jitter | Float value, valid if&nbsp;cloudProviderBackoff&nbsp;is true

**Anything else you would like to add:**
https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@shysank i am interested to pick this issue.

**Comment by Ankitasw** [comment]
@shysank / @CecileRobertMichon  do we need to add back off config options in RateLimitConfig or shall we define a new config for backoff and then override it as how it is done for rate limits?

**Comment by shysank** [comment]
@Ankitasw I don't think should be part of RateLimitConifg. You can create a new struct to encapsulate backoff options and embed it in CloudProviderConfigOverrides. Eventually they must map to cloud-provide-azure [config](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/d585c2031925b39c925624302f22f8856e29e352/pkg/provider/azure.go#L93) struct which we do it using our own [CloudProviderConfig](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/bdd9f8c0c92505224215a2e5e234088ee8234d32/controllers/helpers.go#L323) struct.
