### ISSUE TITLE
Support existing IP as node outbound IPs

### ISSUE THREAD

**Issue by yangl900** [kubernetes-sigs/cluster-api-provider-azure#1394]
/kind feature

**Describe the solution you'd like**

In many cases user would like to configure the cluster outbound IP to a set of pre-created static IPs or IP prefixes. External systems like SQL firewall will whitelist this IP in its ACL. 

We should allow customization of node outbound IPs to reuse existing IPs. This way new clusters, or re-created clusters can reuse the same set of IP, such that all remote ACLs won't need update.

Interface would be a new `outboundIPs` property in the `NodeOutboundLB` property from azurecluster

Summary
* Use outbound IP as ACL is common practice
* Modifying those ACLs are difficult, sometimes impossible
* Re-create cluster / migrating old clusters (from self-managed) to cluster API is common scenario
* To allow reusing same ACL, we should allow reuse existing IP as outbound

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: any
- Kubernetes version: (use `kubectl version`): any
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by CecileRobertMichon** [comment]
Related to #1159

**Comment by shysank** [comment]
@Ankitasw are you still working on this one?

**Comment by Ankitasw** [comment]
Hey @shysank no I have not got enough time to relook into this, if somebody is interested, they can take ahead the existing PR opened and work on it.

**Comment by CecileRobertMichon** [comment]
Prior work: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1747

**Comment by nawazkh** [comment]
Had an internal discussion with the team about this issue. 
We are trying to test another approach on exposing all the LB Specs, hosted by ASO, wrapped by CAPZ. 
If that succeeds, requests like these, where the user wants to pick different permutations of resources to acheive their green path (here that resource is LB and public IP) would get much easier to achieve. 
If that approach doesn't succeed, we will reopen this issue. 

For now, closing out the issue and the PR related to it. 
/close
