### ISSUE TITLE
Update containerservice sdk API version from 2020-02-01 to 2021-05-01

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#1418]
/kind feature
/area managedclusters

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Update the container service sdk from 2020-02-01 to the latest as the existing api is outdated and does not have the latest changes.

eg: The existing api has support only for legacy AAD integration with AKS. The latest API model provides support for the new style of integration of AAD with AKS. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
/retitle Update containerservice sdk API version from 2020-02-01 to 2021-05-01
