### ISSUE TITLE
Add documentation for AzureMachinePool.Spec.Strategy

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1427]
/kind feature

**Describe the solution you'd like**
There should be documentation for AzureMachinePool.Spec.Strategy and how the setting affect rolling out updates and deleting AzureMachinePoolMachines. This is a follow up from: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1332#discussion_r648565449.

**Comment by nader-ziada** [comment]
I think this is fixed, right @devigned?

**Comment by devigned** [comment]
/close

Yes. Good find, @nader-ziada. Thank you!
