### ISSUE TITLE
e2e workload validation for managedclusters

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#1455]
/kind feature
/area managedclusters

**Describe the solution you'd like**
add workload validation e2e building on the work in #1386

**Anything else you would like to add:**
nothing crazy, something comparable to existing capz clusters. mostly sanity testing.

**Comment by alexeldeib** [comment]
alternatively/in addition: validation of the AKS ARM resource vs. the CRD?

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1509 gets us some initial validation

**Comment by alexeldeib** [comment]
/good-first-issue

adding some additional validation would be fairly straightforward

**Comment by LochanRn** [comment]
Hi @alexeldeib would like to pick this issue. I am not good with e2e so doing this will give me a good learning. So if i have understood correctly, we should scale up workloads and scale them down and then check if the workloads are being added as expected.

**Comment by alexeldeib** [comment]
there are a few things we can do here:
- scale up/down agent pools like you mention, validate things follow our expectations
- run a more complex workload than the timesync daemonset. 
    - create a load balancer, is it reachable
    - validate network policies
    - etc.

mostly thinking we should try to align testing on unmanaged/managed clusters as closely as possible (where it makes sense).

**Comment by LochanRn** [comment]
cool, I will pick this. But I might bug you on slack for help. Please spare with me 😜
