### ISSUE TITLE
[docs/UX] should we reduce the number of flavors

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1456]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The number of "flavors" in templates/ has grown exponentially as new features were added during the v1alpha4 dev cycle. Each flavor doesn't represent a best practices cluster spec or even a complete cluster, but rather the default working cluster with some modifications to turn on the feature on top. The flavors get published as [release artifacts](https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases) and can be used by `clusterctl generate cluster --flavor`. 

There are currently 17 (!!) cluster templates in the [templates/](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/templates) directory that will be translated to flavors when we release v0.5.0. 

Is this too many? Will it confuse users more than help them? Should we keep the "quickstart" flavors to the bare minimum and keep all the other feature templates in the test/ template dir?

Opening this issue to start a discussion. Will also bring it up at the next office hours.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
What if we decomposed all of the resources used to make the flavors, published all the decomposed resources / patches and wrote docs about how to compose those resources to create their own flavors?

**Comment by CecileRobertMichon** [comment]
I feel like the decomposed resources (or at least the patches to enable a specific feature) are already published in https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/templates/flavors. Maybe we can add more docs on composing them to create your own flavor in [readme](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/templates/flavors/README.md) + include it in the book?

**Comment by CecileRobertMichon** [comment]
[@nader-ziada on slack] I agree there are too many and I would assume most users would need some combination

**Comment by CecileRobertMichon** [comment]
[@alexeldeib on slack] I agree it’s a lot but I like that we have so many full examples. We also do a decent job of using patches to generate the full manifests, so what David mentioned on GH is kind of a thing already if you go look at the source

**Comment by devigned** [comment]
> I feel like the decomposed resources (or at least the patches to enable a specific feature) are already published in https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/templates/flavors. 

I was thinking more like including them in the release artifacts so they would be more easily used / linked.

**Comment by nader-ziada** [comment]
how about something along the following 
- move the test templates to the test folder similar to how CAPD does (and PR #1423) 
- keep a basic template and the patches in the templates folder
- document how users can generate their own combinations using the patch files and kustomize

**Comment by alexeldeib** [comment]
> Is this too many? Will it confuse users more than help them? 

I think this intersects with Nader's slack comment -- I like the number of examples, mostly because it's easy for a user to get something that just works (even if the selection itself is confusing). Something more "guided" // simpler in terms of helping the user choose might be nice? which is what a cli makes me think of.

**Comment by CecileRobertMichon** [comment]
> which is what a cli makes me think of.

maybe we need better integration with https://github.com/Azure/azure-capi-cli-extension :) cc @mboersma
