### ISSUE TITLE
Stop using v1beta1 CRD's by upgrading aad-pod-identity to 1.8.0

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes-sigs/cluster-api-provider-azure#1458]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We have the `aad-pod-identity` CRDs copied in the [CAPZ repository](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/config/default/aad-pod-identity-deployment.yaml). These are `apiextensions.k8s.io/v1beta1` CRDs. But
`aad-pod-identity` v1.8.0 has been released. [The biggest change is that the CRD's have been migrated from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1](https://azure.github.io/aad-pod-identity/docs/#v18x-breaking-change). 

It would be good to stop using apiextensions.k8s.io/v1beta1 CRDs. We can upgrade the `aad-pod-identity` dependency and the CRDs in the capz repository.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The release notes would need to reflect that it contains a breaking change.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nader-ziada** [comment]
this is coming in PR #1360

**Comment by CecileRobertMichon** [comment]
this done

/close
