### ISSUE TITLE
Missing MaxSurge in KCP scale-in e2e test

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-azure#1462]
`Spec.RolloutStrategy.RollingUpdate.MaxSurge` should be set to 0 for testing scale-in rollout. See https://github.com/kubernetes-sigs/cluster-api/pull/4347/

Looks like it is not set here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/data/infrastructure-azure/cluster-template-kcp-scale-in.yaml

**Comment by devigned** [comment]
The link above for `cluster-template-kcp-scale-in.yaml` is 404 for me. However, I do see that https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f3ecc734ea7b1c216cf46659baff191dccb10e6e/test/e2e/data/infrastructure-azure/v1alpha4/cluster-template-kcp-scale-in/cluster-with-kcp.yaml#L8 was updated recently with https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1423. I believe this should resolve this issue. Do you agree, @sedefsavas?

**Comment by nader-ziada** [comment]
#1423 just got merged and should fix it

**Comment by sedefsavas** [comment]
yes, #1423 solved the issue.

**Comment by nader-ziada** [comment]
thanks @sedefsavas
