### ISSUE TITLE
Add AzureClusterIdentity to all published templates 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1471]
/kind feature

**Describe the solution you'd like**
- Add `AzureClusterIdentity` to the published templates to allow users to set the credentials using a Secret instead of environment variables.
- The templates need the AzureClusterIdentity resource and a reference to it in the AzureCluster.
- Add comment about needing a secret with the `password` already created.

This will make the Azure credentials environment variables optional in the infrastructure components yaml spec by defaulting the values to "". 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/close

done in #1360
