### ISSUE TITLE
AKS multi-tenancy e2e test flaky 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1481]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
- the e2e test `Creating an AKS cluster using a different SP identity` has been failing a few times in the last few days when running e2e tests even if the change is unrelated to ManagedControlPlane or the exp/ folder
- Can't find anything obvious in the logs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
/assign 

there are some minor fixes we can make in the reconciler to avoid extra requeues, but the most frequent failure I've found seems to be related to list VMSS returning stale data for a long time, and I'm investigating that.

**Comment by alexeldeib** [comment]
ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1488
