### ISSUE TITLE
CAPI: Control plane creation is stuck in Scaling Up state.

### ISSUE THREAD

**Issue by abhishek-jnpr** [kubernetes-sigs/cluster-api-provider-azure#1482]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created CAPI cluster and followed below steps.

1) kind create cluster
2) clusterctl init --infrastructure azure -b kubeadm:v0.3.19 -c kubeadm:v0.3.19 --core cluster-api:v0.3.19
3) clusterctl config cluster capi-quickstart --kubernetes-version v1.18.16 --control-plane-machine-count=3 --worker-machine-count=3 > capi-quickstart.yaml

abhishekr-mbp:capi abhishekr$ kind version
kind v0.11.1 go1.16.4 darwin/amd64
abhishekr-mbp:capi abhishekr$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.19", GitCommit:"665d56652a787180dc36ecbfdf183b1e436fba75", GitTreeState:"clean", BuildDate:"2021-06-09T18:25:37Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
abhishekr-mbp:capi abhishekr$

```
abhishekr-mbp:capi abhishekr$ kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioned
abhishekr-mbp:capi abhishekr$
```
```
abhishekr-mbp:capi abhishekr$ clusterctl describe cluster capi-quickstart
NAME                                                                READY  SEVERITY  REASON                   SINCE  MESSAGE
/capi-quickstart                                                    False  Warning   ScalingUp                34m    Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - AzureCluster/capi-quickstart              True                                      36m
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane  False  Warning   ScalingUp                34m    Scaling up control plane to 3 replicas (actual 1)
│ └─Machine/capi-quickstart-control-plane-6hkj8                     False  Info      WaitingForBootstrapData  35m    1 of 2 completed
└─Workers
  └─MachineDeployment/capi-quickstart-md-0
    └─3 Machines...                                                 False  Info      WaitingForBootstrapData  36m    See capi-quickstart-md-0-855c5bfccf-hn2mn, capi-quickstart-md-0-855c5bfccf-kwb58, ...
```

```
abhishekr-mbp:capi abhishekr$ kubectl describe  KubeadmControlPlane/capi-quickstart-control-plane
Name:         capi-quickstart-control-plane
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=capi-quickstart
Annotations:  <none>
API Version:  controlplane.cluster.x-k8s.io/v1alpha3
Kind:         KubeadmControlPlane
Metadata:
  Creation Timestamp:  2021-06-30T17:46:24Z
  Finalizers:
    kubeadm.controlplane.cluster.x-k8s.io
  Generation:  1
  Managed Fields:
    API Version:  controlplane.cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:infrastructureTemplate:
          .:
          f:apiVersion:
          f:kind:
          f:name:
        f:kubeadmConfigSpec:
          .:
          f:clusterConfiguration:
            .:
            f:apiServer:
              .:
              f:extraArgs:
                .:
                f:cloud-config:
                f:cloud-provider:
              f:extraVolumes:
              f:timeoutForControlPlane:
            f:controllerManager:
              .:
              f:extraArgs:
                .:
                f:allocate-node-cidrs:
                f:cloud-config:
                f:cloud-provider:
                f:cluster-name:
              f:extraVolumes:
            f:etcd:
              .:
              f:local:
                .:
                f:dataDir:
          f:diskSetup:
            .:
            f:filesystems:
            f:partitions:
          f:files:
          f:initConfiguration:
            .:
            f:nodeRegistration:
              .:
              f:kubeletExtraArgs:
                .:
                f:cloud-config:
                f:cloud-provider:
              f:name:
          f:joinConfiguration:
            .:
            f:nodeRegistration:
              .:
              f:kubeletExtraArgs:
                .:
                f:cloud-config:
                f:cloud-provider:
              f:name:
          f:mounts:
          f:useExperimentalRetryJoin:
        f:replicas:
        f:version:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-06-30T17:46:24Z
    API Version:  controlplane.cluster.x-k8s.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"kubeadm.controlplane.cluster.x-k8s.io":
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
        f:ownerReferences:
          .:
          k:{"uid":"f228de8a-46fd-4bf2-a51d-005a4be5bbe1"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:status:
        .:
        f:conditions:
        f:observedGeneration:
        f:replicas:
        f:selector:
        f:unavailableReplicas:
        f:updatedReplicas:
    Manager:    manager
    Operation:  Update
    Time:       2021-06-30T17:48:14Z
  Owner References:
    API Version:           cluster.x-k8s.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Cluster
    Name:                  capi-quickstart
    UID:                   f228de8a-46fd-4bf2-a51d-005a4be5bbe1
  Resource Version:        2030
  UID:                     ff2bbfb9-09f4-4a21-9a76-6900b753707a
Spec:
  Infrastructure Template:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
    Kind:         AzureMachineTemplate
    Name:         capi-quickstart-control-plane
    Namespace:    default
  Kubeadm Config Spec:
    Cluster Configuration:
      API Server:
        Extra Args:
          Cloud - Config:    /etc/kubernetes/azure.json
          Cloud - Provider:  azure
        Extra Volumes:
          Host Path:                /etc/kubernetes/azure.json
          Mount Path:               /etc/kubernetes/azure.json
          Name:                     cloud-config
          Read Only:                true
        Timeout For Control Plane:  20m0s
      Controller Manager:
        Extra Args:
          Allocate - Node - Cidrs:  true
          Cloud - Config:           /etc/kubernetes/azure.json
          Cloud - Provider:         azure
          Cluster - Name:           capi-quickstart
        Extra Volumes:
          Host Path:   /etc/kubernetes/azure.json
          Mount Path:  /etc/kubernetes/azure.json
          Name:        cloud-config
          Read Only:   true
      Dns:
      Etcd:
        Local:
          Data Dir:  /var/lib/etcddisk/etcd
      Networking:
      Scheduler:
    Disk Setup:
      Filesystems:
        Device:  /dev/disk/azure/scsi1/lun0
        Extra Opts:
          -E
          lazy_itable_init=1,lazy_journal_init=1
        Filesystem:  ext4
        Label:       etcd_disk
        Device:      ephemeral0.1
        Filesystem:  ext4
        Label:       ephemeral0
        Replace FS:  ntfs
      Partitions:
        Device:      /dev/disk/azure/scsi1/lun0
        Layout:      true
        Overwrite:   false
        Table Type:  gpt
    Files:
      Content From:
        Secret:
          Key:      control-plane-azure.json
          Name:     capi-quickstart-control-plane-azure-json
      Owner:        root:root
      Path:         /etc/kubernetes/azure.json
      Permissions:  0644
    Init Configuration:
      Local API Endpoint:
        Advertise Address:
        Bind Port:          0
      Node Registration:
        Kubelet Extra Args:
          Cloud - Config:    /etc/kubernetes/azure.json
          Cloud - Provider:  azure
        Name:                {{ ds.meta_data["local_hostname"] }}
    Join Configuration:
      Discovery:
      Node Registration:
        Kubelet Extra Args:
          Cloud - Config:    /etc/kubernetes/azure.json
          Cloud - Provider:  azure
        Name:                {{ ds.meta_data["local_hostname"] }}
    Mounts:
      [LABEL=etcd_disk /var/lib/etcddisk]
    Use Experimental Retry Join:  true
  Replicas:                       3
  Rollout Strategy:
    Rolling Update:
      Max Surge:  1
    Type:         RollingUpdate
  Version:        v1.18.16
Status:
  Conditions:
    Last Transition Time:  2021-06-30T17:48:14Z
    Message:               Scaling up control plane to 3 replicas (actual 1)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-06-30T17:47:14Z
    Reason:                WaitingForKubeadmInit
    Severity:              Info
    Status:                False
    Type:                  Available
    Last Transition Time:  2021-06-30T17:47:14Z
    Status:                True
    Type:                  CertificatesAvailable
    Last Transition Time:  2021-06-30T17:47:44Z
    Message:               1 of 2 completed
    Reason:                WaitingForBootstrapData @ Machine/capi-quickstart-control-plane-6hkj8
    Severity:              Info
    Status:                False
    Type:                  MachinesReady
    Last Transition Time:  2021-06-30T17:48:14Z
    Message:               Scaling up control plane to 3 replicas (actual 1)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  Resized
  Observed Generation:     1
  Replicas:                1
  Selector:                cluster.x-k8s.io/cluster-name=capi-quickstart,cluster.x-k8s.io/control-plane
  Unavailable Replicas:    1
  Updated Replicas:        1
Events:
  Type     Reason                 Age                   From                              Message
  ----     ------                 ----                  ----                              -------
  Warning  ControlPlaneUnhealthy  4m11s (x71 over 39m)  kubeadm-control-plane-controller  Waiting for control plane to pass preflight checks to continue reconciliation: [machine capi-quickstart-control-plane-6hkj8 does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdMemberHealthy condition]
abhishekr-mbp:capi abhishekr$
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@abhishek-jnpr can try following these steps https://capz.sigs.k8s.io/topics/troubleshooting.html to see if you find any interesting logs in the controllers and/or cloud-init ? 

The `WaitingForBootstrapData` condition seems to indicate the KubeadmConfig is having trouble generating the bootstrap data, can you please share you KubeadmConfigTemplate yaml? `kubectl get kcp - o yaml`

Also, check `kubectl logs deploy/capi-kubeadm-control-plane-controller-manager -n capi-kubeadm-control-plane-system manager -f` to see if any error messages stand out.

**Comment by abhishek-jnpr** [comment]
@CecileRobertMichon please find the logs below. There is a connection error message related to connection to workload cluster.

abhishekr-mbp:capi abhishekr$ kubectl logs deploy/capi-kubeadm-control-plane-controller-manager -n capi-kubeadm-control-plane-system manager -f
I0702 18:54:20.112881       1 controller.go:182] controllers/KubeadmControlPlane "msg"="Could not connect to workload cluster to fetch status" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "err"="failed to create remote cluster client: default/capi-quickstart: Get https://capi-quickstart-21785c0e.eastus.cloudapp.azure.com:6443/api?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
I0702 18:54:20.114833       1 controller.go:244] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default"
I0702 18:54:20.149823       1 controller.go:355] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "Desired"=3 "Existing"=1
I0702 18:54:20.149946       1 scale.go:212] controllers/KubeadmControlPlane "msg"="Waiting for control plane to pass preflight checks" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "failures"="[machine capi-quickstart-control-plane-6hkj8 does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdMemberHealthy condition]"
I0702 18:54:50.124054       1 controller.go:182] controllers/KubeadmControlPlane "msg"="Could not connect to workload cluster to fetch status" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "err"="failed to create remote cluster client: default/capi-quickstart: Get https://capi-quickstart-21785c0e.eastus.cloudapp.azure.com:6443/api?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
I0702 18:54:50.125838       1 controller.go:244] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default"
I0702 18:54:50.163212       1 controller.go:355] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "Desired"=3 "Existing"=1
I0702 18:54:50.163339       1 scale.go:212] controllers/KubeadmControlPlane "msg"="Waiting for control plane to pass preflight checks" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "failures"="[machine capi-quickstart-control-plane-6hkj8 does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdMemberHealthy condition]"
I0702 18:55:20.141362       1 controller.go:182] controllers/KubeadmControlPlane "msg"="Could not connect to workload cluster to fetch status" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "err"="failed to create remote cluster client: default/capi-quickstart: Get https://capi-quickstart-21785c0e.eastus.cloudapp.azure.com:6443/api?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
I0702 18:55:20.143034       1 controller.go:244] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default"
I0702 18:55:20.178836       1 controller.go:355] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "Desired"=3 "Existing"=1
I0702 18:55:20.178958       1 scale.go:212] controllers/KubeadmControlPlane "msg"="Waiting for control plane to pass preflight checks" "cluster"="capi-quickstart" "kubeadmControlPlane"="capi-quickstart-control-plane" "namespace"="default" "failures"="[machine capi-quickstart-control-plane-6hkj8 does not have APIServerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have ControllerManagerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have SchedulerPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdPodHealthy condition, machine capi-quickstart-control-plane-6hkj8 does not have EtcdMemberHealthy condition]"

**Comment by abhishek-jnpr** [comment]
@CecileRobertMichon  Thanks for the document reference. I was able to figure out the issue by collecting logs with below command.

kubectl logs deploy/capz-controller-manager -n capz-system manager

After providing required NAT permission to IAM role, I can now see the VMs created in azure portal.

E0703 07:01:57.178226       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachineService: failed to create inbound NAT rule: failed to create inbound NAT rule capi-quickstart-control-plane-xvcjp: network.InboundNatRulesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code=\"AuthorizationFailed\" Message=\"The client 'f33caa02-a6e5-4a48-94a6-23586998fde7' with object id 'f33caa02-a6e5-4a48-94a6-23586998fde7' does not have authorization to perform action 'Microsoft.Network/loadBalancers/inboundNatRules/write' over scope '/subscriptions/bf4b32bf-e155-4ecd-a981-4b348978e06a/resourceGroups/capi-quickstart/providers/Microsoft.Network/loadBalancers/capi-quickstart-public-lb/inboundNatRules/capi-quickstart-control-plane-xvcjp' or the scope is invalid. If access was recently granted, please refresh your credentials.\"" "controller"="azuremachine" "name"="capi-quickstart-control-plane-xvcjp" "namespace"="default"
I0703 07:03:02.809516       1 azurecluster_controller.go:187] controllers/AzureCluster "msg"="Reconciling AzureCluster" "azureCluster"="capi-quickstart" "cluster"="capi-quickstart" "namespace"="default"

**Comment by nadiia-dubchak** [comment]
Hello @abhishek-jnpr I seem to be having the same problem as you did. Could you please clarify how exactly you were able to "provide required NAT permission to IAM role"? I'm not sure what you mean by this, thank you!

**Comment by jackfrancis** [comment]
@nadiia-dubchak After reading the comments it seems like he updated the IAM configuration (added new role assignment(s)) to the service principal or user|machine-assigned identity his management cluster is using to build Azure infra. For example, the easiest way would be to give your service principal or identity "Contributor" access to the subscription that your cluster is runnning on (though those permissions may be too broad depending on your scenario).

@abhishek-jnpr can you share more details about how you unblocked your scenario? Thanks!
