### ISSUE TITLE
Create separate pre-submit job for changes in exp/ folder

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#1483]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- Run the e2e test related to changes in the `exp` folder only when a PR is making any changes in relevant code path
- This includes for example this ManagedControlPlane e2e test `Creating an AKS cluster using a different SP identity`
- Skip these tests from the main presubmits

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
This is done

/close
