### ISSUE TITLE
Pre-Created VNET seems to fail cluster creation

### ISSUE THREAD

**Issue by monojit18** [kubernetes-sigs/cluster-api-provider-azure#1494]
/kind bug

**What steps did you take and what happened:**

1. Create a VNET on Azure
2. Create 2 Subnets - Master and Worker
3. Specify those details in the cluster config yaml under _networkspec_ section e.g.

_networkSpec:
    vnet:
      name: capz-workshop-cluster-vnet
      cidrBlocks:
      - 16.0.0.0/21
    subnets:
    - name: capz-master-subnet
      role: control-plane
      cidrBlocks:
      - 16.0.0.0/24
    - name: capz-worker-subnet
      role: node
      cidrBlocks:
      - 16.0.1.0/24
    apiServerLB:
      type: Public_

4. Deploy cluster config yaml
5. Cluster creation starts as-usual but is hung at control plane Provisioning step
_kubectl get Machine -A_ 
always shows control panel node as _Provisioning_ and Worker nodes as _Pending_

**What did you expect to happen:**
The cluster to be created with all success

**Anything else you would like to add:**
Removing the pre-created VNET from Azure and then specifying the same configuration thru cluster config yaml (i.e. allowing CAPZ to create the VNET itself) allows Cluster to be created successfully

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
Do you see any errors coming from the CAPZ controller logs? Can you share any errors the controller is logging?

**Comment by CecileRobertMichon** [comment]
some more info on checking those: https://capz.sigs.k8s.io/topics/troubleshooting.html

**Comment by monojit18** [comment]
I will try and look into the logs as suggested by tomorrow and let you know!
sorry for delays due to other priorities

**Comment by monojit18** [comment]
Team,
[capz-error-log.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/6871952/capz-error-log.txt)

This is the error log with pre-created VNET and Subnet in a pre-created Resource Group

K8s Version: 1.18.19
clusterctl version: 3.20
OS: MacOS BigSur 11.4

The master Node is created and I can VM is in running state in the portal.
But the Reconciling step is hanging forever and hence subsequent Worker machine are also on Pending state

Following is what I am getting from:
k get Machine -A

_default     capz-k8s-cluster-control-plane-92772     azure:///subscriptions/6bdcc705-8db6-4029-953a-e749070e6db6/resourceGroups/capz-k8s-rg/providers/Microsoft.Compute/virtualMachines/capz-k8s-cluster-control-plane-tgldb   Provisioning   v1.18.19
default     capz-k8s-cluster-md-0-75c9fd6849-49zpl                                                                                                                                                                             Pending        v1.18.19
default     capz-k8s-cluster-md-0-75c9fd6849-crv6c                                                                                                                                                                             Pending        v1.18.19
default     capz-k8s-cluster-md-0-75c9fd6849-z8tww                                                                                                                                                                            Pending        v1.18.19_
<img width="1393" alt="Screenshot 2021-07-24 at 11 19 29 AM" src="https://user-images.githubusercontent.com/2395966/126858865-320cd219-b01d-4d55-83ad-cc3ced9cd6a7.png">

Due to this my Private Cluster creation is also failing: #1495 
Can you please help/suggest if I am missing anything here?

**Comment by devigned** [comment]
Looks like the machine deployment never sees the bootstrap secret become available. It would probably be helpful if you can provide the CAPI & CABPK logs.

**Comment by monojit18** [comment]
> Looks like the machine deployment never sees the bootstrap secret become available. It would probably be helpful if you can provide the CAPI & CABPK logs.

Sure, can you tell me how to get those? can you please tell me the commands?

**Comment by devigned** [comment]
If you run `kubectl get pod -A` you should see `capi-system` and the capi controller pod. Similarly, you should see the capbk pod. Run `kubectl log pod -n capi-system capi-controller-pod-name` and then the analogous command for capbk.

**Comment by CecileRobertMichon** [comment]
The first control plane machine is created but the Machine is still in "Provisioning" state which to me seems like it never initialized the k8s cluster. That's [this TSG case](https://capz.sigs.k8s.io/topics/troubleshooting.html#a-virtual-machine-is-running-but-the-k8s-node-did-not-join-the-cluster). If you do `kubectl describe azuremachine capz-k8s-cluster-control-plane-tgldb` you should see a status Condition that says bootstrap failed.

Can you please [check the cloud init logs](https://capz.sigs.k8s.io/topics/troubleshooting.html#checking-cloud-init-logs-ubuntu) on the control plane VM to see what went wrong?

**Comment by monojit18** [comment]
[capz-issue-logs-27072021.zip](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/6883237/capz-issue-logs-27072021.zip)

Tried capturing all the logs that you have asked for; can you please have a look and let me know if anything else is required?

**Comment by devigned** [comment]
```
[ 1261.123154] cloud-init[1771]: [2021-07-27 04:47:47] [wait-control-plane] Waiting for
the kubelet to boot up the control plane as static Pods from directory
"/etc/kubernetes/manifests". This can take up to 20m0s
[ 1261.124063] cloud-init[1771]: [2021-07-27 04:48:27] [kubelet-check] Initial timeout of
40s passed.
[ 1261.124362] cloud-init[1771]: [2021-07-27 05:08:12]
[ 1261.125053] cloud-init[1771]: [2021-07-27 05:08:12] Unfortunately, an error has
occurred:
[ 1261.126300] cloud-init[1771]: [2021-07-27 05:08:12]
timed out waiting for the
condition
[ 1261.126966] cloud-init[1771]: [2021-07-27 05:08:12]
[ 1261.127703] cloud-init[1771]: [2021-07-27 05:08:12] This error is likely caused by:
[ 1261.128283] cloud-init[1771]: [2021-07-27 05:08:12]
- The kubelet is not
running
[ 1261.128888] cloud-init[1771]: [2021-07-27 05:08:12]
- The kubelet is unhealthy
due to a misconfiguration of the node in some way (required cgroups disabled)
[ 1261.129493] cloud-init[1771]: [2021-07-27 05:08:12]
[ 1261.130085] cloud-init[1771]: [2021-07-27 05:08:12] If you are on a systemd-powered
system, you can try to troubleshoot the error with the following commands:
[ 1261.130632] cloud-init[1771]: [2021-07-27 05:08:12]
- 'systemctl status
kubelet'
[ 1261.131268] cloud-init[1771]: [2021-07-27 05:08:12]
- 'journalctl -xeu
kubelet'
```

Looks like kubelet timed out after 20 mins. One more log :crossed_fingers:. Please grab `journalctl -xeu kubelet` from the control plane node.

**Comment by monojit18** [comment]
[journalctl-control-plane.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/6902542/journalctl-control-plane.txt)

PFA

Please let me know if this helps!

BTW, log is from the Azure portal as I could not ssh into the VM with ssh capi@<apiServerIP>
<img width="927" alt="Screenshot 2021-07-29 at 11 28 00 PM" src="https://user-images.githubusercontent.com/2395966/127541926-53c774d0-5ce1-4543-93f3-93d807851284.png">

**Comment by monojit18** [comment]
Dear Team,

Just wanted to check if this information helps or something else is expected?

**Comment by CecileRobertMichon** [comment]
@monojit18 have you tried with a larger vnet/subnet cidr? /24 is pretty small, I wonder if that's causing any issues. That's the only thing I can think of that would be different between your pre-created vnet and the CAPZ created one.

Unfortunately, the journal logs you sent above are truncated so it's not showing any useful debugging information. I can try to repro later with the same subnet size to see if I can find out more. Our e2e tests are creating clusters with a pre-existing Vnet (larger CIDR though) at every run successfully so it's not a generalized issue it seems.

**Comment by monojit18** [comment]
@CecileRobertMichon : OK Sure I will try with a larger CIDR also....surprisingly it is getting created with same CIDR range  the template!
But I am now suspecting another thing - https://capz.sigs.k8s.io/topics/custom-vnet.html - looking at this link; it seems when I want to have pre-created VNETs, I should not specify the CIDR again!
I will try around the options and update here...

**Comment by monojit18** [comment]
This seems to be working now. For Pre-Created VNet, I have now attached a pre-configured NSG allowing 6443 port as suggested in the https://capz.sigs.k8s.io/topics/custom-vnet.html
(_If providing an existing vnet and subnets with existing network security groups, make sure that the control plane security group allows inbound to port 6443, as port 6443 is used by kubeadm to bootstrap the control planes. Alternatively, you can provide a custom control plane endpoint in the KubeadmConfig spec._)

Post that everything works as expected!
Thanks for all the help and suggestion...Closing this issue now!

But one caveat: I think it would be a better seamless experience, had the CAPZ api can take care of this, in case of no-NSG, i would create and attach one or the same?

Thanks again for the hep!

**Comment by CecileRobertMichon** [comment]
> But one caveat: I think it would be a better seamless experience, had the CAPZ api can take care of this, in case of no-NSG, i would create and attach one or the same?

The thinking behind not doing that has been that when a vnet is not managed by CAPZ, we should not modify any of it, including subnets and NSGs, since those might be in-use by other clusters/applications.
