### ISSUE TITLE
Use mage instead of make?

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/cluster-api-provider-azure#1511]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

This issue is a proposal to replace the `Makefile` with [mage](https://magefile.org). I believe that, if done properly, this change will have a minimal impact to the developer experience. Achieving that result will require some planning and care. For that reason, I believe the size, scope and impact of this change warrants at least an enhancement proposal.

***Goals***
1. Replace `Makefile` scripting code with standard Go, which is presumably more universally understandable and accessible
1. Enlist the features of Go to improve the build system
    - The concurrency features would be particularly useful to speed up builds that can be done concurrently

***Non-Goals/Future Work***
1. Increase the number of build targets
1. Expand the scope of the `Makefile`, or its `mage` equivalent (the `magefile`)

**User Story**

As a developer on this project, I would like to read and write Go code to achieve common tasks that are currently done in the `Makefile`. I have this desire for two reasons:

- This repository is 93.4% Go code (according to GitHub), so context switching to the Make language is sub-optimal
- Go's features can be used to improve the experience for all developers on this project

**Detailed Description**

I would like the `Makefile` to be replaced with a `magefile`, possibly over multiple smaller changes.

**Contract changes [optional]**

None

**Data model changes [optional]**

None

/kind proposal

**Comment by jackfrancis** [comment]
Hi @arschles!

**Comment by arschles** [comment]
Hi @jackfrancis ! 👋

**Comment by arschles** [comment]
Does anybody have any thoughts on this? I'm happy to close it if nobody is interested.

**Comment by devigned** [comment]
If we were to stop using `make`, I would prefer [just](https://github.com/casey/just). I don't have anything against `mage`. I find `just` to be easier to use.
