### ISSUE TITLE
Add support for cert/pwd auth for cloud provider azurejson

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1521]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When the AzureClusterIdentity uses a Certificate & password, it should be able to pass those to the azurejson secret for cloud provider auth if no managed identity is specified.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
The issue I'm running into here is that cloud provider only accepts 

```
	// The path of a client certificate for an AAD application with RBAC access to talk to Azure RM APIs
	AADClientCertPath string `json:"aadClientCertPath,omitempty" yaml:"aadClientCertPath,omitempty"`
```

which is the _filepath_ to a certificate file, which means that the file must be not only written to the VM but also mounted on the CCM container. I'm unable to do this from the CAPZ azurejson controller.

**Comment by alexeldeib** [comment]
Volume mount the host path to ccm? Doesn’t it require a patch on ccm no matter what for the volume mount? I realize that means cluster template changes, but I think it’s reasonable to ask for that if you use this functionality

**Comment by CecileRobertMichon** [comment]
> Doesn’t it require a patch on ccm no matter what for the volume mount? I realize that means cluster template changes, but I think it’s reasonable to ask for that if you use this functionality

It does, and yes that might be what have to end up doing but this is a step down from the original ask of getting the cert from the AzureClusterIdentity and putting it in the cloud provider config (like SP client secret). The other problem is that I have no good way of knowing which filepath it's at since the user can put it wherever they want so it's tricky to set the cloud provider config `AADClientCertPath` value for them.

**Comment by CecileRobertMichon** [comment]
This is what I came up with: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1531/files#diff-2ecc665ce49ded769d9199f6979a596aaeb1554236e93cfbf7524596095ce359R126
