### ISSUE TITLE
NAT Gateway flavor fails with Public IP not found

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1525]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

Tried to create a NAT Gateway cluster using the NAT Gateway template with Tilt, got this error:

```
[manager] E0714 00:13:48.203297      36 controller.go:302] controller-runtime/manager/controller/azurecluster "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to reconcile public IP: cannot create public IP: network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Network/publicIPAddresses/subscriptions' under resource group 'nat-gateway-template' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"" "name"="nat-gateway-template" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureCluster" 
```

@nprokopic @shysank what am I missing? is there something special that needs to be done for this to work on my sub or is it a bug in the code?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
I think the bug is because of this: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/dd6fadb1ee9992dd05327de6d879dd2e55ae79c1/azure/services/natgateways/natgateways.go#L106

We are trying to set nat gw pip id to Name which contains `/` and hence it fails.

**Comment by shysank** [comment]
Ah, just noticed the good-first-issue tag. Sorry about that.

**Comment by CecileRobertMichon** [comment]
> Ah, just noticed the good-first-issue tag. Sorry about that.

no problem, thanks for taking care of it :D

**Comment by fiunchinho** [comment]
@CecileRobertMichon I believe you confused @nprokopic and me :smile: . I'm glad the issue is fixed now.

**Comment by CecileRobertMichon** [comment]
oops, sorry about that 😄
