### ISSUE TITLE
Webhook registration should accept both v1 and v1beta1 admissions

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1528]
Admission Review was previously set to only accept v1beta1 objects given
that Controller Runtime didn't support v1 (even though the two revisions
are effectively the same). We should add support for both within our
manifests before k8s 1.22.

We should implement the equivalent of https://github.com/kubernetes-sigs/cluster-api/pull/4942 for CAPZ webhhooks. 

To do so, we need to edit the kubebuilder annotations in each _webbook.go file and run `make generate` to update manifests.

/help
/good-first-issue
/priority-important-soon

Marking as good-first-issue because it's a small scope, well defined change but feel free to assign even if this isn't your first issue.

**Comment by Evalle** [comment]
happy to help, /assign
