### ISSUE TITLE
Support for windows worker nodes

### ISSUE THREAD

**Issue by awesomenix** [kubernetes-sigs/cluster-api-provider-azure#153]
/kind feature

Since kubernetes 1.14 just GA windows worker nodes, add support for the same in cluster api

**Describe the solution you'd like**
1. VM Extension service needs to be refactored to handle CSE in Microsoft.Compute namespace https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f53efdb852dab776e412e4c0cd5a91cc3f760019/pkg/cloud/azure/services/virtualmachineextensions/virtualmachineextensions.go#L69
2. Change default CNI to use Flannel, which has windows support (part of addons)
2. Change VM Startup scripts to include support for windows, following guide here https://github.com/Azure/aks-engine/blob/1242dcc6fa5f7a55c685eb94fd82d8f668e90965/parts/k8s/kuberneteswindowssetup.ps1

**Anything else you would like to add:**
aks-engine has successful implementation, following the process would help implementing it here.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by justaugustus** [comment]
Currently blocked on adding support for Kubernetes 1.14: #154
I'm fine with this, but the CNI needs to be configurable. Default to weave for most cases, but use flannel, if you need to support Windows.

/priority important-longterm
/milestone next

**Comment by justaugustus** [comment]
Added Canal (flannel + Calico policy) as CNI in #181.

**Comment by justaugustus** [comment]
Issue needs to updated to outline proposal for Windows support _prior_ to implementation.
cc. @PatrickLang @marosset @ksubrmnn
/assign @marosset @CecileRobertMichon

**Comment by justaugustus** [comment]
@ksubrmnn to coordinate separate meeting for Windows proposal discussion.

**Comment by timothysc** [comment]
@CecileRobertMichon - Is this targeted for any near-term milestone?  If we can lend a hand here just let us know, I think it would be great to enable windows deployments.  

cc @nader-ziada @yastij @ncdc

**Comment by CecileRobertMichon** [comment]
Windows CAEP [doc](https://docs.google.com/document/d/14evDl_3RgEFfchmgPzNw6lb1vIttN_Hb9333UnUJ734/edit?usp=sharing) authored by @jsturtevant and @ksubrmnn is under review

**Comment by jsturtevant** [comment]
The VHD image support for Windows is in progress: https://github.com/kubernetes-sigs/image-builder/pull/382
