### ISSUE TITLE
Make user-assigned identity the default in flavors and e2e

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1534]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Managed identity is more secure than writing SP creds on disk and is the recommended approach for VM identity. #1531 makes that more clear in docs. However, most templates/flavors and e2e templates are still using SP creds. We should switch them over to user-assigned so we can get better coverage on managed identity, improve our CI security, and eventually deprecate (maybe?) SP authentication for cloud-provider.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This will require a msft person to be involved on the e2e side as we'll need to provision a managed identity for Prow to be able to use with the test subscription.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nader-ziada** [comment]
@CecileRobertMichon is there anything else to do here?

**Comment by CecileRobertMichon** [comment]
yes, this would require changing the templates and adding a managed identity to prow so we can use it in e2e. For flavors, it would require users passing in the managed identity ID so it would require some extra steps and documentation.
