### ISSUE TITLE
While updating agentPools need to check for only fields which are mutable.

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#1536]
/kind bug
/area managedclusters
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When an update is triggered for agentpools the agentpool service compares the exiting agentPool and the updated agentPool  
before it actually makes a CreateOrUpdate api call.

> https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/40fde825296677d91daef3fbd083a118f2aad3b7/azure/services/agentpools/agentpools.go#L88-L101

The current logic checks for the all the fields while comparison, most of the fields are immutable and should be avoided.

The fields for which AKS supports mutating are 
- k8sVersion  
- count
- mode

**What did you expect to happen:**
The right way to implement it would be: 
```
existingProfile := containerservice.AgentPool{
	ManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{
		Count:               existingPool.Count,
		OrchestratorVersion: existingPool.OrchestratorVersion,
		Mode:                existingPool.Mode,
	},
}

normalizedProfile := containerservice.AgentPool{
	ManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{
		Count:               profile.Count,
		OrchestratorVersion: profile.OrchestratorVersion,
		Mode:                profile.Mode,
	},
}

// Diff and check if we require an update
diff := cmp.Diff(existingProfile, normalizedProfile)
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@LochanRn are you taking this one or should we mark it as good-first-issue?

/area managedclusters

**Comment by LochanRn** [comment]
I have included it in the system-node-pool PR.
