### ISSUE TITLE
Changing Kubernetes Version to 1.14 doesnt result in working cluster

### ISSUE THREAD

**Issue by awesomenix** [kubernetes-sigs/cluster-api-provider-azure#154]
/kind bug

Follow steps in getting started guide and change the kubernetes version to 1.14, clusterctl errors out with

```
Waiting for kubectl apply... unknown error couldn't kubectl apply, output: error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Initializers): invalid object doesn't have additional properties
```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
Result in a working cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.1.0
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): ubuntu 16.04/18.04

**Comment by justaugustus** [comment]
@awesomenix -- Let's reframe this. It isn't a bug; it should be a tracking issue for supporting Kubernetes 1.14.

/remove-kind bug
/kind feature
/priority important-soon
/milestone v1alpha1

**Comment by justaugustus** [comment]
I'm working on this as part of #168.
/lifecycle active

**Comment by vibhsaxena** [comment]
+ following 

similar error: 
# kubectl apply -f test.yaml
error: SchemaError(io.k8s.api.apps.v1beta1.ScaleSpec): invalid object doesn't have additional properties

**Comment by alexeldeib** [comment]
Is this still an issue? I built a cluster with 1.14.1 and it seems to work fine. Logs [here ](https://gist.github.com/alexeldeib/1fe2a9b40a65cf58a9f56ec058c343a2)(ctrl-f "1.14.1" to see the nodes).

**Comment by justaugustus** [comment]
Correct. This is no longer be an issue on `master`.
/close
