### ISSUE TITLE
remove ssh timesync test once daemonset version is stable

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#1543]
/kind cleanup 

after merging https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1509, we should get some CI signal and then remove the SSH implementation, since the DS implementation will work for private clusters and other resources with no public IPs.

**Comment by amino19** [comment]
@alexeldeib : Hey, Can I know, one have to write CI workflow for #1509 ? :slightly_smiling_face:

**Comment by jayesh-srivastava** [comment]
Hi. I am a new contributor and I want to work on this issue. Can you please guide me through this and assign me the issue?

**Comment by alexeldeib** [comment]
Slow reply, apologies 🙂 

Here's what I'd like to see here:
- Change [this test](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d52c4046c8f613e6173e0cf37508e45d5b5f9dbb/test/e2e/azure_test.go#L154-L162) to use the daemonset implementation I added in #1509 
- Run it _**a lot**_. Like, at least 20 times or so. If it fails on something unrelated to the timesync test that's fine, it'd be nice if you can record the failures so we can debug flakes later. 
- If the timesync test looks stable after many runs, delete the code for the other implementation, and we'll merge the PR. 

Looks like @amino19 might have gotten the head start on this one, but there are plenty of other issues up for grabs :)

**Comment by alexeldeib** [comment]
If you'd still like to work on this @amino19, you can `/assign` yourself or let me know and I can (and I'll remove good-first-issue/help-wanted).

**Comment by amino19** [comment]
@alexeldeib : Sure, Thanks for this info. :slightly_smiling_face:

**Comment by amino19** [comment]
@alexeldeib : I'm not that ace in it, you have to guide me a lot!  :slightly_smiling_face:
