### ISSUE TITLE
PR jobs are duplicating the test results in testgrid

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1548]
The PR jobs appear to be duplicating the test results. Example https://testgrid.k8s.io/provider-azure-presubmit#pull-kubernetes-e2e-capz-conformance

```
Kubernetes e2e suite.[sig-cli] Kubectl client Kubectl label should update the label on a resource [Conformance]
Kubernetes e2e suite.[sig-cli] Kubectl client Kubectl label should update the label on a resource [Conformance] [1]
```

_Originally posted by @jsturtevant in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1388#issuecomment-883656614_

**Comment by CecileRobertMichon** [comment]
this is only happening on the presubmit for some reason https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-conformance-v1alpha4-k8s-main

**Comment by CecileRobertMichon** [comment]
The duplicated specs haven't run since 8/11 (https://testgrid.k8s.io/provider-azure-presubmit#pull-kubernetes-e2e-capz-conformance), so this might be fixed?

/assign

Will check back in 7 days to make sure new runs don't have the issue

**Comment by jsturtevant** [comment]
I don't see duplicates in https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-conformance-v1alpha4-k8s-main

@CecileRobertMichon ok if we close?

**Comment by CecileRobertMichon** [comment]
yep I don't see anymore duplicates either

/close

**Comment by CecileRobertMichon** [comment]
> Will check back in 7 days to make sure new runs don't have the issue

oops
