### ISSUE TITLE
Use dl.k8s.io instead of hardcoded GCS URIs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1551]
https://github.com/kubernetes-sigs/cluster-api/pull/4958

/help

**Comment by sayantani11** [comment]
Hey is the issue open? I would like to contribute if I could get some insights and some help

**Comment by CecileRobertMichon** [comment]
Hi @sayantani11, yes it is. The ask is to replace all hardcoded usages of `gs://` (https://github.com/kubernetes-sigs/cluster-api-provider-azure/search?q=gs%3A%2F%2F) with dl.k8s.io, just like https://github.com/kubernetes-sigs/cluster-api/pull/4958 did for the Cluster API project.

Here is the motivation: 

> The only time a kubernetes GCS bucket name should be showing up in a
hardcoded URI is if gsutil is being used (e.g. gsutil cp gs://foo/bar .)
Otherwise, for tools like curl or wget, dl.k8s.io is much nicer for us
as a project, since we can transparently change where that redirects to
without having to change code everywhere
These changes will mean no changes will be necessary to accommodate a
gs://kubernetes-release -> gs://k8s-release migration equivalent of the
CI migration we're going through right now
(kubernetes/k8s.io#2318)

Some of our yaml templates are generated so make sure you run `make generate` after making changes to make sure all templates are updated.

**Comment by jayesh-srivastava** [comment]
Hey, @CecileRobertMichon I have made the necessary changes and made the PR. I have also signed the CLA, but its not working out. Can you please guide me?

**Comment by jayesh-srivastava** [comment]
I am a new contributor btw, and I really want to become a regular contributor.

**Comment by sayantani11** [comment]
@CecileRobertMichon Got it I am working on it

**Comment by sayantani11** [comment]
@CecileRobertMichon I wanted to know am I supposed to convert all all hardcoded usages of gs:// with dl.k8s.io or only the ones in https://github.com/kubernetes-sigs/cluster-api-provider-azure/search?q=gs%3A%2F%2F

**Comment by sayantani11** [comment]
@jayesh-srivastava  I guess before you make a PR the issue should be assigned to you. I requested to work on it first. So requesting to consider this.

**Comment by jayesh-srivastava** [comment]
@sayantani11 Oh okay. Didn't know about it. Sorry, all yours.

**Comment by CecileRobertMichon** [comment]
@jayesh-srivastava welcome! I look forward to your contributions. If you're looking for other good issues to work on, check out https://github.com/kubernetes-sigs/cluster-api-provider-azure/labels/help%20wanted.

@sayantani11 thanks for opening the PR!

**Comment by jayesh-srivastava** [comment]
@CecileRobertMichon Thank you so much. Can new contributors join the kubernetes-sigs github org?

**Comment by CecileRobertMichon** [comment]
Here are the requirements to become a member: https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by jayesh-srivastava** [comment]
Thanks for sharing.

**Comment by CecileRobertMichon** [comment]
no problem! Also you should come hang out with us in the [#cluster-api-azure](https://kubernetes.slack.com/archives/CEX9HENG7) channel on k8s slack if you're not already there

**Comment by jayesh-srivastava** [comment]
Thanks again for this. I joined the channel. Looking forward to learning with all you amazing guys.

**Comment by CecileRobertMichon** [comment]
Here's another easy first PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1555

**Comment by jayesh-srivastava** [comment]
Yeah was a bit late : ) Nevertheless will look out for good first issues. Thanks for helping.
