### ISSUE TITLE
Upgrade job should upgrade from 1.20 

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1555]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main is broken since https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1524 merged because it's trying to upgrade from 1.19 to 1.21 which is not allowed. We should change the `KUBERNETES_VERSION_UPGRADE_FROM` variable default 
in https://github.com/nader-ziada/cluster-api-provider-azure/blob/08f456963fb47f801e75eae730837e3cffe57bfc/test/e2e/config/azure-dev.yaml to `v1.20.9` which is the latest 1.20 patch.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Rahul-D78** [comment]
hi @CecileRobertMichon can I work on this

**Comment by CecileRobertMichon** [comment]
@jayesh-srivastava I'm sorry, it looks like @Rahul-D78 has already assigned themselves this issue :(

**Comment by jayesh-srivastava** [comment]
Oh okay, no worries : )

**Comment by CecileRobertMichon** [comment]
/close

@nader-ziada looks like upgrade tests are still failing after your PR https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main but we can tackle in a separate issue, closing this one
