### ISSUE TITLE
Add webhook health check

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-azure#1558]
/kind feature

**Describe the solution you'd like**
It would be nice if the controller health checks would use the readiness of the webhook server (instead of the no-op Ping).

For reference, the implementation in cluster-api: https://github.com/kubernetes-sigs/cluster-api/pull/4989

**Anything else you would like to add:**
This requires at least controller-runtime v0.9.3.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Note: This controller-runtime health check is only available since v0.9.3

this means we first need a new version of CAPI.

**Comment by sbueringer** [comment]
@CecileRobertMichon Just out of curiosity. Why do you need a new CAPI version to upgrade controller-runtime?

**Comment by CecileRobertMichon** [comment]
I guess we don't need to. Historically we've updated controller-runtime as part of CAPI updates, since CAPI defined the minimum version, but we could use a later patch, as long as we're on v0.9.x.

Whoever takes this on would have to first update the controller-runtime version in go.mod to v0.9.3.

/good-first-issue

**Comment by jayesh-srivastava** [comment]
Hi. I am a new contributor and I would like to work on this issue. Can you please guide me through this? It would be a great help to me. Also, can I assign the issue to myself?

**Comment by devigned** [comment]
@jayesh-srivastava have you had an opportunity to review the link @sbueringer helpfully added above, https://github.com/kubernetes-sigs/cluster-api/pull/4989 ? That link shows why and what needs to be applied in this repo. If you still have questions after reviewing, please let us know.

**Comment by jayesh-srivastava** [comment]
@devigned Yeah I saw that link. A little overwhelming because I am a new contributor, can you please just guide me as to where to start from?

**Comment by devigned** [comment]
The gist of what is happening in the 8 lines of the other PR is that a health check is added to the main.go to ensure the controller's webhooks have started. The same thing needs to happen in this repo.

**Comment by jayesh-srivastava** [comment]
Okay okay, I understood. Thanks @devigned . Will try to resolve this issue.

**Comment by sbueringer** [comment]
There was an error found in the healthcheck. The fix PR is already merged in controller-runtime, but we should wait until the next controller-runtime version is released with adding it to CAPZ.

xref:
* Slack discussion: https://kubernetes.slack.com/archives/CD6U2V71N/p1627643594012600
* bugfix PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1616

**Comment by sbueringer** [comment]
fyi controller-runtime v0.9.6 has been released with a fix. So we should be good to go (I also verified it via the e2e tests of the cluster-api repo).
