### ISSUE TITLE
Provide availability zones support in managedclusters

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#1559]
/kind feature
/area managedclusters

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Provide availability zones support for mananged clusters in capz

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by LochanRn** [comment]
Proposal: Add a availabilityZones spec of type *[]string  to the AMMP api.

```
type AzureManagedMachinePoolSpec struct {
	// AvailabilityZones - Availability zones for nodes. Must use VirtualMachineScaleSets AgentPoolType.
	AvailabilityZones *[]string `json:"availabilityZones,omitempty"`
       ...
}
```

The field will be immutable and can be added only during the creation of an managedcluster/agentpool.

**Comment by CecileRobertMichon** [comment]
@LochanRn this will specify zones for the agentpool if I understand correctly. What about the control plane? Will setting the zones on the first agent pool also determine zones for the control planes? 

Azure docs say

> The control plane components such as etcd or the API are spread across the available zones in the region if you define the --zones parameter at cluster creation time. The specific zones which the control plane components are spread across are independent of what explicit zones are selected for the initial node pool.

**Comment by LochanRn** [comment]
Hmm good question . :). I am not completely sure. So when we create a managedCluster it takes in an array of [agentPools](https://github.com/Azure/azure-sdk-for-go/blob/9baec13ba8eb54f684c5b0e1c645fa646eb25d3e/services/containerservice/mgmt/2021-05-01/containerservice/models.go#L2041). If we have just one agent pool(system node pool) being passed in during creation, it would depend on whether it has AZ set for that pool or not. But if there are multiple pools passed in during the creation time and say we have it set for a few agent pools and not set for others. Idk how does it decide 😅

**Comment by alexeldeib** [comment]
I had to check this a bit myself. I believe clusters are simply AZ-enabled or not. If you specify any AZs at create time, the control plane will be AZ-enabled and spread automatically. You don't get any additional configuration, and I don't believe we do e.g. single AZ control plane or anything like that. 

> The control plane components such as etcd or the API are spread across the available zones in the region if you define the --zones parameter at cluster creation time. The specific zones which the control plane components are spread across are independent of what explicit zones are selected for the initial node pool.

Looks like the docs are correct, anyway 🙂
