### ISSUE TITLE
EnableAcceleratedNetworking for the primary NIC of each VM is flaking in PRs

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1565]
/kind bug
/kind flake

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
EnableAcceleratedNetworking for the primary NIC of each VM is flaking in PRs:

the job is mostly failing: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

examples:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1563/pull-cluster-api-provider-azure-e2e/1420164734728015872
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1544/pull-cluster-api-provider-azure-e2e/1420241139092426752/build-log.txt

PR:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1544#issuecomment-888089166
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1563

**What did you expect to happen:**
Accelerated networking test to pass

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The line that is failing:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_accelnet.go#L93

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I've seen this one a couple of times as well... I'm curious to see if accelerated networking is actually disabled or if it's failing to check that it's on.

**Comment by CecileRobertMichon** [comment]
looks like it might be the later: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1563/pull-cluster-api-provider-azure-e2e/1420164734728015872/artifacts/clusters/capz-e2e-paf0p9-ha/azure-activity-logs/capz-e2e-paf0p9-ha.log has four matches for `enableAcceleratedNetworking` and they are all set to true.

**Comment by CecileRobertMichon** [comment]
Opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1571 to help us investigate
