### ISSUE TITLE
AzureMachinePool upgrade does not wait for new node to be Ready before proceeding 

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1570]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Upgraded a MachinePool to 1.21 (knowing it would fail because of #1568). The new node joined the cluster and stayed NotReady, as expected. However, this didn't stop the MP from proceeding with the upgrade, and deleting the old instance.

```
kubectl --kubeconfig kubeconfig get nodes                                                                                                                         

NAME                                     STATUS                        ROLES                  AGE     VERSION
capi-quickstart-mp-control-plane-gwcrq   Ready                         control-plane,master   9m25s   v1.20.9
capi-quickstart-mp-mp-0000000            NotReady,SchedulingDisabled   <none>                 8m1s    v1.20.9
capi-quickstart-mp-mp-0000001            Ready                         <none>                 8m4s    v1.20.9
capi-quickstart-mp-mp-0000002            NotReady                      <none>                 3m24s   v1.21.2
```

I eventually ended up with 2 nodes, both not ready, and no working node to run my potentially existing workloads.

**What did you expect to happen:** 

We should block upgrade until new nodes are Ready to make sure we always have the required number of nodes available, similar to how MachineDeployment does it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Update: the behavior might actually be correct because maxUnavailable it set to 1 which means out of 2 replicas, 1 get be unavailable.

The last ready instance did not get deleted:

```
k get ampm
NAME VERSION READY STATE
capi-quickstart-mp-mp-0-1 v1.20.9 true Succeeded
capi-quickstart-mp-mp-0-2 v1.21.2 Succeeded
capi-quickstart-mp-mp-0-3 v1.21.2 Succeeded
```

therefore respecting the contract of "always keep one node available at all times".

/assign @devigned 
to confirm and close if there's nothing to see here

**Comment by jackfrancis** [comment]
Given that we haven't received any bug reports describing this potential issue let's close this based on @CecileRobertMichon's latest comment.

/close
