### ISSUE TITLE
Tiltfile should tolerate creds set in base 64 encoding

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1573]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We should reorder the tiltfile so that auth validation (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Tiltfile#L97) happens after decoding B64 variables (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Tiltfile#L218-L221) so that B64 values are included when checking if the right creds are set.

Suggestion is to move

```
    substitutions = settings.get("kustomize_substitutions", {})
    for key in keys:
        if key[-4:] == "_B64":
            os.environ[key[:-4]] = base64_decode(os.environ[key])
```

to the beginning on `validate_auth`.           

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
Can I work on it?

**Comment by CecileRobertMichon** [comment]
@sayantani11 go for it. Make sure you test the changes locally by following the instructions at https://capz.sigs.k8s.io/developers/development.html#tilt-for-dev-in-capz to set up tilt and make sure it comes up successfully.

/assign @sayantani11

**Comment by sayantani11** [comment]
@CecileRobertMichon Are we moving
```
substitutions = settings.get("kustomize_substitutions", {})
    for key in keys:
        if key[-4:] == "_B64":
            os.environ[key[:-4]] = base64_decode(os.environ[key])
```

and also removing

```
substitutions = settings.get("kustomize_substitutions", {})
    missing = [k for k in keys if k not in substitutions and not os.environ.get(k)]
    if missing:
        fail("missing kustomize_substitutions keys {} in tilt-setting.json".format(missing))
```

**Comment by sayantani11** [comment]
It's a bit unclear to what it is meant by beginning on ```valid_auth```
