### ISSUE TITLE
Panic in conversion when upgrading to v1alpha4

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1576]
/kind bug

**What steps did you take and what happened:**
1. create cluster in v1alpha3
2. upgrade capz provider to v1alpha4
3. edit cluster created above
4. check logs  - panics in azuremachinetemplate_conversion.go

**What did you expect to happen:**
should not panic

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.5.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
We should add a test that does this conversion

**Comment by shysank** [comment]
The fuzz tests cover them, but we had overridden it for `Image`. I've fixed it in the PR.

**Comment by CecileRobertMichon** [comment]
This is what I meant: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1365

**Comment by shysank** [comment]
Agree that we should port https://github.com/kubernetes-sigs/cluster-api/pull/4417/. However, IIUC that's more related to registering older api version to scheme whereas this issue is about handling the conversion a particular field, which I think, is better covered by the fuzz tests.
