### ISSUE TITLE
 Running Kubelet in User Namespace

### ISSUE THREAD

**Issue by dmeytin** [kubernetes-sigs/cluster-api-provider-azure#1578]
/kind feature

Starting from Kubernetes 1.22 it's possible to execute the entire Kubernetes stack in the user space.
This will allow to prevent running containers as root by default.

More information is here: https://github.com/kubernetes/website/blob/48004e777f48b870c9cdc6be8cb27bab427d74e7/content/en/docs/tasks/administer-cluster/kubelet-in-userns.md#running-kubernetes-inside-rootless-dockerpodman

**Environment:**

- cluster-api-provider-azure version: 0.5.5
- Kubernetes version: (use `kubectl version`): 1.22+
- OS (e.g. from `/etc/os-release`):  all

**Comment by CecileRobertMichon** [comment]
@neolit123 @fabriziopandini is this supported by kubeadm?

**Comment by alexeldeib** [comment]
it'd also require VM images configured to use cgroupv2 by default. I don't know if that's the case yet on ubuntu 20.04, or if we'd have to configure boot params to force it. so this likely requires bootstrappper + image tweaks to work. 

worth noting, we're talking about an alpha feature in 1.22 which itself depends on another alpha feature (cgroupv2). I'm excited about those changes as much as the next person, but we're a way out from this being any kind of default IMO.

**Comment by alexeldeib** [comment]
cgroupv2 alone might not actually require anything (?) from the bootstrapping side -- off the top of my head kubelet just gets a path to a cgroup root and checks for cgroupv2 vs cgroupv1. the user ns stuff is separate of course.

**Comment by alexeldeib** [comment]
Wow, this was originally proposed 5 years ago as part of K8s 1.5 (! Not a typo). Long time coming.

sorry for spam :)

**Comment by neolit123** [comment]
> @neolit123 @fabriziopandini is this supported by kubeadm?

i haven't tried it, but it should work.
also kind uses kubeadm and it supposedly have worked for the contributor who developed it.

> worth noting, we're talking about an alpha feature in 1.22 which itself depends on another alpha feature (cgroupv2). I'm excited about those changes as much as the next person, but we're a way out from this being any kind of default IMO.

i agree, image building users could opt-in entirely on their own and this doesn't have to be on the provider side.
it is possible to pass the KubeletInUserNamespace feature gate via a kubelet CLI flag too:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

**Comment by neolit123** [comment]
> https://github.com/kubernetes/website/blob/48004e777f48b870c9cdc6be8cb27bab427d74e7/content/en/docs/tasks/administer-cluster/kubelet-in-userns.md#running-kubernetes-inside-rootless-dockerpodman

> This document describes how to run Kubernetes Node components such as kubelet, CRI, OCI, and CNI without root privileges, by using...

kube-proxy (also a node component) cannot be run as non-root for the time being:
https://github.com/kubernetes/kubeadm/issues/2410
