### ISSUE TITLE
Automatic Deployment of Log Workspace during Cluster creation

### ISSUE THREAD

**Issue by monojit18** [kubernetes-sigs/cluster-api-provider-azure#1580]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Just to make the cluster creation process as seamless as AKS:

- Allow specifying a Pre-Created Log workspace along with Resource Group in the CAPZ template; which would deploy Container Insights solution post cluster creation
- Allow specifying a flag as an intent for Monitoring  as an add-on for the cluster; which would create necessary Log Workspace and Container Insights solution post cluster creation

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is currently supported by AKS-engine

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
This is relatively easy but requires https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1145#issuecomment-887302628 for us to support any addons.

**Comment by CecileRobertMichon** [comment]
@monojit18 are you looking for this to be enabled for AKS (AzureManagedCluster) clusters, or CAPZ self-managed clusters?

**Comment by alexeldeib** [comment]
Oops, thanks Cecile. I misread “as seamless as AKS” as asking for support for managed clusters

**Comment by monojit18** [comment]
Sorry actually my bad!
I should have been bit more clear!

What I meant was to have this feature for CAPZ managed cluster - the experience would then be similar to what we do while creating AKS clusters (e.g. using Azure CLI).
Since monitoring is a very common requirement and hardly anyone would go for a K8s cluster without this feature on Azure; it would make life easy for cluster admins!

**Comment by monojit18** [comment]
> @monojit18 are you looking for this to be enabled for AKS (AzureManagedCluster) clusters, or CAPZ self-managed clusters?

Hi Cecile, I meant CAPZ managed cluster only...explained this separately below
