### ISSUE TITLE
AzureManagedMachinePool providerID should be fully lowercased to match cloud provider

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#1585]
/kind bug

**What steps did you take and what happened:**
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1503#issuecomment-893642739

Cloud provider ID on the node: capi-infra provider: azure:///subscriptions//resourceGroups/**spc_mc_lochan-rg_rnl-aks_eastus**/providers/Microsoft.Compute/virtualMachineScaleSets/aks-workerpm65h-31427834-vmss/virtualMachines/0

provider ID provider by AzureManagedMachinePool: azure:///subscriptions//resourceGroups/**SPC_MC_lochan-rg_rnl-aks_eastus**/providers/Microsoft.Compute/virtualMachineScaleSets/aks-workerpm65h-31427834-vmss/virtualMachines/0

**What did you expect to happen:**

We should normalize this here using strings.ToLower() or similar: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/eced64af3f168b8e76dfb16c76c221bf079c7f29/exp/controllers/azuremanagedmachinepool_reconciler.go#L156

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Evalle** [comment]
I can take a look at this.
/assign
