### ISSUE TITLE
Virtual network in managed clusters should be moved from AMCP to AMMP 

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#1599]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Current AzureManagedControlPlaneSpec.VirtualNetwork field is a "global" cluster field, it gets applied to all node pools.

In Azure, this part of the network spec belongs to [ManagedClusterAgentPoolProfile](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#managedclusteragentpoolprofile), so it is configurable per node pool.

Virtual network is not even part of cluster-wide [ContainerServiceNetworkProfile](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#containerservicenetworkprofile).

We must align CAPZ managed cluster network spec and adding vnetSubnetID and podSubnetID (from Azure's ManagedClusterAgentPoolProfile) to AzureManagedMachinePoolSpec as optional fields

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

See https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1590#issuecomment-896016819 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
I mentioned the original motivation for this over in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/929, but if we don't create/byo bnet, AKS will not predictably name the resource, which is kind of wonky (and marks it hard to implement e.g. #826 which is personal favorite). I'm fine with moving e.g. subnetID or name to AMMP spec, but I think the vnet should still be reconciled in the control plane. wdyt?

wdyt?

**Comment by alexeldeib** [comment]
ah, just saw the comment over in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1590#issuecomment-896016819. I think that's reasonable

**Comment by nprokopic** [comment]
We can keep `AzureManagedControlPlaneSpec.VirtualNetwork` and its current behavior, with improvements from https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1590 (fixing the deletion problem for BYO VNets), and keep that part of the `AzureManagedControlPlaneSpec`, have it applied to all node pools by default, so that part does not have to change much.

On top of that, we can add `vnetSubnetID` and `podSubnetID` (from Azure's `ManagedClusterAgentPoolProfile`) to `AzureManagedMachinePoolSpec` as optional fields, so that there is an option to specify separate BYO subnets per node pool (like Azure allows it).

That way we have a default behavior for all node pools (like now), with the option to override that per node pool.

**Comment by jackfrancis** [comment]
It's been a while since we've engaged this issue. Are we able to concretely define what work needs to be done here @LochanRn @nprokopic?

**Comment by nprokopic** [comment]
> It's been a while since we've engaged this issue. Are we able to concretely define what work needs to be done here @LochanRn @nprokopic?

Currently VNet where the managed cluster is deployed is specified in `AzureManagedControlPlaneSpec`, which means all agent pools will be deployed to that same VNet.

On the other hand, in Azure spec for managed clusters the VNet/subnet is specified on the agent pool level, [here in `ManagedClusterAgentPoolProfile`](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP#managedclusteragentpoolprofile) you can see `vnetSubnetID` field.

(Without diving into implementation details) I would say that the concrete work to do here is: for managed clusters, allow specifying a subnet per agent pool (`AzureManagedMachinePoolSpec`), similarly to `AzureMachinePools` https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3fda20ca562276ed2bc53dd6e9bd3fe2032daff6/exp/api/v1beta1/azuremachinepool_types.go#L89

**Comment by jackfrancis** [comment]
@nprokopic thanks, that makes sense!

/remove-lifecycle stale

**Comment by LochanRn** [comment]
@CecileRobertMichon  @nprokopic @jackfrancis for this use-case I was thinking about keeping the existing implementation as it is and add additional spec in AMMP. The vnet and subnet details provided in AMCP can be used as default vnet if the user does not provide any VNET in ammp. This will not require a migration logic as well. 

Different Scenarios:  

1. If a user does not provide any vnet, capz creates a new vnet and uses the same to deploy all the machinepools. 
2. A user provides VNet details in AMCP alone then all the machine pools will be deployed in that VNet. 
3. A user has 3 machinepools and the user provides VNet details in AMCP and configures only 1 AMMP then the for that specific MP we would use the VNet details provided in the AMMP but for the rest of the AMMP we can use the default VNet configured in AMCP.
4. A user configures only one of the AMMP with VNet details, and does not configure AMCP Vnet details capz creates a VNet and all the Machine pools which do not have a Vnet configured will use the VNet created by capz. But the AMMP which has VNet details configured will be deployed in that specific 
VNet. 


So the Vnet details provided in AMMP would be given the highest priority, next would be AMCP, if Vnet is configured in AMCP then it would deploy all the MachinePools which do not have a VNet configured in that VNet. If none of the details are provided capz would create a VNet and all the MachinePools can be deployed in that VNet. 

This will not affect any of the existing clusters as well .

**Comment by CecileRobertMichon** [comment]
@LochanRn to clarify, does AKS let you set one VNET per agent pool, or is it one _subnet_ per agentpool? My understanding is that it's the latter. If so, we can do something similar to AzureCluster/AzureMachinePool: VNET is defined in the AzureCluster, and each AzureMachinePool has its own subnet name https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/api/v1beta1/azuremachinepool_types.go#L89

**Comment by LochanRn** [comment]
@CecileRobertMichon It expects a vnet-subnet-id 😅
https://github.com/Azure/azure-sdk-for-go/blob/4dbc884ed47f19c14c6beb157aa2efca9cd66c8d/services/containerservice/mgmt/2021-05-01/containerservice/models.go#L1298

and the VnetSubnetId is created based on vnet and subnet 
https://github.com/spectrocloud/cluster-api-provider-azure/blob/c2dd3b44a3e527ce1d8a9cde97f592c747f3a050/azure/defaults.go#L230

**Comment by LochanRn** [comment]
okay, my bad sorry i wrongly interpreted it. 😅
