### ISSUE TITLE
Determine on removing hardcoded kubernetes-cni version in vm startup scripts

### ISSUE THREAD

**Issue by awesomenix** [kubernetes-sigs/cluster-api-provider-azure#160]
/kind bug

**What steps did you take and what happened:**
Currently the kubernetes-cni version is hardcoded to 0.6.0 to workaround a bug, need to remove once upstream kubernetes package or update the packages 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3d7c03326b06ea6c825cd4e899b61e2134f61469/pkg/cloud/azure/services/config/controlplane.go#L143

**What did you expect to happen:**

Either no hardcoding or tracking updating this version from time to time

**Environment:**

- cluster-api-provider-azure version: 0.1.0
- Kubernetes version: (use `kubectl version`): 1.13.4
- OS (e.g. from `/etc/os-release`): 18.04 Ubuntu Linux

**Comment by justaugustus** [comment]
This isn't really our bug, we just need to track when this gets fixed and allow the values to be configurable in the meantime.

/remove-kind bug
/kind feature
/priority critical-urgent
/milestone v1alpha1

**Comment by CecileRobertMichon** [comment]
@awesomenix @justaugustus is this issue still relevant? Can I help?

**Comment by justaugustus** [comment]
Closed via #281.
/close

**Comment by justaugustus** [comment]
(Bootstrap moved to CABPK `preKubeadmCommands`)
