### ISSUE TITLE
Optional installation of aad pod identity library

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1604]
/kind feature
#1514 allows to use service principal from a directly embedded secret which obviates the need of installing aad pod identity library. However, the infrastructure components artifact, which is part of a capz release doesn't have the option of removing aad pod identity from its inventory. We must find a way to do this.

**Describe the solution you'd like**
Make aad pod identity library installation optional. Preferably enabled by default, but can be disabled by passing some argument or other mechanisms.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Related to #1545
