### ISSUE TITLE
Allow user to specify APIServerAccessProfile

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-azure#1605]
/kind feature

**Describe the solution you'd like**
Allow user to specify [APIServerAccessProfile](https://github.com/Azure/azure-sdk-for-go/blob/v55.2.0/services/containerservice/mgmt/2021-05-01/containerservice/models.go#L2067) in [AzureManagedControlPlaneSpec](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/exp/api/v1alpha4/azuremanagedcontrolplane_types.go#L28)

**Comment by richardchen331** [comment]
@CecileRobertMichon can i work on this?

**Comment by CecileRobertMichon** [comment]
@richardchen331 go for it! You can reach out to @alexeldeib @LochanRn and @nprokopic for guidance if you need it.

**Comment by CecileRobertMichon** [comment]
make sure to comment `/assign` if you're taking this on :)

**Comment by richardchen331** [comment]
Thanks @CecileRobertMichon !
