### ISSUE TITLE
Refactor the exp/ folder to separate experiments into their own directory

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1606]
Currently, all CAPZ experimental features (AzureMachinePool and AzureManagedCluster as of today) are in the same directory under exp/. 

Proposal: create subdirectories under exp/ to isolate each feature. 

Pros:
- better isolation between features (ie. less risk of introducing a bug in a PR changing the other one)
- OWNERs for each one
- Easier to remove an experiment from the project (just delete the directory)

Cons:
- Duplicated api/controller directories under exp/
- need to update import paths used throughout the project

**Comment by CecileRobertMichon** [comment]
cc @alexeldeib @nprokopic @LochanRn @devigned 

thoughts?

**Comment by LochanRn** [comment]
One major interdependency between AMMP and AMCP would be scope. Both AMMP and AMCP controllers use the ManagedControlPlaneScopeParams.
So when we refactor the code we need to refactor the existing scope as well which as you said it might have duplications. 

Also I wanted to understand better regarding what level of access will we have for reviewing ?

**Comment by CecileRobertMichon** [comment]
@LochanRn we would only split the files under exp/, the scope would be unaffected.

> Also I wanted to understand better regarding what level of access will we have for reviewing ?

reviewer on the exp/ types for now.

**Comment by LochanRn** [comment]
Ohh okay right makes sense scope is in different dir.

**Comment by nprokopic** [comment]
Is there maybe a way to target files for OWNERS? I believe that, for example, GitHub CODEOWNERS feature allows that.

**Comment by CecileRobertMichon** [comment]
> Is there maybe a way to target files for OWNERS? 

I don't think there is: https://git.k8s.io/community/contributors/guide/owners.md

> Each directory that contains a unit of independent code or content may also contain an OWNERS file. This file applies to everything within the directory, including the OWNERS file itself, sibling files, and child directories.
