### ISSUE TITLE
Replacing Windows with Windows + WSL2 for clarification

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-azure#1608]
/kind documentation

Currently the docs mention setting up of the project in Windows OS, but for better results it is suggested the project is set up in a nix environment.

**Describe the solution you'd like**
Modifying the docs and mentioning the setting up of the project in Windows + WSL2 instead Windows. This would provide clarification that the files should be checked out to wsl file system for obtaining better results.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
@CecileRobertMichon Could you please review the issue? And I would like to work on it.

**Comment by CecileRobertMichon** [comment]
LGTM, thanks!

/assign @sayantani11
