### ISSUE TITLE
Migrate codecov action to v2

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1656]
https://github.com/codecov/codecov-action

v1 is being depracated, we should use v2 instead in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/cover.yaml.

This might require changing some of the parameters to work with v2.

/help
/good-first-issue

**Comment by yogagit123** [comment]
> /assign @yogagit123

Please do not assign to yogit2020 
/assign @yogagit123

**Comment by sayantani11** [comment]
@yogagit123 This issue is actually taken as @himanshu007-creator is working on it as stated above

**Comment by nader-ziada** [comment]
@yogagit123 @himanshu007-creator looks like both of you submitted PRs to address the same issue, can you both please chat with each other and consider not duplicating the work? Thanks

**Comment by CecileRobertMichon** [comment]
Has anyone verified that the new version works without any additional required changes?

**Comment by sayantani11** [comment]
@CecileRobertMichon Let me know if the issue isn't solved. I guess there are some additional changes required as well, I went through the docs. I will be happy to update it.
