### ISSUE TITLE
Ensure we are using the cloudprovider PrimaryScaleSetName configuration properly

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#1665]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This is an exploratory issue related to the MachinePool feature. Ensure

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The Azure cloud provider runtime comes with a `PrimaryScaleSetName` configuration property, described thusly in code:

```
	// The name of the scale set that should be used as the load balancer backend.
	// If this is set, the Azure cloudprovider will only add nodes from that scale set to the load
	// balancer backend pool. If this is not set, and multiple agent pools (scale sets) are used, then
	// the cloudprovider will try to add all nodes to a single backend pool which is forbidden.
	// In other words, if you use multiple agent pools (scale sets), you MUST set this field.
	PrimaryScaleSetName string `json:"primaryScaleSetName,omitempty" yaml:"primaryScaleSetName,omitempty"`
```

Let's make sure that we understand the above configuration so that we can properly configure clusters that are using > 1 MachinePool.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@jackfrancis you've confirmed this only applies to basic LBs correct? If so we can close this

**Comment by jackfrancis** [comment]
I haven't confirmed that. (Though I have confirmed that using a bunch of VMSS pools in a Standard LB configuration does not produce a bunch of different LBs like the comment states; it still reuses the one "cluster" LB.)
