### ISSUE TITLE
Latest Bazel breaks build process

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/cluster-api-provider-azure#167]
/kind bug

**What steps did you take and what happened:**
Installed latest Bazel (`0.24.0`) and tried to run `make manifests / binaries` (after running `make dep-ensure`) and received the following error:

    make[1]: Entering directory '/home/john/go/src/sigs.k8s.io/cluster-api-provider-azure'
    bazel build //config
    ERROR: /home/john/go/src/sigs.k8s.io/cluster-api-provider-azure/config/BUILD.bazel:19:1: in _go_genrule rule //config:config: 
    Traceback (most recent call last):
        File "/home/john/go/src/sigs.k8s.io/cluster-api-provider-azure/config/BUILD.bazel", line 19
            _go_genrule(name = 'config')
        File "/home/john/.cache/bazel/_bazel_john/5c7329cb935c22d1a9cbe36f59c261e7/external/io_kubernetes_build/defs/go.bzl", line 72, in _go_genrule_impl
            ctx.action(inputs = (list(all_srcs) + resol...), <5 more arguments>)
        File "/home/john/.cache/bazel/_bazel_john/5c7329cb935c22d1a9cbe36f59c261e7/external/io_kubernetes_build/defs/go.bzl", line 75, in ctx.action
            ctx.configuration.default_shell_env + go.env
    The `+` operator for dicts is deprecated and no longer supported. Please use the `update` method instead. You can temporarily enable the `+` operator by passing the flag --incompatible_disallow_dict_plus=false

**What did you expect to happen:**
Build successfully.

**Anything else you would like to add:**
Not a Bazel expert but looks like this was caused by the most recent version defaulting to raising an error on the deprecated `+` dict operator. This is used by the version of `k8s/repo-infra` that is vendored into CAPZ. It looks like it's been resolved [upstream](https://github.com/kubernetes/repo-infra/commit/67ffed74d39a09f25c647d634053f6098c0c8f22#diff-d5e8a5f33185be2c8ae5152d2ef1ecb5) and needs to be vendored in. However I tried updated the deps in `WORKSPACE` for CAPZ but it still fails in the same way (after clean and cache bust). 

I don't know how dependencies of dependencies work but looks like `kubernetes/kubernetes` is being pulled in by CAPZ as well and their `WORKSPACE` also vendors an old version of `k8s/repo-infra` so could be coming from there?

The short-term workaround is to add `--incompatible_disallow_dict_plus=false` to the ${BAZEL_BUILD_ARGS} in `WORKSPACE`. Happy to open a PR for this if it's the desired short-term fix? (it disables the new default behavior in Bazel).

**Environment:**

- cluster-api-provider-azure version: 0.1.0
- Kubernetes version: (use `kubectl version`): v1.14.0
- OS (e.g. from `/etc/os-release`): Ubuntu LTS 16.04

**Comment by justaugustus** [comment]
Hey @johnharris85 -- This should be fixed, as we've bumped `k8s.io/repo-infra` in #166 (ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/6c364f9b67572effe331f724dc3d67fc10eb7f4d/WORKSPACE#L41).
Can you test again and report back? I'll leave this open until then.

/assign
/priority critical-urgent
/milestone v1alpha1

**Comment by johnharris85** [comment]
LGTM!
