### ISSUE TITLE
Install Azure Disk & File CSI drivers by default from 1.22

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/cluster-api-provider-azure#1673]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
From AKS 1.21, Azure Disk CSI driver is already the default storage driver, and we would like to turn on azure disk csi migration from 1.23, related PR: https://github.com/kubernetes/kubernetes/pull/104670, it's time to install Azure Disk & File CSI drivers by default on capz cluster from 1.22

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
this is tracked in https://github.com/kubernetes-sigs/cluster-api/issues/4166

**Comment by CecileRobertMichon** [comment]
might be useful to review: https://github.com/sedefsavas/cluster-api-provider-aws/blob/csi-migration/docs/book/src/topics/external-cloud-provider-with-ebs-csi-driver.md#validated-upgrade-paths-for-existing-clusters

**Comment by CecileRobertMichon** [comment]
We have CSI migration tests in place for k8s 1.22 -> 1.23 upgrade (https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-22-1-23) as well as instructions for installing the CSI drivers with Helm in https://capz.sigs.k8s.io/topics/addons.html#storage-drivers

We're installing the CSI drivers via Helm for every e2e cluster test for v1.23+ (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/common.go#L267).

I'm closing this as complete for now. CSI drivers are an external addon and not in scope to be installed by CAPZ itself. In the future we may want to include it in our reference templates but that requires some better way of defining addons (like https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220712-cluster-api-addon-orchestration.md)

cc @dtzar 

/close
