### ISSUE TITLE
Optionally supply Availability Zone

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#169]
/kind feature

**Describe the solution you'd like**
We recently added the capability to automatically use Availability Zones in Azure regions that support them. The current behavior is to choose a random AZ within the region and utilize it, but let's instead allow users to select one.

Some things I'd like to see in terms of behavior:
- AZ can be set as an env var (default to `""`) within generate-yaml.sh
- If AZ is an empty string, feel free to randomize selection. Log the fact that this has been randomly selected
- If AZs are not supported in the region, ignore the AZ selection, and log the fact that AZs cannot be used in the region.

/priority important-soon
/milestone v1alpha1
/assign @awesomenix

**Comment by awesomenix** [comment]
Customer requirements are creating a zone redundant cluster, which means all nodes and masters are tolerant to zone failures. Typical option is for customer to provide an option to be zone redundant or not, and cluster api could automatically choose the best option for them, not sure of a scenario where customer has to manually choose an availability zone for the vm's

The right way to fix this would be an option provided by cluster-api as part of machinesets, which chooses the availability zone based on available ones in the region as part of machinespec.

**Comment by justaugustus** [comment]
@awesomenix -- Apologies if I skipped some details here.

Zone-redundant services should continue to be redundant wherever possible.
What I was referring to here was _zonal_ resources. The randomized AZ is fine for zonal cluster resources, but consider awareness of existing topology i.e., I want to build my cluster zonal resources datacenter-adjacent to some existing resource. That would still be a valuable use case.

This should definitely be part of the MachineSpec, as you mentioned. 
The reason to supply it as an environment variable is so the variable can be substituted in the MachineSpec during manifest generation (`make manifests` --> `generate-yaml.sh`).
