### ISSUE TITLE
PublicIP resources should not PUT on each AzureCluster reconcile

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1692]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
When reconciling an `AzureCluster` each reconcile loop will cause a PUT for each PublicIP resource.

**What did you expect to happen:**
PublicIP resources should only be mutated with a PUT if the desired state has changed.

/assign @CecileRobertMichon

**Comment by karuppiah7890** [comment]
I'll see if this can be handled as part of the sync to async migration in #1716 or else migrate as is. I'll check the code and see the difference in effort with and without the bug fix

**Comment by karuppiah7890** [comment]
cc @CecileRobertMichon

**Comment by karuppiah7890** [comment]
@devigned I was just trying out the PUT API multiple times with same request body to see the behavior. I see that the public IP (I tried IPv6) is not affected. What's the aim of this issue? To reduce the API calls to Azure when there's no change? and to also avoid PUT request which is usually meant to do updates (generally by overwrites)? Or is there any other aim / extra aim for this issue?

If it's only about avoiding unnecessary PUT API calls, how do we plan to do it? Currently I see there's no GET API call in `publicips` service [in `Reconcile`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/publicips/publicips.go#L55-L56). So, do we want to do a GET API call and compare the current spec from K8s with the current public IP resource from Azure and do PUT API call only if there's a diff?

**Comment by karuppiah7890** [comment]
Maybe we should also talk about what kind of updates are allowed for Public IPs. I mean, looking at some of the validations being done [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e5327290e4fd5df3fae5779296b8e1d2c73c508e/api/v1alpha4/azurecluster_validation.go) by using the [webhook](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e5327290e4fd5df3fae5779296b8e1d2c73c508e/api/v1alpha4/azurecluster_webhook.go), looks like there's not much we can change for anything related to Public IPs

So, do we expect any kind of updates with respect to Public IPs in the form of [Public IP Spec](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e5327290e4fd5df3fae5779296b8e1d2c73c508e/azure/types.go#L27-L32)?

**Comment by devigned** [comment]
Great questions, @karuppiah7890. The goal here is to minimize "writes" (mutations) to the Azure API. Azure APIs have lower throttling limits for writes than for reads, particularly reads that GET by resource ID.

For any resource, we should be able to GET from Azure, compare the state in Azure, then only mutate state in Azure if the desired state in K8s is different than the state in Azure.

**Comment by karuppiah7890** [comment]
Makes sense @devigned 👍

**Comment by CecileRobertMichon** [comment]
/unassign
/assign @karuppiah7890

We realized in #1791 that there might also be a bug associated with this behavior: since we update the public IP when it already exists, it means we will also update an IP that was pre-created by the user and thus add the CAPZ managed tags to it which would cause it to be deleted later on when deleting the cluster because CAPZ would see it as "managed".
