### ISSUE TITLE
Dev Guide: No mention of setting `CLUSTER_IDENTITY_NAME` for creating workload cluster

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/cluster-api-provider-azure#1700]
As part of https://capz.sigs.k8s.io/developers/development.html#customizing-the-cluster-deployment , there's no mention of setting `CLUSTER_IDENTITY_NAME` environment variable but it's used in the template yaml - https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/621f596ed7a2f46d7c6a6a239a35e9eea7385380/templates/cluster-template.yaml#L211

Due to this, when creating workload cluster using `make create-workload-cluster` command, we get an error

```bash
error: error when retrieving current configuration of:
Resource: "infrastructure.cluster.x-k8s.io/v1alpha4, Resource=azureclusteridentities", GroupVersionKind: "infrastructure.cluster.x-k8s.io/v1alpha4, Kind=AzureClusterIdentity"
Name: "", Namespace: "default"
from server for: "STDIN": resource name may not be empty
```

Full log -

```bash
cluster-api-provider-azure $ make create-workload-cluster
# Create workload Cluster.
/Users/karuppiahn/projects/github.com/kubernetes-sigs/cluster-api-provider-azure/hack/tools/bin/envsubst-drone < /Users/karuppiahn/projects/github.com/kubernetes-sigs/cluster-api-provider-azure/templates/cluster-template.yaml | kubectl apply -f -
cluster.cluster.x-k8s.io/capz-cluster created
azurecluster.infrastructure.cluster.x-k8s.io/capz-cluster created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capz-cluster-control-plane created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-cluster-control-plane created
machinedeployment.cluster.x-k8s.io/capz-cluster-md-0 created
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-cluster-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capz-cluster-md-0 created
error: error when retrieving current configuration of:
Resource: "infrastructure.cluster.x-k8s.io/v1alpha4, Resource=azureclusteridentities", GroupVersionKind: "infrastructure.cluster.x-k8s.io/v1alpha4, Kind=AzureClusterIdentity"
Name: "", Namespace: "default"
from server for: "STDIN": resource name may not be empty
make: *** [create-workload-cluster] Error 1
```

**Comment by karuppiah7890** [comment]
I see `CLUSTER_IDENTITY_NAME` being set in here though - https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7a76e16a66d2953bc9467a19e952c5b4b27ee1d9/hack/create-dev-cluster.sh#L55 , which seems to be creating management and workload cluster though using [this](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7a76e16a66d2953bc9467a19e952c5b4b27ee1d9/hack/create-dev-cluster.sh#L80) from [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7a76e16a66d2953bc9467a19e952c5b4b27ee1d9/Makefile#L540-L545)

**Comment by karuppiah7890** [comment]
There's also no mention of `AZURE_CLUSTER_IDENTITY_SECRET_NAME` and `AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE` which are also needed here - https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/621f596ed7a2f46d7c6a6a239a35e9eea7385380/templates/cluster-template.yaml#L217-L218

**Comment by karuppiah7890** [comment]
Maybe something like https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1f0278cd4f3e5fc3ab7567f8580e38ece94c70c5/hack/create-dev-cluster.sh#L54-L56 could be mentioned in the dev guide along with what's already there in https://capz.sigs.k8s.io/developers/development.html#customizing-the-cluster-deployment

**Comment by CecileRobertMichon** [comment]
thanks for opening an issue @karuppiah7890. Agreed we should add it to docs.

/kind documentation
/good-first-issue
