### ISSUE TITLE
AKS clusters should allow users to specify more optional configuration for node pools

### ISSUE THREAD

**Issue by meixingdb** [kubernetes-sigs/cluster-api-provider-azure#1701]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Add optional configurations for users to specify specs for AKS node pools. The list of options include:
// MaxCount - Maximum number of nodes for auto-scaling
// +optional
MaxCount 
// MinCount - Minimum number of nodes for auto-scaling
// +optional
MinCount 
// EnableAutoScaling - Whether to enable auto-scaler
// +optional
EnableAutoScaling 
// EnableNodePublicIP - Enable public IP for nodes
// +optional
EnableNodePublicIP 
// EnableFIPS - Whether to use FIPS enabled OS
// +optional
EnableFIPS
// OsDiskType - OS disk type to be used for machines in a given agent pool. Allowed values are 'Ephemeral' and 'Managed'. If unspecified, defaults to 'Ephemeral' when the VM supports ephemeral OS and has a cache disk larger than the requested OSDiskSizeGB. Otherwise, defaults to 'Managed'. May not be changed after creation. Possible values include: 'Managed', 'Ephemeral'
// +optional
OsDiskType 
// NodeLabels - Agent pool node labels to be persisted across all nodes in agent pool.
// +optional
NodeLabels 
// NodeTaints - Taints added to new nodes during node pool create and scale. For example, key=value:NoSchedule.
// +optional
NodeTaints 
// VnetSubnetID - VNet SubnetID specifies the VNet's subnet identifier for nodes and maybe pods
// +optional
VnetSubnetID 
// AvailabilityZones - Availability zones for nodes. Must use VirtualMachineScaleSets AgentPoolType.
// +optional
AvailabilityZones 
// ScaleSetPriority - ScaleSetPriority to be used to specify virtual machine scale set priority. Default to regular. Possible values include: 'Spot', 'Regular'
// +optional
ScaleSetPriority 
// MaxPods - Maximum number of pods that can run on a node.
// +optional
MaxPods 
// KubeletConfig - KubeletConfig specifies the configuration of kubelet on agent nodes.
// +optional
KubeletConfig 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sadysnaat** [comment]
@meixingdb @LochanRn will it make sense to add 
update after or some update lifecycle management to nodepool in AKS 
for image-pathces?

**Comment by sadysnaat** [comment]
> @meixingdb @LochanRn will it make sense to add update after or some update lifecycle management to nodepool in AKS for image-pathces?

Created a separate feature request https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1755

**Comment by CecileRobertMichon** [comment]
/close

Please open individual issues for each feature request
