### ISSUE TITLE
async disks

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1711]

**Comment by karuppiah7890** [comment]
Finally started working on this issue 😅

**Comment by Jont828** [comment]
@karuppiah7890 Hey, I didn't see that you had assigned the issue and I started working on it. Are you still working on this too?

**Comment by karuppiah7890** [comment]
Yes @Jont828 , I have some code in my fork branch. I'm half way done I think. Not sure though

**Comment by karuppiah7890** [comment]
The branch I'm working on is - https://github.com/karuppiah7890/cluster-api-provider-azure/tree/fix-1711 . Let me know if it makes sense to continue or if you want to take over and complete it, in which case I can unassign myself

**Comment by Jont828** [comment]
Yeah I can take over and add you as coauthor. I've finished the changes involving the spec and just have to do the tests.

**Comment by karuppiah7890** [comment]
Cool ! I was looking towards contributing and closing this issue but it's okay as I'm also caught up with a few other PRs

And I think you don't have to add me as a co author 😅 unless there's any code getting contributed from me (from my fork branch)

**Comment by Jont828** [comment]
Sounds good, I wrote it up on my own before I saw that the issue was taken. Thanks for understanding!
