### ISSUE TITLE
async privatedns

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1715]

**Comment by Jont828** [comment]
Hey @shysank, how's it going on async private DNS? I've refactored a lot of the async PRs and also merged #1874 which changes the GET logic, so let me know if you have any questions!

**Comment by shysank** [comment]
hey @Jont828, thanks! I was distracted with other things, so couldn't get to this sooner. I've opened a pr to address this, ptal whenever you get a chance.

**Comment by Jont828** [comment]
Sounds good! Just left some comments.
