### ISSUE TITLE
Bump api version to v1beta1 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1722]
/kind feature

**Describe the solution you'd like**
As discussed in the office hours meeting on 09/16/2021, there is consensus that capz already satisfies all the criteria required to upgrade to beta api.

- Bump API version to v1beta1 to match Cluster API Core

**Anything else you would like to add:**

- [x] #1723
- [x] #1724
- [x] #1725
- [x] #1726
- [x] #1727
- [x] #1736
- [x] #1809 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
cc @CecileRobertMichon 
For some reason `convert task to issue` is not working for me. Can you see if it works whenever you get a chance?

**Comment by CecileRobertMichon** [comment]
@shysank done, it might be because I have write / admin permissions on the repo

**Comment by randomvariable** [comment]
i didn't know this was a feature. i painstakingly created each issue in capa and capv for nothing. :(

**Comment by randomvariable** [comment]
btw, you might also want to do an upgrade test from v1alpha4 to v1beta1
