### ISSUE TITLE
When workload cluster is not in working state AzureCluster still reports Ready

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1732]
/kind bug

**What steps did you take and what happened:**

Similar report to https://github.com/kubernetes-sigs/cluster-api/issues/5324, I deleted all the machines in azure for a workload and the Azure cluster still reported `READY=true`

```
kubectl get azuremachines   
NAME                                     READY   STATE
capz-e2e-wy8d22-ha-control-plane-9kvww   false   Deleted
capz-e2e-wy8d22-ha-control-plane-9s4tw   false   Deleted
capz-e2e-wy8d22-ha-control-plane-jpbqg   false   Deleted
capz-e2e-wy8d22-ha-md-0-jvk2d            false   Deleted
capz-e2e-wy8d22-ha-md-0-ng92q            false   Deleted
capz-e2e-wy8d22-ha-md-win-6g9fj          false   Deleted
capz-e2e-wy8d22-ha-md-win-nxr7h          false   Deleted
```

```
kubectl get azurecluster  
NAME                 CLUSTER              READY   REASON
capz-e2e-wy8d22-ha   capz-e2e-wy8d22-ha   True    
```

**What did you expect to happen:**

If all my machines are deleted and there is no control plane I wouldn't expect my azurecluster to report ready=true

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: main branch
- Kubernetes version: (use `kubectl version`): 1.22.1
- OS (e.g. from `/etc/os-release`): windows/ubuntu mix

**Comment by jsturtevant** [comment]
Had a brief conversation with @CecileRobertMichon offline. The word "Cluster" is what's confusing me here, I interpreted it as the whole cluster (machines included) but in CAPI terminology it means just "cluster network infrastructure" (which happens to be fine in this case)

Not sure if there is action to take here. One thought would be to update the CAPI terminology to be clearer but that would be pretty heavy at this point. Not sure if others find it confusing like I did.

**Comment by karuppiah7890** [comment]
Just curious, what does "cluster network infrastructure" mean in this case? and how is it fine? 🤔

Are we talking about network resources in Azure? Virtual Networks, Subnets and the kind?

**Comment by jsturtevant** [comment]
Yes, it is the virtual networks, subnets, etc.  In this case all of the components are existing and configured (minus backend pools that point to the VM's there were deleted)

**Comment by karuppiah7890** [comment]
It is indeed a weird experience to be told that cluster is ready when no workload can run in the cluster and when the Kubernetes platform itself does not exist

**Comment by CecileRobertMichon** [comment]
I agree, I think "Cluster" is a misrepresentation of what the Cluster CRD + controller actually do. Here's where that's defined in the CAPI book: https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure.html

Going to start a discussion in slack to see what other CAPI folks think.
