### ISSUE TITLE
cluster upgrade fails when provider is updated from 0.4.14 to 0.5.x

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1739]
/kind bug

**What steps did you take and what happened:**

1. Create a MC using CAPZ 1.4.14.
2. Create WC with k8s version 1.20
3. Upgrade MC to CAPZ 1.5.2
4. Upgrade WC to k8s version 1.21. 
5. fails in pip reconciliation with the following error 
`
Error: Code=\"ResourceAvailabilityZonesCannotBeModified\" Message=\"Resource /subscriptions/bla/resourceGroups/bla/providers/Microsoft.Network/publicIPAddresses/bla-apiserver has an existing availability zone constraint 1, 2, 3 and the request has availability zone constraint NoZone, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.\
`
**What did you expect to happen:**
The cluster should upgrade 

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
@CecileRobertMichon the only change I can see is the sdk update from `2019-06-01` to `2021-02-01`. I couldn't find anything that's different happening in the client side. Is it possible that for the old api version, the zones were automatically set in the backend?

**Comment by shysank** [comment]
If so, we have to options:
1. Revert to the old sdk version.
2. Explicitly set all az's for the region in the client. wdyt?

**Comment by CecileRobertMichon** [comment]
could it be related to https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/966 ?

**Comment by CecileRobertMichon** [comment]
this goes back to https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1727, we really need to add an upgrade test

**Comment by CecileRobertMichon** [comment]
if possible we should avoid reverting to old SDK, or at least find a solution for the long term because we shouldn't stay stuck on the old version forever. If reverting the SDK is the quickest way to mitigate the issue while we we investigate a fix, then let's do that.

Option 2 of setting zones explicitly in the client seems like it's what we want.

**Comment by shysank** [comment]
I'll try option 2, do some tests locally; time-box it for a day or two. If it doesn't work out, I'll revert back to option 1.

**Comment by devigned** [comment]
@shysank ping me if you want to pair on this.
