### ISSUE TITLE
BYO DNS Zone

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1749]
/kind feature

**What steps did you take and what happened:**
1. Created a private cluster with custom vnet
2. Create a dns zone through azure cli/ui and the appropriate links and records 
3. Delete the cluster
4. capz tries to delete the dns zone created in step 2, but fails because there are some active links.

**What did you expect to happen:**
CAPZ should support byo dns zone

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
are we applying tags to the DNS zone? I don't think BYO dns zone is an existing feature right now...

**Comment by shysank** [comment]
> are we applying tags to the DNS zone? 

No, we are not.

>I don't think BYO dns zone is an existing feature right now...

Agreed, i'll change this to feature.  

Curious though, should we tag all the resources that capz creates, and only delete those that are tagged?

**Comment by CecileRobertMichon** [comment]
@shysank agreed, I think we should standardize the owned tag across all resources. We could also think about using a "shared" tag (I think CAPA does this already) to signify a resource is managed by CAPZ but its lifecycle is shared with another component (eg. network security groups are also updated by cloud provider).

cc @karuppiah7890 who has been doing a lot of thinking on tags + resource management in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1721

**Comment by karuppiah7890** [comment]
This area is new to me, I'll check this out sometime. Let me know if you folks are looking for any specific inputs from my side
