### ISSUE TITLE
Add support for node image upagrdes to AKS nodepool 

### ISSUE THREAD

**Issue by sadysnaat** [kubernetes-sigs/cluster-api-provider-azure#1755]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Add node os image upgrade support for AKS nodepools from UpgradeProfile 
2. UpgradeLifeCycle support for node pools

***Non-Goals/Future Work***

**User Story**

As an operator I would like my AKS nodepools to have latest image applied for latest security vulnerability or os patches

**Detailed Description**
I would like to enable auto updated my nodepools with latest images

or something like CSR request that I can approve and it will apply latest image patch

**Contract changes [optional]**

**Data model changes [optional]**

/kind proposal

**Comment by dtzar** [comment]
This should be supported out of the box now with the ASO v2 API. cc @nojnhuh @nawazkh

**Comment by nojnhuh** [comment]
> This should be supported out of the box now with the CAPZ ASO v2 API. cc @nojnhuh @nawazkh

More context: https://capz.sigs.k8s.io/topics/aso#experimental-aso-api

**Comment by nojnhuh** [comment]
> > This should be supported out of the box now with the CAPZ ASO v2 API. cc @nojnhuh @nawazkh
> 
> More context: https://capz.sigs.k8s.io/topics/aso#experimental-aso-api

This would be the particular kind of change to apply to the flavor template to achieve this:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/21479a9a4c640b43e0bef028487c522c55605d06/templates/cluster-template-aks-aso.yaml
```diff
diff --git a/templates/cluster-template-aks-aso.yaml b/templates/cluster-template-aks-aso.yaml
index 29f77594e..e83d8c9f7 100644
--- a/templates/cluster-template-aks-aso.yaml
+++ b/templates/cluster-template-aks-aso.yaml
@@ -37,6 +37,9 @@ spec:
         name: ${CLUSTER_NAME}
       servicePrincipalProfile:
         clientId: msi
+      autoUpgradeProfile:
+        nodeOSUpgradeChannel: NodeImage
+        upgradeChannel: patch
   version: ${KUBERNETES_VERSION}
 ---
 apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
```

The ManagedCluster resource embedded in the AzureASOManagedControlPlane has this structure: https://azure.github.io/azure-service-operator/reference/containerservice/v1api20231001/#containerservice.azure.com/v1api20231001.ManagedCluster

/close
