### ISSUE TITLE
cluster-api-azure-controller v0.5.3 release image pull errors

### ISSUE THREAD

**Issue by dthorsen** [kubernetes-sigs/cluster-api-provider-azure#1758]
/kind bug

**What steps did you take and what happened:**
I followed the quick start guide to create a management cluster in kind with the Azure provider. After I did this I noticed the capz-controller-manager pod was failing to start with image pull errors. I tried to manually pull the image referenced in the pod template and I got this error:
```
$ docker pull us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.5.3
Error response from daemon: manifest for us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.5.3 not found: manifest unknown: Failed to fetch "v0.5.3" from request "/v2/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller/manifests/v0.5.3".
```

It looks like the promotion job is failing here: https://testgrid.k8s.io/sig-release-releng-blocking#post-k8sio-image-promo
The build logs indicate a permissions issue, but I am not sure where those would be set, and I am quite certain I would not have access to fix them.

**What did you expect to happen:**
I expected the cluster-api-azure-controller v0.5.3 container image to pull successfully.

**Environment:**

- cluster-api-provider-azure version: v0.5.3
- Kubernetes version: (use `kubectl version`): v1.19.11
- OS (e.g. from `/etc/os-release`): Ubuntu 21.04

**Comment by dthorsen** [comment]
Likely related, the serviceaccount files were modified by an audit PR shortly before the v0.5.3 release: https://github.com/kubernetes/k8s.io/pull/2867

**Comment by nader-ziada** [comment]
issue in image promotion fixed and now the image is available 

tested `docker pull us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.5.3` 

/close
