### ISSUE TITLE
Identity type validations should include `ManualServicePrincipal`

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1762]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
When reviewing different IdentityTypes and Identity validation, I think there is some missing work to enable the ManualServicePrincipal identity.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/946668db0cab11e201a23a816458f72d8b3886fa/api/v1alpha4/types.go#L375-L386

**What did you expect to happen:**
A management cluster without `aad-pod-identity` deployed should be able to create workload clusters using a ManualServicePrincipal identity.

Also, identity types should be validated to ensure they have all fields needed to function. For example, both types of service principal identities should validate ClientSecret has been set with a secret reference and for UserAssigned, resource ID must be set. It would be best to do this in a web hook validator to provide an early feedback for users.

**Comment by CecileRobertMichon** [comment]
@devigned isn't VMIdentity different from the aad-pod-identity mode? VMIdentity is the identity on VMs while the ManualServicePrincipal is an AzureClusterIdentity

**Comment by devigned** [comment]
Yes it is. I’ll review the issue. However, I think the second part about validating is still valid.
