### ISSUE TITLE
windows host-process containers

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-azure#1780]
/kind feature

**Describe the solution you'd like**
Lets run Calico (and other CNIs hopefully soon, like antrea)  in a pod for Windows nodes ! ( containerd 1.6).  Windows 2022 , k8s 1.22... 

James has this working here #1672  !

**Anything else you would like to add:**
thank you james :)

**Comment by jsturtevant** [comment]
Hostprocess containers is supported now
/close
