### ISSUE TITLE
Move annotation name constants out of `api/`

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/cluster-api-provider-azure#1789]
Following the conversation from here - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1721/files#r729934347 , we need to move annotation name constants `VMTagsLastAppliedAnnotation`, `RGTagsLastAppliedAnnotation` out of `api/` . We need to figure out the right location to move them to too

**Comment by sayantani11** [comment]
@CecileRobertMichon Where are we suppose to move it?

**Comment by CecileRobertMichon** [comment]
How about in a new azure/consts.go file?
