### ISSUE TITLE
Log messages not pointing to the correct line number

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1827]
**Describe the solution you'd like**
One unfortunate side effect of [composite logger](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/70ea4017712a6778c0ba94d50bde98135c44ba1e/util/tele/composite_logger.go#L44) is that now all the log messages point to `composite_logger: 44`, which makes it hard to debug. As a user, I want to see the line number in the log, and just check what's happening there instead of searching for a pattern and guessing where the log might have been printed from. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
@CecileRobertMichon @devigned is it just me, or have you felt this way too?

**Comment by CecileRobertMichon** [comment]
I hadn't noticed this but if that's case it's definitely a disadvantage. Not sure how we could work around this 🤔

**Comment by devigned** [comment]
This is fixed in #1806. I was _very_ displeased when seeing the same line number each time.

**Comment by devigned** [comment]
I'll focus a bit more on #1806 after determining the root cause for AKS test failures. I no have a reproducible failure, so I think I'm close.

**Comment by shysank** [comment]
fixed in #1812
