### ISSUE TITLE
[Windows ContainerD with Calico] Race condition when applying IPAMConfig

### ISSUE THREAD

**Issue by lippertmarkus** [kubernetes-sigs/cluster-api-provider-azure#1832]
/kind bug

**What steps did you take and what happened:**
When applying CNIs and kube-proxy addons via ClusterResourceSets there sometimes is a race condition where the `IPAMConfig` CRD is not yet created by https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/calico.yaml#L2143-L2156 but the Calico for Windows addon got already applied. Because of this the [`IPAMConfig`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/windows/calico/calico.yaml#L1-L8) isn't created because the CRD doesn't exist yet. Calico therefore fails because strict affinity isn't set to true.

Example:
```bash
# CNI Linux
wget https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/calico.yaml
kubectl create configmap calico-addon --from-file=calico.yaml

# CNI and kube-proxy for Windows
mkdir calico-windows
curl https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/calico/calico.yaml -o calico-windows/calico.yaml
curl https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/calico/kube-proxy-windows.yaml -o calico-windows/kube-proxy-windows.yaml

# fix envsubst (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1831)
sed 's/${KUBERNETES_VERSION\/+\/_}/${KUBERNETES_VERSION}/' calico-windows/kube-proxy-windows.yaml

export KUBERNETES_VERSION=v1.22.3 
kubectl create configmap calico-windows-addon --from-file=calico-windows --dry-run=client -o yaml | envsubst \$KUBERNETES_VERSION | kubectl apply -f -

# create ClusterResourceSets to apply all previos addons to all "calico" clusters
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/calico-resource-set.yaml

# check logs
$ kubectl --kubeconfig=./mycluster.kubeconfig logs pod/calico-node-windows-4k8bf -n kube-system calico-node-startup
...
Unable to ensure network for os error=global strict affinity should not be false for Windows node

# check IPAMConfig
$ kubectl --kubeconfig=./mycluster.kubeconfig get IPAMConfig -A
No resources found
```

Manually creating the `IPAMConfig` afterwards leads to correct startup of Calico on Windows nodes.

**What did you expect to happen:**
If a resource can't be created through a ClusterResourceSet it should be retried.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): v1.22.3
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by jsturtevant** [comment]
Thanks for the good reproduction steps.  We use the ClusterResourcesets in our CI runs to apply the CNI I am not sure we can retire them but we should see if we can improve this flow.

**Comment by jsturtevant** [comment]
I don't think we are seeing this in our e2e tests, but it does look there is a possibility for this issue

/remove-lifecycle stale
