### ISSUE TITLE
Panic in VMSS cluster e2e spec

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#1840]
/kind bug

**What steps did you take and what happened:**

A memory access error sometimes causes a panic when e2e tests are running. [Here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1455783680084545536) is one example.

<details>
  <summary>Stack Trace:</summary>
<pre>
•! Panic [1461.804 seconds]
Workload cluster creation
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:43
  Creating a VMSS cluster
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:333
    with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes [It]
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:334
    Test Panicked
    runtime error: invalid memory address or nil pointer dereference
    /usr/local/go/src/runtime/panic.go:212
    Full Stack Trace
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.labelNodesWithMachinePoolName(0x2583200, 0xc000126018, 0x259dc40, 0xc0007dc000, 0xc000f9a720, 0x19, 0xc000f1e000, 0x3, 0x4)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_machinepool_drain.go:202 +0xc3
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.testMachinePoolCordonAndDrain(0x2583200, 0xc000126018, 0x25a1810, 0xc0005cdb10, 0x25a1880, 0xc000a9b580, 0xc00121d420, 0x10, 0xc000cb9f80, 0x27, ...)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_machinepool_drain.go:147 +0x432
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.AzureMachinePoolDrainSpec(0x2583200, 0xc000126018, 0xc0000e4cc8)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_machinepool_drain.go:89 +0x798
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.glob..func1.6.1.4()
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:394 +0x6c
    github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc00019cc40, 0x22a56e4, 0x1a, 0xc0004c54a0, 0x0, 0x2aa3611, 0x4f, 0x189, 0xc000035800, 0xab7)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:181 +0x323
    github.com/onsi/ginkgo.Context(0x22a56e4, 0x1a, 0xc0004c54a0, 0xc0005cdb01)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:347 +0xaa
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.glob..func1.6.1()
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:393 +0x89e
    github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0009d0840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xa3
    github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0009d0840, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x15c
    github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0008eb0a0, 0x253e900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0x87
    github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc00004e4b0, 0x0, 0x253e900, 0xc0001708c0)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x72f
    github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc00004e4b0, 0x253e900, 0xc0001708c0)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0xf2
    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0000cec60, 0xc00004e4b0, 0x1)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0x111
    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0000cec60, 0x1)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x147
    github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0000cec60, 0xc000572040)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0x117
    github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00019cc40, 0x7ff680fccd38, 0xc0003a4600, 0x22865ff, 0x8, 0xc0008ea880, 0x2, 0x2, 0x258c578, 0xc0001708c0, ...)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x546
    github.com/onsi/ginkgo.runSpecsWithCustomReporters(0x2540720, 0xc0003a4600, 0x22865ff, 0x8, 0xc0008ea860, 0x2, 0x2, 0x2)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x218
    github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x2540720, 0xc0003a4600, 0x22865ff, 0x8, 0xc000096f30, 0x1, 0x1, 0xc00048ef48)
    	/home/prow/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x136
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.TestE2E(0xc0003a4600)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/e2e_suite_test.go:256 +0x1da
    testing.tRunner(0xc0003a4600, 0x23783a0)
    	/usr/local/go/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
    	/usr/local/go/src/testing/testing.go:1238 +0x2b3
------------------------------
Workload cluster creation 
  With 3 control-plane nodes and 2 Linux and 2 Windows worker nodes
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_test.go:205
</pre>
</details>

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vaibhavvsharma** [comment]
Hi, I am a beginner. I would love to take this. Please guide me.

**Comment by mboersma** [comment]
Hi @vaibhavvsharma. Thanks for taking a look at this, and I apologize for my slow response.

This is an intermittent error that we have seen in the Azure end-to-end tests in the Kubernetes [TestGrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure) system. It doesn't happen often, so you probably can't reproduce it on your computer by running the e2e tests (with `scripts/ci-e2e.sh`, for example).

But the Go stack trace in the description of this issue points to a nil pointer exception or invalid memory reference at a specific line of code. That may be enough information to propose a fix for the error. Sometimes a problem like this can be avoided by checking that a variable is not `nil` before proceeding. Sometimes it points to a logic error earlier in the code, where a variable should have been set but wasn't.

I hope that helps. Please let me know what other questions you have.

**Comment by viniciussaturnino** [comment]
Hey, i'll try this issue with matgomes21

**Comment by Jont828** [comment]
Hey are there any updates on this issue?

**Comment by mboersma** [comment]
I haven't seen this error happen in e2e in several months. It may still be out there, but the stack trace I quoted above doesn't match up to the current code, so someone would have to compare it against the code circa November 2021 to investigate. Maybe we should close this issue and open a fresh one if we see panics in future testing.
