### ISSUE TITLE
Add support for running Windows gMSA tests 

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1860]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Should be able to run the upstream gMSA tests with capz.  The scripts that enable this upstream are extensions: https://github.com/kubernetes-sigs/windows-testing/tree/master/extensions

The two tests we currently have are: https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-serial-slow-master&include-filter-by-regex=GMSA

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
consider using gmsa v2

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/sig windows

**Comment by jsturtevant** [comment]
There are a few requirements for this test to be run as outlined in https://github.com/kubernetes/kubernetes/blob/f95c70080f21fe9aa6f14b72b75078d79ef68614/test/e2e/windows/gmsa_full.go#L17-L37 which are implemented by https://github.com/kubernetes-sigs/windows-testing/tree/master/extensions in aks-e

The top level steps are to:

- Create a Windows DomainController
- Create a gMSA account and generate the credspec manifest file has been written to C:\gmsa\gmsa-cred-spec-gmsa-e2e.yml on Worker node that the test will be run on
- DNS needs to be configured properly on node and in coredns to be able to see DomainController 
- For gmsa ccg plugin we will also need to create a KeyVault and give a service principal access
  -   this is different than the requirement needing the gmsa account installed on that same worker.  [With plugins this step is not required but the plugin will need to be installed](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#additional-credential-spec-configuration-for-non-domain-joined-container-host-use-case)

Proposed requirements for creating external resources are: 

- any external resources (domain controller, keyvault, SP) should should be created if not already present
  - this allows any user to run this set of tests without having to have the infra set up and configured, but can be skipped if the domain controller is already there.
- be representative to some degree of how a customer might use this in capz.
  - this allows for us to provide an example and validate that example generally works in capz using the keyvault plugin

We have a few options for creating the external services (Domain controller, keyvault, sp).  In no particular order (numbered to make easier to reference):

1. Configure via golang API's during e2e test configuration, including configuration via SSH: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7979a9705adabde2085801b04f87ad00e8888e1e/test/e2e/conformance_test.go#L180-L192
  - pros: 
    - we are already doing other configuration here and have some code written for ssh
    - would be able to control flakes with retries and such
  - cons: not exactly the way customers would do it 
2. Configure via scripts at one of the entry points (example would be to add it to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-conformance.sh)
  - pros: 
    - can be used across entry points
    - Script is closer to way a customer might do this, could use arm template
  - cons: 
    - its more bash scripts
    - it still need a way to get the info into the workload clusters
3. Use pre-kubeadm commands for configuration: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/prow-ci-version-windows/patches/machine-deployment-ci-version.yaml
  - pros: there is some work done here already and might be easy to install the plugin via this mechnism
  - cons: 
    - not sure restarts will work?  
    - doesn't handle creating external resources
4. Use a tool like https://github.com/Azure/azure-service-operator to create and configure key-vault and SPs.
  - pros: more likely a way a customer might create keyvault/SP.  
  - cons: not really the way a customer will create Domain (none of these are) 

It will likely be a combination of these approaches.  I lean towards shell scripts (2) for creating Domain controller/keyvault/SP, using e2e configuration (1) to upload the correct files to the worker nodes and installing the plugin via ssh or pre-kubeadm. 

I like the idea of using service operator for some of this because closer to what customer might use but requires pulling that in as dependency.

Other options I missed? Thoughts?

**Comment by jsturtevant** [comment]
Another thought I realized I missed was turning one of the existing nodes into a Domain controller after the cluster is provisioned. This is the way it is done today in the Aks-engine configuration

**Comment by jsturtevant** [comment]
Another requirement is we should be able to easily swap out other plugins for testing as well.

**Comment by jsturtevant** [comment]
Current plan is:

1. The ccg plugin will be installed by image builder but can be overridden by the post-kubeadm script.
2. Use bash script to create DC, keyvalut and relevant security accounts (domain users and azure identity). The script will drop the credital spec file in place that the e2e suite can pick it up.
2. the e2e suite code will pick this file up and place it on a Windows node, label the node appropriately and give the node access to the keyvault secret, unsure dns is correctly configured.
3. The test is already configured to install the webhook, will find the correctly labeled node and credential spec file and so will run the test (instead of skipping which is what is happening now)

**Comment by jackfrancis** [comment]
/reopen
/remove-lifecycle rotten

@jsturtevant I assume we're not able to close this issue yet

**Comment by jsturtevant** [comment]
these are running https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master-serial-slow&include-filter-by-regex=GMSA

/close
