### ISSUE TITLE
Add support for ci-entrypoint to collect Windows logs

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1864]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
`ci-entrypoint.sh` script collects logs in a different way than the e2e test framework: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/feba723784818f210a7c4cb96e82d7b38d0b2334/scripts/ci-entrypoint.sh#L141

It doesn't currently support Windows because it uses a daemon set and and is missing the logs to collect for the Windows. See https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/hack/log/log-dump.sh

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/sig windows

**Comment by sayantani11** [comment]
@jsturtevant Can you explain a bit more on the issue? Like what should happen? or what should change?

**Comment by sayantani11** [comment]
@jsturtevant Can you explain a bit more on the issue? Like what should happen? or what should change?
