### ISSUE TITLE
Replace all occurrences of ToNot(HaveOccurred())

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1866]
Replace all occurrences of `Expect(err).To(HaveOccurred())` with (`Expect(err).NotTo(HaveOccurred())` (ToNot -> NotTo)

> Nit: I prefer `NotTo` because it doesn't split an infinitive (yes I know that's considered [an archaic rule](https://en.wikipedia.org/wiki/Split_infinitive), but it still sounds wrong to me)

-- @mboersma 

/good-first-issue

**Comment by Evalle** [comment]
Hi @CecileRobertMichon @mboersma is it an internal joke or should we really add the change? 
According to this [comment](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1767#discussion_r749637975) @mboersma prefers to have `NotTo` :)

**Comment by CecileRobertMichon** [comment]
@Evalle my apologies, I messed up the order in the description :D 

it should be replace all occurrences of `ToNot`... will fix the description

/retitle Replace all occurrences of ToNot(HaveOccurred())

**Comment by Evalle** [comment]
I see :) thanks for the clarification. Let me create a PR.
