### ISSUE TITLE
Add e2e test for Windows that verifies Accelerated networking is working

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1867]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We have had issues with accelerated networking in azure in the past with Windows.  We would like to have a test that verifies the behavior and prevents regression.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

https://github.com/Azure/aks-engine/issues/2281 for reference.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/sig windows

**Comment by jsturtevant** [comment]
we can use [packetmon](https://docs.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon) to validate the traffic is flowing through the correct nic by tracking packet counters on the  Mellanox nic that is added when acceleration is enabled.

**Comment by jackfrancis** [comment]
/remove-lifecycle stale

A quick thought: the easiest test delivery/validation mechanism would be a helm chart that wraps a `Job` resource which runs and if finished to completion indicates a successful outcome.
