### ISSUE TITLE
Only show relevant conditions for the AzureCluster / AzureMachine

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1868]
When building a cluster, the user should only see conditions that apply to that specific cluster in the Status and as part of summary. For example, if the cluster has no vnet peerings, it should not show a "vnet peerings ready" condition.

This is related to https://github.com/kubernetes-sigs/cluster-api/issues/5624.

Two ways we can go about achieving this:

1) Remove the WithConditions() option in SetSummary https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/cluster.go#L599. This will ensure the controller only uses conditions that are set to set Ready status.
Pros: minimal code changes required, no changes required if we add or remove services later
Cons: external controllers setting conditions on the object may interfere, some glitches are possible where the status temporarily becomes Ready even though not all resources are ready if all the set conditions are true and some conditions haven't been set yet.

2) Add conditional logic to determine the set of Conditions needed based on the length of the different resource specs (ie. `if len(spec) != 0 { // append condition to list of conditions}`, sort of similar to what CAPA is doing here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/461ef72c3b647e729298ec5507c3387dabf7b015/pkg/cloud/scope/cluster.go#L209-L233
Pros: well defined set of conditions, Ready status will always be correct
Cons: more logic required, logic will need to evolve whenever we add/remove services

In both cases, we will also need to change services to only set update the Status if the spec has > 0 resources https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/vnetpeerings/vnetpeerings.go#L75

**Comment by Jont828** [comment]
Sure, I'd be happy to take a look!

**Comment by CecileRobertMichon** [comment]
@Jont828 could we prioritize this one so we can merge it before releasing v1.2 which includes a lot of new async services? Let me know if you need any help.
