### ISSUE TITLE
Separate out upgrade specs into its own job

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#1869]
/kind feature

**Describe the solution you'd like**
With new upgrade tests added as part of #1810 and #1771 capi e2e spec is now taking ~2.5 hrs to complete. This is undesirable. #1816 tried to address this by increasing ginkgo nodes count, but it increased the percentage of flakes, and we are still working on it find the root cause.

In the interim, to reduce the time taken to run capi e2e tests, we want to split the spec into different jobs so that they can be run simultaneously. We want something like this:

1. Remove kcp upgrades and merge with cluster upgrade tests. https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1810#issuecomment-970605421
2. Extract clusterctl upgrade tests (v1alpha3->v1beta1, v1alpha4->v1beta1) into a separate spec 
3. Keep the remaining capi e2e spec as it is.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
I took care of 1 in #1735

**Comment by shysank** [comment]
@CecileRobertMichon can we close this one?

**Comment by CecileRobertMichon** [comment]
Yes!

/close
