### ISSUE TITLE
Refactor Get existing logic into CreateResource() async helper

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1871]
Currently, we're implementing the same logic to get the existing resource for each service in the client CreateOrUpdateAsync function that has been refactored by #1702. We should try to extract that logic to CreateResource() so it can be shared by all the services, have better unit testing. That will also ensure the clients have minimal business logic and stay as close to wrappers of the SDK as possible.

**Comment by Jont828** [comment]
Sure I'd be happy to help out
