### ISSUE TITLE
Investigate HA control plane

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#188]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
I'm interested in this! The goal would be for multi-master, multi-AZ, yeah?

**Comment by justaugustus** [comment]
@alexeldeib -- sorry, I missed your note on this, else I would've let you run with this one!

Closed via #245, #243.
/close
/assign
/remove-lifecycle stale
/priority important-soon
/milestone v1alpha1
