### ISSUE TITLE
Migrate from "getting full resource to get tags" to "just getting tags at resource scope"

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes-sigs/cluster-api-provider-azure#1899]
This is based on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1745#discussion_r741488690

For example, in this method

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1a16f42bc104b6a8f5931dcb36f7c5ca184ff4e3/azure/services/publicips/publicips.go#L142-L151

We need to replace `GET` public IP API call (`s.Client.Get`) with `GET` Tags At Scope API call with Public IP as scope to just get the tags as we want only tag data to check if Public IP is managed or not. A `GET` public IP API call is heavier with more data and hence unnecessary.

References -
- `GET` public IP API call - https://docs.microsoft.com/en-us/rest/api/virtualnetwork/public-ip-addresses/get
- `GET` Tags At Scope API call - https://docs.microsoft.com/en-us/rest/api/resources/tags/get-at-scope

cc @CecileRobertMichon

**Comment by Jont828** [comment]
Sorry I forgot about this, I can take a look and work on this soon.

**Comment by Jont828** [comment]
@CecileRobertMichon @karuppiah7890 I'm currently taking a look at this and I had a couple things to clarify. 
1. Is the public IP scope in this case just the resource ID?
2. Is the intended change to initialize the [tags client](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/tags/client.go) and use that instead?

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle rotten

1. Yes, it should be
2. Yes exactly. There is already a `GetAtScope` function we can use.

**Comment by Jont828** [comment]
Okay sounds good. I'll revisit #2210 as well and see if we can make some changes to the tags service to make it easier to use here.
