### ISSUE TITLE
Release branching strategy

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#190]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by rbitia** [comment]
We are currently following the CAPI branch releasing strategy. 
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/developer/releasing.md

**Comment by rbitia** [comment]
We also have a doc in our CAPZ repo: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/releasing.md
Closing for now. 

/close
