### ISSUE TITLE
Context deadline exceeded on RG GET

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1901]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

Observed in PR #1711, repro'ed locally: 

```
E1201 19:33:57.222382      38 controller.go:317] controller/azurecluster "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to reconcile resource group: failed to create resource cecile-9211/cecile-9211 (service: group): failed to get desired parameters for group cecile-9211: failed to get RG cecile-9211: resources.GroupsClient#Get: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded" "name"="cecile-9211" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureCluster" 
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Interestingly it seems like the RG GET is actually timing out after 12 seconds. I wouldn't expect an Azure GET API to take 12 seconds.... cc @devigned @Jont828 

![Screen Shot 2021-12-01 at 12 12 06 PM](https://user-images.githubusercontent.com/8650424/144306833-a3a2f18f-baaa-43ac-8af7-d3f6beb83c2f.png)

**Comment by devigned** [comment]
> Interestingly it seems like the RG GET is actually timing out after 12 seconds. I wouldn't expect an Azure GET API to take 12 seconds.... cc @devigned @Jont828
> 
> ![Screen Shot 2021-12-01 at 12 12 06 PM](https://user-images.githubusercontent.com/8650424/144306833-a3a2f18f-baaa-43ac-8af7-d3f6beb83c2f.png)

This looks like it's talking to IMDS IP rather than ARM. Are you sure it's not AAD pod identity / IMDS exceeding 12 seconds?

**Comment by CecileRobertMichon** [comment]
sorry for the tag, I just pasted the comment here yesterday because I realized I had previously put it in the wrong issue...

**Comment by CecileRobertMichon** [comment]
From a separate investigation (slack thread) this error seems to occur when pod identity is not able to fetch the token from IMDS under 12 seconds, possibly because the token is not valid. It's not ideal that it doesn't return an error and just times out, there might be a way to improve the logging when this happens so the user knows it's a problem with their client id/secret.

**Comment by yastij** [comment]
/reopen

@CecileRobertMichon - we've been seeing similar issues at the infra/machine level:

```
message:'inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer upgrade-9599mgmt-azure-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded'
```

```
kubernetes version update failed, reason:'DeletionFailed @ Machine/upgrade-9601azure-antrea-control-plane-jwwl9', message:'interfaces failed to delete. err: failed to delete resource xxxxxx (service: interfaces): network.InterfacesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded' 
```

these clusters are still relying aad-pod-identity, not sure if that's reproducible with workload identity
