### ISSUE TITLE
custom cloud provider secret is overwritten with default values

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#1902]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Contents of the control plane [custom cloud provider secret](https://capz.sigs.k8s.io/topics/cloud-provider-config.html) are overwritten with default values.

**What did you expect to happen:**
The secret should not be overwritten if it already exists and is not marked as owned by the cluster.

**Anything else you would like to add:**
@nilo19 ran into this and reported it to me. I have not verified the behavior.

/help
/good-first-issue

**Comment by CecileRobertMichon** [comment]
/remove-good-first-issue

we should validate this issue exists before we mark it as suitable for new contributors
