### ISSUE TITLE
Use kustomize remote URL's to manage addons

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1917]
/kind feature

**Describe the solution you'd like**

Currently we copy the addon's into our code base, modify and maintain them.  We can use kustomizes remote url and a make command to automate this as done in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1903

example from pr:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.2/components.yaml
```

```
.PHONY: generate-addons
generate-addons:
	$(KUSTOMIZE) build $(ADDONS_DIR)/metrics-server > $(ADDONS_DIR)/metrics-server/metrics-server.yaml
```

Possible files we could switch to this method:

- [ ] cloudprovider
- [x] [calico](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/calico.yaml)
- [x] [calico ipv6](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/calico-ipv6.yaml)
- [ ] [storage classes for azure disk/file](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/storageclass-azure-file.yaml)
- [ ] [windows files](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
we've made a progress on this. I've checked off a few of the checkboxes

**Comment by CecileRobertMichon** [comment]
For cloud-provider we might not be able to do this as there is no manifest artifact published as part of [releases](https://github.com/kubernetes-sigs/cloud-provider-azure/releases). There are [sample manifest in the repo ](https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/examples/out-of-tree) but @feiskyer pointed out those shouldn't be used directly as addon manifests since they use a `Pod` for CCM which should only be applied as a static Pod (instead of a `Deployment`).

**Comment by feiskyer** [comment]
this would require all addons supporting kustomize for setting various parameters. Have we confirmed all addons would support kustomize?

**Comment by CecileRobertMichon** [comment]
@feiskyer not sure what you mean by "supporting kustomize" ? Kustomize is just used to customize a yaml manifest, it can be used with any yaml spec and doesn't need the k8s application to do anything to support it. 

As long as the addon manifest is published somewhere in a publically accessible URI (for example, on github) then we can just fetch it and use kustomize to add patches to it. 

Note: we're exploring moving in a different direction and using Helm charts instead. cc @jackfrancis
