### ISSUE TITLE
Implement tagging

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#193]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
what are the requirements here? is tagging referring to Azure resource tags?

**Comment by alexeldeib** [comment]
refs:
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/proposal/aws-resource-handling.md#tagging-of-resources
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/704

**Comment by juan-lee** [comment]
@justaugustus I thought AWS needs tags because they don't have concept of resource groups? Do we need this?

**Comment by CecileRobertMichon** [comment]
FYI I am taking a stab at this because it overlaps with BYO vnet.
