### ISSUE TITLE
user agent CAPZ version is missing

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1949]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Using v1.1.0 tag, seeing user agent as `Go/go1.16.12 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v58.1.0 network/2021-02-01 cluster-api-provider-azure/`

![Screen Shot 2022-01-05 at 4 49 37 PM](https://user-images.githubusercontent.com/8650424/148310590-43de3feb-301f-4e64-a85d-44279f7b765d.png)

**What did you expect to happen:**

The user agent should have the Git Version of capz, ie. `cluster-api-provider-azure/v1.1.0`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
To reproduce:
- checkout a tagged version of CAPZ, eg. `v1.0.1` 
- run `make tilt-up`
- create a workload cluster
- select the “traces: jaeger-all-in-one” resource in the tilt UI, and click “View traces” near the top of the screen. Or visit http://localhost:16686/ in your browser.
- click on any of the Reconcile spans and expand one of the HTTP requests 
- see that the userAgent row has an empty string instead of the CAPZ version

**Comment by Jont828** [comment]
This should be fixed on the image releases now that this [test-infra PR](https://github.com/kubernetes/test-infra/pull/25233) has merged.

**Comment by CecileRobertMichon** [comment]
@Jont828 should we revert the echo lines added for debugging in #1963 now that this is fixed?

**Comment by CecileRobertMichon** [comment]
@Jont828 you should be able to verify that this is fixed now that https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v1.1.2 is out

**Comment by CecileRobertMichon** [comment]
/reopen

/assign @Jont828 

to validate that this is fixed in the latest release and revert the debug output added in #1963
