### ISSUE TITLE
Add optional override for API Endpoint

### ISSUE THREAD

**Issue by dmlb2000** [kubernetes-sigs/cluster-api-provider-azure#1958]
/kind feature

**Describe the solution you'd like**
I'd like to be able to override what Azure provider is sending back to Cluster API as the API Endpoint. This will allow for more complex BYO infrastructure between the K8S management cluster and Azure deployed K8S clusters while still ensuring connectivity.

**Anything else you would like to add:**
I'll try to add the code, not as familiar with Go, but gotta learn some time.

**Environment:**

- cluster-api-provider-azure version: main
- Kubernetes version: (use `kubectl version`): v1.23 or v1.22
- OS (e.g. from `/etc/os-release`): Windows, Ubuntu, MacOS, depends on where things are at.

**Comment by dmlb2000** [comment]
Yes this got fixed by the other pull request.

Thanks
David Brown

**Comment by CecileRobertMichon** [comment]
yes

/close
