### ISSUE TITLE
Run regular tests for AKS (AzureManagedCluster) scenarios

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#1960]
/area test

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As the `AzureManagedCluster` feature for building AKS clusters using capz matures, we want to E2E test this "basic" scenario with every PR as a way of proactively protecting the health of this feature.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Briefly, what we want to do:

1. Define what the "basic" `AzureManagedCluster` scenario is.
2. Integrate the "basic" scenario into the regular test definitions that must run on every PR in order for merge to main.
3. Move the existing, "non-basic" `AzureManagedCluster` features into one or more ad hoc tests to ensure that those features continue to have a first-class project test gesture.
4. Set up a regular (e.g., daily) E2E test implementation that runs any of the "non-basic" `AzureManagedCluster` feature validations. For example, one or more github actions that runs on a regular schedule.

For reference, existing test templates that validate AKS scenarios are here:

- templates/test/ci/cluster-template-prow-aks-multi-tenancy.yaml
- templates/cluster-template-aks.yaml
- templates/cluster-template-aks-multi-tenancy.yaml
- templates/cluster-template-aks-aad.yaml

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
cc @zmalik since you've been working on adding AKS features
