### ISSUE TITLE
capz AKS cluster test is failing

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#1965]
/kind failing-test

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The test `capz-e2e.Workload cluster creation Creating an AKS cluster with a single control plane node and 1 node` is failing consistently: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-main

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Looks like it might be https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1945

https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/fdae34a56...c507e7d47

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/close 

fixed by #1971
