### ISSUE TITLE
Azure Marketplace images

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#197]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Could you give a bit more details on what you had in mind? Would the goal be to add variables for specifying OS image publisher/offer/sku/version? I see that right now it is hardcoded to Canonical UbuntuServer 18.04-LTS latest. I'd be interested in picking this up.

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/270.
/close
