### ISSUE TITLE
Add support to check to see if Azure features are registered

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#1975]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In the subnet service, we'd like to check `Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet` in order to construct the API call, because otherwise we'd run into a `SubscriptionNotRegisteredForFeature` error. Currently, there's a workaround in the subnet service but ideally we could check to see if a given feature is registered before making an API call, and if not, report an error to the user.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Note from our conversation earlier: it's also possible that the `AllowMultipleAddressPrefixesOnSubnet` feature doesn't require registration anymore and that workaround can be removed
