### ISSUE TITLE
Add support for GPU nodes in AKS (managed cluster)

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#1979]
/kind feature

**Describe the solution you'd like**
Support for GPU nodepools in AKS
https://docs.microsoft.com/en-us/azure/aks/gpu-cluster 

**Anything else you would like to add:**
one way to solve this is to allow custom headers for the requests to the agentpool creation. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by NovemberZulu** [comment]
Given than this [feature seems experimental](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#update-your-cluster-to-use-the-aks-gpu-image-preview), and even [official CLI uses magic parameters](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#update-your-cluster-to-use-the-aks-gpu-image-preview), I don't think there is support in official Go SDK. Assuming custom headers work reliably, it can be an OK solution for now. I wonder if there are other usecases for them...

**Comment by zmalik** [comment]
another way is the manual nvidia plugin also as CAPA is doing for EKS
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/templates/cluster-template-eks-managedmachinepool-gpu.yaml#L72

but I believe that as AKS is providing an automated solution we should go for it. As the manual DS can always be installed by the users. 

Instead of custom headers, I was imagining a field in `spec` which get translated into the the custom header for the GPU

**Comment by alexeldeib** [comment]
> but I believe that as AKS is providing an automated solution we should go for it. As the manual DS can always be installed by the users.

personally, I would suggest using the vanilla VHD (GPU drivers will still get installed automatically) and deploying the device plugin as daemonset. I'd actually like to move AKS internally closer to that model, but we need to figure out how to get there from where we are without breaking existing expectations. 

The nvidia operator should also work fine on AKS I believe, which I think is what's used for normal CAPZ clusters -- could try simply copying that.

**Comment by CecileRobertMichon** [comment]
> I guess general custom header support is a different feature then?

regardless of how we decide to implement this one, I think it'd be nice to also support custom headers to be able to turn on feature flags in AKS for testing purposes

**Comment by zmalik** [comment]
> personally, I would suggest using the vanilla VHD (GPU drivers will still get installed automatically) and deploying the device plugin as daemonset.

I feel the other way around to support the AKS features that users might get with a managed solution. A good example would be the cluster autoscaler. Which can be enabled via AKS or users can have their our own autoscaler deployment targeting the vmss. 

> regardless of how we decide to implement this one, it'd be nice to also support custom headers

I agree. If we are all ok then I will open a separate issue to support the custom headers for AKS control plane and agentpools. And that can be used also for the GPU feature.

**Comment by zmalik** [comment]
created https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1981 for aks custom headers support
