### ISSUE TITLE
golang-ci lint should be in parity with capi 

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#1982]
/kind bug

**What did you expect to happen:**
Did a comparison of golang-ci linters used in core capi vs capz and found out that couple of linters are missing in capz. If it makes sense, we could add those missing linters in capz too. The following section has the comparison matrix. 

TL;DR

Missing linters in CAPZ but present in CAPI:  
- gci
- gocritic
- ifshort
- predeclared
- stylecheck
- thelper
- unparam

We can discuss about these and if it makes sense then we can add these linters too. 

Ref link for what these linters do : 
https://golangci-lint.run/usage/linters/

**Anything else you would like to add:**
golang-ci lint comparison matrix: 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-24fe2445-7fff-3148-7a4d-deba751d0d33"><div dir="ltr" style="margin-left:0pt;" align="left">

S.no | Linters[golang-ci] | CAPI | CAPZ
-- | -- | -- | --
1 | asciicheck | ✔ | ✔
2 | bodyclose | ✔ | ✔
3 | deadcode | ✔ | ✔
4 | depguard | ✔ | ✔
5 | dogsled | ✔ | ✔
6 | errcheck | ✔ | ✔
7 | errorlint | ✖ | ✔
8 | exportloopref | ✔ | ✔
9 | gci | ✔ | ✖
10 | goconst | ✔ | ✔
11 | gocritic | ✔ | ✖
12 | gocyclo | ✔ | ✔
13 | godot | ✔ | ✔
14 | gofmt | ✔ | ✔
15 | goimports | ✔ | ✔
16 | goprintffuncname | ✔ | ✔
17 | gosec | ✔ | ✔
18 | gosimple | ✔ | ✔
19 | govet | ✔ | ✔
20 | ifshort | ✔ | ✖
21 | importas | ✔ | ✔
22 | ineffassign | ✔ | ✔
23 | misspell | ✔ | ✔
24 | nakedret | ✔ | ✔
25 | nilerr | ✔ | ✔
26 | nolintlint | ✔ | ✔
27 | prealloc | ✔ | ✔
28 | predeclared | ✔ | ✖
29 | revive | ✔ | ✔
30 | rowserrcheck | ✔ | ✔
31 | staticcheck | ✔ | ✔
32 | structcheck | ✔ | ✔
33 | stylecheck | ✔ | ✖
34 | thelper | ✔ | ✖
35 | typecheck | ✔ | ✔
36 | unconvert | ✔ | ✔
37 | unparam | ✔ | ✖
38 | unused | ✖ | ✔
39 | varcheck | ✔ | ✔
40 | whitespace | ✔ | ✔

</div><br /></b>

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sonasingh46** [comment]
cc @CecileRobertMichon @mboersma @shysank

**Comment by mboersma** [comment]
I think we should try to match the linters used in CAPI, because it will make the code style and contributor experience more similar. I've submitted several PRs in the past to get CAPZ closer to that goal, but frankly I did most of the low-hanging fruit first, so there may be some tricky ones remaining.

I would just advise that we create one PR per linter, to make it easier to review. Thanks for doing this!

**Comment by shysank** [comment]
+1 to having one pr per linter. We can create sub tasks/issues for better tracking like we did for async services.

**Comment by sbueringer** [comment]
> I think we should try to match the linters used in CAPI, because it will make the code style and contributor experience more similar. I've submitted several PRs in the past to get CAPZ closer to that goal, but frankly I did most of the low-hanging fruit first, so there may be some tricky ones remaining.
> 
> I would just advise that we create one PR per linter, to make it easier to review. Thanks for doing this!

Sounds great. We will try to do the same for core CAPI.

There might be some strong opinions about some linters, but I think in those cases we don't have to force complete parity, but it would be nice to get to it as close as we can get consensus on.

**Comment by sonasingh46** [comment]
Closing this issue as all the tasks under this has been covered.
