### ISSUE TITLE
Conversion is not completely implemented for all API types

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-azure#1989]
/kind bug

Hey folks,
in core CAPI we have a tool called conversion-verifier which loops over all types and ensures the controller-runtime conversion interfaces are implemented correctly, i.e. it checks the types have the Hub / ConvertTo / ConvertFrom functions.

The results for CAPZ are:
* type "infrastructure.cluster.x-k8s.io/AzureClusterIdentityList" in package "sigs.k8s.io/cluster-api-provider-azure/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/AzureManagedClusterList" in package "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/AzureManagedControlPlaneList" in package "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/AzureMachinePoolList" in package "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/AzureManagedMachinePoolList" in package "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods

I think it would be great to:
* implement the missing methods
* integrate the conversion-verifier in CI

The conversion-verifier can be found here:
* Code: https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier
* Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

I can provide additional details if needed / if you want to implement this issue.

**Environment:**

- cluster-api-provider-azure version: latest
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): -

**Comment by mboersma** [comment]
/close

Fixed by #2042
