### ISSUE TITLE
Allow configurable Kubernetes versions

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#199]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@justaugustus is this not already possible via the `KUBERNETES_VERSION` variable?

**Comment by justaugustus** [comment]
@CecileRobertMichon -- good catch!
This issue predated that variable, so we can close this out. :)
/close
