### ISSUE TITLE
Cluster Overview Department Management

### ISSUE THREAD

**Issue by Manny27nyc** [kubernetes-sigs/cluster-api-provider-azure#1997]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Goal 1
1. Goal 2

***Non-Goals/Future Work***
1. Non-Goal 1
1. Non-Goal 2

**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Contract changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

**Data model changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

/kind proposal

**Comment by CecileRobertMichon** [comment]
/close

please repoen with details and filled out description
