### ISSUE TITLE
Use go install instead of go get to install binaries

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2004]
https://go.dev/doc/go-get-install-deprecation

Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.

In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. 

we should stop using go get to install hack/tools and instead rely on go install here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/go_install.sh#L54

/good-first-issue

**Comment by jayesh-srivastava** [comment]
Hi @CecileRobertMichon, can you please help me with this as to why the tests are failing.

**Comment by CecileRobertMichon** [comment]
commented on the PR
