### ISSUE TITLE
Add a template for out-of-tree cloud provider + multiple vmss pools

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cluster-api-provider-azure#2019]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Both some existing e2e tests (e.g., `cloud-provider-azure-autoscaling-multipool`) and some testing scenarios we plan to cover in the future (e.g., multiple slbs) require a cluster with out-of-tree cloud provider + multi vmss pools.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@nilo19 if this is only for cloud provider e2e tests why not use https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/tests/k8s-azure/manifest/cluster-api ?

**Comment by nilo19** [comment]
> @nilo19 if this is only for cloud provider e2e tests why not use https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/tests/k8s-azure/manifest/cluster-api ?

Because I can see there is a lot of generated contents in the manifests in capz repo, e.g., https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-external-cloud-provider.yaml
I'm not sure how to generate it into a template and whether it is useful during the CI tests.
