### ISSUE TITLE
verify targets should be in parity with capi

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2026]
/kind bug

**What did you expect to happen:**
Did a comparison of verify targets used in core capi vs capz and found out that couple of verify targets are missing in capz. If it makes sense, we could add those missing targets in capz too. This should help improve the developer experience in my opinion. The following section has the comparison matrix. 

TL;DR

Missing targets in CAPZ but present in CAPI:  
- lint-fix
- apidiff
- verify-conversions
- verify-tiltfile
- verify-book-links

We can discuss about these and if it makes sense then we can add these targets too. 

**Comparison Matrix:**
Validations (executed via make)
S.no | make target| CAPI | CAPZ| CAPZ
-- | -- | -- | --| --
1 | lint-fix | ✔ | ❌| runs golangci-lint with --fix 
2 | apidiff | ✔ | ❌| diffs API changes on PRs
3 | verify | ✔ | ✔| target which runs all the other verify targets
4 | verify-modules | ✔ | ✔| verifies go.mod’s are up-to-date
5 | verify-gen | ✔ | ✔| verifies all generated files are up-to-date
6 | verify-conversions | ✔ | ❌| verifies all API types implement conversions
7 | verify-boilerplate | ✔ | ✔| verifies file headers
8 | verify-shellcheck | ✔ | ✔| verifies shell scripts
9 | verify-tiltfile | ✔ | ❌| verifies tiltfile
10 | verify-book-links | ✔ | ❌| verifies links in books

**Note:** The `lint-fix` target will get fixed by PR [1987](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1987)

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
apidiff is a script: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-apidiff.sh

it's also a script in CAPI https://github.com/kubernetes-sigs/cluster-api/blob/main/scripts/ci-apidiff.sh, wonder if it's still being used

**Comment by sonasingh46** [comment]
The script is used in PROW job. Thanks for pointing put the apidiff script in CAPZ. 
The corresponding target name in capz is `go-apidiff`. Wondering if it makes sense to have the same target name as that of CAPI to help improve contributor experience .

**Comment by sbueringer** [comment]
@CecileRobertMichon It's used by the ProwJobs.

In core CAPI we have:
* the shell script ci-apidiff which shows the apidiff to ${PULL_BASE_SHA}
* the makefile target apidiff which shows the apidiff to origin/main

In CAPZ:
* the shell script ci-apidiff which shows the apidiff to ${PULL_BASE_SHA}

I think in both repos we have targets to just build the binary. 

The difference seems to be that in CAPI we have an additional target to run the diff against origin/main (for convenience?)

**Comment by sonasingh46** [comment]
Closing this as the required PRs are merged.
