### ISSUE TITLE
Add stylecheck linter

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2030]
/kind bug

Add `stylecheck` linter in the CAPZ repo. 

Some similar PR references for adding linters are below: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1986
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1985

**What did you expect to happen:**
Refer to the umbrella [issue](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1982) 

Ref link for linters: 
https://golangci-lint.run/usage/linters/

/good-first-issue

**Comment by sonasingh46** [comment]
@matgomes21 -- Thank you for taking up the issue. Feel free to reach out if you need any help.

**Comment by matgomes21** [comment]
@sonasingh46  Thanks! I let you know if I need some help.
