### ISSUE TITLE
Fix AKS (AzureManagedCluster) cluster create on release-0.5

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2039]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The release-0.5 branch has a broken AKS implementation. At least the following PRs will need to be manually cherry-picked in order to restore functionality:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1850
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2025

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@jackfrancis I can do a manual cherry pick directly in #2028 since there is a merge conflict

**Comment by CecileRobertMichon** [comment]
/close

fixed in #2028
