### ISSUE TITLE
nodeRef is only set on a machine when the SyncPeriod is expired

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-azure#204]
/kind bug

**What steps did you take and what happened:**

**What did you expect to happen:**

atm the actuator will only set the nodeRef on a machine when the `actuators.exists` operation is invoked and a node with a matching providerID is there, which will only happen when a machine controller reconciliation is triggered by the SyncPeriod expiration.
The same is likely happening on aws

We should find a way to react as soon as the node comes up 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by enxebre** [comment]
cc @vikaschoudhary16

**Comment by nader-ziada** [comment]
@enxebre As far as I understand, what you are describing is the behaviour of `CAPI`, the machine controller only check if the noderef is available every cycle which happens by the duration defined in `SyncPeriod`

if there is a specific problem with this; we could do something like what was done in this PR (https://github.com/kubernetes-sigs/cluster-api/pull/2432) to trigger a reconcile, but we would need to discuss with the `CAPI` team
