### ISSUE TITLE
Change apidiff test to only fail for actual breaking API changes

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2051]
Right now the apidiff test fails as soon there is a breaking change in an exposed field or in an exposed function. While this is greatly useful for reviews, it results in a lot of false positives since we often have to change exported functions in the codebase and currently accept these changes.

We should consider modifying the job so it only looks at api/ changes since that's the area that is exposed to users where we want to avoid breaking changes. This might mean diverging from what CAPI is doing but it would be more appropriate for now until we either move types and functions we don't want exposed as a library to internal/ similarly to what CAPI did, and/or reach a stable codebase/library.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 @mboersma @shysank thoughts?

**Comment by jackfrancis** [comment]
Can we add a label (only admins are allowed to add to a PR) that tells the test: "don't run for this change"?

Ideally we'd be able to bypass only the checks that are changes and keep every other check running. But maybe it we ensure that an admin manually investigates the apidiff failure before permitting it by adding a label we're O.K.?

**Comment by CecileRobertMichon** [comment]
The test runs on every PR but it's not required for merge. So I usually as an approver verify that there are no breaking changes before commenting "/approve". This does require approvers to remember to check it. 

There is already a prow command for overriding a particular test failure but if we were to mark this test as required I have a feeling we would be using that command very often. It would also likely confuse new contributors and they might try to "fix" the test because they don't understand why it's failing.

**Comment by jackfrancis** [comment]
Makes sense. I think given how we want to occasionally permit API breaking changes the current test setup makes sense.

**Comment by mboersma** [comment]
So basically we would be ignoring `exp/` in the apidiff check?

I think the status quo is ok (it fails sometimes and requires a human to verify the changes aren't actually breaking). But if we did restrict the checking, we should try to give that a time limit while we work toward stability and/or moving things to internal packages like CAPI.

**Comment by shysank** [comment]
I agree to restricting it to just `api/`. There are so many false positives right now that I've ignored it almost all the time even in cases when I shouldn't have; when there are actual user facing api changes. We could probably still log the other changes as warnings, but only fail if there are actual user facing api changes.

**Comment by shysank** [comment]
> So basically we would be ignoring `exp/` in the apidiff check?

I think we'd still want to include `exp/api` but not other internal types/functions.

**Comment by sedefsavas** [comment]
We are having a similar discussion in CAPA https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3282

Regarding moving code to internal packages, CAPA will have a very limited code to expose. We are discussing if we can avoid doing this with just documenting.

Wanted to check if there is a similar discussion here as well or CAPZ is committed to use internal packages.

**Comment by CecileRobertMichon** [comment]
/reopen 

since #2232 reverted the change

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle stale
/unassign @meghanajangi

Please feel free to reassign if you pick this up again

**Comment by jackfrancis** [comment]
I don't think there's a way for go-apidiff to add per-directory (or file) exclusions:

https://github.com/joelanford/go-apidiff

I assume that means it's in-scope to use a different tool for this validation?

**Comment by CecileRobertMichon** [comment]
Absolutely, that would be a valid alternative. Another alternative would be to move everything that's not meant to be consumed externally into an `internal/` dir

https://github.com/joelanford/go-apidiff/issues/14#issuecomment-1086866074
