### ISSUE TITLE
AMMP controller watch event mapping function from CAPI machine pools using wrong GVK

### ISSUE THREAD

**Issue by dantiandb** [kubernetes-sigs/cluster-api-provider-azure#2058]
/kind bug

**What steps did you take and what happened:**
Noticed that in some cases of CAPI machinepool changes, watch events were not properly triggering for AMMP. When increasing log verbosity, looking through the CAPZ controller manager logs saw this:

```
I0208 21:35:28.127713       1 helpers.go:462]  "msg"="gk does not match"  "gk"={"Group":"cluster.x-k8s.io","Kind":"AzureManagedMachinePool"} "infraGK"={"Group":"infrastructure.cluster.x-k8s.io","Kind":"AzureManagedMachinePool"}
```

Seems like `clusterv1exp` is used instead of `infrav1exp` when setting up the watch here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/azuremanagedmachinepool_controller.go#L100

Which causes the mapping func check to fail here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/exp/controllers/helpers.go#L461

Not sure if using `clusterv1exp` was intentional, but that appears to be the root cause of the watch events not triggering?

**What did you expect to happen:**
On CAPI machinepool changes, watch events should consistently trigger and corresponding AMMP reconcile request should be submitted.

**Environment:**
- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): v1.21.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS

**Comment by CecileRobertMichon** [comment]
/area managedclusters

thanks for opening an issue @dantiandb. That definitely looks like a bug. Going to mark it as good first issue since the fix is straightforward but anyone should feel free to assign.

/good-first-issue

**Comment by thiagompc** [comment]
Thanks @dantiandb !
