### ISSUE TITLE
Add unit tests for AzureManagedMachinePool controller

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#2078]
/kind feature

**Describe the solution you'd like**

The file `exp/controllers/azuremanagedmachinepool_controller.go` does not have corresponding unit tests, but should. 

PR #2074 shows AMMPs are in use, and ideally that change would be covered by testing. I think it's too much to ask for that one-line change to implement an entire test module, so I opened this issue.

**Anything else you would like to add:**

Its neighbor `exp/controllers/azuremachinepool_controller.go` has some unit tests in a couple different files. Those could perhaps be used as a model or starting point.

**Comment by Aayush987** [comment]
@mboersma I am sorry for responding late. But actually, I am new to testing but I really want to learn and contribute to this issue can you link me to some resources which will help me write unit tests. I have asked for help from someone but I think he is busy right now.

**Comment by mboersma** [comment]
@Aayush987 no worries. In general, we would expect there to be a file `exp/controllers/azuremanagedmachinepool_controller_test.go` that contains Go unit tests covering the exported functions in `azuremanagedmachinepool_controller.go`.

There is a general tutorial on writing unit tests in Go [here](https://go.dev/doc/tutorial/add-a-test). And there are other controllers in the same package that do have unit tests: you can use those as a model.

I hope that helps! Let me know if you have more specific questions.

**Comment by KushalBeniwal** [comment]
@Aayush987 are you still working on this issue?

I have experience writing tests, so, if you want to co-work on this issue and learn along the way then I'm open to do so!

**Comment by Aayush987** [comment]
> @Aayush987 are you still working on this issue?
> 
> I have experience writing tests, so, if you want to co-work on this issue and learn along the way then I'm open to do so!

Ya ,I mean I want to work on it but i am still learning to write tests. But if you can help me to learn it will be great.

**Comment by Jont828** [comment]
Hey what's the status on this issue btw?

**Comment by KushalBeniwal** [comment]
Hey apologies, life happened and I couldn't work on the issue till now. Will complete it ASAP!

**Comment by xiujuanx** [comment]
Look like this issue is still not be taken, so I will work on this issue, thanks!

/assign

**Comment by willie-yao** [comment]
Hi @swastik959, thanks for taking a look at this issue! I saw that the issue was assigned to @xiujuanx . Did you contact them and/or are they not working on the issue anymore?

**Comment by xiujuanx** [comment]
The `azuremanagedmachinepool_controller.go` had been moved to another path, you can check [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commits/main/controllers/azuremanagedmachinepool_controller.go). Also I think [PR-3190](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3190) is not related with managedMachinePool controller. @swastik959 , if I am wrong, pls correct me. Thanks!

I am working on this issue and draft a PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3195. I mean draft is because I encountering an issue. My added unit tests can't pass and show below error:
```
=== RUN   TestAzureManagedMachinePoolReconcile
=== RUN   TestAzureManagedMachinePoolReconcile/should_successfully_reconcile
(string) (len=11) "==========="
    controller.go:269: missing call(s) to *mock_azure.MockReconciler.Reconcile(expected a context.Context, but got <nil>) /Users/xiujuanx/workspace/projects/cluster-api-provider-azure/controllers/azuremanagedmachinepool_controller_test.go:36
    controller.go:269: aborting test due to missing call(s)
=== RUN   TestAzureManagedMachinePoolReconcile/should_successfully_delete
(string) (len=11) "==========="
    controller.go:269: missing call(s) to *mock_azure.MockReconciler.Delete(expected a context.Context, but got <nil>) /Users/xiujuanx/workspace/projects/cluster-api-provider-azure/controllers/azuremanagedmachinepool_controller_test.go:50
    controller.go:269: aborting test due to missing call(s)
--- FAIL: TestAzureManagedMachinePoolReconcile (0.00s)
    --- FAIL: TestAzureManagedMachinePoolReconcile/should_successfully_reconcile (0.00s)
    --- FAIL: TestAzureManagedMachinePoolReconcile/should_successfully_delete (0.00s)
```
I have struggling with it for two days and still can't find the root cause. So could anybody pls help me take a look about this? Thanks a lot!

**Comment by xiujuanx** [comment]
For above I mentioned problems, I have fixed and  [pr-3195](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3195) is ready for reviewing:
```
=== RUN   TestAzureManagedMachinePoolReconcile
=== RUN   TestAzureManagedMachinePoolReconcile/Reconcile_succeed
=== RUN   TestAzureManagedMachinePoolReconcile/Reconcile_delete
--- PASS: TestAzureManagedMachinePoolReconcile (0.01s)
    --- PASS: TestAzureManagedMachinePoolReconcile/Reconcile_succeed (0.01s)
    --- PASS: TestAzureManagedMachinePoolReconcile/Reconcile_delete (0.00s)
```
Thanks!
