### ISSUE TITLE
Add registry config header for containerd

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes-sigs/cluster-api-provider-azure#2079]
/kind feature

**Describe the solution you'd like**

Suggestion ported from https://github.com/Azure/aks-engine/issues/4374 - See how many people are building CAPZ clusters by adding a registry config header for containerd - https://github.com/Azure/acr/blob/main/docs/http-headers.md#header-values

**Comment by CecileRobertMichon** [comment]
@bridgetkromhout this is done and will be part of any new Azure OS images built from image-builder after today.
