### ISSUE TITLE
Optionally enable/disable inbound nat rules for api server lb

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#2094]
/kind feature

Right now, an inbound nat rule is created for api server lb which forwards request for ssh interactions. This may not be suitable for certain environments where we'd want to restrict access to the control plane machine.

**Describe the solution you'd like**

Provide a way to disable the ssh nat rule.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@shysank you can restrict access to the control plane machines by providing [network security rules in the template](https://capz.sigs.k8s.io/topics/custom-vnet.html#custom-security-rules). By default, a rule is added to expose the SSH port but you could remove it to make sure the machines can't be accessed from the public internet. 

IMO it's still useful to have the NAT rules so you can use the LB IP to ssh into the VMs from within the VNet, even if you want to restrict access to the public internet.

**Comment by shysank** [comment]
I agree that for most cases it is useful to be able to ssh from within then vnet (atleast) for debugging purposes, but for scenarios where such a privilege might be a security violation, should we provide an option to disable it? Enable by default for majority of use cases, disable through override for the rest of them?

**Comment by CecileRobertMichon** [comment]
FWIW you can also add a network security rule to block inbound traffic on port 22 from _within_ the VNet. The default [network security rules](https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview) allow this but they have very high priority numbers, and they are meant to be overridden by custom rules that allow the user to control exactly what traffic is allowed. 

If there is still a use case for disabling NAT rules, happy to consider it. Would be curious to know exactly how the following is defined: "a privilege might be a security violation". If SSH traffic is completely denied, is it still a violation if the NAT rule exists?

**Comment by shysank** [comment]
You're right, the mere existence of a nat rule should not have any effect on the security.
