### ISSUE TITLE
Improve usability for rotating cloud provider credentials 

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#2096]
/kind feature

The current process of rotating is as follows:
1. update azure.json secret with new credentials
2. rollout machines to copy new credentials to /etc/kubernetes/azure.json

This is a bit cumbersome especially the rolling out part where the user has to do some kind of scale operation to trigger a rollout. 

**Describe the solution you'd like**
Provide an easier way to rotate cloud provider creds. This is partly mitigated by using managed identities, but it'd be great if we can have a better user experience for unmanaged identities as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Would something like a [VM run command ](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest) to update the files in place on the Machines be closer to what your looking for? Is the goal here to avoid rolling machines?

**Comment by shysank** [comment]
Apologies for not replying to this earlier. Looked into [VM run command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest), but couldn't envision what the workflow would look like. Do you mean using a script that periodically checks for cloud provider secret and restarts the processes? 

There is also a capi constraint especially for worker nodes, where we don't have a proper way of rolling out machines without doing some changes to the machine deployment (like `rolloutAfter` for control plane nodes). https://github.com/kubernetes-sigs/cluster-api/pull/4596
