### ISSUE TITLE
AzureMachineTemplate Reconcile occasionally fails to find AzureClusterIdentity

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2121]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

AzureMachineTemplate controller sometimes fails with:

```
E0224 22:27:33.232967       1 controller.go:317] controller/azuremachinetemplate "msg"="Reconciler error" "error"="failed to create scope: failed to retrieve AzureClusterIdentity external object \"capz-e2e-wdy4nd\"/\"cluster-identity\": AzureClusterIdentity.infrastructure.cluster.x-k8s.io \"cluster-identity\" not found (from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2119/pull-cluster-api-provider-azure-e2e-v1beta1/1496972953802248192/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-5bc6f7f446-kgpkr/manager.log) 
```

Eventually, the error seems to go away but this happens multiple times on each cluster create. We should investigate why the object is not found: is it actually being temporarily removed or is it not able to find it even if it's there? What can we do to prevent this error?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sonasingh46** [comment]
I have observed same behaviour multiple time while I was looking at the CI logs. Let me take a stab at this.

**Comment by willie-yao** [comment]
/remove-lifecycle stale
@sonasingh46 Are you still taking a look at this issue? Thanks so much for taking a stab at it!
