### ISSUE TITLE
Create additional E2E tests 

### ISSUE THREAD

**Issue by meghanajangi** [kubernetes-sigs/cluster-api-provider-azure#2124]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Create E2E tests for the following use-cases in AzureCluster codebase:
- Create a Cluster in VNET with peerings
- Create a Cluster with a Private LB for API server
- Create a Private Cluster with an outbound LB
- Create Cluster using AzureClusterIdentity

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/assign

**Comment by CecileRobertMichon** [comment]
Hi @meghanajangi, we already have e2e tests for the scenarios you mentioned:

- Create a Cluster in VNET with peerings: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-private.yaml#L71
- Create a Cluster with a Private LB for API server: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-private.yaml#L53
Create a Private Cluster with an outbound LB: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-private.yaml#L56 (although we are moving to default to NAT Gateways in the future, see #1532)
Create Cluster using AzureClusterIdentity: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-private.yaml#L251 (this is also the case for every test)

**Comment by CecileRobertMichon** [comment]
I'm going to close this. Feel free to reopen if you feel my comment above doesn't fully cover what you had in mind.

/close
