### ISSUE TITLE
Add support for WS2022 to other test templates

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#2139]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently we only support running WS 2022 in kubernetes CI flow.  The template `test/ci/cluster-template-prow.yaml` doesn't have an equivilant WS2022 flavor.

Found this with https://github.com/kubernetes/test-infra/pull/25444#discussion_r815632202

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

While the simpliest is to add an additional template that uses WS2022 we should consider how to provide away to select the default image if we want WS 2022 instead of 2019:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d241f821b1ed4a355369116e5ecce5cc31bee1b5/azure/defaults.go#L321

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/sig windows

**Comment by andyzhangx** [comment]
@jsturtevant is there any way I could enable 2022 windows test on azure disk csi driver test infra?

I see there is an example here:
https://github.com/kubernetes/test-infra/blob/90069405dd67b3e82959b7b07ae326bac3987e8c/config/jobs/kubernetes-sigs/sig-windows/release-master-windows.yaml#L233-L265

can I apply to https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/azuredisk-csi-driver/azuredisk-csi-driver-config.yaml?

**Comment by andyzhangx** [comment]
> it looks like those templates are using `test/ci/cluster-template-prow.yaml` which doesn't currently support 2022. Will need provide away to swap out the default 2019 image.

@jsturtevant any progress to support 2022 test run on test-infra?

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2194

**Comment by marosset** [comment]
/close
This work was completed with #2194
