### ISSUE TITLE
Add e2e test for creating a cluster using custom images

### ISSUE THREAD

**Issue by meghanajangi** [kubernetes-sigs/cluster-api-provider-azure#2152]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently e2e test for creating a cluster using custom images is not present.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/assign

**Comment by jackfrancis** [comment]
@meghanajangi Could you clarify what "custom images" means in this context? We have test coverage for capz reference images, which is functionally equivalent to a "custom image" (you would just reference another image)

Feel free to add `/remove-lifecycle rotten` if we still want to do this!
