### ISSUE TITLE
Enable working machinepool drain tests

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2159]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Recently we discovered the the machinpool drain tests run during capz E2E don't actually check for success/fail. While enabling that we observed that the original, serial validation implementation is flaky.

This issue is to remind us that we actually aren't functionally testing machinepool drain, and we do want to do that.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The deliverable is "implement working E2E test coverage that validates successful machinepoolmachine drain as a side-effect of the delete operation.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
if anyone would like to work on this one, a good way to make sure we have time to check for successful draining before the machine pool deletes would be to add a finalizer at the beginning of the drain test then remove it after checking for successful drain and proceeding with delete.

/help

**Comment by jackfrancis** [comment]
@CecileRobertMichon don't our VMSS tests already have this?

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/a7a55bf327393858ead8fcc0632f9998cb18cdee/test/e2e/azure_test.go#L386

**Comment by CecileRobertMichon** [comment]
I think we removed most of the test logic in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2160/files because it was flaky

**Comment by willie-yao** [comment]
@mboersma @Jont828 Before working on this, I wanted to check if any of you have taken a look at getting working cordon/drain tests? I'm just double-checking since both of you have been working on machinepools lately.

**Comment by mboersma** [comment]
I haven't specifically looked at cordon + drain tests. In the [`azure_machinepools.go`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_machinepools.go) test spec there is scale out / scale in test code that checks for the taints that cordon + drain uses, if that's helpful.
