### ISSUE TITLE
Update capi-->capz tests to use out-of-tree cloud-provider-azure

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2165]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

After https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1994 merges let's update the capz v1beta1 templates that capi tests consume so that we standardize to out-of-tree cloud-provider-azure by default. Ref:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/test/e2e/data/infrastructure-azure/v1beta1

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Closing in favor of #715 since they are duplicates

/close
