### ISSUE TITLE
CAPZ should not use ObjectMeta.ClusterName

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-azure#2173]
/kind bug

There is an upstream discussion about dropping ObjectMeta.ClusterName: https://github.com/kubernetes/kubernetes/pull/108717. Related CAPI issue: https://github.com/kubernetes-sigs/cluster-api/issues/6305

This field is not populated by Kubernetes and we should not use it as an CAPZ Cluster Name.

This issue is about doing some research where we use it in CAPZ and fix it if it is used.

h/t https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3321

/kind bug

**Comment by CecileRobertMichon** [comment]
Ask: find all the occurrences of `.ClusterName` and replace them with `.Spec.ClusterName`. 

`.ClusterName` is from metadata because ObjectMeta is inlined. We want to use the `ClusterName` value from `Spec` instead as `ObjectMeta.ClusterName` is unset and will soon be removed.
