### ISSUE TITLE
Migrate from AAD pod identity to Azure Workload Identity

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2205]
/kind feature

[Azure AD Workload Identity](https://github.com/Azure/azure-workload-identity) is the next iteration of [Azure AD Pod Identity](https://github.com/Azure/aad-pod-identity) that enables Kubernetes applications to access Azure cloud resources securely with [Azure Active Directory](https://azure.microsoft.com/en-us/services/active-directory/) based on annotated [service accounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/). 

Since Azure AD Pod Identity is getting deprecated, we should migrate all CAPZ usage to Azure Workload Identity.

**Comment by sonasingh46** [comment]
I can work on this one. 
/assign sonasingh46

**Comment by CecileRobertMichon** [comment]
@sonasingh46 let me know if you need any help with this one. Excited to see it moving forward.

/cc @chewong @aramase

**Comment by CecileRobertMichon** [comment]
@sonasingh46 is this something you're still working on?

Now that workload identity supports managed identity and identity federation, this would allow us to use managed identities even for management clusters not in Azure (eg. kind clusters!) https://github.com/Azure/azure-workload-identity/issues/325

**Comment by sonasingh46** [comment]
I had given some first pass time on this issue and then paused for some time on this. 
By the way, the info you shared sounds great and I can start on this again asap. 
I think the first step would be to start with a design document for this and I would love to do this.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 I'm going to mark this for the current release milestone given that you're working on it, if it's too tight we can move it to the next one (the next release date is ~1 month away)

/milestone v1.6

**Comment by jackfrancis** [comment]
Moving this to the next milestone, but worth mentioning that we definitely want to prioritize this for 1.7 (let's not push it out indefinitely)

**Comment by surajssd** [comment]
@CecileRobertMichon 

> Now that workload identity supports managed identity and identity federation, this would allow us to use managed identities even for management clusters not in Azure (eg. kind clusters!) https://github.com/Azure/azure-workload-identity/issues/325

Is there a documentation to do this for a generic k8s cluster? I found most of the [docs for this](https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity) refer to doing stuff on AKS, while I want to solve this for any k8s cluster on Azure. I am trying to solve this very problem for another project https://github.com/confidential-containers/cloud-api-adaptor/issues/974

**Comment by CecileRobertMichon** [comment]
@surajssd yes here: https://azure.github.io/azure-workload-identity/docs/topics/self-managed-clusters.html

**Comment by surajssd** [comment]
> @surajssd yes here: https://azure.github.io/azure-workload-identity/docs/topics/self-managed-clusters.html

Thanks 😇

**Comment by sonasingh46** [comment]
Just linking the doc PR here for the record. 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3770
