### ISSUE TITLE
Support Custom VM Extensions for AzureMachines

### ISSUE THREAD

**Issue by BDworak** [kubernetes-sigs/cluster-api-provider-azure#2221]
/kind feature

**Describe the solution you'd like**
Support deployment of custom VM extensions from the Azure Extension gallery as part of a VM deployment. Currently if you want to add any extensions to a deployed VM you have to deploy afterwards via Azure Portal or az cli(https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/overview). 

**Anything else you would like to add:**
A custom extension is already deployed to facilitate capz bootstrapping however additional extensions are not supported. The use case I am targeting directly is the deployment of the "Microsoft.Azure.ActiveDirectory.AADSSHLoginForLinux" extensions to facilitate AAD SSH login to the virtual machines. 

**Environment:**

- cluster-api-provider-azure version: 1.2.0
- Kubernetes version: (use `kubectl version`): 1.23.5 
- OS (e.g. from `/etc/os-release`): 
 ```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by jsturtevant** [comment]
Info on the azure Azure AD extension: https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux

**Comment by CecileRobertMichon** [comment]
@BDworak thanks for opening the issue! We already have code in place to reconcile extensions so this shouldn't be too hard to add. @Jont828 is actually working on refactoring some of the extensions code in #2177, after that PR is merged we could look at supporting this. We would just need to expose an API field in AzureMachines for specifying extensions to be deployed then wire it up to the existing extensions service in CAPZ code.
