### ISSUE TITLE
Creating Service Principal with Latest Cli Fails

### ISSUE THREAD

**Issue by evanfreed** [kubernetes-sigs/cluster-api-provider-azure#2226]
/kind bug

**What steps did you take and what happened:**

- Download the latest azure-cli
- Follow the [Getting Started](https://capz.sigs.k8s.io/topics/getting-started.html) docs.  
- Command to create the service principal now fails with the most recent `az` cli version.

```shell
az ad sp create-for-rbac --role contributor
...
Usage error: To create role assignments, specify both --role and --scopes.
```

**What did you expect to happen:**

I expected the service principal to get created without any issues.  A work around to mimic current behavior is:

```shell
az ad sp create-for-rbac --role contributor --scopes=/subscriptions/$(az account show --query id -o tsv)
```

I'd be happy to PR the change to the guide to the above unless there's better guidance on what scopes we should be defining.

**Anything else you would like to add:**

Looks like there was a breaking change introduced that requires `--scope` to be defined ([reference](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#role))

My cli version:

```shell
az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "support": "1.0.3"
  }
}
```

**Comment by jackfrancis** [comment]
Thanks for reporting!

I think adding the `--scopes="${AZURE_SUBSCRIPTION_ID}"` to the existing docs would work.

@CecileRobertMichon @shysank any concerns that the above addition would be too broad to recommend in the quick docs?

**Comment by CecileRobertMichon** [comment]
+1 to amending the doc, CAPZ needs contributor access on the sub in order to be able to create a resource group (unless you BYO resource group, but that won't be the case for more new users)

Scopes needs to be in the `/subscriptions/123` format so `az ad sp create-for-rbac --role contributor --scopes=/subscriptions/${AZURE_SUBSCRIPTION_ID}` is what we need.
