### ISSUE TITLE
Kube-proxy failed to start on windows nodes but ci jobs still ran test cases

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/cluster-api-provider-azure#2228]
/kind bug
/kind flake

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The PROW job ci-kubernetes-e2e-capz-master-containerd-windows ran and had several networking/DNS related test failures.
Upon further investigation kube-proxy for one of the Windows nodes failed to start.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1513303552783552512

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1513303552783552512/artifacts/clusters/capz-conf-furxog/kube-system/kube-proxy-windows-4w8cf/kube-proxy.log
```
WARNING: The names of some imported commands from the module 'hns' include unapproved verbs that might make them less 
discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose 
parameter. For a list of approved verbs, type Get-Verb.
Running kub-proxy service.
Waiting for HNS network Calico to be created...
HNS network Calico found.
Program 'kube-proxy.exe' failed to run: The specified executable is not a valid application for this OS platform.At 
line:1 char:1
+ c:/k/kube-proxy.exe --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ c:/k/kube-proxy.exe --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
 
kubeproxy version 
Write files so the kubeconfig points to correct locations


    Directory: C:\var\lib


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        4/11/2022  12:07 AM                kube-proxy                                                            
DSR feature is not supported.
Overlay network requires kube-proxy >= v1.14.  Detected .
At C:\C\bc4eae3e4d9d2ac6e28c5df2af98d818af850b0479d9a05a0324297dd5abe96e\kube-proxy\start.ps1:79 char:9
+         throw "Overlay network requires kube-proxy >= v1.14.  Detecte ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Overlay network...14.  Detected .:String) [], RuntimeException
    + FullyQualifiedErrorId : Overlay network requires kube-proxy >= v1.14.  Detected .
 
```

**What did you expect to happen:**
I would have expected tests to not run in this case and instead have this issue surface as a cluster-provisioning issue.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): master (1.24)
- OS (e.g. from `/etc/os-release`): windows

/sig windows

**Comment by marosset** [comment]
The cluster had 2 nodes and kube-proxy started fine on one node but not on the other.

Maybe there was a file corruption during the copy operation in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/prow-ci-version/patches/kubeadm-bootstrap-windows.yaml ?

Or maybe the kube-proxy ds started too soon?

Needs more investigation to figure out what happened

**Comment by claudiubelu** [comment]
Looking in the test logs [1] for the test run that failed [2], we can see the following:

```
Apr 11 00:07:47.200: INFO: 2 / 2 pods ready in namespace 'kube-system' in daemonset 'kube-proxy-windows' (0 seconds elapsed)
```

Technically, the kube-proxy pod on the problematic node is "started", but that is obviously not true [3]. I assume that the kube-proxy pod started before the kube-proxy binary finished copying, resulting in that error.

For this, we could do the following:

- ensure that all the binaries are completely copied on the nodes before starting the test suite.
- have the kube-proxy pod exit when an error occurs in its powershell script, so the pod will then get restarted later when the kube-proxy was copied over and can start properly. The Kubernetes E2E tests already makes sure that all the daemonsets in the ``kube-system`` namespace are started, so having the pod fail when it's not yet ready is a good idea, this would mean that we won't start the test suite with an inactive kube-proxy (which would reduce further flakes).

I think adding ``$ErrorActionPreference = "Stop"`` in the kube-proxy's ``start.ps1`` script should solve this issue.

[1] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1513303552783552512/build-log.txt
[2] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1513303552783552512
[3] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1513303552783552512/artifacts/clusters/capz-conf-furxog/kube-system/kube-proxy-windows-4w8cf/kube-proxy.log
