### ISSUE TITLE
Occasional issues pulling windows container images from dockerhub

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/cluster-api-provider-azure#2230]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**

Many of the container images used to bring up windows nodes (kube-proxy, calico, etc) are hosted at [docker.io/sigwindowstools](https://hub.docker.com/u/sigwindowstools) and now CI jobs are having trouble pulling the images.

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/16a804d4a2624ce9748bb1d42d2786fd3c6d934d/templates/addons/windows/calico/calico.yaml#L166
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/16a804d4a2624ce9748bb1d42d2786fd3c6d934d/templates/addons/windows/calico/calico.yaml#L208
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9250e50ef766bc5a2fabddfc753f102dee32b0a1/templates/addons/windows/calico/kube-proxy-windows.yaml#L24

https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1280#issuecomment-1097920756

**What did you expect to happen:**
These images should not be hosted on dockerhub to avoid rate limiting imposed there

**Anything else you would like to add:**
These images are produced in https://github.com/kubernetes-sigs/sig-windows-tools

I think it would make sense to publish the images to a github hosted container registry like we do for csi-proxy, eventflow-logger, and other Windows / k8s related images.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@marosset was this related to the "v" prefix issue or is this something else?

**Comment by marosset** [comment]
The issue we were seeing with the azuredisk PR jobs has been resolved but this issue is still valid.
I'm going to work on publishing images `ghcr.io/kubernetes-sigs/sig-windows` (and back-filling all the existing images) when I get  a little bit of time.

**Comment by jackfrancis** [comment]
I assume the root cause is throttling from docker.io?

**Comment by marosset** [comment]
> I assume the root cause is throttling from docker.io?

Yes, we'd like to move away from docker hub to avoid throttling there.

**Comment by marosset** [comment]
> > I assume the root cause is throttling from docker.io?
> 
> Yes, we'd like to move away from docker hub to avoid throttling there.

And also it makes sense to manage the images in kubernetes-sigs managed resources.

**Comment by jackfrancis** [comment]
assuming this work hasn't been done, so

/remove-lifecycle stale

**Comment by nawazkh** [comment]
housekeeping
/remove-lifecycle rotten

**Comment by willie-yao** [comment]
@marosset Thanks for working on this! Are there any updates on getting the `ghcr.io/kubernetes-sigs` images marked as public?

**Comment by dtzar** [comment]
/remove-lifecycle rotten

@marosset - has this been resolved now?

**Comment by marosset** [comment]
> /remove-lifecycle rotten
> 
> @marosset - has this been resolved now?

Yes - I think this has been resolved
/close
