### ISSUE TITLE
Stop setting KUBE_TEST_REPO_LIST for 1.24+ clusters testing Windows

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/cluster-api-provider-azure#2236]
/kind feature
/area test

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Stop setting `KUBE_TEST_REPO_LIST` during Windows test passes for K8s 1.24+

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

In K8s v1.23 and below we need to specify an alternate container registry because some tests use an etcd image which doesn't include a Windows image.
In K8s 1.24 a Windows image was added to the etcd images (starting with k8s.gcr.io/etcd:3.5.3-0)
e2e.test binary was updated to use etcd:3.5.3-0 during K8s 1.24 development.

Because of this clusters used for e2e testing should no longer specify an alternate image repo.

https://github.com/kubernetes-sigs/windows-testing/tree/master/images#image-repository-list

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
cc @marosset @jsturtevant to address stale status

**Comment by jsturtevant** [comment]
I believe we've addressed this with https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2337
/close
