### ISSUE TITLE
Stale nodes left behind on a workload cluster

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-azure#2241]
/kind bug

**What steps did you take and what happened:**
- Create a workload cluster with a MHC targeting NotReady worker nodes 
- For some reason, the worker nodes of the cluster do not get into the Ready state (the CPI pods do not get deployed)
- MHC reaps the not Ready Machines to retry creating new nodes.
```bash
[vc-robo@sc2-10-187-103-200 worker]$ k get nodes
NAME STATUS ROLES AGE VERSION
robo-antrea-control-plane-2z4j9 Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-gpwnq Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-j8kq5 Ready control-plane,master 16h v1.20.4
robo-antrea-md-0-6769cbc7cd-25h2m NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-25xg9 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-445kj NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-49cxp NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-4cc59 Ready <none> 8h v1.20.4
robo-antrea-md-0-6769cbc7cd-4n6wj NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-4p5c4 NotReady <none> 11h v1.20.4
robo-antrea-md-0-6769cbc7cd-4t2hd NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-52gwb NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-54vmq NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-5mj54 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-5xw9j NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-6vh4z NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-6zvrd NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-7czsf NotReady <none> 12h v1.20.4
robo-antrea-md-0-6769cbc7cd-7l6xp NotReady <none> 8h v1.20.4
``` 

**What did you expect to happen:**
Reaped nodes by MHC should not show up in the output of `kubectl get nodes`

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
> For some reason, the worker nodes of the cluster do not get into the Ready state (the CPI pods do not get deployed)

Do you know why cloud provider pods are not getting deployed? Are you using cloud provider azure in "[external](https://capz.sigs.k8s.io/topics/cloud-provider-config.html#external-cloud-provider)" mode? 

Cloud provider is responsible for cleaning up old nodes that are no longer assoicated with a Machine so if you don't have cloud provider running that would also explain why the nodes are being left behind

**Comment by jackfrancis** [comment]
@srm09 is this issue still occuring?
