### ISSUE TITLE
login trying too aggressively

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/cluster-api-provider-azure#2250]
/kind bug

**What steps did you take and what happened:**
Tried to create a new cluster.
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: xxx
  namespace: yyy
spec:
  allowedNamespaces:
    list:
    - zzz
  clientID: someid
  clientSecret:
    name: sp-cert
    namespace: yyy
  tenantID: someotherid
  type: ServicePrincipal

Then created the secret like so:
kubectl create secret generic -n yyy sp-cert --from-file=certificate=key.pem

**What did you expect to happen:**
If it were to fail to work, it should slow down

Instead capz-nmi is spewing constantly about:
E0420 20:34:00.878482       1 server.go:399] failed to get service principal token for pod: capz-system/capz-controller-manager-c75cd8b88-j7sww, error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'someid'.\r\nTrace ID: someid\r\nCorrelation ID: 9c578966-9524-4a0b-9114-3fd1fa918609\r\nTimestamp: 2022-04-20 20:34:00Z","error_codes":[7000215],"timestamp":"2022-04-20 20:34:00Z","trace_id":"someid","correlation_id":"someid","error_uri":"https://login.microsoftonline.com/error?code=7000215"} Endpoint https://login.microsoftonline.com/someid/oauth2/token?api-version=1.0

It should probably back off at some point

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by kfox1111** [comment]
Seems related to https://github.com/Azure/azure-cli/issues/9970. The docs don't hint that you need to produce a "certificate" with a key and cert in it, in the right order. I was able to login via az login using that format. still not workign with the capz though.

**Comment by CecileRobertMichon** [comment]
> If it were to fail to work, it should slow down
> 
> Instead capz-nmi is spewing constantly about:
E0420 20:34:00.878482       1 server.go:399] failed to get service principal token for pod: capz-system/capz-controller-manager-c75cd8b88-j7sww, error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'someid'.\r\nTrace ID: someid\r\nCorrelation ID: 9c578966-9524-4a0b-9114-3fd1fa918609\r\nTimestamp: 2022-04-20 20:34:00Z","error_codes":[7000215],"timestamp":"2022-04-20 20:34:00Z","trace_id":"someid","correlation_id":"someid","error_uri":"https://login.microsoftonline.com/error?code=7000215"} Endpoint https://login.microsoftonline.com/someid/oauth2/token?api-version=1.0


@chewong @aramase does AAD pod identity / NMI not backoff if the controller fails?

**Comment by CecileRobertMichon** [comment]
From a CAPZ perspective I took a quick look, https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d1c2f870bd81b7a0b904faf0608d0a93910e8726/azure/scope/identity.go#L284 is missing the [service principal with certificate type](https://azure.github.io/aad-pod-identity/docs/concepts/azureidentity/) so that's a bug, looks like https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/778 was never fully implemented...

/assign

**Comment by chewong** [comment]
I don't think so. It's up to Azure SDK to perform the backoff if it fails.

**Comment by aramase** [comment]
> @chewong if you use controller runtime it should implement back-off for you and slow down requeues when many successive errors are returned from Reconcile() https://github.com/kubernetes-sigs/controller-runtime/blob/8c39906c77cdb574482c01fcd74a76b105b06522/pkg/controller/controller.go#L90

@CecileRobertMichon NMI is just a plain http server, that process incoming token requests. It uses adal to get a service principal/managed identity token. The token request is all during runtime of the workload, so we don't have a scenario where we need to reconcile to ensure desired state = actual state. This means no controller-runtime or `Reconcile()` loops in NMI.

The backoff @chewong is referring to is during `spt.Refresh()` in adal. There are retries in SDK for token request errors and it does in exponential backoff in some scenarios based on the response code.

**Comment by CecileRobertMichon** [comment]
@aramase is the scenario described above (response code 401) one of the ones where it should do exponential backoff? @kfox1111 is observing that it's not slowing down.
