### ISSUE TITLE
Fetch scripts for observability Helm charts don't work on Linux

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#2255]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:** Running the scripts for fetching observability Helm charts results in a failure on Linux. For example, this script fails due to tar.

```
$ ./fetch-otel-resources.sh
tar: /^opentelemetry-collector/chart: Not found in archive
tar: -: Not found in archive
tar: Exiting with failure status due to previous errors
```

**Anything else you would like to add:** The issue is that the `tar` command in the scripts is the BSD version of tar while Linux uses GNU's version. If we want to keep the script the same, we could include a copy of BSD tar in `hack/tools/bin`.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Jont828** [comment]
@CecileRobertMichon I could probably look into this. It looks like on both Linux and Mac I have the `bsdtar` command that works the way our script expects. What do you think about changing references to `tar` to `bsdtar`?

**Comment by CecileRobertMichon** [comment]
Another option would be to add it to hack/tools so we don't make any assumptions about the local dev env. @mboersma wdyt?

**Comment by mboersma** [comment]
This `tar` command does use `-s` BSD magic, but not in a sophisticated way. AFAICT we are just renaming the destination (and ignoring "test" and "examples" directories, IIRC):

```shell
tar xvz -C "$OTEL_ROOT" -s /^opentelemetry-collector/chart/ -
```

Maybe the script could be rewritten not to use any esoteric `tar` arguments so it would work with both BSD and GNU. 🌈
