### ISSUE TITLE
conformance_test.go exit code to 0 event the non last test suite has failures

### ISSUE THREAD

**Issue by bingbing8** [kubernetes-sigs/cluster-api-provider-azure#2265]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
./conformance_test.go

**What did you expect to happen:**
Normally there are 2 test suites (junit.e2e_suite.1.xml is the last) run. If the first one has failure but the second test suite (junit.e2e_suite.1.xml) passed. The exit code of conformance_test.go is 0. I expect the script exit with error to indicate there are failures in any of the test suites.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.2
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): ws2022

**Comment by jackfrancis** [comment]
@bingbing8 I'd like to ensure we address this. In your original report you mention 2 test suites, do you mean the one from upstream kubernetes and the one from capz?

**Comment by CecileRobertMichon** [comment]
@jackfrancis (when you're back in the new year): here is an example of this in practice: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2941/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1603522577655926784

The github status reports success, even though the conformance suite had 1 failed spec.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/8650424/208962824-9767cfe8-a533-4455-88f8-86805b2d773d.png">

**Comment by jackfrancis** [comment]
After an initial investigation, it appears that the cluster-api is itself wrapping kubetest inside a container execution lifecycle. And the above test output suggests that the underlying container, though its runtime reported 1 error, did not return a non-zero exit code.

Specifically, I'm not seeing evidence that this conditional path was reached:

https://github.com/kubernetes-sigs/cluster-api/blob/v1.3.2/test/infrastructure/container/docker.go#L500-L502

If that had been reached, then the capz test runner would get this back:

https://github.com/kubernetes-sigs/cluster-api/blob/v1.3.2/test/framework/kubetest/run.go#L194-L196

Which would trigger this:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/v1.7.1/test/e2e/conformance_test.go#L238

One thing that is interesting is that cluster-api is wrapping the error response back from the `RunContainer` invocation in its kubetest package with this message: ""Unable to run conformance tests". Does that suggest that whomever implemented this understood that running a kubetest E2E flow in this way would always return zero after execution, regardless of the error response from the actual kubetest runtime? Are we meant to be introspecting for terminal kubetest execution state in some other way?

cc @sbueringer @fabriziopandini in case you have any context here

**Comment by sbueringer** [comment]
We have a similar issue: https://github.com/kubernetes-sigs/cluster-api/issues/5123#issuecomment-1370032836 (not sure if it's 100% the same)

Essentially we never look into the junit report generated by the conformance tests. So we also don't fail our e2e test if there were errors in the conformance tests.

**Comment by jackfrancis** [comment]
@sbueringer that sounds like a lower-level explanation that would produce these outcomes.

Let's keep this CAPZ issue open and move our practical energies towards fixing things to https://github.com/kubernetes-sigs/cluster-api/issues/5123

**Comment by jackfrancis** [comment]
So I ran a follow-up local test, and got an error during the conformance test:

```
    [FAILED] error while waiting for pod svcaccounts-2356/oidc-discovery-validator to be Succeeded or Failed: pod "oidc-discovery-validator" failed with status: {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-02-02 20:27:57 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-02-02 20:28:14 +0000 UTC Reason:PodFailed Message:} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-02-02 20:28:14 +0000 UTC Reason:PodFailed Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-02-02 20:27:57 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.1.0.5 PodIP:192.168.12.82 PodIPs:[{IP:192.168.12.82}] StartTime:2023-02-02 20:27:57 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:oidc-discovery-validator State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2023-02-02 20:28:01 +0000 UTC,FinishedAt:2023-02-02 20:28:12 +0000 UTC,ContainerID:containerd://ffadf26019d4692c5095d9f6399d9676437db1c29622d144365b902d91173bd9,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:registry.k8s.io/e2e-test-images/agnhost:2.43 ImageID:registry.k8s.io/e2e-test-images/agnhost@sha256:16bbf38c463a4223d8cfe4da12bc61010b082a79b4bb003e2d3ba3ece5dd5f9e ContainerID:containerd://ffadf26019d4692c5095d9f6399d9676437db1c29622d144365b902d91173bd9 Started:0xc003584c1d}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
    In [It] at: test/e2e/auth/service_accounts.go:637 @ 02/02/23 20:28:48.077
```

That was eventually bubbled up thusly:

```
  Summarizing 1 Failure:
    [FAIL] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
    test/e2e/auth/service_accounts.go:637
  
  Ran 338 of 7084 Specs in 2168.955 seconds
  FAIL! -- 337 Passed | 1 Failed | 0 Pending | 6746 Skipped
```

And then:

```
  [FAILED] in [It] - /Users/jackfrancis/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:238 @ 02/02/23 13:02:03.43
• [FAILED] [4064.682 seconds]
Conformance Tests [It] conformance-tests
/Users/jackfrancis/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:98

  [FAILED] Unexpected error:
      <*errors.withStack | 0xc0009e64c8>: {
          error: <*errors.withMessage | 0xc001908840>{
              cause: <*errors.errorString | 0xc000680710>{
                  s: "error container run failed with exit code 1",
              },
              msg: "Unable to run conformance tests",
          },
          stack: [0x5f43e59, 0x61f2927, 0x44e34fb, 0x44f79f8, 0x4077281],
      }
      Unable to run conformance tests: error container run failed with exit code 1
  occurred
  In [It] at: /Users/jackfrancis/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:238 @ 02/02/23 13:02:03.43

  Full Stack Trace
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.glob..func3.2()
    	/Users/jackfrancis/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:238 +0x18fa
```

My CLI session confirmed:

```
$ echo $?
2
```

Also worth noting that my comment above about "the kubetest container will always return zero" is definitely not correct:

`Unable to run conformance tests: error container run failed with exit code 1`

It's arguable that "Unable to run conformance tests" is not the correct wrapping text, but regardless the underlying error that it wraps ("error container run failed with exit code 1") suggests that capi's kubetest abstractions _are_ honoring the underlying kubetest runtime exit code.

So... I'm kind of confused.

**Comment by CecileRobertMichon** [comment]
Did you check if the failures show in junits reports? Eventually that's what gets bubbled up to Testgrid as the "green" pass

**Comment by jackfrancis** [comment]
[junit.zip](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/10574427/junit.zip)

cc @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
So it looks like one has SuiteSucceeded `true` while the other has `false`? seems like that may be the issue

**Comment by jackfrancis** [comment]
In which case this would be a testgrid bug? (Or maybe we need to explicitly always only publish one junit file, or maybe we're misnaming the junit file?)

**Comment by sbueringer** [comment]
> Did you check if the failures show in junits reports? Eventually that's what gets bubbled up to Testgrid as the "green" pass

I think this is not correct. While testgrid shows the junit results the junit results don't control if Spyglass shows the test as succeeded.

**Comment by sbueringer** [comment]
I wonder if you hit something else in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2265#issuecomment-1414533434.

This job reports something else: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2941/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1603522577655926784

You see the error logs from the conformance test and then our test returns PASS. And that happens as I described above because our test framework does not read the junit reports to decide if a test is failed or not.

**Comment by jackfrancis** [comment]
@sbueringer so you're suggesting that the exit code result is < 100% reliable in terms of terminal outcome, and we need to fall back to introspecting junit whenever we get an exit 0 because the actual non-successful terminal outcome may only exist in junit output?

**Comment by sbueringer** [comment]
I didn't get a non-zero exit code when I reproduced it as I described it on the other issue.

I don't know/ remember if we are even getting the exit code from the conformance tests

**Comment by jackfrancis** [comment]
[This](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2265#issuecomment-1414533434) suggests that we (capi e2e) are getting the exit code from the conformance test.

**Comment by sbueringer** [comment]
But that's not what we see in prow, right?

**Comment by jackfrancis** [comment]
In @CecileRobertMichon's linked repro prow *did* get a zero exit code:

```
+ EXIT_VALUE=0
```

@sbueringer This is why I wonder if your comment suggests the edge case we're after is actually:

1. conformance test run (kubetest runtime) returned exit code 0
2. a test failure was observed during the run and recorded in junit output

Because we're only looking at the exit code from the kubetest runtime we report success.

**Comment by sbueringer** [comment]
Yup, that's what I was trying to say.

I think in your case [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2265#issuecomment-1414533434) the e2e test would actually fail.

**Comment by jackfrancis** [comment]
@sbueringer agreed

In which case, I think we may be misconfiguring kubetest? The configuration surface area is so vast, perhaps the errors observed in these scenarios are configured to be "swallowed" and only returned as historical details (in the junit output). Maybe we need to look more into how we configure these tests and ensure that for tests that we require to pass, we are bubbling them up to the exit code signal.

**Comment by sbueringer** [comment]
Might be. I'm not 100% sure we actually retrieve the exit code of ginkgo correctly today.

Up until a few weeks ago we where running the container even with restart. So it was restarting after the test was done..
Hm maybe that plays into what you're seeing. Could it be that the ContainerInspect is looking into the newly restarted container instead of the "run" which just failed?

xref: fix in CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/7946

**Comment by jackfrancis** [comment]
Interesting, have you observed a repro since that change?

CAPZ update to v1.3.3 in-progress: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3136

**Comment by sbueringer** [comment]
I didn't observe one. But neither a case where a conformance test case failed and then the job failed (looks like the conformance tests were always green the last few days)

**Comment by CecileRobertMichon** [comment]
@jackfrancis is this issue still active?

**Comment by jackfrancis** [comment]
@CecileRobertMichon I'm not aware of any active investigation into this.

I audited this page's history of successful results and didn't encounter any that exhibited the documented symptoms here. Perhaps we should close this issue and re-open if we observe this repro in the future?

**Comment by CecileRobertMichon** [comment]
I was able to find one where a conformance test case failed and the job actually failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/capz-conformance-master/1650489167919976448

So looks like this is now fixed

/close
