### ISSUE TITLE
Improve output from failing bootstrap extension command

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-azure#2272]
/kind feature

**Describe the solution you'd like**

As mentioned in #2271, right now bootstrap extension command defined as https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/290195e7a391033b578a4e10567cec09d34b3c4c/azure/defaults.go#L106 does not produce any usable output to the user except the error about unexpected exit code. For user not familiar with CAPI, it might be difficult to debug and there is definitely an opportunity to improve this error message.

The error could print something like `Timed out waiting for file /run/cluster-api/bootstrap-success.complete to appear`, or perhaps also include the time spent waiting for it.

**Comment by CecileRobertMichon** [comment]
AFAIK extensions can't return an error message, only an exit code. The way we surface errors to the user is via conditions and controller logs [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/vmextensions/vmextensions.go#L88). We could print an error log in the extension log itself but this would only be visible if the user logs into the VM and looks for the extension log which most users new to CAPI/Azure might not know how to find.

**Comment by invidian** [comment]
As mentioned in #2271, here is what output looks like when node provisioning fails:
`I0502 10:52:11.195577       1 recorder.go:103] events "msg"="Warning"  "message"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service vmextensions: extension state failed. This likely means the Kubernetes node bootstrapping process failed or timed out. Check VM boot diagnostics logs to learn more: failed checking if the operation was complete: failed checking if the operation was complete: Code=\"VMExtensionProvisioningError\" Message=\"VM has reported a failure when processing extension 'CAPZ.Linux.Bootstrapping'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n\\n[stderr]\\n/bin/sh: line 1: return: can only return' from a function or sourced script\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot \"" "object"={"kind":"AzureMachine","namespace":"capz-e2e-t54iso","name":"capz-e2e-t54iso-flatcar-control-plane-fz2k4","uid":"5e3fa822-2326-42b8-a011-7638d4f64e19","apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","resourceVersion":"5173"} "reason"="ReconcileError"`

Almost this entire message can be seen when you do `kubectl describe azuremachine`. Here you see that both stdout and stderr are printed, meaning we only need to print something from the executed command to make it appear much closer to the user, this is what I had in mind.

**Comment by CecileRobertMichon** [comment]
I stand corrected, I didn't realize the extension output included stdout and stderr. 

+1 on printing the error in the output
