### ISSUE TITLE
Enforce consistent import names across the module

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-azure#2289]
/kind feature

**Describe the solution you'd like**

Right now, packages are often imported using different name between the packages, which makes it more difficult to navigate and refactor the code base. Example:
```console
$ git grep sigs.k8s.io/cluster-api-provider-azure/api/v1beta1 | cut -d: -f2 | grep sigs | sort | uniq -c | sort -h
      1         apiv1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
      2         clusterapiproviderazureapiv1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
      2         infrav1alpha4 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
      8         infrav1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
      8         "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
     28         v1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
    142         infrav1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
```

Package `sigs.k8s.io/cluster-api-provider-azure/api/v1beta1` is imported 7 different ways, including craziness like `infrav1alpha4 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"`

To promote better consistency and predictability, I suggest using `importas` linter https://github.com/golangci/golangci-lint/blob/7c1d8b75bd4aed28783a7b6a4dd852b7be9dc3d5/.golangci.example.yml#L903-L922, which allows enforcing style of imports.

**Environment:**

- cluster-api-provider-azure version: c5b5f632

**Comment by mboersma** [comment]
We are already using `importas` to enforce the same import aliases that CAPI does, but I think we should feel free to expand the [list of aliases](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.golangci.yml#L58-L74) for better local consistency.
