### ISSUE TITLE
Windows Flavor link is broken

### ISSUE THREAD

**Issue by himanshuz2** [kubernetes-sigs/cluster-api-provider-azure#2291]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Click on the Chapter 1.25 windows support - CAPZ book and the link to Windows ContainerD flavor template
Link is broken

**https://capz.sigs.k8s.io/templates/cluster-template-machinepool-windows-containerd.yaml**

**What did you expect to happen:**
Flavor template to deploy a cluster with windows node 

**Anything else you would like to add:**
It will be helpful to provide a working example of template and command to deploy Hybrid Cluster to Azure with Control Plane, Linux Node Pool  (VMSS) and Windows Nod Pool (VMSS). 

**Environment:**
Ubuntu, Azure 

- cluster-api-provider-azure version: Cluster API v1beta1 (v1.0.x)
- Kubernetes version: (use `kubectl version`): 1.23.6
- OS (e.g. from `/etc/os-release`):  Ubuntu VERSION="22.04 LTS (Jammy Jellyfish)"

**Comment by CecileRobertMichon** [comment]
Thanks for reporting @himanshuz2

Link should be https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/cluster-template-windows-containerd.yaml

/good-first-issue
