### ISSUE TITLE
Can't connect to capz cluster using kubeconfig

### ISSUE THREAD

**Issue by cnadolny** [kubernetes-sigs/cluster-api-provider-azure#2293]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Hi - I’m looking for some help with capz.
I’m running it on a Kubernetes cluster. I’m able to create a capz cluster with no errors.

This is what I’ve ran:
```
az aks create -g ${AZURE_RESOURCE_GROUP} -n ${AKS_CLUSTER_NAME} -k ${K8S_VERSION} --network-plugin azure

kubectl create secret generic "${AZURE_CLUSTER_IDENTITY_SECRET_NAME}" --from-literal=clientSecret="${AZURE_CLIENT_SECRET}" --kubeconfig="$(pwd)/${AKS_CLUSTER_NAME}.kubeconfig"

export EXP_MACHINE_POOL=true
export EXP_AKS=true

clusterctl init --infrastructure azure
clusterctl generate cluster ${WORKER_CLUSTER_NAME} --kubernetes-version v1.23.3 --control-plane-machine-count=3 --worker-machine-count=3 > worker-cluster.yaml

kubectl apply -f worker-cluster.yaml
```

No errors in logs, everything is ready - as in the cluster is in Provisioned state and kubeadmcontrolplane is initialized and the api server available. 

I then grab the kubeconfig like so:
`clusterctl get kubeconfig ${WORKER_CLUSTER_NAME} > ${WORKER_CLUSTER_NAME}.kubeconfig`

But when I try to connect to the cluster with kubectl, it hangs:
`Claudias-MBP:e2e cnadolny$ k get svc --kubeconfig=${WORKER_CLUSTER_NAME}.kubeconfig`

Any suggestions?

**What did you expect to happen:**

Should be able to connect to cluster

**Environment:**

- cluster-api-provider-azure version: 1.0.5
- Kubernetes version: (use `kubectl version`): 1.20.4
- OS (e.g. from `/etc/os-release`): Mac

**Comment by cnadolny** [comment]
All pods and resources seem to be looking good/running:

Claudias-MBP:e2e cnadolny$ k get po -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-5665b4f958-fr5l8       1/1     Running   0          80m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-86c4dcbc4c-88wmt   1/1     Running   0          80m
capi-system                         capi-controller-manager-7ffdd578bc-22t5m                         1/1     Running   0          80m
capz-system                         capz-controller-manager-749c6d588-w44fw                          1/1     Running   0          80m
capz-system                         capz-nmi-485dj                                                   1/1     Running   0          80m
capz-system                         capz-nmi-hjkzs                                                   1/1     Running   0          80m
capz-system                         capz-nmi-rwjvz                                                   1/1     Running   0          80m
cert-manager                        cert-manager-848f547974-frczq                                    1/1     Running   0          81m
cert-manager                        cert-manager-cainjector-54f4cc6b5-drgtq                          1/1     Running   0          81m
cert-manager                        cert-manager-webhook-7c9588c76-khq6j                             1/1     Running   0          81m
kube-system                         azure-ip-masq-agent-77hts                                        1/1     Running   0          83m
kube-system                         azure-ip-masq-agent-sf4h8                                        1/1     Running   0          84m
kube-system                         azure-ip-masq-agent-t4ft9                                        1/1     Running   0          83m
kube-system                         coredns-6dcbc8c69b-jqr25                                         1/1     Running   0          86m
kube-system                         coredns-6dcbc8c69b-wsxcg                                         1/1     Running   0          83m
kube-system                         coredns-autoscaler-8bdbf6ddd-nx6dg                               1/1     Running   0          85m
kube-system                         csi-azuredisk-node-f75n6                                         3/3     Running   0          84m
kube-system                         csi-azuredisk-node-nvxf8                                         3/3     Running   0          83m
kube-system                         csi-azuredisk-node-zsn9p                                         3/3     Running   0          83m
kube-system                         csi-azurefile-node-9bjst                                         3/3     Running   0          83m
kube-system                         csi-azurefile-node-9jpt9                                         3/3     Running   0          83m
kube-system                         csi-azurefile-node-hfgbz                                         3/3     Running   0          84m
kube-system                         konnectivity-agent-5c8c6b4496-8mxs6                              1/1     Running   0          78m
kube-system                         konnectivity-agent-5c8c6b4496-vz4d4                              1/1     Running   0          78m
kube-system                         kube-proxy-cdspc                                                 1/1     Running   0          84m
kube-system                         kube-proxy-fnvdz                                                 1/1     Running   0          83m
kube-system                         kube-proxy-vf9lz                                                 1/1     Running   0          83m
kube-system                         metrics-server-5f6d77c848-ccrs5                                  1/1     Running   0          86m

Claudias-MBP:e2e cnadolny$ k get cluster-api
NAME                                                                                 AGE
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0   82m

NAME                                                                                        CLUSTER                        AGE
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-97mgp   remediator-e2e-worker-b0e421   78m
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-9jpfl   remediator-e2e-worker-b0e421   80m
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-rvp4l   remediator-e2e-worker-b0e421   76m
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-gsxnj            remediator-e2e-worker-b0e421   82m
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-jcqp8            remediator-e2e-worker-b0e421   82m
kubeadmconfig.bootstrap.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-s6dj5            remediator-e2e-worker-b0e421   82m

NAME                                                                   CLUSTER                        REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE   VERSION
machinedeployment.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0   remediator-e2e-worker-b0e421   3          1       3         2             ScalingUp   82m   v1.23.3

NAME                                                                          CLUSTER                        NODENAME                                           PROVIDERID                                                                                                                                                                                           PHASE     AGE   VERSION
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-9k95w     remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-control-plane-dnspz   azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-control-plane-dnspz   Running   76m   v1.23.3
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-c972n     remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-control-plane-x52rg   azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-control-plane-x52rg   Running   80m   v1.23.3
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-vp7hd     remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-control-plane-8qlbw   azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-control-plane-8qlbw   Running   78m   v1.23.3
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-5768684dbd-czgsq   remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-md-0-6l2mn            azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-md-0-6l2mn            Running   82m   v1.23.3
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-5768684dbd-s57dx   remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-md-0-xmrph            azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-md-0-xmrph            Running   82m   v1.23.3
machine.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-5768684dbd-tq9qp   remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421-md-0-2xrzq            azure:///subscriptions/000/resourceGroups/remediator-e2e-rg-55217097/providers/Microsoft.Compute/virtualMachines/remediator-e2e-worker-b0e421-md-0-2xrzq            Running   82m   v1.23.3

NAME                                                    PHASE         AGE   VERSION
cluster.cluster.x-k8s.io/remediator-e2e-worker-b0e421   Provisioned   82m   

NAME                                                                       CLUSTER                        REPLICAS   READY   AVAILABLE   AGE   VERSION
machineset.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-5768684dbd   remediator-e2e-worker-b0e421   3          1       1           82m   v1.23.3

NAME                                                                                           CLUSTER                        INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE   VERSION
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane   remediator-e2e-worker-b0e421   true          true                   3          3       3         0             82m   v1.23.3

NAME                                                                    AGE
azureclusteridentity.infrastructure.cluster.x-k8s.io/cluster-identity   82m

NAME                                                                                            READY   REASON   STATE
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-8qlbw   True             Succeeded
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-dnspz   True             Succeeded
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane-x52rg   True             Succeeded
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-2xrzq            True             Succeeded
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-6l2mn            True             Succeeded
azuremachine.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0-xmrph            True             Succeeded

NAME                                                                        CLUSTER                        READY   REASON
azurecluster.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421   remediator-e2e-worker-b0e421   True    

NAME                                                                                              AGE
azuremachinetemplate.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-control-plane   82m
azuremachinetemplate.infrastructure.cluster.x-k8s.io/remediator-e2e-worker-b0e421-md-0            82m

**Comment by CecileRobertMichon** [comment]
Hi @cnadolny 👋 

Not sure what's wrong here... If the control plane is ready and initialized that means the apiserver should be reachable. Is it possible it has anything to do with your local environment? are you able to reach the public apiserver LB?

**Comment by alexeldeib** [comment]
debugged this offline a bit -- seems we got a network manager policy which blocks internet traffic to 443 on public ips. 

poking at some workarounds :)
