### ISSUE TITLE
Document the new release cadence and support policy

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2295]
1. What release cadence should we adopt going forward? CAPI is [discussing formalizing a release cadence](https://github.com/kubernetes-sigs/cluster-api/issues/6442). Current proposal from discussion is to not follow CAPI release cadence but to define our own CAPZ release cadence for minor (feature) releases of either 1 minor release every month or every 2 months
2. How many minor release branches should we “support”  at any given time? For example, if we release features every 2 months, we could keep backporting bug fixes to the last 2 releases at any given time, meaning each minor release would be “in support” for ~4 months.

For release 1.3, we decided to try out using a 2 months release cadence, where the milestone due date is used to indicate the next release date.

We are also going to support (backport fixes to) the last two minor releases. For example, v1.2 and v1.3. As soon as v1.4 comes out, v1.2 becomes EOL and we maintain release branches for v1.3 and v1.4.

This issue tracks documenting that process after the initial trial and error period, if we decide to stick to it. Feedback welcome.

**Comment by CecileRobertMichon** [comment]
We should also document what our criteria for backports is, including bug fixes and security patches, as well as evolving tests. We might want to consider limiting test evolution to the last release since that's what we're doing in practice currently. @jackfrancis @mboersma thoughts?

**Comment by jackfrancis** [comment]
I agree.

1. We should probably as a rule "require" test changes/fixes/evolutions to be cherry-picked into the last release branch, so that we minimize friction for any critical test fix
2. Officially document "test maintenance" as an allowable changeset for a cherry-pick (in addition to bug fixes and security patches)

**Comment by CecileRobertMichon** [comment]
How about this: cherry-pick user-facing bug fixes to the latest two minor release branches, and the test improvements that have no user-facing changes to the latest release branch only (except for broken tests that need to be fixed on all release branches that are still active).
