### ISSUE TITLE
Switch to gen2 reference images

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#2296]
/kind feature

**Describe the solution you'd like**

The CAPZ reference images use Azure [generation 2 VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2) by default.
- When I follow the quick start, I end up with a cluster running on gen2 VMs. 
- Reference images for future Kubernetes releases are only published in gen2 versions.

**Describe alternatives you've considered**

We could leave gen1 as the default.
We could publish both gen1 and gen2 reference images.

**Additional context**

See also #1003 and https://github.com/kubernetes-sigs/image-builder/pull/878#discussion_r866291520

**Comment by ffais** [comment]
Hi @mboersma, gen2 reference images are still missing. Do you know why?

**Comment by mboersma** [comment]
Hi @ffais! I guess we never really committed to switching to `-gen2` images by default, and this work item fell by the wayside.

The reference images are primarily for tests, and we try to keep the matrix of (k8s version * OS distro) small to keep costs down. There hasn't been a business justification that drove us to complete this switch.

Our strong recommendation if you're using CAPZ is to build and host your own images, because we may not publish every variation you need, and because we don't patch them with security fixes or other updates.

Also note that CAPZ switched from defaulting to Azure Marketplace to a community gallery in the `main` branch.
- Updated docs: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/self-managed/custom-images.md
- #5167

**Comment by ffais** [comment]
Thanks for the clarification, everything is clearer now.
