### ISSUE TITLE
Review e2e logic for selecting templates on Windows after dockershim templates are removed

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#2315]
Prior to this we needed different templates for windows and so we tacked windows to the end: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/30bfbb55d43f10343c634a3f90396ff206444021/test/e2e/conformance_test.go#L125-L127

After this merged we might not need this logic anymore as we can re-use the same templates.  I will create an issue to follow up on this after this merges

_Originally posted by @jsturtevant in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2292#discussion_r877394683_

**Comment by jsturtevant** [comment]
should also review naming: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2292#discussion_r877360744

**Comment by CecileRobertMichon** [comment]
can also remove image selection logic for dockershim: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2302/files#r884006531
