### ISSUE TITLE
Migrate to Cluster API master / v1alpha2

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-azure#232]
/kind feature

Describe the solution you'd like
In an effort to move this provider to v1alpha2 CAPI types, we should update the dependency to Cluster API latest master release after the switch to Go Modules.

**Comment by justaugustus** [comment]
Hi @ericzhang08 -- this work is already planned between @vincepri and myself.
/unassign @ericzhang08 
/assign @justaugustus @vincepri

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/281.
/close
