### ISSUE TITLE
Support configurable Network Interfaces

### ISSUE THREAD

**Issue by dthorsen** [kubernetes-sigs/cluster-api-provider-azure#2327]
/kind feature

**Describe the solution you'd like**
* Ability to configure the number of Network Interfaces to created and attached to a new VM upon AzureMachine creation / AzureMachinePool scale up
* Ability to configure multiple IPConfigurations on a Network Interface of an AzureMachine / AzureMachinePool
* Ability to attach a pre-existing Network Interface to a new AzureMachine

**Anything else you would like to add:**
These features are useful for implementing more complex network topologies such as is needed to support use of the Azure CNI, separate pod subnets, and VM's with static IP's that must re-attach to a replacement VM.

Related to: #467 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dthorsen** [comment]
@brianlieberman 

/assign

**Comment by CecileRobertMichon** [comment]
@dthorsen @brianlieberman are you currently working on this? @jikuma and @bridgetkromhout are interested in this feature as well for Azure CNI

**Comment by CecileRobertMichon** [comment]
@brianlieberman @dthorsen I see a PR in a fork :) Are you planning on opening it in the upstream CAPZ repo?

**Comment by dthorsen** [comment]
@CecileRobertMichon We are indeed. That fork is just where we are doing the initial pass at development. I think we are to a point that it just needs an update to the validatingwebhook logic and then we should be ready to PR upstream.

**Comment by jackfrancis** [comment]
@dthorsen @brianlieberman I've gone ahead and moved this out of the 1.5 milestone as we plan to ship v1.5.0 next week. We look forward to this landing in the v1.6 release cycle!
