### ISSUE TITLE
Support autoscaling on self-managed MachinePool using MachinePool Machines

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2328]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Now autoscaling is supported only for managed clusters (aks). And regular clusters should be supported as well.
Issue for managed one: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1669

I am add autoscaling CI for cloud-provider-azure with CAPZ.
The original job defined with aks-engine: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L422-L483
The current cluster template: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-autoscaler.json

Config is:
```
"pools": [
    {
        "name": "agentpool1",
        "config": {
            "min-nodes": "1",
            "max-nodes": "1000"
        }
    }
],
"config": {
    "scale-down-delay-after-add": "5m",
    "scale-down-unneeded-time": "5m"
}
```

related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/919

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle rotten
/lifecycle active
/assign @Jont828 
/reopen

cc @dtzar

**Comment by Jont828** [comment]
/retitle Support autoscaling on self-managed MachinePool using MachinePool Machines

**Comment by Jont828** [comment]
This should be done since #3998 is merged, closing this issue out.
