### ISSUE TITLE
Possibly incorrect WORKER_MACHINE_COUNT for multiple vmss/vmas templates

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2336]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am using `ci-entrypoint.sh` with
1) an external multiple (2) vmss template for CI
2) using `WORKER_MACHINE_COUNT` for each MachinePool in the template
3) not setting `WORKER_MACHINE_COUNT` explicitly.

Then, the script will say: `Waiting for 3 control plane machine(s), 2 worker machine(s), and  windows machine(s) to become Ready`. However the fact is that there're 4 worker nodes in total. It leads to unnecessary waiting for node ready.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-entrypoint.sh#L121-L130

I come up with 2 solutions:
1. Users should not use `WORKER_MACHINE_COUNT` in the template but expected number. And set `WORKER_MACHINE_COUNT` to be total node number
2. Add an environment variable `TOTAL_WORKER_NODE` and the waiting logic in `ci-entrypoint.sh` use this variable

If CAPZ is going to provide multiple vmss template in the repo, I think such issue should be considered as well. So I'd like to keep my templates consistent with the possible plan.

**What did you expect to happen:**
Show actual worker nodes in output and wait for actual nodes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
@CecileRobertMichon @jackfrancis could you please share your ideas on this. Thank you.

**Comment by CecileRobertMichon** [comment]
`WorkerMachineCount` is actually coming directly from the Cluster API test framework: https://github.com/kubernetes-sigs/cluster-api/blob/e03faf0282d7a16199004e763228dc2b3b5600ef/test/framework/clusterctl/client.go#L181

we might need to discuss this in the CAPI repo if it needs any modifications to the framework. Alternatively, we could do 1) and use `WorkerMachineCount` as the total, but then we need another mechanism for controlling replicas in test templates.

**Comment by lzhecheng** [comment]
Yes, I agree 1) is a better one.
