### ISSUE TITLE
API server gets stuck in pending during deployment when used in pre-submit

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#2338]
/kind bug
/kind failing-test

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Control plane pods get stuck: https://github.com/kubernetes/kubernetes/pull/110235#issuecomment-1139912269

```
kube-apiserver-capz-conf-6bprnv-control-plane-frsww          capz-conf-6bprnv-control-plane-frsww Pending       []
kube-controller-manager-capz-conf-6bprnv-control-plane-frsww capz-conf-6bprnv-control-plane-frsww Pending       []
kube-scheduler-capz-conf-6bprnv-control-plane-frsww          capz-conf-6bprnv-control-plane-frsww Pending 
```

**What did you expect to happen:**
node to come online

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Rest of the nodes work, re-retriggering works.  This seems to only happen with the pre-submit job, haven't seen it in the CI jobs.
 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
is there a link to a repro where this happened? Anything interesting happening in logs?

**Comment by jsturtevant** [comment]
Nothing interesting in the logs that I could find.  I am working if it is related to tainting the nodes and the image being pulled/scheduled afterwards due to it being built as part of PR process.  Some type of timing issues with nodes coming ready and images starting up.

It happened twice on https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=110235 

logs:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110235/pull-kubernetes-e2e-capz-windows-containerd/1530227297892700160

**Comment by jackfrancis** [comment]
Are the Pending pods scheduled onto Windows nodes (where they aren't able to run)?

**Comment by jsturtevant** [comment]
No, they are scheduled the control-plane node:

```
ENDLOG for container kube-system:kube-scheduler-capz-conf-br5412-control-plane-ppxn2:kube-scheduler
Jun  8 01:07:45.480: FAIL: Error waiting for all pods to be running and ready: 3 / 18 pods in namespace kube-system are NOT in RUNNING and READY state in 10m0s
POD                                                          NODE                                 PHASE   GRACE CONDITIONS
kube-apiserver-capz-conf-br5412-control-plane-ppxn2          capz-conf-br5412-control-plane-ppxn2 Pending       []
kube-controller-manager-capz-conf-br5412-control-plane-ppxn2 capz-conf-br5412-control-plane-ppxn2 Pending       []
kube-scheduler-capz-conf-br5412-control-plane-ppxn2          capz-conf-br5412-control-plane-ppxn2 Pending       []
```

**Comment by marosset** [comment]
/remove-lifecycle stale

I ran into this again (on a few attempts) against https://github.com/kubernetes/kubernetes/pull/111332

**Comment by marosset** [comment]
/remove-lifecycle stale

Still an issue AFAIK

**Comment by mboersma** [comment]
/priority awaiting-more-evidence

@marosset is this still a current problem?
