### ISSUE TITLE
`ci-entrypoint.sh` creates Windows clusters without calico installed on Windows Nodes

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2341]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I created a Windows cluster but found that network is not ready on Windows Nodes. Calico Pods are running on Linux Nodes but not on Windows ones. There's only a calico Linux DaemonSet.
* KUBERNETES_VERSION: latest
* TEST_WINDOWS: true
* TEST_CCM: true

**What did you expect to happen:**
Created a Windows cluster with Windows Nodes ready, CNI installed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
```
zhechengli@devbox:~/github.com/lzhecheng/cluster-api-provider-azure$ kg ds -A
NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
kube-system   calico-node                  3         3         3       3            3           kubernetes.io/os=linux     11m
kube-system   cloud-node-manager           3         3         3       3            3           kubernetes.io/os=linux     11m
kube-system   cloud-node-manager-windows   2         2         0       2            0           kubernetes.io/os=windows   11m
kube-system   containerd-logger            2         2         2       2            2           kubernetes.io/os=windows   11m
kube-system   csi-proxy                    0         0         0       0            0           kubernetes.io/os=windows   11m
kube-system   kube-proxy                   3         3         3       3            3           kubernetes.io/os=linux     11m
```

```
zhechengli@devbox:~/github.com/lzhecheng/cluster-api-provider-azure$ kgpa
NAMESPACE     NAME                                                            READY   STATUS              RESTARTS   AGE     IP             NODE                                    NOMINATED NODE   READINESS GATES
kube-system   calico-kube-controllers-57cb778775-w56pb                        1/1     Running             0          11m     192.168.46.4   zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   calico-node-66j2k                                               1/1     Running             0          10m     10.1.0.6       zhechengli-0530-2-md-0-bvfc4            <none>           <none>
kube-system   calico-node-fjzzl                                               1/1     Running             0          10m     10.1.0.4       zhechengli-0530-2-md-0-prxk4            <none>           <none>
kube-system   calico-node-v85lg                                               1/1     Running             0          11m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   cloud-controller-manager-6c7dfbcb66-qsg4w                       1/1     Running             0          11m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   cloud-node-manager-9nzwx                                        1/1     Running             0          10m     10.1.0.4       zhechengli-0530-2-md-0-prxk4            <none>           <none>
kube-system   cloud-node-manager-s82bz                                        1/1     Running             0          10m     10.1.0.6       zhechengli-0530-2-md-0-bvfc4            <none>           <none>
kube-system   cloud-node-manager-windows-kn5q6                                0/1     ContainerCreating   0          9m45s   <none>         zhechengl-7l8rv                         <none>           <none>
kube-system   cloud-node-manager-windows-pclxw                                0/1     ContainerCreating   0          9m37s   <none>         zhechengl-477np                         <none>           <none>
kube-system   cloud-node-manager-wjqdz                                        1/1     Running             0          11m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   containerd-logger-59x2w                                         1/1     Running             0          9m45s   10.1.0.5       zhechengl-7l8rv                         <none>           <none>
kube-system   containerd-logger-c9h4w                                         1/1     Running             0          9m37s   10.1.0.7       zhechengl-477np                         <none>           <none>
kube-system   coredns-d5c9cd585-84f5h                                         1/1     Running             0          12m     192.168.46.3   zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   coredns-d5c9cd585-8rjnn                                         1/1     Running             0          12m     192.168.46.1   zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   etcd-zhechengli-0530-2-control-plane-wpr65                      1/1     Running             0          12m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   kube-apiserver-zhechengli-0530-2-control-plane-wpr65            1/1     Running             0          12m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   kube-controller-manager-zhechengli-0530-2-control-plane-wpr65   1/1     Running             0          12m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   kube-proxy-c2n65                                                1/1     Running             0          10m     10.1.0.4       zhechengli-0530-2-md-0-prxk4            <none>           <none>
kube-system   kube-proxy-pg2nr                                                1/1     Running             0          12m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   kube-proxy-zrtp7                                                1/1     Running             0          10m     10.1.0.6       zhechengli-0530-2-md-0-bvfc4            <none>           <none>
kube-system   kube-scheduler-zhechengli-0530-2-control-plane-wpr65            1/1     Running             0          12m     10.0.0.4       zhechengli-0530-2-control-plane-wpr65   <none>           <none>
kube-system   metrics-server-74557696d7-t2slp                                 1/1     Running             0          11m     192.168.46.2   zhechengli-0530-2-control-plane-wpr65   <none>           <none>
```

```
zhechengli@devbox:~/github.com/lzhecheng/cluster-api-provider-azure$ kgno -owide
NAME                                    STATUS     ROLES           AGE   VERSION                              INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
zhechengl-477np                         NotReady   <none>          12m   v1.25.0-alpha.0.717+92263ee0dd2588   10.1.0.7      <none>        Windows Server 2019 Datacenter   10.0.17763.2366    containerd://1.6.0-rc.1
zhechengl-7l8rv                         NotReady   <none>          12m   v1.25.0-alpha.0.717+92263ee0dd2588   10.1.0.5      <none>        Windows Server 2019 Datacenter   10.0.17763.2366    containerd://1.6.0-rc.1
zhechengli-0530-2-control-plane-wpr65   Ready      control-plane   14m   v1.25.0-alpha.0.717+92263ee0dd2588   10.0.0.4      <none>        Ubuntu 18.04.5 LTS               5.3.0-1034-azure   containerd://1.3.4
zhechengli-0530-2-md-0-bvfc4            Ready      <none>          12m   v1.25.0-alpha.0.717+92263ee0dd2588   10.1.0.6      <none>        Ubuntu 18.04.5 LTS               5.3.0-1034-azure   containerd://1.3.4
zhechengli-0530-2-md-0-prxk4            Ready      <none>          13m   v1.25.0-alpha.0.717+92263ee0dd2588   10.1.0.4      <none>        Ubuntu 18.04.5 LTS               5.3.0-1034-azure   containerd://1.3.4
```

```
zhechengli@devbox:~/github.com/lzhecheng/cluster-api-provider-azure$ kdno zhechengl-477np
Name:               zhechengl-477np
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2s_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=westus2
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=zhechengl-477np
                    kubernetes.io/os=windows
                    node.kubernetes.io/instance-type=Standard_D2s_v3
                    node.kubernetes.io/windows-build=10.0.17763
                    topology.kubernetes.io/region=westus2
                    topology.kubernetes.io/zone=0
Annotations:        cluster.x-k8s.io/cluster-name: zhechengli-0530-2
                    cluster.x-k8s.io/cluster-namespace: default
                    cluster.x-k8s.io/machine: zhechengli-0530-2-md-win-7b8765b5ff-whhtx
                    cluster.x-k8s.io/owner-kind: MachineSet
                    cluster.x-k8s.io/owner-name: zhechengli-0530-2-md-win-7b8765b5ff
                    kubeadm.alpha.kubernetes.io/cri-socket: npipe:////./pipe/containerd-containerd
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 30 May 2022 14:19:57 +0000
Taints:             node.kubernetes.io/not-ready:NoExecute
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Mon, 30 May 2022 14:21:36 +0000   Mon, 30 May 2022 14:21:36 +0000   RouteCreated                 RouteController created a route
  MemoryPressure       False   Mon, 30 May 2022 14:30:40 +0000   Mon, 30 May 2022 14:19:57 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Mon, 30 May 2022 14:30:40 +0000   Mon, 30 May 2022 14:19:57 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Mon, 30 May 2022 14:30:40 +0000   Mon, 30 May 2022 14:19:57 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                False   Mon, 30 May 2022 14:30:40 +0000   Mon, 30 May 2022 14:19:57 +0000   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
....
```
**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
@CecileRobertMichon

**Comment by himanshuz2** [comment]
I have the same issue.
root@CAPZ-Management:/home/bmadministrator/.kube# kubectl --kubeconfig=./my-cluster-1.kubeconfig describe node win-p-win000000
Name:               win-p-win000000
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2s_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=centralus
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=win-p-win000000
                    kubernetes.io/os=windows
                    node.kubernetes.io/instance-type=Standard_D2s_v3
                    node.kubernetes.io/windows-build=10.0.17763
                    topology.kubernetes.io/region=centralus
                    topology.kubernetes.io/zone=0
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: npipe:////./pipe/containerd-containerd
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 31 May 2022 11:40:18 -0400
Taints:             node.kubernetes.io/not-ready:NoExecute
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  win-p-win000000
  AcquireTime:     <unset>
  RenewTime:       Tue, 31 May 2022 12:00:23 -0400
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Tue, 31 May 2022 11:55:46 -0400   Tue, 31 May 2022 11:40:18 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Tue, 31 May 2022 11:55:46 -0400   Tue, 31 May 2022 11:40:18 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Tue, 31 May 2022 11:55:46 -0400   Tue, 31 May 2022 11:40:18 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Tue, 31 May 2022 11:55:46 -0400   Tue, 31 May 2022 11:40:18 -0400   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Addresses:
  Hostname:    win-p-win000000

**Comment by jackfrancis** [comment]
How is calico being installed? If it's being installed via `ClusterResourceSet`s then a Windows-specific `ClusterResourceSet` must be present on the mgmt cluster, and it must have the Windows-specific calico stuff defined in it.

cc @marosset @jsturtevant

**Comment by himanshuz2** [comment]
Thank you.  I figured out that.  The documentation at https://cluster-api.sigs.k8s.io/user/quick-start.html needs to be updated to reflect this.  
I used this flavor

clusterctl generate cluster my-cluster-1 --kubernetes-version v1.23.6     --flavor machinepool-windows-containerd > my-cluster-1.yaml

https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/flavors/machinepool-windows

This flavor templated should then include creating the clusterresource.   When I create cluster with the command  I expect that it will create a working cluster with windows node having calico on it otherwise this flavor template is incomplete.

**Comment by himanshuz2** [comment]
Or clusterctl init for azure should create the ClusterResourceSet?  In short the quickstart and the book is not updated for the use case where someone wants to create a cluster with windows nodepool in it.

**Comment by lzhecheng** [comment]
ci-entrypoint.sh is using `templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml` for windows right? It seems the 2 components you mentioned are already included. @marosset

**Comment by CecileRobertMichon** [comment]
1. @himanshuz2 for the quickstart specifically, we give instructions to apply https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/calico.yaml which doesn't contain the windows daemonset. We could update the instructions to also apply the Windows-specific stuff from https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/release-1.3/templates/addons/windows/calico as a separate step for Windows clusters. 

I'm hesitant to require ClusterResourceSets in the quickstart as it is an experimental feature that requires enabling a feature flag and is going away soon (even if that's how we install CNIs in tests). 

As a more long-term fix, with #2334 we will need a single helm install command to install Calico for both Windows and Linux and with k8s 1.23+ the `WindowsHostProcessContainers` feature gate will be on by default. As a side note, @jsturtevant / @marosset I'm curious if https://github.com/projectcalico/calico/pull/5968 allows us to stop needing special sigwindows images for windows calico and just use the default published ones with release 3.23+? 

2. @lzhecheng for ci-entrypoint.sh, the CNIs should all be installed via ClusterResourceSet as @marosset mentioned so not sure why the pods aren't coming up. Are the same issue with the other external cloud provider template or just the one using a k8s CI version ?

**Comment by jsturtevant** [comment]
> I'm curious if [projectcalico/calico#5968](https://github.com/projectcalico/calico/pull/5968) allows us to stop needing special sigwindows images for windows calico and just use the default published ones with release 3.23+?

We can use the calico CNI images.  Its on my list to test out.  We are more hesitant on the kube-proxy image they ship and sig-windows is considering building an official sig-windows kube-proxy image.

**Comment by lzhecheng** [comment]
@CecileRobertMichon I didn't test with other templates. Here is the job running in testgrid that fails because of windows node not ready. You may refer to this.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L660
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-conformance-windows-capz/1531481902450479104

**Comment by jsturtevant** [comment]
It seems like the template that is chosen when `TEST_CCM: true` is set might not include the correct resource sets.

**Comment by CecileRobertMichon** [comment]
I think the issue is that it's looking for label `cni: ${CLUSTER_NAME}-calico` but the cluster has label `cni: calico`

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml#L554
