### ISSUE TITLE
wrong image in kube-proxy-windows.yaml

### ISSUE THREAD

**Issue by himanshuz2** [kubernetes-sigs/cluster-api-provider-azure#2344]
/kind bug
Yaml file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/calico/kube-proxy-windows.yaml is wrong.

The following image doesn't exist with any KUBERNETES_VERSION at this dockerhub . https://hub.docker.com/r/sigwindowstools/kube-proxy/tags

Image doesn't exist 
sigwindowstools/kube-proxy:${KUBERNETES_VERSION/+/_}-calico-hostprocess

**What steps did you take and what happened:**
Closest that works is the following image that exists in your personal repo.
jsturtevant/kube-proxy:v1.24.0-alpha.2-calico-hostprocess

changed the yaml file then kube-proxy-windows.yaml got deployed,

**What did you expect to happen:**
Yaml file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/addons/windows/calico/kube-proxy-windows.yaml should have been correct and when deployed create kube-proxy-windows on windows node

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: GitVersion:"v1.1.3"
- Kubernetes version: (use `kubectl version`):  "v1.23.6"
- OS (e.g. from `/etc/os-release`):  "22.04 LTS (Jammy Jellyfish)"

**Comment by jackfrancis** [comment]
@himanshuz2 the string `sigwindowstools/kube-proxy:${KUBERNETES_VERSION/+/_}-calico-hostprocess` is meant to be interpreted by `envsubst`, with the `$KUBERNETES_VERSION` environment variable set to a valid Kubernetes version that exists in the upstream k/k CI container registry.

cc @marosset @jsturtevant

**Comment by himanshuz2** [comment]
Can you please check all the tags on [sigwindowstools/kube-proxy?  ](https://hub.docker.com/r/sigwindowstools/kube-proxy/tags)

There is no such tag ending in -calico-hostprocess.  The tages there are ending with the name of the windows OS version such as nanoserver etc.

**Comment by marosset** [comment]
- https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.24.0-calico-hostprocess/images/sha256-20b5356dd7454e8343db69f03ebbe816d34c166591d2fe27f47d312fc0a1b975?context=explore
- https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.6-calico-hostprocess/images/sha256-4f18357f76cd3ddeb62b8994a608ff9808b613a31d8e0b4c9b5dc16249c32076?context=explore
- https://hub.docker.com/layers/kube-proxy/sigwindowstools/kube-proxy/v1.23.5-calico-hostprocess/images/sha256-0f8a44b795d1824358f24cc56f0024d18a39ae044656686596d8b7fa6d78e1fa?context=explore

Is there a specific K8s version you are looking for @himanshuz2 ?
