### ISSUE TITLE
Multiple VMSS cluster scaling problem

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2347]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I am using an external cluster template to create a multiple vmss cluster.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/022c69eabd040cfdae4464ad24f961a7bf3d4f9d/tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml
The creation is a success and everything looks fine except one problem:
If I scale down one MachinePool, the other one' Nodes, MachinePool decrease (unexpected). Its VMSS VM instance is still unchanged (expected).
```
kubectl scale machinepool --replicas 1 <one-machine-pool>
```

**What did you expect to happen:**
Only the scaled MachinePool and its Nodes decrease.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by mboersma** [comment]
@jackfrancis was this fixed by #2536?

**Comment by jackfrancis** [comment]
@lzhecheng can you still repro this?

I haven't been able to repro this, but I did try after #2536 so it's possible that (and related) changes was responsible, as one of the things we fixed was machines having the wrong providerID ref (e.g., a machine in a different pool).

**Comment by lzhecheng** [comment]
Recently such error hasn't happended. Closing this issue for now.
