### ISSUE TITLE
AzureMachine controller

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-azure#235]
/kind feature

**Describe the solution you'd like**
After the v1alpha2 types are created, we need a new Kubebuilder controller that watches AzureMachine and Machine events. This controller replaces v1alpha1's actuator logic and it should follow the specs detailed in Machine states and preboot proposal.

**Comment by justaugustus** [comment]
Closed via #281.
/close
/assign @CecileRobertMichon @vincepri
