### ISSUE TITLE
Tag CAPZ managed resources uniformly 

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-azure#2354]
/kind feature

**Describe the solution you'd like**
Tag CAPZ managed resources such as NSGs, route tables and NAT gateways using the same method currently used on virtual networks or load balancers i.e. sigs.k8s.io_cluster-api-provider-azure_cluster__clustername_ "owned"

**Anything else you would like to add:**
N/A

**Comment by CecileRobertMichon** [comment]
@josh-ferrell I noticed that network interfaces are also not tagged, are you interested in tackling it as part of this issue or should we open a separate issue for it? All 3 initial issues that you opened for this are now closed.

**Comment by sonasingh46** [comment]
Created a PR to tag network interfaces.
