### ISSUE TITLE
Add a CI job: ci-entrypoint.sh with latest-xxx as KUBERNETES_VERSION

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2359]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, there's a CI job for ci-entrypoint:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-main.yaml#L466
I think we should have another CI job to verify `latest-xxx` as `KUBERNETES_VERSION`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
@jackfrancis IIRC, this situation has been covered right? If so please close this issue. Thanks.

**Comment by jackfrancis** [comment]
@lzhecheng I'm not sure we have a separate job for this. The job you link to calls `ci-entrypoint.sh` with no args. Is that what we want to fulfill this issue?

**Comment by lzhecheng** [comment]
> @lzhecheng I'm not sure we have a separate job for this. The job you link to calls `ci-entrypoint.sh` with no args. Is that what we want to fulfill this issue?

It has been a while and the situation has changed a lot so let's forget that link : )

cloud-provider-azure CI jobs are consuming `latest-xxx` but we need a presubmit job in capz to avoid breaking those jobs. It can be a new one or be integrated into an old one. If we don't have it right now, I think we should keep the issue open.

**Comment by jackfrancis** [comment]
@lzhecheng here's a link to the most recent (as of now) run of the capz presubmit job:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2495/pull-cluster-api-provider-azure-ci-entrypoint/1580979430652645376/build-log.txt

It built a 1.23.9 cluster. Are we saying that we want to update the job spec that runs this job to use a different "latest" configuration? As you can see in the above output no `KUBERNETES_VERSION` variable is being assigned, so we just use the capz default.
