### ISSUE TITLE
Add validating webhook for v1alpha2 types

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-azure#236]
/kind feature

**Describe the solution you'd like**
Using validating webhook, we need to add validation logic for AzureMachineTemplate objects to achieve immutability.

**Comment by justaugustus** [comment]
This is complete with the carryover in #281, right?
/close
/assign @CecileRobertMichon @vincepri

**Comment by CecileRobertMichon** [comment]
/close

won't do this for v1alpha2, #292 tracks this effort for v1alpha3
