### ISSUE TITLE
Modify NGW IsManaged function to use tag

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-azure#2382]
/kind feature

**Describe the solution you'd like**
Modify NGW IsManaged function to utilize "owned" tag

**Anything else you would like to add:**
Dependent on #2369 being closed.

**Comment by jackfrancis** [comment]
/remove-lifecycle rotten

@josh-ferrell now that #2369 is done, would you like to take this on?
