### ISSUE TITLE
Network unavailable on Node after a cluster is created

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2389]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
It is a VMSS cluster running some e2e tests. Somehow, after a cluster is created, networking on cluster Nodes are not working properly: `3 node(s) had untolerated taint {node.kubernetes.io/network-unavailable`. And there should be 3 Nodes in total instead of 4. I dump Pod describe:
```
Warning  FailedScheduling  5m2s  default-scheduler  0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 1 node(s) were unschedulable, 3 node(s) had untolerated taint {node.kubernetes.io/network-unavailable: }. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
 [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:647]
Jun 16 08:40:01.041: INFO: Kubernetes configuration file name: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/kubeconfig [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/utils/kubectl.go:100]
Jun 16 08:40:01.041: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/kubeconfig --namespace=e2e-tests-mpservice-mdz7w describe pod multiport-test-f87785767-trsh6' [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/utils/kubectl.go:140]
Jun 16 08:40:01.376: INFO: stderr: "" [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/utils/kubectl.go:165]
Jun 16 08:40:01.376: INFO: stdout: "Name:           multiport-test-f87785767-trsh6\nNamespace:      e2e-tests-mpservice-mdz7w\nPriority:       0\nNode:           <none>\nLabels:         app=multiport-test\n                pod-template-hash=f87785767\nAnnotations:    <none>\nStatus:         Pending\nIP:             \nIPs:            <none>\nControlled By:  ReplicaSet/multiport-test-f87785767\nContainers:\n  test-app:\n    Image:        nginx:1.15\n    Port:         80/TCP\n    Host Port:    0/TCP\n    Environment:  <none>\n    Mounts:\n      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-89m5x (ro)\nConditions:\n  Type           Status\n  PodScheduled   False \nVolumes:\n  kube-api-access-89m5x:\n    Type:                    Projected (a volume that contains injected data from multiple sources)\n    TokenExpirationSeconds:  3607\n    ConfigMapName:           kube-root-ca.crt\n    ConfigMapOptional:       <nil>\n    DownwardAPI:             true\nQoS Class:                   BestEffort\nNode-Selectors:              <none>\nTolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s\n                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s\nEvents:\n  Type     Reason            Age   From               Message\n  ----     ------            ----  ----               -------\n  Warning  FailedScheduling  5m2s  default-scheduler  0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 1 node(s) were unschedulable, 3 node(s) had untolerated taint {node.kubernetes.io/network-unavailable: }. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.\n" [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/utils/kubectl.go:166]
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1847/pull-cloud-provider-azure-e2e-ccm-vmss-capz/1537339985768747008/build-log.txt

From logs, `kubectl get node` shows that Nodes are ready at the beginning.

Job configuration:
```
- name: TEST_CCM
  value: "true"
- name: CONTROL_PLANE_MACHINE_COUNT
  value: "1"
- name: KUBERNETES_VERSION
  value: "latest"
- name: CLUSTER_TEMPLATE
  value: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
- name: AZURE_LOADBALANCER_SKU
  value: "Standard"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
@CecileRobertMichon PTAL. Thank you!

**Comment by CecileRobertMichon** [comment]
@lzhecheng is this happening consistently or was it a flake?

cc @Jont828

**Comment by lzhecheng** [comment]
@CecileRobertMichon Recently all pr-cloud-provider-azure-e2e-ccm-vmss-capz tests are failing for some reason.
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#pr-cloud-provider-azure-e2e-ccm-vmss-capz

I used a PR to dump Pod describe info and that's the one I showed above.
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1847#issuecomment-1157631101

I am not sure if my helm related PR fixes the issue or just one factor, leading to test failure.

**Comment by Jont828** [comment]
It looks like in those tests for today we don't have any cluster artifacts in the artifacts folder, i.e. capz-controller-manager logs. For the dump pod PR, the [artifacts](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1847/pull-cloud-provider-azure-e2e-ccm-vmss-capz/1537339985768747008/) it looks like it's failing before we've got the controller manager set up. Is that caused by this line?

```
output, err := utils.RunKubectl(ns.Name, "describe", "pod", pod.Name)
Expect(err).NotTo(HaveOccurred())
```

**Comment by lzhecheng** [comment]
@Jont828 I think the reason for no artifacts is that the whole execution time exceeded the timeout limit.
My PR just dumps pod describe info for debugging purpose.

**Comment by jackfrancis** [comment]
I confirmed that the template here works with the ci-entrypoint.sh script:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml

The following PRs were opened to help get things working:

- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1901
- https://github.com/kubernetes/test-infra/pull/26628
