### ISSUE TITLE
AKS cluster name must match-control plane name

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-azure#2438]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Used https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/v1.3.1/cluster-template-aks.yaml but changed `AzureManagedControlPlane` to `name: ${CLUSTER_NAME}-control-plane`.

The cluster fails to come up with:
```
E0617 19:57:58.080445 1 controller.go:317] controller/azuremanagedcontrolplane "msg"="Reconciler error" "error"="error creating AzureManagedControlPlane default/aks-test-3500138-control-plane: failed to reconcile AzureManagedControlPlane service managedclusters: failed to get credentials for managed cluster: containerservice.ManagedClustersClient#ListClusterAdminCredentials: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.ContainerService/managedClusters/aks-test-3500138' under resource group 'aks-test-3500138' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"" "name"="aks-test-3500138-control-plane" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureManagedControlPlane"
```

**What did you expect to happen:**
It should be possible to change `AzureManagedControlPlane` `metadata.name`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I tracked it down to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/240f5dd4104e7fb0603494a77e429b6884dbfc3f/azure/scope/managedcontrolplane.go#L389, but was not sure if the `Name` value should come from either `AzureManagedCluster` or `Cluster` types or if this was done intentionally.

**Environment:**

- cluster-api-provider-azure version: 
v1.3.1
- Kubernetes version: (use `kubectl version`): 
v1.22.6
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/area managedcluster
/help

@nawazkh this might be a good one for you to look into when you have time

**Comment by jackfrancis** [comment]
It looks like the current capz implementation requires a tight coupling between `AzureManagedCluster`'s and `AzureManagedControlPlane`'s `Name` value.

It seems that if we _just_ change the value of `AzureManagedControlPlane` there is a mismatch in the way we retrieve the kubeconfig secret.

@CecileRobertMichon does this ring a bell? Happy to dig into this more independently if this behavior is a mystery.

**Comment by CecileRobertMichon** [comment]
I'm not sure, haven't looked into this much, but I'm guessing this is a bug in CAPZ implementation and there really isn't a good reason for the tight coupling. We might need to change the place where we do `ListClusterAdminCredentials` to use the AzureManagedCluster name or vice versa.

**Comment by nawazkh** [comment]
Hmm, I lost track of this earlier, Thanks for the pointers @jackfrancis and @CecileRobertMichon , I will dig into it

**Comment by nawazkh** [comment]
@dkoshkin We do not see this error on latest version of CAPZ, would advise you to use/upgrade to latest version.
This was fixed as part of PR https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2168

**Comment by dkoshkin** [comment]
Verified its working now thanks!
```
clusterctl describe cluster aks-control-plane-name-test
NAME                                                                                 READY  SEVERITY  REASON  SINCE  MESSAGE
Cluster/aks-control-plane-name-test                                                  True                     108s
├─ClusterInfrastructure - AzureManagedCluster/aks-control-plane-name-test
├─ControlPlane - AzureManagedControlPlane/aks-control-plane-name-test-control-plane  True                     108s
└─Workers
  ├─MachinePool/aks-control-plane-name-test                                          True                     97s
  └─MachinePool/aks-control-plane-name-test-md-0                                     True                     97s
```
