### ISSUE TITLE
Node outbound public IP name created incorrectly when using ClusterClass, missing hash

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-azure#2441]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Create a CAPZ Cluster using ClusterClass. The node outbound IP gets created with the name pip-_clustername_-node-outbound instead of pip-_azureclustername_-node-outbound and the load balancer fails to get created with the following error:

`loadbalancers failed to create or update. err: failed to create resource azure-cc/jf (service: loadbalancers): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/SUBID/resourceGroups/AZURE-CC/providers/Microsoft.Network/publicIPAddresses/PIP-JF-Q6N2M-NODE-OUTBOUND referenced by resource /subscriptions/SUBID/resourceGroups/azure-cc/providers/Microsoft.Network/loadBalancers/jf was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[{"code":"NotFound","message":"Resource /subscriptions/SUBID/resourceGroups/AZURE-CC/providers/Microsoft.Network/publicIPAddresses/PIP-JF-Q6N2M-NODE-OUTBOUND not found."}]`

**What did you expect to happen:**
The node outbound loadbalancer IP gets created using the Azure cluster name similar to the API server IP.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 1.3.2
- Kubernetes version: (use `kubectl version`): 1.23.5
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2459 should fix it 

this was a general bug whenever the Cluster.Name != AzureCluster.Name and there are control plane or node outbound IPs, not strictly related to ClusterClass

**Comment by josh-ferrell** [comment]
Thanks @CecileRobertMichon
