### ISSUE TITLE
Don't download Calico release manifest on every "make generate-flavors" execution

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-azure#2449]
/kind feature

**Describe the solution you'd like**
The manifest is 1GB in size and there is no point downloading it on every run. Likely required manifests should be saved to some hidden working directory (e.g. existing `_artifacts`?) and release archive should only be downloaded when expected files are missing from there.

Make should be able to "cache" the results and trigger re-download if Calico version changes.

This will also prevent polluting root project directory with ambiguous directories like `release-v3.23.0`.

**Comment by jackfrancis** [comment]
I'm working on a solution that will use helm to install this at runtime.

In the meantime I recommend replacing `make generate-flavors` in your workflows with `hack/gen-flavors.sh`, which only does template flavor generation and skips the calico foo.

**Comment by invidian** [comment]
I've already opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2450, which seem like a straightforward solution. Do you mind having a look still @jackfrancis?
