### ISSUE TITLE
Cluster creation failure with latest-xxx as KUBERNETES_VERSION

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#2469]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
With latest-xxx as KUBERNETES_VERSION, only 1 control-plane node is successfully created. While "latest" as KUBERNETES_VERSION seems ok.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-azure-e2e-capz-1-24/1546014024162873344

**What did you expect to happen:**
Cluster creation succeeds and all nodes are up.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/assign @jackfrancis 

This is fixed by https://github.com/kubernetes/kubernetes/pull/111021

**Comment by jackfrancis** [comment]
All jobs look recovered, thanks for your patience @lzhecheng!
