### ISSUE TITLE
Clusterctl thinking Machines are down when they aren't according to kubectl

### ISSUE THREAD

**Issue by pizza654321** [kubernetes-sigs/cluster-api-provider-azure#2492]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Inconsistency between ./clusterctl describe cluster and kubectl --kubeconfig \kubeconfig get nodes. This may be an error with CAPI and not CAPZ, somewhat unsure.

**What did you expect to happen:**
Clusterctl should see that the machine deployments created exist but likely cannot due to a networking problem, but all of the machine deployments are still up according to kubectl and seeing as we've successfully deployed on this cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Logs:
clusterctl describe cluster capi-quickstart:
NAME                                                                READY  SEVERITY  REASON  SINCE  MESSAGE 

  

Cluster/capi-quickstart                                             True                     5h32m 

  

├─ClusterInfrastructure - AzureCluster/capi-quickstart              True                     2d10h 

  

├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane  True                     5h32m 

  

│ └─5 Machines...                                                   True                     3d8h   See capi-quickstart-control-plane-22rkx, capi-quickstart-control-plane-k447l, ... 

└─Workers 

  

  └─MachineDeployment/capi-quickstart-md-0                          True                     19d 

  

    └─10 Machines...                                                False  Error     Failed  9d     See capi-quickstart-md-0-98984f5f4-cptnd, capi-quickstart-md-0-98984f5f4-d5wbv, ... 

kubectl --kubeconfig \capi-diff.kubeconfig get nodes:

NAME                                  STATUS   ROLES           AGE   VERSION 

capi-quickstart-control-plane-ctdrf   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-d9vvx   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-dskvf   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-gsgb6   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-jngj9   Ready    control-plane   19d   v1.24.0 

capi-quickstart-md-0-4vdjr            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-6czbd            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-6nhmq            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-bt8wl            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-cdsjd            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-fbcdt            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-fw8v2            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-jx8nl            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-p7mcn            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-v42g7            Ready    <none>          19d   v1.24.0 

**Environment:**

- cluster-api-provider-azure version: Deployed on v1.3.2, also deployed using clusterctl v1.1.4
- Kubernetes version: (use `kubectl version`):  1.24.2
- OS (e.g. from `/etc/os-release`): Azure Cloud Shell Bash

**Comment by CecileRobertMichon** [comment]
What is the full error message / failure reason on the Machines and/or AzureMachines if you do `kubectl describe Machine <failed machine name>` and `<kubectl describe AzureMachine <failed azure machine name>`  from the management cluster?

**Comment by pizza654321** [comment]
kubectl get machine: 
NAME                                   CLUSTER           NODENAME                              PROVIDERID                                                                                                                                                                            PHASE     AGE   VERSION
capi-quickstart-control-plane-22rkx    capi-quickstart   capi-quickstart-control-plane-gsgb6   azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-control-plane-gsgb6   Running   19d   v1.24.0
capi-quickstart-control-plane-k447l    capi-quickstart   capi-quickstart-control-plane-dskvf   azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-control-plane-dskvf   Running   19d   v1.24.0
capi-quickstart-control-plane-pzrhr    capi-quickstart   capi-quickstart-control-plane-jngj9   azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-control-plane-jngj9   Running   19d   v1.24.0
capi-quickstart-control-plane-qprms    capi-quickstart   capi-quickstart-control-plane-d9vvx   azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-control-plane-d9vvx   Running   19d   v1.24.0
capi-quickstart-control-plane-t2dgk    capi-quickstart   capi-quickstart-control-plane-ctdrf   azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-control-plane-ctdrf   Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-cptnd   capi-quickstart   capi-quickstart-md-0-bt8wl            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-bt8wl            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-d5wbv   capi-quickstart   capi-quickstart-md-0-p7mcn            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-p7mcn            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-dkn78   capi-quickstart   capi-quickstart-md-0-cdsjd            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-cdsjd            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-ldrd9   capi-quickstart   capi-quickstart-md-0-fbcdt            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-fbcdt            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-lrlq4   capi-quickstart   capi-quickstart-md-0-v42g7            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-v42g7            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-qwk8c   capi-quickstart   capi-quickstart-md-0-jx8nl            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-jx8nl            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-rnrqw   capi-quickstart   capi-quickstart-md-0-fw8v2            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-fw8v2            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-t68xh   capi-quickstart   capi-quickstart-md-0-6czbd            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-6czbd            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-tc2w5   capi-quickstart   capi-quickstart-md-0-4vdjr            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-4vdjr            Running   19d   v1.24.0
capi-quickstart-md-0-98984f5f4-w4mq8   capi-quickstart   capi-quickstart-md-0-6nhmq            azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-6nhmq            Running   19d   v1.24.0

**Comment by pizza654321** [comment]
kubectl describe machine: 
Name:         capi-quickstart-md-0-98984f5f4-cptnd
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=capi-quickstart
              cluster.x-k8s.io/deployment-name=capi-quickstart-md-0
              machine-template-hash=545409190
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Machine
Metadata:
  Creation Timestamp:  2022-07-01T23:12:26Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generate Name:  capi-quickstart-md-0-98984f5f4-
  Generation:     3
  Managed Fields:
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"machine.cluster.x-k8s.io":
        f:generateName:
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
          f:cluster.x-k8s.io/deployment-name:
          f:machine-template-hash:
        f:ownerReferences:
          .:
          k:{"uid":"365cc493-d41a-4558-978a-11dcce428ef6"}:
      f:spec:
        .:
        f:bootstrap:
          .:
          f:configRef:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
            f:uid:
          f:dataSecretName:
        f:clusterName:
        f:infrastructureRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
          f:uid:
        f:providerID:
        f:version:
    Manager:      manager
    Operation:    Update
    Time:         2022-07-01T23:16:20Z
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:addresses:
        f:bootstrapReady:
        f:conditions:
        f:infrastructureReady:
        f:lastUpdated:
        f:nodeInfo:
          .:
          f:architecture:
          f:bootID:
          f:containerRuntimeVersion:
          f:kernelVersion:
          f:kubeProxyVersion:
          f:kubeletVersion:
          f:machineID:
          f:operatingSystem:
          f:osImage:
          f:systemUUID:
        f:nodeRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:uid:
        f:observedGeneration:
        f:phase:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2022-07-01T23:16:20Z
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineSet
    Name:                  capi-quickstart-md-0-98984f5f4
    UID:                   365cc493-d41a-4558-978a-11dcce428ef6
  Resource Version:        8172552
  UID:                     1f83f9a0-e394-49d8-bf56-7323f3a9eafb
Spec:
  Bootstrap:
    Config Ref:
      API Version:     bootstrap.cluster.x-k8s.io/v1beta1
      Kind:            KubeadmConfig
      Name:            capi-quickstart-md-0-9f8z7
      Namespace:       default
      UID:             fe623cd6-998c-4ce4-912e-517a19a6b101
    Data Secret Name:  capi-quickstart-md-0-9f8z7
  Cluster Name:        capi-quickstart
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Kind:         AzureMachine
    Name:         capi-quickstart-md-0-bt8wl
    Namespace:    default
    UID:          c171df02-0f00-4b80-9833-305caf018613
  Provider ID:    azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-bt8wl
  Version:        v1.24.0
Status:
  Addresses:
    Address:        capi-quickstart-md-0-bt8wl
    Type:           InternalDNS
    Address:        10.0.2.21
    Type:           InternalIP
  Bootstrap Ready:  true
  Conditions:
    Last Transition Time:  2022-07-18T08:19:22Z
    Message:               inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer capi-quickstart-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-07-01T23:15:01Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2022-07-18T08:19:22Z
    Message:               inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer capi-quickstart-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  InfrastructureReady
    Last Transition Time:  2022-07-01T23:18:48Z
    Status:                True
    Type:                  NodeHealthy
  Infrastructure Ready:    true
  Last Updated:            2022-07-01T23:16:20Z
  Node Info:
    Architecture:               amd64
    Boot ID:                    276054bf-68e7-437c-a2c5-82bc326cf9d1
    Container Runtime Version:  containerd://1.6.2
    Kernel Version:             5.13.0-1023-azure
    Kube Proxy Version:         v1.24.0
    Kubelet Version:            v1.24.0
    Machine ID:                 0717e85d8697421fa54f0a85027ff1f7
    Operating System:           linux
    Os Image:                   Ubuntu 20.04.4 LTS
    System UUID:                1b667246-f192-ac41-ad92-e9c68259aab8
  Node Ref:
    API Version:        v1
    Kind:               Node
    Name:               capi-quickstart-md-0-bt8wl
    UID:                22836967-9476-4254-b6f6-bcafecc28990
  Observed Generation:  3
  Phase:                Running
Events:                 <none>

**Comment by pizza654321** [comment]
kubectl get AzureMachine:

NAME                                  READY   REASON   STATE
capi-quickstart-control-plane-ctdrf   True             Succeeded
capi-quickstart-control-plane-d9vvx   True             Succeeded
capi-quickstart-control-plane-dskvf   True             Succeeded
capi-quickstart-control-plane-gsgb6   True             Succeeded
capi-quickstart-control-plane-jngj9   True             Succeeded
capi-quickstart-md-0-4vdjr            False   Failed   Succeeded
capi-quickstart-md-0-6czbd            False   Failed   Succeeded
capi-quickstart-md-0-6nhmq            False   Failed   Succeeded
capi-quickstart-md-0-bt8wl            False   Failed   Succeeded
capi-quickstart-md-0-cdsjd            False   Failed   Succeeded
capi-quickstart-md-0-fbcdt            False   Failed   Succeeded
capi-quickstart-md-0-fw8v2            False   Failed   Succeeded
capi-quickstart-md-0-jx8nl            False   Failed   Succeeded
capi-quickstart-md-0-p7mcn            False   Failed   Succeeded
capi-quickstart-md-0-v42g7            False   Failed   Succeeded

**Comment by pizza654321** [comment]
kubectl describe azuremachine: 
Name:         capi-quickstart-md-0-4vdjr
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=capi-quickstart
              cluster.x-k8s.io/deployment-name=capi-quickstart-md-0
              machine-template-hash=545409190
Annotations:  cluster-api-provider-azure: true
              cluster.x-k8s.io/cloned-from-groupkind: AzureMachineTemplate.infrastructure.cluster.x-k8s.io
              cluster.x-k8s.io/cloned-from-name: capi-quickstart-md-0
API Version:  infrastructure.cluster.x-k8s.io/v1beta1
Kind:         AzureMachine
Metadata:
  Creation Timestamp:  2022-07-01T23:12:24Z
  Finalizers:
    azuremachine.infrastructure.cluster.x-k8s.io
  Generation:  3
  Managed Fields:
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cluster.x-k8s.io/cloned-from-groupkind:
          f:cluster.x-k8s.io/cloned-from-name:
        f:labels:
          .:
          f:cluster.x-k8s.io/cluster-name:
          f:cluster.x-k8s.io/deployment-name:
          f:machine-template-hash:
        f:ownerReferences:
          .:
          k:{"uid":"365cc493-d41a-4558-978a-11dcce428ef6"}:
          k:{"uid":"43de416c-b6cc-46f8-b5a1-6c983224acf5"}:
      f:spec:
        .:
        f:identity:
        f:osDisk:
          .:
          f:cachingType:
          f:diskSizeGB:
          f:osType:
        f:sshPublicKey:
        f:userAssignedIdentities:
        f:vmSize:
    Manager:      manager
    Operation:    Update
    Time:         2022-07-01T23:12:25Z
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cluster-api-provider-azure:
        f:finalizers:
          .:
          v:"azuremachine.infrastructure.cluster.x-k8s.io":
      f:spec:
        f:providerID:
        f:subnetName:
    Manager:      cluster-api-provider-azure-manager
    Operation:    Update
    Time:         2022-07-01T23:15:58Z
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:addresses:
        f:conditions:
        f:ready:
        f:vmState:
    Manager:      cluster-api-provider-azure-manager
    Operation:    Update
    Subresource:  status
    Time:         2022-07-01T23:16:34Z
  Owner References:
    API Version:           cluster.x-k8s.io/v1beta1
    Kind:                  MachineSet
    Name:                  capi-quickstart-md-0-98984f5f4
    UID:                   365cc493-d41a-4558-978a-11dcce428ef6
    API Version:           cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Machine
    Name:                  capi-quickstart-md-0-98984f5f4-tc2w5
    UID:                   43de416c-b6cc-46f8-b5a1-6c983224acf5
  Resource Version:        5213555
  UID:                     397eb238-7b46-40e9-9658-aad6a149af02
Spec:
  Identity:  UserAssigned
  Os Disk:
    Caching Type:  None
    Disk Size GB:  128
    Os Type:       Linux
  Provider ID:     azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourceGroups/rp-vnet-deploy-capz-mult/providers/Microsoft.Compute/virtualMachines/capi-quickstart-md-0-4vdjr
  Ssh Public Key:  c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFDNE9FRVc5MTh3bU9uTlh5cnZjTHc4Q2RtTUhWYlpHeWZsVjJSZ01VSGJnaWtzeGt3SzlQaE1TVWd0RDVjZmtTYkxpRC8rRFBzMkRtaWExSnNWR0RHeHNQUCs3cVNvTUtxS0hJRktiMEZTdS93bHl1L3BjMFhFajZaYytBelVOQ2djcWRYMXFERDJ1bnRsV3B3cUp5VmdDUmltS1ZRT3VhVHhuaHZLYzZBbUFZUjJ0eUNyVU1FOEFmVFlJbnBKaStXaFE1SXM2eVlBdk84bHdnNnZnZVlPTnhSQi9tUGN5UHp2WXNKTzliYWxhS1FCNGdWQ1gvOWRmY0lxdXlIWG1KbGREcFRSUU9pV25xeUJnTk5KRHRLSkxVNnVJQUp1dDlhQXF5ZlZvdnVpbWNybjBpMTZvaUJPMXF5ak5TZHVtZVl2MUdSOTFkUzV6Z1hXN0dZdS84akdlZWFxWGg0aWhiNGxJUFRodUZITGE4dlVtUHdTWlVhV1VVWmQ4TVdUS3ZzanZ5WVY1bTBLWThwQXc4QlkyR1g1V21xbkpZdE5paFFDeDExMVo4b3FoZC8zdi9CN3BHbm8xS09oQ29rTjUvOEdxMERFMmp0aXpPYWFVa29yNW9DblV2YlByZXFHQ3JoVHk0QU51ZmVqZW5ib3h0OGxCOUNzL1J3Z0pFMUpiWGNsWERCVmdFVWFEWCt0d0VrTFFnMmpqMVJIWmZRU3hOZkJOd1dnLyt5ZFROSWhDZGtTek91YzdUbU85UjRFdjlVRGJjemRjdUVuT3hGc3lTU2VQRFA1bkJNSDN6OVBwUWk0anV3SytLWFQ3N3V3T2RBZHlxd09DQ1dBR0JnMjVtU3plZW5LK1h2TGJySnFDMFFmdE5PZnpqVC81UjFqcERMWWJpdlFmZnRQc1E9PQ==
  Subnet Name:     node-subnet-custom
  User Assigned Identities:
    Provider ID:  azure:///subscriptions/84c559c6-30a0-417c-ba06-8a2253b388c3/resourcegroups/dogfood2-eus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/eus-acr-test-vmss-identity
  Vm Size:        Standard_D2s_v3
Status:
  Addresses:
    Address:  capi-quickstart-md-0-4vdjr
    Type:     InternalDNS
    Address:  10.0.2.22
    Type:     InternalIP
  Conditions:
    Last Transition Time:  2022-07-12T09:09:59Z
    Message:               inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer capi-quickstart-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-07-12T09:09:59Z
    Status:                True
    Type:                  BootstrapSucceeded
    Last Transition Time:  2022-07-12T07:55:54Z
    Status:                True
    Type:                  DisksReady
    Last Transition Time:  2022-07-05T14:34:39Z
    Message:               inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer capi-quickstart-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  InboundNATRulesReady
    Last Transition Time:  2022-07-12T04:18:51Z
    Status:                True
    Type:                  NetworkInterfacesReady
    Last Transition Time:  2022-07-12T07:55:54Z
    Status:                True
    Type:                  VMRunning
  Ready:                   true
  Vm State:                Succeeded
Events:                    <none>

**Comment by CecileRobertMichon** [comment]
> Last Transition Time: 2022-07-12T09:09:59Z
Message: inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer capi-quickstart-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
Reason: Failed
Severity: Error
Status: False
Type: Ready

Looks like CAPZ is unable to reach Azure APIs to list existing resources to make sure that everything is still healthy, this might point to a networking issue from the CAPZ manager pod or expired credentials, although if it was expired credentials I would expect a more clear error message with a 503 error, not a context deadline exceeded error.

**Comment by pizza654321** [comment]
Does anything on the manager pod rotate IPs? Since this happens over time, at the beginning of deployment it typically has everything ready and not failed everywhere, so my guess had been that IPs get rotated for safety over time. Thank you!

**Comment by CecileRobertMichon** [comment]
> Does anything on the manager pod rotate IPs?

Do you mean LB public IP, VM private IPs, pod IPs or something else?

CAPZ itself does not rotate IPs. All it does once the initial resources have been created is periodically GET each resource and make sure that nothing has changed & that Azure resources are still existing and healthy. In this case looks like it times out trying to List inbound NAT rules in the load balancer. The fact that it's failing on NAT rules is not very significant apart from the fact that NAT rules are one of the first resources to be reconciled for AzureMachines on each loop (2nd right after public IPs).

What's interesting is that this is happening on the worker machines but not the control plane machines it seems. Is CAPZ reconciling the control plane AzureMachines without any errors / do they show Ready ?

**Comment by CecileRobertMichon** [comment]
If this is indeed just happening on worker machines, this PR will fix it: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2502

I don't fully grasp why it would fail to List from worker machines only however.

**Comment by sonasingh46** [comment]
I have hit this issue for control plane
```
'Failed @ Machine/mgmt-sh-1916826-220808-064240-control-plane-bptph', message:'inboundnatrules failed to create or update. err: failed to get existing NAT rules: could not list inbound NAT rules for load balancer mgmt-sh-1916826-220808-064240-internal-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded'
```

**Comment by yastij** [comment]
/close

for control plane it seems that it's mostly a transient issue, the machine moved into Ready after some reconciliations

**Comment by sonasingh46** [comment]
Just for the record: 
For control plane machine, like Yassine said -- it can be due to a transient network issue and then recover and a `InboundNatReady` with a success status is written back on the azuremachine.

In case of worker machine -- once a transient list errror of inbound NAT happens, the error os written to the azuremachine conditions but when the list succeeds next time, as per the code before this PR, the success status is never written. This is because the `Reconcile` returns early as the NatSpec len is 0 for worker machines.
