### ISSUE TITLE
Make azure and async spec type default values consistent with Azure Go SDK types

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#2494]
/kind bug

The `azure.AgentPoolSpec` type (found in `azure/types.go`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/types.go)) has fields such as `AgentPoolSpec.AvailabilityZones` which is a `[]string` and `AgentPoolSpec.VnetSubnetID` which is a `string`. These types are used to initialize the Go SDK type `containerservice.AgentPool` which has corresponding pointer types such as `AgentPool.AvailabilityZones` which is a `*[]string` and `AgentPool.VnetSubnetID` which is a `*string` with code like this.

```
containerservice.AgentPool{
    AvailabilityZones: &spec.AvailabilityZones,
    ...
    VnetSubnetID:      &spec.VnetSubnetID,
}
```

As a result, when `spec.AvailabilityZones` and `spec.VnetSubnetID` are uninitialized with values `[]` and `""`, `AgentPool.AvailabilityZones` is set to `&nil` instead of `nil` and `AgentPool.VnetSubnetID`  is set to `&""` instead of `nil`. This results in a bug where the Azure Go SDK fields become initialized with pointers to default values. If the spec field is guaranteed to be set, this is not noticeable, but if not it will cause unit tests for the spec to fail.

**Comment by Jont828** [comment]
@CecileRobertMichon

**Comment by Jont828** [comment]
Another consideration is that sometimes we might want to pass a pointer to an int type. For example, `containerservice.AgentPool.OSDiskSizeGB` has the following description:
```
field OsDiskSizeGB *int32
OsDiskSizeGB - OS Disk Size in GB to be used to specify the disk size for every machine in this master/agent pool. If you specify 0, it will apply the default osDisk size according to the vmSize specified.
```
In this case we might not want to have it be `nil` if OS disk size is not in the spec.

**Comment by dtzar** [comment]
IMO we should prioritize [the migration to a supported SDK track ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2670) first and fix this issue as we go along (if it's still appropriate).

**Comment by willie-yao** [comment]
/lifecycle frozen

We are prioritizing migration to ASO and will re-evaluate this depending on if it's still needed. More details at #3113

**Comment by dtzar** [comment]
Do you think this is still needed @Jont828 @nojnhuh ?

**Comment by nojnhuh** [comment]
I think the kinds of bugs this attempts to address are much less of a concern now with ASO. Overall I'm +1 to closing this and re-opening if we do encounter any more bugs that this would have saved. Or at least recording that this is very low priority.

**Comment by Jont828** [comment]
I'll defer to @nojnhuh on this since most of these spec types were replaced with the ASO types. Closing it out for now, and if we need to reopen, we could probably just make a new issue specific to ASO.

/close
