### ISSUE TITLE
Remove UseExperimentalRetryJoin from reference templates

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2496]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The deprecated `UseExperimentalRetryJoin` feature is now marked as deprecated by cluster-api:

- https://github.com/kubernetes-sigs/cluster-api/pull/6938

Let's remove this option from all capz reference and test templates, and documentation.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
@jackfrancis @CecileRobertMichon https://cs.k8s.io/?q=UseExperimentalRetryJoin&i=nope&files=&excludeFiles=&repos=
As I can see here, I don't think that `UseExperimentalRetryJoin` is used in reference templates in CAPZ.

**Comment by jackfrancis** [comment]
@sayantani11 thanks for picking this up!

That search is case-sensitive, and the yaml template usage follows the json spec in the type definition. So this is what we're looking for:

https://cs.k8s.io/?q=useExperimentalRetryJoin&i=nope&files=&excludeFiles=&repos=

**Comment by sayantani11** [comment]
@jackfrancis Thanks for the clarification. I'll make a PR asap.
