### ISSUE TITLE
Add OIDCIssuerProfile configuration option

### ISSUE THREAD

**Issue by nijave** [kubernetes-sigs/cluster-api-provider-azure#2498]
/kind feature

**Describe the solution you'd like**
In order to enable Azure Workload Identity, the OIDC issuer needs to be enabled on new clusters. Add a field AzureManagedControlPlane for enabling OIDC issuer.

**Anything else you would like to add:**
Basically just a configuration option that does the same as this cli command https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#update-an-aks-cluster-with-oidc-issuer

**Environment:**

- cluster-api-provider-azure version: v1.4.0
- Kubernetes version: (use `kubectl version`): v1.22
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
Since we haven't added any AKS preview features yet to CAPZ, there's some work we need to do yet to determine how those should be implemented generally which is being tracked in #2625. Once that's done, this looks like it would be a great first preview feature to implement!

/unassign

**Comment by mjnovice** [comment]
+1 for this feature.

**Comment by andreipantelimon** [comment]
Workload Identity is now Merged in CAPZ and since AAD Pod Identity is getting deprecated, this feature is mandatory. Is there a guide on how to enable this?

**Comment by CecileRobertMichon** [comment]
@mboersma @nojnhuh this is one where we need either ASO (#3529) or SDK v2 (#3409)  to be able to unblock it
