### ISSUE TITLE
Add unit tests for VM converter

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#2538]
/kind feature

**Describe the solution you'd like:** Add unit tests for [vm.go](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/converters/vm.go) in the converters package similar to the other converters.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sonasingh46** [comment]
@Jont828 -- There has already been a test that I wrote sometime back 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2166
( Lost track of it ) 
Just trying save ourselves from multiple efforts ( if at all )

**Comment by willie-yao** [comment]
@sonasingh46 Thanks for pointing this out! I am new to the project and didn't realize this has been done already, sorry about that. 
Would you be willing to take over this issue and continue working on #2166? If not, I can also work on it and credit you for any tests you've written already.

**Comment by sonasingh46** [comment]
@willie-yao -- No problem at all! I just wanted to make sure we do not repeat the efforts. Do not worry about credit and all. You go ahead and make the changes. I will close the PR in favour of yours.

**Comment by willie-yao** [comment]
@sonasingh46 Thank you so much! I'll take over the issue then. This is super helpful and I really appreciate it!
