### ISSUE TITLE
apiversion upgrade main test is broken

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2557]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

On 8/5, https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-apiversion-upgrade-main started failing with 

```
{ Failure /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.0/e2e/clusterctl_upgrade.go:147
Timed out after 180.004s.
Deployment capi-system/capi-controller-manager failed to get status.Available = True condition
```

This correlates to when CAPI was upgraded to v1.2.0:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/e13e1b4d3...9db52bed7?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
While looking into the test failure, I noticed we don't have a release branch test for this. Is there a scenario where we could break a release branch after its creation (we should assume that as long as we don't cut a release from main unless it's 100% green that it will ship w/ functional upgrade)?
