### ISSUE TITLE
error getting kubeconfig: failed to get client config for cluster: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#259]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Building from master following the steps in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/development.md

Results in:

```
I0814 14:32:22.631847   38129 getkubeconfig.go:62] error getting kubeconfig: failed to get client config for cluster: invalid configuration: no configuration has been provided
I0814 14:32:32.630141   38129 getkubeconfig.go:59] Waiting for kubeconfig on cluster-13-controlplane-0 to become ready...
```

Investigating...

**Environment:**

- cluster-api-provider-azure version: master (c79b9182ee425cf2d814e72339fa8f22ce1d9387)
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by justaugustus** [comment]
@CecileRobertMichon -- are you still having issues with this?

**Comment by CecileRobertMichon** [comment]
@justaugustus yes, I just retried this morning from a freshly rebased master branch and still getting the same error...
