### ISSUE TITLE
Remove KCP adoption test

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2596]
The below test was added to ensure existing clusters with control plane machines before KCP (KubeadmControlPlane) was introduced could be adopted by a KCP object: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/capi_test.go#L158

All new clusters should be using KCP for clusters built since ~ v1alpha4 so we should deprecate (remove) the test from the CAPI e2e test suite, and remove the associated e2e test templates (https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption) and all references to it.

**Comment by willie-yao** [comment]
@CecileRobertMichon would we want to remove [cluster-template-kcp-adoption.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/data/infrastructure-azure/v1beta1/cluster-template-kcp-adoption.yaml) and [cluster-with-kcp.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/data/infrastructure-azure/v1beta1/bases/cluster-with-kcp.yaml) as well?

**Comment by CecileRobertMichon** [comment]
@willie-yao yes

**Comment by willie-yao** [comment]
Update: we do not want to remove `cluster-with-kcp.yaml` as it is the basis for several other templates
