### ISSUE TITLE
[AKS] node labels update remove the AKS system labels

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#2603]
/kind bug

**What steps did you take and what happened:**
Node labels update can remove the AKS system labels on the agentpool

few features in AKS add some labels to the agentpool which do show up in `az aks nodepool show` call.

Such as Spot instance type. 

```
"nodeLabels": {
    "kubernetes.azure.com/scalesetpriority": "spot",
  },
```

Any update on those labels would remove the above-mentioned label added by AKS.

**What did you expect to happen:**

CAPZ to not to remove any label starting with `kubernetes.azure.com` 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version:
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
This was fixed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2604
