### ISSUE TITLE
Allow custom repositories for all container images

### ISSUE THREAD

**Issue by anthonsu** [kubernetes-sigs/cluster-api-provider-azure#2608]
/kind bug

There are 3rd party docker image repositories being found in capz clusters. Here is the list of images.

_docker.io/calico/cni:v3.23.0
docker.io/calico/kube-controllers:v3.23.0
docker.io/calico/node:v3.23.0
k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.1
k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller:v1.2.1
k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v1.2.1
k8s.gcr.io/coredns/coredns:v1.8.0
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/kube-apiserver:v1.21.10
k8s.gcr.io/kube-controller-manager:v1.21.10
k8s.gcr.io/kube-proxy:v1.21.10
k8s.gcr.io/kube-scheduler:v1.21.10
mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod10132021
mcr.microsoft.com/azuremonitor/containerinsights/ciprod:win-ciprod10132021
mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.8.9
quay.io/jetstack/cert-manager-cainjector:v1.8.2
quay.io/jetstack/cert-manager-controller:v1.8.2
quay.io/jetstack/cert-manager-webhook:v1.8.2
registry.k8s.io/cluster-api-azure/cluster-api-azure-controller:v1.4.1_

**What steps did you take and what happened:**
We created capz clusters and scanned the assets inside and found the images above.

**What did you expect to happen:**
Those 3rd party images/repositories may should be migrated to microsoft/azure ones.  

**Environment:**

- cluster-api-provider-azure version: 1.4.1
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-02-16T11:18:16Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): "Ubuntu 20.04.4 LTS"

**Comment by Michael-Sinz** [comment]
I would say that it may not be a "Microsoft/Azure" repository but maybe a "repository controlled/selected by the user"

We (Skyman) will need to be able to control the repository to be one of ours (or maybe a Microsoft one, but that may be tricky with things like AirGapped)

**Comment by CecileRobertMichon** [comment]
/retitle Allow custom repositories for all container images
