### ISSUE TITLE
Feature request - `Node` should have label of corresponding Virtual Machine resource id / VM name

### ISSUE THREAD

**Issue by grzesuav** [kubernetes-sigs/cluster-api-provider-azure#2610]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Each `Node`  in AKS cluster have corresponding VirtualMachine/ VirtualMachineScaleSet. This information should be exposed via label on the node object, to make it easy to identify the underlying resource in azure.

It would be needed to cross reference metrics from `Azure Metrics` portal with other metrics, exposed via i.e. `kube-state-metrics`. Currently, from azure metric we can get `VMName` dimension, which does not match node name.
Example:
- node name - `aks-001-xxxxx-vmss000046`
- VMName - `aks-001-xxxxx-vmss_150`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Similar info is in `spec.provider_id`, however there is FQRN which is not easy/possible to process by promQL query

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@grzesuav this information is available on the `Node` object spec as `ProviderID`

**Comment by grzesuav** [comment]
@CecileRobertMichon not really, it is fully qualified resource id, so it links to  `vmss` and `id` (as a number) of the virtual machine. There is no VM name there

**Comment by jackfrancis** [comment]
@grzesuav I think in the sense that you're talking about, there *is* no VM name associated with a VMSS instance. The "VMSS + instance" *is* the canonical unique reference to the underlying VM.

Sorry in advance if I'm misunderstanding things...

**Comment by CecileRobertMichon** [comment]
Side note: this might be a more appropriate issue for https://github.com/Azure/AKS/issues, as I imagine you'd want all AKS clusters to have that label, not just the ones built from CAPZ

**Comment by mboersma** [comment]
/close

@grzesuav please open this against AKS, where the change would be more appropriate.
