### ISSUE TITLE
Show resource diffs for AKS clusters in the capz-controller-manager logs when making updates

### ISSUE THREAD

**Issue by AAkindele** [kubernetes-sigs/cluster-api-provider-azure#2611]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**

1. Create an AKS cluster following the documentation <https://capz.sigs.k8s.io/topics/managedcluster.html>.
1. Increase the capz-controller-manager deployment log level from 0 to 5 by changing the `--v` flag.
1. After the cluster has been created, make a change to the cluster outside of Cluster API.
    - ex: Add tags, `environment=testing` to the AKS cluster from the Azure portal.
1. Make a change to the AzureManagedControlPlane configuration yaml so the changes are different from the ones made in the portal.
    - ex: Add tags. `environment=development`
1. Wait till Cluster API updates the cluster
1. Review the capz-controller-manager logs to see that there are no log entries showing the diff between tags.

**What did you expect to happen:**

When looking at capz-controller-manager logs, there should be log entries when diffs are identified between current AKS cluster state and target state.

**Anything else you would like to add:**

Example of expected log entries from a different Azure resource.
<https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/85c1951c4f1cfdec5fabb5b5a5b9a865082421f0/azure/services/agentpools/agentpools.go#L157>

**Environment:**

- cluster-api-provider-azure version: 1.4.1
- Kubernetes version: (use `kubectl version`): 1.22.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS

**Comment by nawazkh** [comment]
@AAkindele Can you talk more about point 4? 
> Make a change to the AzureManagedControlPlane configuration yaml so the changes are different from the ones made in the portal.
ex: Add tags. environment=development

What did you mean by _Add tags. environment=development_? Did you add it to the annotations or labels of  AzureManagedControlPlane manifest?

**Comment by AAkindele** [comment]
@nawazkh Apologies for the lack of details. I added the tags to AzureManagedControlPlane using `spec.additionalTags`.

Example below with most of the fields removed for brevity.

```yaml

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: capi-quickstart
spec:
  additionalTags:
    environment: development

```

**Comment by jackfrancis** [comment]
@AAkindele can you clarify that this is actually a feature request for additional log information (at a higher verbosity) rather than a bug with the way capz reconciles AzureManagedControlPlane tags?

**Comment by AAkindele** [comment]
> @AAkindele can you clarify that this is actually a feature request for additional log information (at a higher verbosity) rather than a bug with the way capz reconciles AzureManagedControlPlane tags?

Correct. This is a request for additional logs when a cluster is being updated. The AzureManagedControlPlane tags was just a way to trigger updates. But it could have been the cluster version, or anything else that would trigger an update to the cluster.
