### ISSUE TITLE
Windows nodes are failing to provision for multiple K8s version

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/cluster-api-provider-azure#2614]
/kind bug

[A clear and concise description of what the bug is.]
Suddenly Windows nodes in CAPZ clusters for many different versions of K8s stopped provisioning.
- https://testgrid.k8s.io/sig-windows-1.24-release#capz-windows-containerd-1.24
- https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-1.25
- https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master

This corresponds to a new set of Windows reference images being published to the CAPI/CAPZ Azure marketplace offer.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by marosset** [comment]
Discussed in https://kubernetes.slack.com/archives/C0SJ4AFB7/p1661950443766179

**Comment by marosset** [comment]
I think for mitigations we can either 
- Unpublish the most recent set of images to the Azur marketplace offer (preferred)
- Update the image selection logic in CAPZ to exclude the most recently published images

@CecileRobertMichon @jsturtevant @jackfrancis @mboersma - FYI

**Comment by CecileRobertMichon** [comment]
FYI for option 2 (Update the image selection logic in CAPZ to exclude the most recently published images
) this is the line that would need to be updated:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/dev/cluster-template-custom-builds.yaml#L361

Looks like all the jobs above are using a custom k8s version.

**Comment by CecileRobertMichon** [comment]
This is fixed and workaround was reverted https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2630

/close
