### ISSUE TITLE
Provide Ubuntu 22.04 support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/cluster-api-provider-azure#2619]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
AKS will support Ubuntu 22.04 very soon, does CAPZ has any plan to support Ubuntu 22.04? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@andyzhangx please move this issue to https://github.com/kubernetes-sigs/image-builder, CAPZ itself doesn't do anything special to support OS versions, it supports whatever OS the image is built with.

**Comment by andyzhangx** [comment]
thanks, filed an issue here: https://github.com/kubernetes-sigs/image-builder/issues/960
