### ISSUE TITLE
Create a branch for new v1alpha1 work

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#262]
https://github.com/kubernetes-sigs/cluster-api/blob/a3c9afc487b107b76d2ecf8a90ae3ff1c942b9c2/docs/developer/update-v1alpha1-provider-to-v1alpha2-infra-provider.md#create-a-branch-for-new-v1alpha1-work

@justaugustus are you able to do this? I don't have permissions to create a branch in the repo.

**Comment by justaugustus** [comment]
/assign
@CecileRobertMichon -- yep. Will execute on what we talked about next week.

**Comment by justaugustus** [comment]
`release-0.2` was created a while ago for this purpose, so we're good to close this.
/close
