### ISSUE TITLE
Allow users to create Service Endpoint(s) with VNET creation

### ISSUE THREAD

**Issue by mtougeron** [kubernetes-sigs/cluster-api-provider-azure#2621]
/kind feature

As part of the subnet creation inside of a CAPZ managed VNET it would be beneficial to users to be able to create [Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). Service Endpoints allow private connections to Azure services such as CosmosDB, ContainerRegistry, KeyVault and several others services. 

We propose that as part of an [AzureCluster.networkSpec.subnets[]](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-azure/infrastructure.cluster.x-k8s.io/AzureCluster/v1beta1@v1.3.2) a new optional field would be added called `serviceEndpoints`. This would be a list of endpoint names that would be validated against a valid list of endpoints. Based on the list in the new field, when a subnet is created, each Service Endpoint would be added to the subnet. 

As part of an [AzureManagedControlPlane.virtualNetwork.subnet](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-azure/infrastructure.cluster.x-k8s.io/AzureManagedControlPlane/v1beta1@v1.3.2) the same new optional field called `serviceEndpoints` would also be added. This would follow the same validation process as with AzureCluster.networkSpec.subnets[].serviceEndpoints. Each Service Endpoint defined would be added to the subnet created as part of the VNET created for AKS.

This feature would only apply when the VNET is managed by CAPZ. BYO VNET would not manage Service Endpoints.

Outstanding questions: 
- Would this require a new apiVersion even though it would be an optional field? 
- Can the list of Service Endpoints be programmatically found via an API call and pre-validated or does the list need to be hardcoded? Or do we rely on the API call to return success/failure for the validation?

/assign @mtougeron @jantzenallphin

**Comment by jantzenallphin** [comment]
Thanks @mtougeron for creating this feature request.

**Comment by jackfrancis** [comment]
@mtougeron quick question about the stated scope in the issue description:

Is the reason why this is not appropriate for BYO VNET because in those scenarios the various service endpoint configurations will have already have been defined? And maintaining those over time within the non-capz-managed VNET is something the user will continue to be able to do independently?

**Comment by mtougeron** [comment]
> @mtougeron quick question about the stated scope in the issue description:
> 
> Is the reason why this is not appropriate for BYO VNET because in those scenarios the various service endpoint configurations will have already have been defined? And maintaining those over time within the non-capz-managed VNET is something the user will continue to be able to do independently?

Correct. IMO if the user is already maintaining the Vnet/Subnet outside of CAPZ, they should maintain all aspects of the Vnet/Subnet outside of CAPZ. Otherwise we could end up in a situation where CAPZ and tool "z" both end up trying to reconcile the state based on different definitions.
