### ISSUE TITLE
Use kubescape security scan tests on all cluster tests

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2629]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Let's aim to decide whether or not the kubescape tests are generally useful in the upcoming release cycle. IMO just running them against one cluster scenario is an appropriate way to evaluate the cost/benefit of this add'l test dependency. But we don't get real value out of the signal (again, IMO) unless we're really running it against all of our tested scenarios.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by mboersma** [comment]
/close

This is closed by #2986. See also #2770 for discussion of kubescape in CAPZ.
