### ISSUE TITLE
Memory leak in the controller

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-azure#2639]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Deploy CAPZ `v1.3.2` and let it run for some time.
Memory leak in the controller even when there are no Azure/AKS clusters.

Here is a graph with just a single non-Azure/AKS cluster:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4969231/188995731-f732611a-c904-4d0c-b322-71fa3225df52.png">

A steeper graph when scaling to ~100 clusters (still 0 Azure/AKS clusters)
![image](https://user-images.githubusercontent.com/4969231/188995674-16a59960-f0f9-4cc9-8acb-df66401c5e0e.png)

**What did you expect to happen:**
The controller should be stable when there are no Azure/AKS clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I enabled pprof to capture some info, here is what it looked like when first starting up
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4969231/188996034-ed983b24-5341-4b74-8e61-a5f0bb143961.png">

And then again after a couple of hours:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/4969231/188996207-22acc02a-b74b-4c29-99ea-d9c62ef689c0.png">

**It pointed us to a potential culprit, a growing slice**:  https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/392137a94135a6995867d8c7fdfd56fabad719fc/util/tele/span_logger.go#L92

I added some debug logging on the length and capacity of that slice and after a few hours its >100,000 KV pairs.

---

A different view in pprof provided some more info on where to look:
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/4969231/188996738-b6515de6-5ad4-4dbf-95d2-d146445f5b79.png">

It doesn't give the exact function, but some hints towards https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/392137a94135a6995867d8c7fdfd56fabad719fc/controllers/azurecluster_controller.go#L88

Looks like the `log` is instantiated once when `SetupWithManager` is called in `main.go`
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/392137a94135a6995867d8c7fdfd56fabad719fc/controllers/azurecluster_controller.go#L73-L78

This is different from [how other providers setup their loggers ](https://github.com/kubernetes-sigs/cluster-api/blob/4cc2fce2111a14ad835ae835fdf8332fe15764ba/test/infrastructure/docker/controllers/dockercluster_controller.go#L53) and gets a new instance of it on every reconcile and does not have a growing slice of KV pairs.

**Environment:**

- cluster-api-provider-azure version:  `v1.3.2`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dkoshkin** [comment]
I thought that maybe the way the KVs are appeneded to the slice may be causing an issue in Go and tried a similar approach to how its done in https://github.com/kubernetes/klog/blob/02fe3234c86b222bc85406122bd0d11acbe5363a/internal/serialize/keyvalues.go#L39-L42

But that just leads to a spiky memory leak. Notice how the spikes happen every 10 minutes, on a periodic reconcile.
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/4969231/188998180-526722eb-548f-40e0-83ae-6435a103fb14.png">

All sings point to a bug in how the `log` gets reused and KVs are appended to it across multiple reconciles.

**Comment by mboersma** [comment]
@dkoshkin this is excellent (not that there's a leak, but that you did this profiling work)! 

I assume the problem exists in 1.4.2 and main as well, but when time permits I'll try `pprof` on that.

**Comment by jonathanbeber** [comment]
The problem still exists in `v1.7.1`

![Screenshot_2023-04-19_17-52-09](https://user-images.githubusercontent.com/8309341/233197987-06afca5f-1a80-4484-bd3e-052233caaf66.jpg)

**Comment by dtzar** [comment]
Matt couldn't reproduce this behavior and we are going to be doing extensive performance testing with https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3547
It has also been a long time since this issue has been opened (with numerous releases since then).
For these reasons, we're marking this as needs-more-evidence.

**Comment by dtzar** [comment]
I'd like to see if it still exists in the latest 1.10.x.  
I also need to ask - Is the load on CAPZ increasing over time by chance?  e.g. are you adding more clusters to manage over the course of a day?

**Comment by jonathanbeber** [comment]
@dtzar these deployment is not managing any CAPZ resource. I will test and report 1.10.x in a few days/weeks and report back.

**Comment by nawazkh** [comment]
> @dtzar this deployment is not managing any CAPZ resource. I will test and report 1.10.x in a few days/weeks and report back.

Hey @jonathanbeber , Did you get a chance to probe further. Or do you have any recommended steps in probing this issue so that we can take it over and check it ourselves?

**Comment by jonathanbeber** [comment]
I'm sorry, @nawazkh, I don't have any contact with CAPZ controllers anymore. You will be able to see the you by simply running the controller and having some metrics collector in place (e.g. prometheus + grafana).
