### ISSUE TITLE
Azure API calls: Rate Limiting and HTTP 429 backoff responses

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2645]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Let's introduce a set of standard interfaces that ensure we have reasonable rate limits in place for all Azure API calls, and that our we are properly sensitive to HTTP 429 'Retry-After' HTTP header responses from the Azure APIs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by mboersma** [comment]
/close

This turns out not to be needed because we have rate limiting in the SDK and a sane way to do this already in CAPI.
