### ISSUE TITLE
AKS Cluster must have at least one system pool unless it is being clusterctl-moved

### ISSUE THREAD

**Issue by h0tbird** [kubernetes-sigs/cluster-api-provider-azure#2656]
/kind bug

**What steps did you take and what happened:**

1.  Create a local `kind` cluster.
2. Set `EXP_MACHINE_POOL=true` and `EXP_AKS=true`.
3. `clusterctl init` with `--infrastructure azure`.
4. `clusterctl generate cluster` with `--flavor aks`.
5. Init the target cluster (same as 3).
6. `clusterctl move` from local `kind` to target AKS.
7. Notice the error below:
```
clusterctl -v 1 move -n little-sunshine --to-kubeconfig little-sunshine.kubeconfig --to-kubeconfig-context little-sunshine
Performing move...
Discovering Cluster API objects
Total objects Count=10
Moving Cluster API objects Clusters=1
Moving Cluster API objects ClusterClasses=0
Pausing the source cluster
Pausing the source cluster classes
Creating target namespaces, if missing
Creating Namespace="little-sunshine"
Creating objects in the target cluster
Creating AzureClusterIdentity="cluster-identity" Namespace="little-sunshine"
Creating Cluster="little-sunshine" Namespace="little-sunshine"
Creating AzureManagedCluster="little-sunshine" Namespace="little-sunshine"
Creating MachinePool="pool0" Namespace="little-sunshine"
Creating MachinePool="pool1" Namespace="little-sunshine"
Creating AzureManagedControlPlane="little-sunshine" Namespace="little-sunshine"
Creating AzureManagedMachinePool="pool1" Namespace="little-sunshine"
Creating Secret="little-sunshine-kubeconfig" Namespace="little-sunshine"
Creating AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting objects from the source cluster
Deleting AzureManagedMachinePool="pool1" Namespace="little-sunshine"
Deleting Secret="little-sunshine-kubeconfig" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Deleting AzureManagedMachinePool="pool0" Namespace="little-sunshine"
Error: action failed after 10 attempts: error deleting "infrastructure.cluster.x-k8s.io/v1beta1, Kind=AzureManagedMachinePool" little-sunshine/pool0: admission webhook "validation.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io" denied the request: if the delete is triggered via owner MachinePool please refer to trouble shooting section in https://capz.sigs.k8s.io/topics/managedcluster.html: AKS Cluster must have at least one system pool
```

**What did you expect to happen:**
I expect all `AzureManagedMachinePool` objects to be deleted from the local `kind` cluster and re-created in the target AKS cluster.

**Anything else you would like to add:**
Having zero system pools should be fine during `clusterctl move` operations.
Maybe the webhook can check wether the parent `cluster` object has the `spec.paused` set to `true`.
Or maybe `clusterctl move` should annotate the objects it is moving and then webhooks would honour that.
The error is raised [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/31c0c44a6c385e825363b6668b7e976cdb3e0ac9/exp/api/v1beta1/azuremanagedmachinepool_webhook.go#L266).

**Environment:**

- cluster-api-provider-azure version: `v1.5.0`
- Kubernetes version: (use `kubectl version`): `v1.25.0`

**Comment by pkbhowmick** [comment]
Hi @nawazkh, 
Is there any update on it?

**Comment by nawazkh** [comment]
I haven't been able to make much progress on this, although I was able to reproduce it locally. Will unassign myself for now if anyone wants to pick it up, or I will get back on this later on.

**Comment by pkbhowmick** [comment]
I am assigning it to me. I faced this issue locally and I think, I can give a try.

**Comment by CecileRobertMichon** [comment]
@jackfrancis @dtzar should we prioritize this for milestone v1.8? it's a known bug for AKS clusters with clusterctl move and would be good to get it fixed before graduation

**Comment by jackfrancis** [comment]
@CecileRobertMichon makes sense. Is this a bug w/ our docs or our default templates, or an actual bug? We should definitely do a thorough audit of the AKS documentation as part of this dev cycle as well as we should expect more usage following official graduation.

**Comment by CecileRobertMichon** [comment]
it's an actual bug (bug in validating webhook to be precise)
