### ISSUE TITLE
Enable CAPZ to deploy cluster on Azure Public MEC

### ISSUE THREAD

**Issue by mogliang** [kubernetes-sigs/cluster-api-provider-azure#2660]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I'd like to make CAPZ able to deploy cluster on [Azure Public MEC](https://azure.microsoft.com/en-us/solutions/public-multi-access-edge-compute-mec).

Since Azure Public MEC share same Azure RP with public azure, and azure api is exactly the same, the expected change is little:
 - Add _extendedlocation_ parameter when creating azure resources
 - Don't set AvailablityZone (public MEC don't have this feature yet)
 - Use Loadblancer outbound instead of NAT Gateway (public MEC don't have NAT gateway)
 - Use Out of tree cloud controller manager. (public MEC support is only added to OOT)
 - Add related Test

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

My workmate and I will submit PR for this feature, but not familiar with the community process, so just want to raise a feature request to let community know.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2660#tasklist-block-44e3d134-f6e2-4560-af5a-7c56b1890b3d

**Comment by hungry1526** [comment]
Hi there, is this the right process to make feature proposal to support Azure Public MEC? For this type of proposal, would it be better to join the office hour and discuss or submit the PR directly as the change will likely be small. Thanks.
