### ISSUE TITLE
Add resource health and service health in AzureManagedCluster status

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2673]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

AzureManagedCluster provides a way to create AKS clusters, but the health status of AzureManagedCluster CR can be improved by incorporating Resource Health Check & Service Health status that are already available for AKS clusters on Azure.

Resource Health documentation: https://docs.microsoft.com/en-us/azure/service-health/resource-health-overview
Service Health documentation: https://docs.microsoft.com/en-us/azure/service-health/service-health-overview
Service Health (Events) API: https://docs.microsoft.com/en-us/rest/api/resourcehealth/events/list-by-single-resource#events

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
A couple questions I have as I'm getting acquainted with these health services:
- At a high level, what information do we want to expose in CAPZ? It looks like the API exposes "availability statuses," "emerging issues," "events," "metadata," and "operations." I haven't taken a deep dive to figure out exactly what each of those means yet, but some guiding principles for what we want would be helpful to have in mind as I learn more.
- It looks like there's a way to wire up events to webhooks and [similar async mechanisms](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-common-schema-integrations). Is that something we could reasonably fit in CAPZ and would prefer over polling the Azure API for that data?

**Comment by dtzar** [comment]
The resource health is completed by #2738, but the service health has not been started.  Can we please separate this work into two issues for tracking/prioritization purposes?

**Comment by CecileRobertMichon** [comment]
opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3001

/close
