### ISSUE TITLE
E2E test scripts should not edit files outside of gitignore

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#2681]
/kind feature
**What steps did you take and what happened:**
1. Run the E2E test script `./scripts/ci-e2e.sh`.
2. Observe that files `manager_pull_policy.yaml` and `manager_image_patch.yaml` in `config/default` have been changed automatically.

**What did you expect to happen:**
The test script should not edit files that can be committed. This results in many unintended changes to be committed, and some of these changes break the Tilt environment as well as other clusters when ran locally.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: v1.5.1
- Kubernetes version: (use `kubectl version`): v1.24.4
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by mboersma** [comment]
/remove-lifecycle stale

We should still fix this. I've mistakenly committed these files twice this month, and I know better.

**Comment by CecileRobertMichon** [comment]
@willie-yao is this done or close to done now that we have https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L220 ?

**Comment by willie-yao** [comment]
@CecileRobertMichon This is still happening as `make clean-release-git` is only ran in `verify-container-images.sh`. I'll see if I can include this in the `ci-e2e.sh` script.
