### ISSUE TITLE
Documentation topics should be in alphabetical order

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#2685]
/kind feature

**Describe the solution you'd like**
In the CAPZ documentation, the topics [summary](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/SUMMARY.md) aren't listed in a consistent format. Some topics follow an alphabetical order while others do not. These should be re-organized to be in alphabetical order.

**Comment by ritesh-karankal** [comment]
Hello @willie-yao,
I would like to work on this.
Are the below topics in the correct order?

AAD Integration
API Server Endpoint
Cloud Provider Config
Control Plane Outbound Load Balancer
Custom Images
Custom Private DNS Zone Name
Data Disks
Dual-Stack
Externally managed Azure infrastructure
Failure Domains
Flannel
Getting Started
GPU-enabled Clusters
Identity use cases
IPv6
Machine Pools (VMSS)
Managed Clusters (AKS)
Multitenancy
Node Outbound Load Balancer
OS Disk
Spot Virtual Machines
SSH Access to nodes
Troubleshooting
Virtual Networks
VM Identity
Windows

**Comment by willie-yao** [comment]
@ritesh-karankal Thanks for working on this! One thing is that we want to keep "Getting Started" and "Troubleshooting" as the first two topics, then sort the rest alphabetically. Besides that it looks good. I wasn't super clear on that and that's on me!
