### ISSUE TITLE
Change `AzureManagedControlPlane.ResourceGroupName` to `AzureManagedControlPlane.ResourceGroup`

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2701]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

As a user I would like to have the declarative interface define a consistent configuration property for "Azure resource group".
As a maintainer I would like to maintain similar configuration across the type system using a consistent naming convention.

**Detailed Description**

[A clear and concise description of what you want to happen.]

Updating the `AzureManagedControlPlane` type definition will be a breaking change for existing users, and should be coordinated and announced accordingly.

**Contract changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

No changes.

**Data model changes [optional]**

`AzureManagedControlPlane.ResourceGroupName` becomes `AzureManagedControlPlane.ResourceGroup`

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

/kind proposal

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle stale

@jackfrancis this one is a breaking change, is it something we want to get done before graduation or should it wait for a new API version?

**Comment by jackfrancis** [comment]
I think the practical benefit of making this change doesn't meet the requirements we'd want for interrupting the AKS API graduation timeline.

Do we want to keep this in the backlog as a TODO for considering when v2 is under development?
