### ISSUE TITLE
DOCS

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#271]
1) Contribute to capi book
2) first time user guide
3) first time contributor guide
    - including how to build from master, something like: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/275#issuecomment-536118064

**Comment by keksdutcheks** [comment]
### **_-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEhuZ5L8J7/UeIYMEQkfOzObmgKj0FAlzZW+sACgkQkfOzObmg
Kj0kxQ/8DDxOeR7BLUOk5Q/qd95LQltuEXxHsc5HWWpwIE/HLE3mBcdvPrrkb6GX
gRH1HSD5baT9bsxf0F6O4QJhnsW7shepgPfJgPvuUciz4tkAEYwI7aBI+61x6Uby
jdbV6bzlQpnZsyqfw/Q2ra4q82yzqIxx8V0FGkbW6VRLTXDCUPrny5czS7BJ7fdB
JciSFDG3PcXK7Q+dCpGvHm15aGgQZqaKOpJPKWVmaZBDy6V4Yo0x4uchPmSCuv2T
qjP0+iPYRCXsRK01UHxh6b7JIwV2HpQiJVLpTiikmCoUyI1m+ZwgCxSy+NiTwlCe
mFMfP3zKbmY3vmSfo93HRRzdMIL5396FtJwo9YfnB4HOheycpKJe6U1wRuDLyrF/
oD9cjEHcyxR/S7suqVOKofFNG4QwEDZrirWf43OL++iBVXfuAVcueeAUfUJMs/GX
zWMqw6xkTVAB5DCZoRFrc3s/amLvUwSB7+AWeAyXo14ct5qYi74odJrEMgUXq1HK
3D/by6DExSwmhR43Il51JhhuP4kxbeAOOgQ7+nIp0XUBOuB3b2m4sK/DDQhFm8zE
t5TF/rvnJoSQR5g/R1zs1thd37sbuet5wvJTMQlnl5K+xZvacSNCGN8r9E4+lv0e
kU7vY7sBj10kfEHjfgcTleehBtM1MZ/73xfr5yIYs8TIXJNfUTw=
=Xd9P
-----END PGP SIGNATURE-----###_**

**Comment by nader-ziada** [comment]
some issues in getting started page https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/338

**Comment by rbitia** [comment]
@CecileRobertMichon Do you think we are good to close this issue?

**Comment by CecileRobertMichon** [comment]
yes, we can open more specific issues on missing docs from now on.

/close
