### ISSUE TITLE
AzureManagedCluster: upgrade control planes first

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2713]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

At present you can initiate discrete upgrade operations against the AzureManagedControlPlane (which updates the version of Kubernetes that the AKS managed control plane runs) or individual MachinePools (which updates the version of Kubernetes that nodes in that pool run).

The official kubeadm docs suggest that the recommended order is to update the control plane, and then the worker nodes. Ref:

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

We should add a webhook validation that doesn't allow you do update a MachinePool's version property (in an AzureManagedCluster cluster) to a version of Kubernetes greater than the version configured on the AzureManagedControlPlane.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by zmalik** [comment]
@jackfrancis would this be a CAPI issue or CAPZ? unless I'm missing something

**Comment by jackfrancis** [comment]
@zmalik good point, I hadn't thought that there's an abstraction jump here (making a capi webhook that is dependent upon a capz resource)

This probably needs more thought....
