### ISSUE TITLE
async scalesetvms refactor

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2720]
We should refactor the scalesetvms service to reuse the async.go framework instead of using its own implementation.

This might need to wait until https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/999 is done first so it doesn't interfere.

**Comment by Jont828** [comment]
@CecileRobertMichon @mboersma I'm thinking I can get started on this now that #3111 is done and ready for final review/merge.
