### ISSUE TITLE
add support for linux OS configuration  for managed nodepools [AKS]

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#2724]
/kind feature

**Describe the solution you'd like**
Add support for the linuxOS Configuration in `AzureManagedMachinePool`.

This can help to create custom OS configuration which AKS already allows to its users.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by juanmaia** [comment]
Hey @nawazkh, what's the status of this feature?

**Comment by nawazkh** [comment]
Hi @juanmaia! It's in the works, will try to raise a PR soon.
