### ISSUE TITLE
v1alpha2 E2E tests

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#274]
To get started, look at https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1122

Also talk to @vincepri about participating in v1alpha3 testing framework proposal.

**Comment by miknoj** [comment]
Hello, I would really like to start contributing and I believe this maybe a good area to start doing so. I have taken the step of trying to spin up a cluster following the developer docs, but they maybe out date. I also tried to followed the steps highlighted in this comment https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/275#issuecomment-536118064 but I maybe missing some dependencies for it failed. Therefore, are there any pointers on how to spin up a v1alpha2 cluster so that I could start work on automating it for testing?

**Comment by CecileRobertMichon** [comment]
Hi @miknoj! Would love to help you get started on contributing. Apologies for the lack of/outdated docs, the repo is still in the middle of the v1alpha2 refresh and [docs](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/271) are in progress.

I'd encourage you to join the k8s Slack [cluster-api-azure channel](https://kubernetes.slack.com/messages/CEX9HENG7) if you're not already in it so you can chat with other contributors and ask quick questions.

In terms of spinning up a cluster, these steps from master should work:

```
export CLUSTER_NAME=$1
export VNET_NAME=$CLUSTER_NAME-vnet

echo "Creating cluster $CLUSTER_NAME..."
export AZURE_LOCATION=<location>
export AZURE_RESOURCE_GROUP=$CLUSTER_NAME
export AZURE_TENANT_ID=<your_tenant_id> 
export AZURE_CLIENT_ID=<your_client_id> 
export AZURE_SUBSCRIPTION_ID=<your_sub_id>
export AZURE_CLIENT_SECRET=<your_client_secret>
export REGISTRY=<your_registry_name
export MANAGER_IMAGE_TAG="dev" // you can rename this if you want

echo "================ DOCKER BUILD ==============="
make docker-build
echo "================ DOCKER PUSH ==============="
make docker-push

echo "================ MAKE CLEAN ==============="
make clean

echo "================ MAKE MANIFESTS ==============="
make generate-manifests
make generate-examples
echo "================ MAKE BINARIES ==============="
make binaries
echo "================ KIND RESET ==============="
make kind-reset

echo "================ CREATE CLUSTER ==============="
make create-cluster-management
```

(note that `make create-cluster` is broken at the moment so only  `make create-cluster-management` will work). If that's still not working, let me know what error(s) you're running into and we can take it from there.

**Comment by miknoj** [comment]
Hey @CecileRobertMichon I was able to successfully get a build to complete and have reviewed kubernetes-sigs/cluster-api-provider-aws#1122. I believe I'm good to go and give this a shot. I will ask questions on the slack if any.
/assign

**Comment by CecileRobertMichon** [comment]
@miknoj any progress on this?

**Comment by CecileRobertMichon** [comment]
/unassign
/assign @jadarsie 

Javier is interested in helping out with this, re-assigning to him.

**Comment by miknoj** [comment]
Hey @CecileRobertMichon, apologies for dropping the ball on this one. Got quite a bit busy these past few weeks. I will go ahead and unassign myself.
/unassign

**Comment by CecileRobertMichon** [comment]
No worries @miknoj! Feel free to pick up another issue whenever you have time.

**Comment by jadarsie** [comment]
WIP branch here, in case someone wants to peek
https://github.com/jadarsie/cluster-api-provider-azure/commits/e2e

**Comment by nader-ziada** [comment]
@CecileRobertMichon we can probably close this issue now that there are specific issues about e2e tests, wdyt?
