### ISSUE TITLE
Switch GPU tests and defaults off NV-series SKUs

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#2756]
/kind bug

**What steps did you take and what happened:**

The current `Standard_NV6` SKU in use for GPU tests will be retired on August 31, 2023. See https://learn.microsoft.com/en-us/azure/virtual-machines/nv-series

We should switch to `Standard_NV12s_v3` as suggested in the migration guide.

This will involve mostly behind-the-scenes work ensuring quota for the CNCF account that is used in testing; I just wanted to point this out as an issue that will require some work soon.

**Comment by mboersma** [comment]
/remove-lifecycle stale

This still needs to happen before August 31, 2023.

**Comment by willie-yao** [comment]
@mboersma Thanks for taking a look at this! Would it be better to tag this as cleanup instead of a bug?

**Comment by mboersma** [comment]
For reference, the latest email from Azure:

## The Azure NV6, NV6_Promo, NV12, NV12_Promo, NV24, NV24_Promo Virtual Machine sizes will be retired on 31 August 2023

*You're receiving this email because you've been a user of NV and NV_Promo Azure virtual machines within the last 12 months.*

As Azure NVsv3 and NVv4 virtual machines have right sized VMs from entry level Virtual Desktop Infrastructure (VDI) with GPU partitioned sizes to medium and high end VDI with better CPU/memory ratio, larger and faster local solid-state drives (SSDs), support for premium and ultra SSDs, and better cost/performance across a broad variety of visualization workloads, **we're retiring our NV-series Azure Virtual Machine sizes on 31 August 2023.**

After 31 August 2023, any remaining NV and NV_Promo size virtual machines subscriptions will be set to a deallocated state, will stop working, and will no longer incur billing charges.

*Note: This VM size retirement only impacts the VM sizes in the NV and NV_Promo series. This retirement announcement does not impact the newer NVv3 and NVv4 series virtual machines.*

### Required action

**We're retiring NV and NV_Promo VMs on 31 August 2023.** All NV and NV_Promo VMs will need to be de-allocated by that date. For recommendations on which VMs to migrate your NV and NV_Promo workloads to or for the creation of net new VMs, please see this [migration guide](https://learn.microsoft.com/azure/virtual-machines/nv-series-migration-guide). Visit the [Azure Virtual Machine pricing page](https://azure.microsoft.com/pricing/details/virtual-machines/linux/) for additional information.

**Comment by mboersma** [comment]
I requested a quota increase but was denied, so I opened a support ticket.
