### ISSUE TITLE
Question about Azure flexible VM scale sets

### ISSUE THREAD

**Issue by FreebeJan** [kubernetes-sigs/cluster-api-provider-azure#2758]
/kind feature

**Describe the solution you'd like**
Currently we have multiple node pools for spot and non-spot instances. 
Mostly the spot instances are good enough for us, only to have a controllable guaranteed number of nodes no matter what the spot capacity/price currerntly is we use multiple pools.
We were wondering if in our case we could use flexible vmss to simplify our setup, e.g. having only one node pool in Kubernetes for both spot and normal instances.

Are flexible vmss supported?

**Comment by CecileRobertMichon** [comment]
@mboersma

**Comment by mboersma** [comment]
Supporting VMSS Flex in cluster-api-provider-azure is something we're actively working on, but it's not available yet. Spot instance support should work as [documented](https://capz.sigs.k8s.io/topics/spot-vms.html). The only restriction I see in the [flex docs](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes?WT.mc_id=modinfra-31635-pierrer#scale-sets-with-flexible-orchestration) is `instances must either be all Spot or all Regular`.

**Comment by dtzar** [comment]
@FreebeJan - are your questions answered on this issue?  We should have VMSS support in the upcoming 1.7 release.

**Comment by CecileRobertMichon** [comment]
/close

please reopen if help is still needed
