### ISSUE TITLE
Documentation bug in Public IP section of API Server Endpoint

### ISSUE THREAD

**Issue by karansinghneu** [kubernetes-sigs/cluster-api-provider-azure#2780]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
They value of the key should be "dnsName" and not "dns"
https://capz.sigs.k8s.io/topics/api-server-endpoint.html
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  location: eastus
  networkSpec:
    apiServerLB:
      type: Public
      frontendIPs:
        - name: lb-public-ip-frontend
          publicIP:
            name: my-public-ip
            dns: my-cluster-986b4408.eastus.cloudapp.azure.com

**What did you expect to happen:**
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  location: eastus
  networkSpec:
    apiServerLB:
      type: Public
      frontendIPs:
        - name: lb-public-ip-frontend
          publicIP:
            name: my-public-ip
            dnsName: my-cluster-986b4408.eastus.cloudapp.azure.com

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by CecileRobertMichon** [comment]
The value of the key should be "dnsName" and not "dns"
https://capz.sigs.k8s.io/topics/api-server-endpoint.html

/good-first-issue
