### ISSUE TITLE
Quick Start for Azure does not work

### ISSUE THREAD

**Issue by sshiba** [kubernetes-sigs/cluster-api-provider-azure#2785]
When following the instructions provided in [Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html) it fails to start the deployment of a Target cluster. 
Note that I double/triple check the value in the secret containing the Service Principal's client secret. Also verified that AzureClusterIdentity values are correct.

The logs for the capz-controller-manager shows the following error:

`E1107 20:49:33.111285       1 controller.go:326]  "msg"="Reconciler error" "error"="failed to reconcile cluster services: failed to get availability zones: failed to get zones for location eastus: failed to refresh resource sku cache: could not list resource skus: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c40bd3d2-e0e6-429c-80ae-e0df34b79efd/providers/Microsoft.Compute/skus?%24filter=location+eq+%27eastus%27&api-version=2021-07-01&includeExtendedLocations=true: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4994bf43-12d2-4704-bcb1-8ea0095687a5'.\\r\\nTrace ID: 75f4f402-9ae7-47c7-b70c-72d8545ba000\\r\\nCorrelation ID: 8e288d37-bde6-484b-b186-16c0f62bd486\\r\\nTimestamp: 2022-11-07 20:49:33Z\",\"error_codes\":[7000215],\"timestamp\":\"2022-11-07 20:49:33Z\",\"trace_id\":\"75f4f402-9ae7-47c7-b70c-72d8545ba000\",\"correlation_id\":\"8e288d37-bde6-484b-b186-16c0f62bd486\",\"error_uri\":\"https://login.microsoftonline.com/error?code=7000215\"} Endpoint https://login.microsoftonline.com/8413b9b0-c4ad-4d81-8e90-927130e9c797/oauth2/token?api-version=1.0" "azureCluster"={"name":"sidney-cluster-eastus","namespace":"default"} "controller"="azurecluster" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureCluster" "name"="sidney-cluster-eastus" "namespace"="default" "reconcileID"="e67efbc3-e841-48e4-bcd7-7fe62ae99648"`

How to reproduce it:
1.  Followed the [pre-requisites instructions](https://capz.sigs.k8s.io/topics/getting-started.html#prerequisites) for Azure infrastructure.
  - az login --tenant <my tenant id>
  - selected the account using `az account set -s <my subscription id>`
  - created an Azure Service Principal with a `contributor` role
  - set the environment variables required for the Azure infrastructure
2. Created a Kind cluster
3. From [The Cluster API Book](https://cluster-api.sigs.k8s.io/user/quick-start.html#initialization-for-common-providers)
  - Set the environment variables for AzureClusterIdentity
  - Created the Secret with client-secret 
     `kubectl create secret generic "${AZURE_CLUSTER_IDENTITY_SECRET_NAME}" --from-literal=clientSecret="${AZURE_CLIENT_SECRET}" --namespace "${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}"`
  - The executed `clusterctl init --infrastructure azure`
4. Set environment variables for Azure as describe [here](https://cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers)
5. Generated the Cluster configuration for Azure
    ```clusterctl generate cluster capi-quickstart \
  --kubernetes-version v1.25.0 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml
```
6. Applied the generated `capi-quickstart.yaml`
7. Monitored the logs for the capz-controller-manager `kubectl logs deploy/capz-controller-manager -n capz-system manager`

**Comment by dtzar** [comment]
@sshiba - I just went through the entire quick start guide from scratch trying to use all of the same values (including using kind) and didn't experience this issue.  It does seem that the service principal doesn't have the appropriate permissions.  Have you tried using a new service principal on a different subscription perhaps?  Tried to reset and update the password using `az ad sp credential reset --id <AZURE_CLIENT_ID>`?
