### ISSUE TITLE
[Feature] Export azure sdk ratelimit metric

### ISSUE THREAD

**Issue by grzesuav** [kubernetes-sigs/cluster-api-provider-azure#2790]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I would like to have idea how much of Azure API ratelimit request CAPZ is using to be able to monitor those and avoid throttling - https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling on Azure side

**Comment by dtzar** [comment]
@nojnhuh - this is very related to performance testing and the ASO work you're doing.

/remove-lifecycle rotten

**Comment by nojnhuh** [comment]
Thanks @dtzar, this will definitely be affected by the ASO transition proposed in #3113. I don't see any Azure SDK-related metrics exposed for Prometheus, but each call is recorded in OpenTelemetry traces with names that look like `*.AzureClient.*`, e.g. `virtualmachines.AzureClient.CreateOrUpdate`. Once ASO is being used for a particular Azure service, ASO will expose Prometheus metrics as described here: https://azure.github.io/azure-service-operator/introduction/metrics/

Even before we have ASO though, it would be good to expose the same SDK metrics without ASO so we have a decent comparison to help evaluate our ASO integration.
