### ISSUE TITLE
Unable to delete machines "ForceDelete" is not allowed

### ISSUE THREAD

**Issue by ericgoode** [kubernetes-sigs/cluster-api-provider-azure#2792]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](`)?]

Yes

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When scaling down a MachineDeployment in UsGovCloud the Machine delete fails with the following error:

E1108 19:18:11.732526       1 controller.go:317] controller/azuremachine "msg"="Reconciler error" "error"="error deleting AzureMachine default/xxxxxx-gpu-0-kfm9k: failed to delete AzureMachine service virtualmachine: failed to delete resource xxxxxx/xxxxxx-gpu-0-kfm9k (service: virtualmachine): compute.VirtualMachinesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"OperationNotAllowed\" Message=\"Operation 'ForceDelete' is not allowed on resource 'xxxxxx-gpu-0-kfm9k' since it manages updates using maintenance control.\"" "name"="xxxxxx-gpu-0-kfm9k" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine"

The key here being "since it manages updates using maintenance control"

**What did you expect to happen:**

VM to delete gracefully and machinedeployment to scale correctly

or

include configuration option to AzureMachineTemplate to disable the maintenance control.

**Anything else you would like to add:**

It's possible that this configuration is available and I just cannot find it. If that is the case the issue could be worked as a documentation issue.

This worked fine until a short time ago. Not totally sure on the dates because we didn't scale down that node pool for awhile.

**Environment:**
AzureGovCloud
Ubuntu 20.04

cluster-api-azure-controller:v1.3.1
K8s 1.22.7

**Comment by axelgMS** [comment]
This error message can happen when the ForceDelete is issued against VMs using Azure Dedicated Hosts or Isolated sizes.
- https://learn.microsoft.com/en-us/azure/virtual-machines/dedicated-hosts
- https://learn.microsoft.com/en-us/azure/virtual-machines/isolation

And it's expected. 
Solution would be to handle the error and fallback to a standard Delete

**Comment by ericgoode** [comment]
If I know that these machines are in use with this machine type, can I designate the standard Delete from the start somewhere?
