### ISSUE TITLE
CAPZ Office Hours doesn't show on k8s community calendar

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#2806]
/kind bug

**What steps did you take and what happened:**

When we changed CAPZ Office Hours to weekly at 9 PT, we made what appeared to be the correct change in kubernetes/community: kubernetes/community#6821.

However, I don't see the meeting on the Kubernetes [community calendar](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk%40group.calendar.google.com).

**Comment by nawazkh** [comment]
I am following the guidelines mentioned in https://github.com/kubernetes/community/blob/master/communication/calendar-guidelines.md to create a _SIG CAPZ Shared Calendar_. 
I'm wondering if we have a _SIG/WG lead mailing list_ or can I add the leads individually?

**Comment by nawazkh** [comment]
> I'm wondering if we have a SIG lead mailing list or can I add the leads individually to grant them full rights to the calendar ("make changes and manage sharing”)?

- Created a Shared Calendar. Made it public.
- Shared the calendar with @mboersma @jackfrancis @CecileRobertMichon with full access rights. Added contributors@kubernetes.io with full access rights too as directed in the docs.
- added kubernetes-sig-cluster-lifecycle@googlegroups.com to with access: "view all the events".
- Created a CAPZ meeting in the shared calendar. 

I still dont see the event on the [community calendar](https://calendar.google.com/calendar/u/0/embed?src=calendar@kubernetes.io&ctz=America/Los_Angeles). Not sure what could be going wrong.

**Comment by CecileRobertMichon** [comment]
Only the SIG leads have access to the calendar AFAIK, you can reach them in Slack on `#sig-clstr-life-leads`

**Comment by nawazkh** [comment]
CAPZ office hours appears to be added to the community calendar and is now visible on the Kubernetes.io calendar too. 
- [K8s contributor calendar](https://calendar.google.com/calendar/u/0/embed?src=cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com&pli=1)
- [Kubernetes.io calendar](https://calendar.google.com/calendar/u/0/embed?src=calendar@kubernetes.io&ctz=America/Los_Angeles)
<img width="1728" alt="Screenshot 2022-11-14 at 2 11 48 PM" src="https://user-images.githubusercontent.com/25679594/201778860-d522f86f-594a-4747-ae66-e749c8a67785.png">

/close
