### ISSUE TITLE
Implement outboundType in `AzureManagedControlPlane`

### ISSUE THREAD

**Issue by zioproto** [kubernetes-sigs/cluster-api-provider-azure#2810]
/kind feature

The current `AzureManagedControlPlaneSpec ` is missing the `outboundType` and currently all clusters created with CAPZ have `outboundType` `loadBalancer` because that is the default value:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9c12ff0fff94eca19a78dc18382e8d9acf0f4cf7/exp/api/v1beta1/azuremanagedcontrolplane_types.go#L39

Here is the REST API spec for `outboundType`:
https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP#outboundtype

Currently is not possible with CAPZ to create clusters with the values:
 * managedNATGateway	
 * userAssignedNATGateway	
 * userDefinedRouting	

Here is the relevant AKS configuration:
https://learn.microsoft.com/en-us/azure/aks/egress-outboundtype

This was referenced in the past in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1159
but as a result of that issue only the `LoadBalancerProfile` was implemented, that is just the detailed configuration for `outboundType` `loadBalancer`

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9c12ff0fff94eca19a78dc18382e8d9acf0f4cf7/exp/api/v1beta1/azuremanagedcontrolplane_types.go#L163

**Comment by nawazkh** [comment]
/assign

@zioproto Did you mean to put a different URL for `REST API spec for outboundType` in your description above? 
> Here is the REST API spec for outboundType:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues

**Comment by zioproto** [comment]
Thanks for spotting the cut and paste error, the correct link is:
https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP#outboundtype

**Comment by nawazkh** [comment]
Hi @zioproto ! Sorry, I haven't been active on this issue, but this has not slipped out of my radar. I will update as I make progress!

**Comment by nawazkh** [comment]
Sorry @zioproto , I haven't been making much progress on this! Thanks @jackfrancis for taking over !

**Comment by jackfrancis** [comment]
@zioproto FYI looks like this was done in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3046 and is released starting w/ v1.8.0. Lemme know if there's more to do here!

Thanks @bmiguel-teixeira!
