### ISSUE TITLE
"failed to find events of Pod xx" errors show up repeatedly in test logs

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#2815]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Seeing repetitive lines in the logs saying `failed to find events of Pod` in the [capz-periodic-e2e-test](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main) tests. 
  - For instance, a green 🟢 run of [periodic-cluster-api-provider-azure-e2e-main.Overall](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1592571805900476416) has a couple of `failed to find events of Pod xxx`. 
  - The same can be observed in a green 🟢 run of [capz-e2e.Workload cluster creation Creating a private cluster [OPTIONAL] Creates a public management cluster in a custom vnet](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1592571805900476416/build-log.txt)

**What did you expect to happen:**
- Expect to not see such errors in the test logs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- N/A

**Environment:**

- cluster-api-provider-azure version: `v1.4.0`
- Kubernetes version: (use `kubectl version`): `v1.22.4`
- OS (e.g. from `/etc/os-release`): `linux`

**Comment by willie-yao** [comment]
@nawazkh Is this still an issue? I checked the last few runs of the E2E periodic test and didn't find any logs with `failed to find events of Pod`

**Comment by nawazkh** [comment]
> @nawazkh Is this still an issue? I checked the last few runs of the E2E periodic test and didn't find any logs with `failed to find events of Pod`

Yeah you are right, I dont see them either. We can close this issue out. 
/close
