### ISSUE TITLE
Tilt environment does not work for FeatureGates

### ISSUE THREAD

**Issue by primeroz** [kubernetes-sigs/cluster-api-provider-azure#2831]
/kind bug

When using the Tilt environment through `make tilt-up` the capi-controller-manager is initially started with the featureflags enabled 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L703

But , for reasons i am yet to fully understand, when the `capi-visualizer` is started a patch of the `capi-controller-manager` happens which not only upgrades `cluster-api` to 1.2.5 but also change the featureflags to false. 
the capi-visualizer `clusterctl` usage must be triggering the `Upgrade` functions even though i was not able to track it down yet.

I opened an issue in the capi-visualizer https://github.com/Jont828/cluster-api-visualizer/issues/13

This is an issue when trying to develop anything like MachinePool that require the featureflag to be enabled both on the CAPI and the CAPZ controllers

at the moment my only solution is to restrict the clusterrole being used by the `capi-visualizer` which is an all powerful cluster-role 

**What steps did you take and what happened:**

* enable `EXP_MACHINE_POOL: "true"` in `tilt-settings.yaml` `kustomize_substitutions` section for CAPZ
* make tilt-up

in a separate terminal do 

* while true; do kubectl get -n capi-system deployment capi-controller-manager -o json | jq '.spec.template.spec.containers[0] | .image,.args'; done
* watch the flags and version of cluster-api-controller change when capi-visualizer is started 
  * you can exclude all other components of the `observability` function in Tiltfile to isolate the issue

---

**pre capi-visualizer** 
```
"k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.4"                                                   
[                                      
  "--leader-elect",                                                                                      
  "--metrics-bind-addr=localhost:8080",
  "--feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=false,RuntimeSDK=false"      
]
```

**post capi-visualizer**
```
"registry.k8s.io/cluster-api/cluster-api-controller:v1.2.5"
[
  "--leader-elect",
  "--metrics-bind-addr=localhost:8080",
  "--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false"
]
```

**What did you expect to happen:**

capi-visualizer should not trigger an update of the CAPI control-plane . 

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by primeroz** [comment]
I create a PR to the upstream chart https://github.com/Jont828/cluster-api-visualizer/pull/14 , if that gets approved i will just update the chart embedded in this repo rather than making an override here

**Comment by CecileRobertMichon** [comment]
cc @Jont828

**Comment by zioproto** [comment]
I confirm the bug, I was not able to apply a `MachinePool` after `make tilt-up`:

```
k apply -f - <<EOF
heredoc> ---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: pool1
  namespace: default
spec:
  clusterName: test
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pool1
      version: 1.23.12
heredoc> EOF
Error from server (spec: Forbidden: can be set only if the MachinePool feature flag is enabled): error when creating "STDIN": admission webhook "validation.machinepool.cluster.x-k8s.io" denied the request: spec: Forbidden: can be set only if the MachinePool feature flag is enabled
```



and I confirm that the following workaround unblocked me:

```
diff --git a/Tiltfile b/Tiltfile
index 05aedabf..03c88183 100644
--- a/Tiltfile
+++ b/Tiltfile
@@ -148,14 +148,6 @@ def observability():
     ))

     internal_kubeconfig = str(local(kind_cmd + " get kubeconfig --name ${KIND_CLUSTER_NAME:-capz} --internal"))
-    k8s_yaml(helm(
-        "./hack/observability/cluster-api-visualizer/chart",
-        name = "visualize-cluster",
-        namespace = "capz-system",
-        set = [
-            "kubeconfig=" + internal_kubeconfig,
-        ],
-    ))

     k8s_resource(
         workload = "jaeger-all-in-one",
@@ -173,12 +165,6 @@ def observability():
     )
     k8s_resource(workload = "opentelemetry-collector", labels = ["observability"])
     k8s_resource(workload = "opentelemetry-collector-agent", labels = ["observability"])
-    k8s_resource(
-        workload = "capi-visualizer",
-        new_name = "visualize-cluster",
-        port_forwards = [port_forward(local_port = 8000, container_port = 8081, name = "View visualization")],
-        labels = ["observability"],
-    )

     k8s_resource(workload = "capz-controller-manager", labels = ["cluster-api"])
     k8s_resource(workload = "capz-nmi", labels = ["cluster-api"])
```
