### ISSUE TITLE
AzureManagedCluster E2E: node pool NodeLabels CRUD tests

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#2859]
/kind feature
/area managedclusters

**Describe the solution you'd like**
Create new AzureManagedCluster E2E: node pool NodeLabels CRUD tests.

**Comment by nojnhuh** [comment]
While testing this manually, I noticed that when any labels are defined for a node pool, deleting all of them from the spec doesn't change anything in AKS. This seems like similar behavior to the autoscaler profile as discussed in this thread: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2838#discussion_r1060830001. It's possible to make changes in the controller to make deleting all labels possible, but then that presents the same issue as discussed in that thread where existing labels managed outside CAPZ would be overridden. Should we treat this scenario the same way, and keep the existing behavior without a way to delete all existing labels from CAPZ?

cc @jackfrancis @mtougeron

**Comment by jackfrancis** [comment]
Slight preference for standardizing to the approach to that in the autoscaler discussion. Though I don't think this is definitive and it's perhaps the better long-term solution to standardize these configuration vectors as "if you use Cluster API then it is exclusively authoritative — out of band changes will be overwritten".

**Comment by nojnhuh** [comment]
Sounds good, I'll keep things as-is at least for the sake of getting this covered by e2e tests and if there's enough motivation to change the behavior later we can reevaluate then.
