### ISSUE TITLE
 AzureManagedCluster E2E: AdditionalTags CRUD tests

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#2866]
/kind feature
/area managedclusters

**Describe the solution you'd like**
Create new AzureManagedCluster E2E: AdditionalTags CRUD tests

**Comment by jackfrancis** [comment]
Deliverables:

1. Test "create" `additionalTags` against both system and user node pool.
2. Test "update" `additionalTags` against pools, and against `AzureManagedControlPlane` as well
3. Test "delete" `additionalTags` against pools and `AzureManagedControlPlane`

@CecileRobertMichon I assume #3 is fine for `AzureManagedControlPlane`?, in other words, the tags that we define in our test template "buildProvenance", "creationTimestamp", and "jobName") aren't required in any way and we can delete them in an E2E scenario?

**Comment by jackfrancis** [comment]
In terms of "deleting all tags", the aks CLI docs suggest you do that via an empty string value:

```
--tags                : Space-separated tags: key[=value] [key[=value] ...]. Use
                      '' to clear existing tags.
```
