### ISSUE TITLE
Use ConvertResourceGroupNameToLower function to use the one from cloud-provider

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#2892]
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2172 make the `ConvertResourceGroupNameToLower`  exportable so it can be used by other projects like CAPZ that need to use the same format for node ProviderID for vmss.

This issue is to delete the `ConvertResourceGroupNameToLower` function from https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/util/azure/azure.go and replace all its references in the CAPZ codebase with the cloud-provider function in https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_wrap.go#L408 by importing that package from the latest cloud-provider-azure release.

/help
/good-first-issue
/kind cleanup

**Comment by chiukapoor** [comment]
@CecileRobertMichon As we are removing the function `ConvertResourceGroupNameToLower` should we also remove the `azure_test` file https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/7bd46ce86b8e49a8f38b1e191e0bd4ce1f08c62a/util/azure/azure_test.go which is testing the function `ConvertResourceGroupNameToLower`?

**Comment by chiukapoor** [comment]
I have created a PR with the `azure_test` file removed, PTAL.
