### ISSUE TITLE
Add trivy scanner github actions for early signal on CVE 

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2911]
/kind feature

**Describe the solution you'd like**

Scanning container images before a release can help give early signal on CVEs. Taking the inspiration from what the cluster-api folks are trying to do. 
Ref:
https://github.com/kubernetes-sigs/cluster-api/pull/7604

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- Step 1: Adding a verify script that scans the container images. 
- Step 2: Adding a github action workflow that can run periodically. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sonasingh46** [comment]
@jackfrancis @CecileRobertMichon @mboersma  -- What do you think?

**Comment by jackfrancis** [comment]
Can we do this in two phases:

1. Periodic job that alerts us to update our various container images/layers
2. Add as an inline requirement when building release images

I'd like to ensure that we establish the ability to actually respond to these alerts before inserting them into the release flow, possibly blocking releases (especially releases that may container *other* CVE fixes in a different surface area).

**Comment by mboersma** [comment]
I like this idea a lot. I'm curious to see what the output of the trivy tool looks like.

But just as with `kubescape`, there are dangers to setting this up:

- It's a vendor-supplied tool, so it may have some level of "nagging" users to upgrade to a paid service. This can usually be ignored, but often at the expense of extended functionality.

- If we make it just an informative report–not something that actually fails tests–it will be ignored until something goes wrong with it. But it may not be reasonable to fail builds based on the trivy scan.

Overall, I'd like to do this in whatever fashion CAPI is pursuing. Just pointing out some caveats.

**Comment by dtzar** [comment]
I'd recommend to regularly run this as a non-blocking workflow job (i.e. 1x a week) with results published to GH and then with the actual image release.  If the image has CVEs in it prior to release, it doesn't mean you have to fix them - but it is responsible to at least let people know.  If you do regular scans, then you could track back to see when something may have been introduced or potentially decide to fix it earlier.

I have an entire secure supply chain image publishing pipeline template you could utilize which includes not only scanning, but also SBOM report and signing everything with notation.
