### ISSUE TITLE
VMProvisionFailed error when deploying AzureMachineTemplate

### ISSUE THREAD

**Issue by skylaro** [kubernetes-sigs/cluster-api-provider-azure#2918]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
After deploying a new AzureMachineTemplate for an Azure Windows VM using a shared image gallery VM image, the object gets put into VMProvisionFailed state.

**What did you expect to happen:**
Expected a successful provisioning state.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Will put the 'kubectl describe' output here later if necessary. For now, I'm wondering how to troubleshoot VM provisioning failures from an Azure standpoint and file the bug afterwards should it be needed.

Status.Conditions output:
Status:
  Bootstrap Ready:  true
  Conditions:
    Last Transition Time:  2022-12-05T15:48:02Z
    Reason:                VMProvisionFailed
    Severity:              Warning
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-12-05T15:44:35Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2022-12-08T19:48:14Z
    Message:               FailureReason: 0xc00104f040
    Reason:                MachineHasFailure
    Severity:              Warning
    Status:                False
    Type:                  HealthCheckSucceeded
    Last Transition Time:  2022-12-05T15:48:01Z
    Reason:                VMProvisionFailed
    Severity:              Warning
    Status:                False
    Type:                  InfrastructureReady
    Last Transition Time:  2022-12-05T15:44:35Z
    Reason:                WaitingForNodeRef
    Severity:              Info
    Status:                False
    Type:                  NodeHealthy
  Failure Message:         Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha3, Kind=AzureMachine with name "e0-wrk-p1-win-b9e8b1468559889ea59e0332fae31518-5dhqf": Azure VM state is Failed
  Failure Reason:          UpdateError
  Last Updated:            2022-12-05T15:48:01Z
  Observed Generation:     2
  Phase:                   Failed

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
@marosset @jsturtevant can you provide some basic cloudbase-init tips for @skylaro (I assume cloudbase-init is where you'd start when looking to debug provisioning errors)

**Comment by skylaro** [comment]
Thank you @jackfrancis. I'm particularly wondering if there's any additional logging that can be configured and if any correlation IDs are generated that can be tracked Azure-side.

**Comment by marosset** [comment]
@skylaro can you ensure that the VM generation for the VM that you used to build your images matches the VM generation you are trying to deploy?

I noticed `Observed Generation: 2` and everything in https://github.com/kubernetes-sigs/image-builder defaults to gen1. 

In Azure gen1 and gen2 VMs expect different disk partitioning schema (gen1 uses MBr gen2 uses GPT) and this would defiantly result a VM provisioning failure.

Otherwise you'll want need to take a snapshot of the OS disk for the VM and get logs off it to help troubleshoot the issue.
Once you do this you can find the cloudbase init logs at https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/fb09bc6e84f1241b08707b310dac281d4ece3d7f/test/e2e/azure_logcollector.go#L301-L328

**Comment by skylaro** [comment]
Thanks so much for that info @marosset . I will note that the provisioning of gen1 windows VMs also fails. Is there a command that can be ran to capture an OS disk snapshot of these VMs so we can investigate those cloudbase-iit logs you mentioned?
