### ISSUE TITLE
Enable Validation, Conversion, and Defaulting Webhooks

### ISSUE THREAD

**Issue by juan-lee** [kubernetes-sigs/cluster-api-provider-azure#292]
/kind feature

**Description**
Move validation, conversion, and defaulting to webhooks. Webhooks enable apply time validation (versus runtime) as well as defaulting and conversion to happen before types are seen by reconcilers.

https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html
https://book.kubebuilder.io/multiversion-tutorial/conversion.html

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/291/files#r332154674

**Comment by richardcase** [comment]
@juan-lee - This would be helpful with #293  to validate the different image kinds. I will try and add this as part of that change,
