### ISSUE TITLE
ci-entrypoint.sh fails intermittently with "error: no objects passed to create" due to missing kubeadm-config ConfigMap

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#2921]
/kind bug
/kind flake

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
The ci-entrypoint pre-submit CI job has been flaky lately and I've noticed a number of failing runs hit the same error here:
```
Error from server (NotFound): configmaps "kubeadm-config" not found
error: no objects passed to create
```
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e0d9257431826beb489db1db65204f55ca8f2155/scripts/ci-entrypoint.sh#L149-L151 

I suspect this is some sort of race between kubeadm creating that ConfigMap and reading it here? And waiting for that to exist would fix this error?

Runs:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2916/pull-cluster-api-provider-azure-ci-entrypoint/1601245720478748672
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2752/pull-cluster-api-provider-azure-ci-entrypoint/1600913653387759616
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2738/pull-cluster-api-provider-azure-ci-entrypoint/1599870510261342208
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2411/pull-cluster-api-provider-azure-ci-entrypoint/1598784340660064256

**What did you expect to happen:**
The kubeadm-config ConfigMap exists before it's read so the test doesn't fail here.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/assign

thanks for reporting, will take a look
