### ISSUE TITLE
Windows CSI AzureDisk E2E failures

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#2922]
/kind bug
/kind failing-test

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

There are an observable number of VMSS cluster scenario E2E test failures due to the Windows CSI azuredisk test. tl;dr "Service kube-system/csi-azuredisk-node-win failed".

Here's an example:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2920/pull-cluster-api-provider-azure-e2e/1601058904534421504

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
cc @marosset @sonasingh46

**Comment by CecileRobertMichon** [comment]
This is the error in the pods:

```
I1209 04:22:05.236594    5100 safe_mounter_windows.go:412] failed to connect to csi-proxy v1 with error: open \\.\\pipe\\csi-proxy-filesystem-v1: The system cannot find the file specified., will try with v1Beta
E1209 04:22:05.236594    5100 safe_mounter_windows.go:424] failed to connect to csi-proxy v1beta with error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
F1209 04:22:05.236594    5100 azuredisk.go:221] Failed to get safe mounter. Error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2920/pull-cluster-api-provider-azure-e2e/1601058904534421504/artifacts/clusters/capz-e2e-i479ne-vmss/kube-system/csi-azuredisk-node-win-b47xg/azuredisk.log

**Comment by marosset** [comment]
Is the csi-proxy daemonSet getting added to the cluster?

**Comment by marosset** [comment]
I see `csi-proxy: enabled` in the vmss cluster template from this set of logs https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2920/pull-cluster-api-provider-azure-e2e/1601058904534421504/ but I do not see the csi-proxy pods in the `kube-system` namespace.

Are these getting included? https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/templates/addons/windows/csi-proxy

**Comment by CecileRobertMichon** [comment]
I see the label but not the associated ClusterResourceSet in that template https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-machine-pool.yaml#L7

**Comment by CecileRobertMichon** [comment]
Just saw another one of these errors here https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1603083451219578880

 https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1603083451219578880/artifacts/clusters/capz-e2e-dwk0bx-vmss/kube-system/csi-azuredisk-node-win-t5k8b/azuredisk.log
