### ISSUE TITLE
Allow configuring role assignment scope for system assigned VM identity

### ISSUE THREAD

**Issue by BDworak** [kubernetes-sigs/cluster-api-provider-azure#2923]
/kind bug

**What steps did you take and what happened:**
I recently added the identity: SystemAssigned property to my control plane and machine pool nodes. The resulting reconciliation is erroring our when it fails to assign contributor roles to the newly created system assigned managed identity.

Here is the error: 
E1210 07:33:33.144651 1 controller.go:326] "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service roleassignments: cannot assign role to VirtualMachine system assigned identity: failed to create resource cluster/not-a-guid (service: roleassignments): authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client 'not-a-guid' with object id 'not-a-guid' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/not-a-subscription-guid/providers/Microsoft.Authorization/roleAssignments/not-a-guid' or the scope is invalid. If access was recently granted, please refresh your credentials.\"" "azureMachine"={"name":"machine-name","namespace":"some-namespace"} "controller"="azuremachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureMachine" "name"="machine-name" "namespace"="some-namespace" "reconcileID"="not-a-guid"

**What did you expect to happen:**
System Assigned managed identity to be turned on with no roles being granted. If I wanted my control plane, worker nodes, or machine pool to have contributor roles, I would assign those to an Azure Identity and do a UserAssigned identity to help manage access and sprawl. In no production environment would you want all of your nodes to have contributor access to your subscription. 

**Environment:**

- cluster-api-provider-azure version: 1.6.0
- Kubernetes version: (use `kubectl version`):  1.23.5
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS

**Comment by CecileRobertMichon** [comment]
Copying answer from Slack thread:

It seems like in your use case user assigned identities would be more appropriate so you can be in control of the identity role assignments and lifecycle end-to-end. To be clear that's already possible with CAPZ today.

That being said, agree it would be good to make it configurable so you can opt out of the roleAssignment creation when selecting system assigned for CAPZ AzureMachines. We could either make it an opt out (you're in charge of creating role assignments out of band after the VM exists) or make it completely configurable (pass in a scope and role that can be used, default to the sub for scope and Contributor for role). I don't remember the history behind giving it do Contributor on the sub but I'm assuming that has to do with being able to create resource groups. 

/retitle Allow configuring role assignment scope for system assigned VM identity
/kind feature
/help
