### ISSUE TITLE
capi-e2e-v1alpha4 job failing in testgrid

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#2927]
/kind bug
/kind failing-test

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
The capi-e2e-v1alpha4 job in testgrid has failed consistently for the past ~3 weeks.

Last successful run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1alpha4/1595521303379447808
First failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1alpha4/1595883696232075264

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
As discussed offline, we should remove the v1alpha4 periodic job as that release is no longer supported

**Comment by CecileRobertMichon** [comment]
this was done in https://github.com/kubernetes/test-infra/pull/28425

/close
