### ISSUE TITLE
Set up CI subscription to use azure workload identity

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2936]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

An effort has been made to migrate to using Azure Workload Identity (AZWI) in place of AAD pod identity as the later has been deprecated. More details can be found on the proposal [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2814)

This requires some configuration and setup to be done for capz CI subscription.

Using AZWI, requires some pre-requisite steps for a bootstrap cluster which is self-managed e.g. a Kind cluster. The steps are describe as below:

**1. Generate a pub/private key pair or BYO key pair and store it to azure key vault.**

The service account keys are in keyvault and retrieved when bootstrapping the kind cluster for the CI
Follow the link on generating key pair: [Key Pair Generation](https://azure.github.io/azure-workload-identity/docs/installation/self-managed-clusters/service-account-key-generation.html)
Follow the link for an example on how to set up: [Example](https://github.com/Azure/azure-workload-identity/blob/main/scripts/create-kind-cluster.sh)

This is a one time step. 

**2. Generate discovery and JWKS document and upload to a publicly accessible URL.**

The steps to generate and publish discovery document are [here](https://azure.github.io/azure-workload-identity/docs/installation/self-managed-clusters/oidc-issuer/discovery-document.html)

The steps to generate and publish JWKS document are [here](https://azure.github.io/azure-workload-identity/docs/installation/self-managed-clusters/oidc-issuer/jwks.html) 

This is a one time step.

**3. Set up a federated identity credential.**
The steps to create a federated identity credential are [here](https://azure.github.io/azure-workload-identity/docs/topics/federated-identity-credential.html)

This is also one time step if the namespace, service account name, namespace and OIDC issuer url is fixed which is so in this case.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sonasingh46** [comment]
cc @CecileRobertMichon

**Comment by sonasingh46** [comment]
cc @aramase

**Comment by aramase** [comment]
> The service account keys are in keyvault and retrieved when bootstrapping the kind cluster for the CI

We retrieve it from Azure Key Vault (AKV) in the azure-workload-identity CI. For CAPZ, i think we can just store this in the `kubernetes-upstream` secrets manager instance and sync it in the test pod as an env var using `ExternalSecret` (ref: https://github.com/kubernetes/test-infra/blob/04cd303e4da537af4b6f15b8a6a8639d8773aeb0/config/prow/cluster/build/build_kubernetes-external-secrets_customresource.yaml#L30-L47)

> Generate discovery and JWKS document and upload to a publicly accessible URL.

Just need to ensure the anonymous access is set only for the 2 containers `.well-known/openid-configuration` and `openid/v1/jwks`.

@CecileRobertMichon i'll be happy to pair with you on the setup if you have any questions.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 I set up the required stuff in the Azure test sub and opened https://github.com/kubernetes/test-infra/pull/28261 to add the keys as environment variables to the presets our jobs use. After that merges, you should just be able to use `SERVICE_ACCOUNT_SIGNING_PUB` and `SERVICE_ACCOUNT_SIGNING_KEY` as environment variables in the scripts that setup the management cluster.

**Comment by sonasingh46** [comment]
Got it. Thank you @CecileRobertMichon. Just a clarifying question: 
Are those env variables going to contain the entire key data as string or it contains location to the file where the keys will get stored?

**Comment by CecileRobertMichon** [comment]
@sonasingh46 the env variables contain the key data encoded in base 64.

**Comment by sonasingh46** [comment]
@CecileRobertMichon -- Forgot to ask -- For point 2 -- I will need the publicly accessible URL -- preferably we can add one more preset in test-infra that has an env containing the URL.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 the url is https://oidcissuercapzci.blob.core.windows.net/oidc-capzci


we can move that to environment variables in test-infra if that's better but you should be able to start testing with this value in the meantime

**Comment by sonasingh46** [comment]
Thank you. I will start testing using that.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 any luck?

**Comment by CecileRobertMichon** [comment]
/close

this is done
