### ISSUE TITLE
Backfill Parameters() Unit Tests for all of the service libraries that don't currently have them

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#2946]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- This issue is branching out of the [feedback here at PR#2829](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2829#issuecomment-1353532717)
- We would like to add more unit tests covering `Parameters()` functions to `spec_test.go`
 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ShivamTyagi12345** [comment]
I will take on this issue . Thanks

/assign

**Comment by nawazkh** [comment]
Hey @ShivamTyagi12345, how is this coming along? Do you need any help on this?

**Comment by nawazkh** [comment]
Hey @ShivamTyagi12345, how is this coming along? Do you need any help on this?

**Comment by chandankumar4** [comment]
I will work on this issue.
/assign
