### ISSUE TITLE
Audit AKS Managed Cluster docs for feature-completeness

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#2948]
/kind documentation
/area managedclusters

**Describe the solution you'd like**

I know I have not been good about adding docs for new features to managed clusters like [this](https://capz.sigs.k8s.io/topics/managedcluster.html#aks-node-pool-osdisktype-configuration), so we should take a pass at the existing managed cluster docs to ensure all implemented features have adequate documentation.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dtzar** [comment]
IF it were reasonably possible, it would be nice to do a delta of what features/capabilities there are in the latest version of the ManagedCluster API compared to what's in CAPZ while doing this work.

**Comment by nojnhuh** [comment]
@dtzar Is that something you'd like to see persisted with the rest of the docs? Or would this be a one-time thing? I'd be hesitant to commit to keeping that kind of info up to date but I'm also not sure what a good ephemeral place for that would be.

At least for this issue, I was planning to go through what's implemented vs. documented in CAPZ without needing to enumerate all of the features currently implemented in AKS, so maybe a separate issue for that would be best.

**Comment by dtzar** [comment]
This would be a one-time thing to help us (even roughly) identify the gaps of what's missing today.
A separate issue makes sense.  Maybe if you anecdotally detect those gaps, we can start to put those on a shared list somewhere?
