### ISSUE TITLE
Split the the v1beta1 prow jobs YAML into last two release branch YAMLs

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2967]
CAPZ has periodic PROW jobs that runs on last two supported release branches. This is here in this file 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-periodics-release-v1beta1.yaml

We should split it into two different YAMLs for the respective release branches as done in CAPI. Here is the example: 

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-3.yaml
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-2.yaml

The side effect of this will result in easier maintenance and organisation of the test jobs.

**Comment by sonasingh46** [comment]
cc @rajaskakodkar @navidshaikh 
In case you are interested.

**Comment by navidshaikh** [comment]
PTAL https://github.com/kubernetes/test-infra/pull/28353
