### ISSUE TITLE
NetworkInterfaces are not deleted if PUT longRunningOperation is in progress

### ISSUE THREAD

**Issue by snehala27** [kubernetes-sigs/cluster-api-provider-azure#2971]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?] Yes

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If a MachineDeployment is scaled up and scaled down immediately(happened in our env due to autoscaler), it creates a new azuremachine and deletes it again. During creation, network interface PUT operation was in progress as a longRunningOperation and meanwhile deletion timestamp was set on azuremachine. In [reconcileDelete](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/async/async.go#L159), while deleting interfaces, it checked for [longRunningOperation](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/async/async.go#L168)(which was already in progress due to previous call). Once the operation was finished, it returned back from the [function](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/async/async.go#L171) after which the finalizer was removed from azureMachine. Thus delete call was never performed on the nic associated with machine

As a result of this, we have lot of dangling NIC's present

Lifecycle of azuremachine: gmazasstage-worker-pool-1-74b5-6m8gm
![azureMachineLifecycle](https://user-images.githubusercontent.com/39336187/209806329-b6bd9cc0-1e76-49dc-bf1d-05d8a4c522da.png)

Status of AzureMachine after deletion timestamp was set. PUT operations can be seen as longRunningOperation and AzureMachineDeletion has already started
![Screenshot 2022-12-28 at 6 13 44 PM](https://user-images.githubusercontent.com/39336187/209814188-860bb4f5-c19d-464f-9558-5013ef7fb5da.png)

Operation performed on the NIC on AzurePortal: No deleteOp is seen
![nicOnAzurePortal](https://user-images.githubusercontent.com/39336187/209807440-76a29d81-6f51-45f4-b34c-898de5d2ce8a.png)

**What did you expect to happen:**
NIC's should get deleted on deleting azureMachine

**Anything else you would like to add:**
Probable solution:
![Screenshot 2022-12-28 at 6 11 31 PM](https://user-images.githubusercontent.com/39336187/209813984-d65d7c4f-a12e-41cd-b2b0-63e5bfdafd4e.png)

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Hi @snehala27, the latest CAPZ code already checks for the futureType to make sure it ignores existing operations of a different type (eg. ongoing create operation if we are trying to delete): https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/async/async.go#L170

This was added in https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/ef6f6637b6ecc408202991d4fcab15fc7a6fac0b and part of CAPZ v1.6.0+

which version of CAPZ are you using?

**Comment by snehala27** [comment]
@CecileRobertMichon Thanks! I am using an older version v1.5.0
