### ISSUE TITLE
Service type loadbalancer does not work when AzureClusterName!=ClusterName with node outbound LB

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2994]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]
When a workload cluster is created with AzureClusterName!=ClusterName and node outbound load balancer is opted, k8s service with type load balancer fails to route even if it gets a public IP assigned.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Create a workload cluster so that AzureClusterName!=ClusterName
- Opt for out bound load balancer. 
- Deploy a service of type load balancer. ( A simple nginx server with service of type load balancer can be used to test ) 
- The nginx server will not be accessible via the public IP

**What did you expect to happen:**
The nginx server should be accessible via the public IP

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- Node outbound load balancer is created whose name is the same as that of azure cluster name. ( by capz )
- When service of type LoadBalancer is created for an app, it creates a load balancer with the same name as cluster name. ( by in-tree cloud provider azure )
- Now this load balancer created for service cannot add backend bools as the one created by capz has already added the nodes in the backend pool. And the reason for this is Azure does not allow multiple load balancers of same type (public or internal) to be attached to the same backend pool. 
- Now the the load balancer created for service is not able to attach backend pool causing the disconnect.

- One suggested fix top off my head is to use ClusterName as the default outbound lb name instead of AzureClusterName. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by wjun** [comment]
Please make sure the change will not break cluster upgrade.

**Comment by sonasingh46** [comment]
cc @CecileRobertMichon @devigned

**Comment by sonasingh46** [comment]
Sure, thanks

**Comment by mboersma** [comment]
This comes up with ClusterClass in particular. What's the specific use case where AzureCluster.Name != Cluster.Name and how can we reproduce it?

Maybe the fix is to enforce that the names agree?

**Comment by fabriziopandini** [comment]
Chiming in after being pinged by @sonasingh46 

> What's the specific use case where AzureCluster.Name != Cluster.Name and how can we reproduce it?

This use case happens with any cluster generated from a ClusterClass, and more specifically it happens when the Topology controller generates an object starting from the AzureClusterTemplate linked from the ClusterClass.

In this case, as a common practice in K8s, the object is named with a well know prefix, the cluster name in this case, plus a random suffix, and this is done to prevent name clashes (nothing prevents someone to create an AzureCluster object with the same).

Also, this is acceptable by Cluster API, because Cluster and the Azure Cluster are explicitly linked by a Reference which requires you to specify the name, and the name can be any valid K8s name.

**Comment by sonasingh46** [comment]
Also one info is -- 
The outbound load balancer name is not editable on AzureCluster object. I tired to to do that and it did not allow me to do that. 
Also the webhook defaults the name of outbound load balancer to AzureClusterName only if it is empty.

**Comment by sonasingh46** [comment]
Also FWIW, this symptom is seen in clusterclass as the default behaviour is ClusterName!=AzureClusterName and then by default the outboundlb name is the same as that of AzureClusterName.  But then it is broken even if ClusterName=AzureClusterName, when someone explicitly gives a name of the outboundlb different then that of ClusterName on the AzureCluster spec. 
One thing I need to figure out is how does cloud-provider-azure picks the ClusterName to create the LB?

**Comment by CecileRobertMichon** [comment]
To set the cluster name cloud-provider uses (when out of tree), you can do `--set infra.clusterName=${AZURE_CLUSTER_NAME}` in the Helm install command:   https://capz.sigs.k8s.io/topics/addons.html#external-cloud-provider

**Comment by CecileRobertMichon** [comment]
@sonasingh46 seems there is also a `loadBalancerName` in clusterConfig (https://cloud-provider-azure.sigs.k8s.io/install/configs/#cluster-config) so we might be able to fix this issue by adding this setting in CAPZ in the generated cloud provider config [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/helpers.go#L257)?

**Comment by sonasingh46** [comment]
Thanks for that info @CecileRobertMichon. I wasn't aware of that flag so that sounds good to me. 
I have made changed in capz code and validated it works well. Also we do not have to worry about any backwards compatibility and migration steps as it was anyways broken when the outbound load balancer name was not the same as that of clustername.  

Also, for intree the cluster name is taken from the controller-manager flag : 
```
 --cluster-name=<cluster-name> 
  
```

**Comment by sonasingh46** [comment]
Just to summarise: 
Solution is to make sure that cloud-provider-azure always creates a load balancer with the same name as that of outbound load balancer name present in the azure cluster. If a outbound lb is not present, it uses the default name i.e cluster name.
And this can done via what Cecile suggested above.

**Comment by CecileRobertMichon** [comment]
> I have made changed in capz code and validated it works well

Did you try with the `loadBalancerName` configuration? Seems like that might be even better as it's more precise

**Comment by sonasingh46** [comment]
>Did you try with the loadBalancerName configuration? Seems like that might be even better as it's more precise
Yes. That only. Oh, I used the word flag -- I meant the flag in azure.json config file. So this is more neat solution.

**Comment by jayunit100** [comment]
is this innocuous enough, i guess, to merge for now?   From what i can tell the tests asutosh has ran so far indicate it makes things generally better.

**Comment by jorgemoralespou** [comment]
Is there a way with capz 1.6.1 to not get into this problem? I have infrastructure in Azure and I'm using TKG (2.1) which uses capz 1.6.1 and I can not automate the creation of LoadBalancers as I need to manually go into the Azure portal and manually select the machine pools for the LoadBalancer used by my Ingress. Is there a way to customize or create a new ClusterClass that would set the same name for Cluster and AzureCluster or that would set the right LoadBalancerName, until I can use the version of capz that fixes this issue?

**Comment by CecileRobertMichon** [comment]
@jorgemoralespou this is fixed in CAPZ v1.6.3+ https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v1.6.3

the only other workaround is to use the same name for Cluster and AzureCluster, not sure if that's something TKG allows you to do or not.
