### ISSUE TITLE
add support to configure azure environment for AKS clusters

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#3029]
/kind feature

**Describe the solution you'd like**
Add support for AKS clusters creation in an another cloud than US Public.

**Anything else you would like to add:**
we are currently leaving the `azure.Environment` empty for managed clusters which defaults to US Public cloud endpoints. It should continue to default to US Public cloud endpoint but providing an override mechanism would be helpful. 
As allowing this to be configurable would allow users to create AKS clusters in other allowed environments. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/close

already done in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3509
