### ISSUE TITLE
Dependabot-code-gen should be updating hack/tools/go.mod and hack/tools/go.sum

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#3032]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- [Dependabot-code-gen](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/dependabot-code-gen.yml) is not updating hack/tools/go.mod and hack/tools/go.sum when Dependabot raises a version update PR. 

**What did you expect to happen:**
- [Dependabot-code-gen](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/dependabot-code-gen.yml) should be updating hack/tools/go.mod and hack/tools/go.sum when Dependabot raises a version update PR. 
- CAPI is updating dependencies in CAPI/hack/tools/go.mod and CAPI/test/go.mod when CAPI/go.mod gets updated. Example: https://github.com/kubernetes-sigs/cluster-api/pull/7884 
Notice that the second commit ([Update Code Gen](https://github.com/kubernetes-sigs/cluster-api/pull/7884/commits/199cfb32759cdded5e73d728c6c4d3b4c5a40d23)) gets applied by [CAPI dependabot-workflow.](https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/dependabot.yml). This doesn't seem to be happening at CAPZ.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nawazkh** [comment]
I opened this issue to keep a track of dependabot-code-den investigation.

**Comment by CecileRobertMichon** [comment]
@nawazkh slightly tangent but I wonder if you have any ideas around how we could ensure we also keep the tools we install in the Makefile up to date https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L71, I noticed a lot of them have old versions

**Comment by nawazkh** [comment]
^note to self. [dependabot-code-gen workflow](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/dependabot-code-gen.yml) should have updated the (direct/indirect) modules present in `hack/tools/go.mod` too.
- [ ] Why is dependabot-code-gen not updating hack/tools/go.mod?
- [ ] How are we using hack/tools/go.mod at CAPZ.

**Comment by nawazkh** [comment]
> @nawazkh slightly tangent but I wonder if you have any ideas around how we could ensure we also keep the tools we install in the Makefile up to date https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Makefile#L71, I noticed a lot of them have old versions

Great thought! We could probably implement something like [`tools.go`](https://www.jvt.me/posts/2022/06/15/go-tools-dependency-management/) to manage our dependencies. 
And also export/set those env variables ([ex `CONTROLLER_GEN`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f71376f0f6d98314d46b2715768de186e512ba3a/Makefile#L74)) to be used in Makefile.

**Comment by nawazkh** [comment]
Also take a look at https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3199#issuecomment-1447264709

**Comment by nawazkh** [comment]
Note to self: Also check if you can automate this in anyway https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3214#issuecomment-1452367469

**Comment by mboersma** [comment]
#4121 is an example of dependabot updating the vendoring in hack/tools correctly. Although the big delta between versions seems to suggest it missed several releases before opening this PR.

Did something in our configuration for dependabot change, or maybe a bug got fixed upstream?

**Comment by nojnhuh** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4199 Also falls into that category and the common thread there seems to be that both are fixing security alerts.
