### ISSUE TITLE
Change metrics-server addon image registry to registry.k8s.io for all templates

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3035]
Metrics server still uses gcr.io images in all test templates: [cluster-api-provider-azure/metrics-server.yaml at main · jackfrancis/cluster-api-provider-azure (github.com)](https://github.com/jackfrancis/cluster-api-provider-azure/blob/main/templates/addons/metrics-server/metrics-server.yaml#L138)

It should be changed to use registry.k8s.io. Looks like there is a v.0.6.2 in registries.k8s.io.

**Comment by swastik959** [comment]
@CecileRobertMichon hi i am new to open source and want to work on this issue can you guide me through it

**Comment by CecileRobertMichon** [comment]
Hi @swastik959, welcome!

In order to fix this issue, you would need to search for all occurrences of `k8s.gcr.io/metrics-server/metrics-server:v0.5.2` in the templates/ directory and replace them with `registry.k8s.io/metrics-server/metrics-server:v0.6.2`, then run `make generate` to generate all templates.

**Comment by swastik959** [comment]
@CecileRobertMichon when i am running make generate command the templates are getting restored to their original state

**Comment by CecileRobertMichon** [comment]
@swastik959 make sure you're editing this line https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/metrics-server/metrics-server.yaml#L138, that file should be used to generate all the other templates

**Comment by swastik959** [comment]
I think I need to change the `resources` section in the 'kustomization.yaml' file to the location of the image components of `v0.6.2`, since thats what `generate-addons` was using along with `$(KUSTOMIZE)` to override the `metrics-server/metrics-server.yaml`

since I couldn't figure out where components for `v0.6.2` were for the registry.k8s.io domain, I simply changed

```
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.2/components.yaml
```
to
```
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.2/components.yaml
```
and changed the `image` tag in metric-server.yaml from `v0.5.2` to `v0.6.2`

this _seems_ to work.

Please let me know if there are any discrepancies

**Comment by CecileRobertMichon** [comment]
@swastik959 thanks, that seems correct, can you please open a PR so I can review the changes?

**Comment by CecileRobertMichon** [comment]
Actually looking at https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.2/components.yaml, it still uses the gcr.io registry, @marosset any ideas where we can get a manifest for metrics server that uses registry.k8s.io? Side note, we might want to switch to using the Helm chart

update: found https://github.com/kubernetes-sigs/metrics-server/issues/1142, looks like they haven't released the change yet

@swastik959 let's proceed with just the version bump for now and we can keep this issue open to track changing the registry once the metrics-server project has a new release

**Comment by mboersma** [comment]
```shell
% docker pull registry.k8s.io/metrics-server/metrics-server:v0.6.2 
v0.6.2: Pulling from metrics-server/metrics-server
Digest: sha256:f977ad859fb500c1302d9c3428c6271db031bb7431e7076213b676b345a88dc2
Status: Image is up to date for registry.k8s.io/metrics-server/metrics-server:v0.6.2
registry.k8s.io/metrics-server/metrics-server:v0.6.2
```

Looks like it's available at registry.k8s.io now. I commented in the PR.

**Comment by CecileRobertMichon** [comment]
@mboersma it's available on the registry but the release artifacts (that we use to auto-generate the templates) still refer to the old registry https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.2/components.yaml

**Comment by Sajiyah-Salat** [comment]
is this issue still persist?

**Comment by CecileRobertMichon** [comment]
/remove-good-first-issue
/remove-help

@Sajiyah-Salat yes but it's blocked until the metrics server project releases new artifacts so it's not ready to be worked on

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/metrics-server/issues/1165 and https://github.com/kubernetes-sigs/metrics-server/pull/1192 should unblock this issue

**Comment by mboersma** [comment]
I think this is waiting for kubernetes-sigs/metrics-server#1212 now.

**Comment by mboersma** [comment]
https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.3 is available:

```shell
% docker pull registry.k8s.io/metrics-server/metrics-server:v0.6.3
v0.6.3: Pulling from metrics-server/metrics-server
dde16751a2cc: Already exists 
...
Status: Downloaded newer image for registry.k8s.io/metrics-server/metrics-server:v0.6.3
registry.k8s.io/metrics-server/metrics-server:v0.6.3
```

**Comment by mboersma** [comment]
/help
/good-first-issue

Now that the v0.6.3 release of metrics-server is out, resources have moved to registry.k8s.io. We should be able to update the registry and version as described in the initial PR comment now.
