### ISSUE TITLE
Remove k8s 1.22 tests and add 1.26

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3055]
Since k8s 1.26 is now out and 1.22 EOL, we should:

- [x]  remove https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-22-1-23
- [x] add a new 1.25 to 1.26 k8s upgrade periodic job
- [x] remove the CSI migration test spec and associated presubmit as it's only valid for 1.22 to 1.23 upgrade
- [x] bump the default k8s versions used in testing (e2e, testgrid, etc.)

**Comment by CecileRobertMichon** [comment]
cc @sonasingh46 @jackfrancis 

/milestone v1.8

**Comment by jackfrancis** [comment]
Status update: only the update the default version to 1.25 change is remaining; I've updated that PR to mark that it fixes this issue when it merges.
