### ISSUE TITLE
Enable accelerated networking on VM sizes that support it

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#307]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#supported-vm-instances

For VMs, enable using the `EnableAcceleratedNetworking` property of [network interfaces](https://sourcegraph.com/github.com/Azure/azure-sdk-for-go/-/blob/services/network/mgmt/2018-07-01/network/models.go#L10581:2)
For VMSS, enable using the `EnableAcceleratedNetworking` property of [scale sets](https://sourcegraph.com/github.com/Azure/azure-sdk-for-go/-/blob/services/compute/mgmt/2019-07-01/compute/models.go#L10331:11)

/good-first-issue

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Tranhaia** [comment]
[takeout-20190908T235113Z-001.zip](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/3747169/takeout-20190908T235113Z-001.zip)
Up loang hệ thống quản lý

**Comment by khunpanpotter3** [comment]
goodjob ?

<a href="http://nigcompany.com/2019/08/joker-slot-%e0%b9%80%e0%b8%84%e0%b8%a3%e0%b8%94%e0%b8%b4%e0%b8%95%e0%b8%9f%e0%b8%a3%e0%b8%b5/">Joker</a>

<a href="https://footballmoment.com///">ข่าวฟุตบอล</a>

**Comment by mallensgod** [comment]
Did you get my comments?

**Comment by mallensgod** [comment]
Allensgod Art & Illustrations LLC/drts1964mil@gmail.com/charlayiyi67@gmail.com/allensgod51@gmail.com/allensgod95. Period the 95 is our usernames. Google fubar-ed it all.

**Comment by mallensgod** [comment]
What exactly is a repository?

**Comment by mallensgod** [comment]
Don't waste my time, It's very pressious.

**Comment by kalit2** [comment]
What is the "key"?

**Comment by justaugustus** [comment]
/milestone v0.3

Ping @devigned to validate API responses for accelerated networking e.g., https://github.com/Azure/azure-sdk-for-go/issues/5968

**Comment by devigned** [comment]
Might be helpful to see how this is approached in aks-engine: https://github.com/Azure/aks-engine/issues/1894

**Comment by CecileRobertMichon** [comment]
keep open

**Comment by CecileRobertMichon** [comment]
@soggiest have you had time to look into this? If not I might give it a shot

**Comment by nader-ziada** [comment]
let me know if you need with this issue

**Comment by soggiest** [comment]
@CecileRobertMichon I haven't had any time to work on this, please go ahead and work on it

**Comment by CecileRobertMichon** [comment]
@mboersma is this something you'd be interested in helping out with?

**Comment by mboersma** [comment]
@CecileRobertMichon I would love to, with the caveat that I'm not yet familiar with the code. But please consider me assigned and I'll start on it this week.

**Comment by CecileRobertMichon** [comment]
Awesome, don't hesitate to lean on me as much as needed for onboarding with the code.  Also I recommend starting here https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/development.md.

/assign @mboersma

**Comment by CecileRobertMichon** [comment]
@mboersma are you still working on this?

**Comment by nader-ziada** [comment]
hey @mboersma , if you are not working on this, mind if I give it a try?  
cc: @CecileRobertMichon

**Comment by mboersma** [comment]
@nader-ziada obviously I haven't gotten anywhere--please do, I don't want to impede progress.

**Comment by mboersma** [comment]
@nader-ziada I actually have this working now in a local branch. I'm adding some tests and will push a PR out soon.

**Comment by nader-ziada** [comment]
Thanks @mboersma
