### ISSUE TITLE
CAPZ fails to scale in K8s VMSS Flex cluster

### ISSUE THREAD

**Issue by zmyzheng** [kubernetes-sigs/cluster-api-provider-azure#3077]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?] Yes

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Step 1: Create a K8s cluster using the template [cluster-template-external-cloud-provider-machinepool.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template-external-cloud-provider-machinepool.yaml) to create a K8s cluster with VMSS Flex as MachinePool
Step 2: Scale in the MachinePool with command: kubectl scale --replicas=<a smaller replica count>  MachinePool/<MachinePoolName>
Step 3: After the above command is executed, all the nodes in the MachinePool will become "Ready,SchedulingDisabled" status but the nodes will never be deleted:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/24629574/214165679-a4b03863-6159-4156-9227-d76488bd129f.png">

**What did you expect to happen:**
Some nodes should be deleted after scaling in.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
![image](https://user-images.githubusercontent.com/24629574/214165902-2929bb66-e2df-44c1-aa70-41f6b87b3dbb.png)
![image](https://user-images.githubusercontent.com/24629574/214165963-8654471b-8198-43af-a296-6db2fd195fc4.png)
<img width="970" alt="image" src="https://user-images.githubusercontent.com/24629574/214166020-177356a9-0574-41b0-ac34-ddef37a2ad20.png">

### Root Cause Analysis:
I briefly went through the CAPZ scaling in logic for MachinePoolMachine, from my understanding, before kicking away the VM from the MachinePool, CAPZ does 2 things:
Thing 1:  run “[kubectl cordon](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepoolmachine.go#L458)” command to prevent new pods to be scheduled into this node 
Thing 2:  run “[kubectl drain](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepoolmachine.go#L463)” command to kill all existing pods in this node.

When I run the “kubectl describe node” command, I can see the taint “node.kubernetes.io/unschedulable:NoSchedule” is added to the node to prevent new pods to be scheduled to it:
 
<img width="354" alt="image" src="https://user-images.githubusercontent.com/24629574/214166100-d9c0e8ca-c295-4f40-96b4-c2c7bdfb23a6.png">

This existence of this taints indicates the “cordon” command succeeds and the issue should be the “drain” command. In the above error message I captured, it looks like the CAPZ is complaining the corresponding node cannot be found. I took a look at the node name in the error message and found CAPZ is trying to use a self-defined node name to identify the node: <MachinePool name>-<VM name> (replace underscore to dash), and I guess this is where the issue is from: **The K8s cluster uses OS hostname (computer name) as the nodeName, but CAPZ defines a different name format so the cluster cannot find the corresponding node.** This partially explains the issue but one thing I don’t figure out yet is, why the issue only exists in the “drain” command while “cordon” command does not meet this issue. Maybe I missed something.

**Environment:**

- cluster-api-provider-azure version: 1.7
- Kubernetes version: (use `kubectl version`): 1.26.0
- OS (e.g. from `/etc/os-release`): Linux

**Comment by mboersma** [comment]
The error message about `DrainingSucceeded` patch not applying is fixed by adding that to the controller's owned conditions, but this doesn't fix the overall failure.

**Comment by mboersma** [comment]
I've tried and failed to find what's going on here–I must be missing something basic.

Note that VMSS Flex in general is broken without a fix for our using `instanceID` as a marker. I would suggest starting with #3196 as a basis for debugging this scale in problem.

At a high level, the initial behavior I see that seems to create other problems is that an AzureMachinePoolMachine is deleted  very quickly in the case of Flex. In the case of Uniform, the AMPM gets "Deleting" status for a minute or longer, then it and the corresponding Node are removed correctly.

When the Flex AMPM disappears quickly, the AMP tries to recreate it and things go wrong very quickly.

As far as I can tell, Node cordon and drain proceed similarly in both Flex and Uniform cases, taking about the same (short) amount of time since I have no real pods scheduled.
