### ISSUE TITLE
VMSS Flex clusters sometimes fail validation

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3085]
/kind bug

**What steps did you take and what happened:**

In `make tilt-up`, deploy the "external-cloud-provider-machinepool" flavor. Some percentage of the time, the deployment will fail in webhook validation for the AzureMachinePool because the owning MachinePool isn't found.

**What did you expect to happen:**

The cluster should deploy, including the AzureMachinePool, so long as the Kubernetes version is v1.26.0 or later.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
Is this only seen during cluster create? Is it fair to assume that this is a race condition during initial resource scaffolding, i.e., "send a bunch of interdependent resource definitions to the apiserver at the same time and rely upon concurrent admission". In which case anticipating said race conditions w/ to sibling/parent resources that may not yet be present in the cluster seems like the obvious solution (not that obvious has qualitiative value).

**Comment by mboersma** [comment]
> Is this only seen during cluster create?

As far as I can tell, yes. I think your assessment is correct and retrying a few times may effectively solve it.
