### ISSUE TITLE
Replace util/webhook code with CustomDefaulter/CustomValidator

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3103]
/kind feature

**Describe the solution you'd like**

@sbueringer [pointed out](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3080#discussion_r1087679502) that much of the CAPZ webhook utility code in `util/webhook` could possibly be replaced by using CustomDefaulter and CustomValidator from controller-runtime. Currently only `azuremachinetemplate_webhook.go` sets up its webhook this way. (But not fully--see the comment below.)

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Small addition. `azuremachinetemplate_webhook.go` is using CustomDefaulter / CustomValidator but it is still implementing the interface on the AzureMachineTemplate struct.

To allow using a client the interfaces have to be implemented on a separate struct.

Example for this can be found in core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/4ec1077b23bbc05758f46084b162376e069fb271/internal/webhooks/cluster.go#L42-L62
