### ISSUE TITLE
Intermittent "cannot re-use a name that is still in use" in e2e when installing Azure Disk CSI driver Helm chart

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3104]
**Which jobs are flaky:**
- periodic-cluster-api-provider-azure-capi-e2e-main
- periodic-cluster-api-provider-azure-e2e-main
- periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-24-1-25-main

**Which tests are flaky:**
- Any that install the Azure Disk CSI driver Helm chart

**Testgrid link:**
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1618124950411939840
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1618306147695988736
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1617218964859916288
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-24-1-25-main/1616553384792297472

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind flake

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
Interesting... this is exactly the issue I thought I fixed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2915

It does check for an existing Helm release before installing it and the logs show it wasn't found which is really strange

```
 STEP: Installing azure-disk CSI driver components via helm @ 01/25/23 06:10:47.556
  Jan 25 06:10:47.682: INFO: getting history for release azuredisk-csi-driver-oot
  Jan 25 06:10:47.790: INFO: Release azuredisk-csi-driver-oot does not exist, installing it
  Jan 25 06:10:53.724: INFO: creating 1 resource(s)
  Jan 25 06:10:55.287: INFO: creating 18 resource(s)
  [FAILED] in [It] - /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/helpers.go:988 @ 01/25/23 06:30:47.791
  STEP: Dumping logs from the "node-drain-hpmcqc" workload cluster @ 01/25/23 06:30:47.791
```

**Comment by nojnhuh** [comment]
I think that error can come up when there's a particular resource that already exists that conflicts with the chart, not just the release name. Like if a Pod exists named "pod" and the chart tries to install a Pod named "pod" I think this same error would come up.

**Comment by CecileRobertMichon** [comment]
I wonder if there is a way to increase verbosity of Helm so we can know exactly which resource conflicted when this happens 🤔

**Comment by nojnhuh** [comment]
Actually this does only refer to release name: https://github.com/helm/helm/blob/835b7334cfe2e5e27870ab3ed4135f136eecc704/pkg/action/install.go#L483

It looks like that error can come up when an old release with that name has been deleted, but I don't see anywhere we uninstall a release. And I don't see any gaps in the existing check that the release exists where that could be incorrect.

FWIW I also don't see any way for Helm to log the resources it creates one-by-one.

**Comment by CecileRobertMichon** [comment]
/assign 

I think I found the issue while testing something unrelated... When the first install fails for any reason, we don't cleanup the failed release and all subsequent retries fail with "cannot re-use a name that is still in use" which then fails the eventually block with that error after timeout is met
