### ISSUE TITLE
Intermittent e2e suite timeout at 4h in CAPI tests when collecting Windows logs

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3108]
**Which jobs are flaky:**
- periodic-cluster-api-provider-azure-capi-e2e-main
- periodic-cluster-api-provider-azure-capi-e2e-v1beta1
- (maybe) periodic-cluster-api-provider-azure-capi-e2e-v1beta1-minus-1
  - The same 4h timeout is hit, but in any particular test case that I can correlate with Windows log collection

**Which tests are flaky:**
- Mostly this one:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f225d0f050eadea3e319c6414b3bb61c6704a616/test/e2e/capi_test.go#L125
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1617037015017066496
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1614862162507862016
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1614680966943477760
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1613956175076790272
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1/1617631196974419968
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1/1614731047528828928
- But also this one:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f225d0f050eadea3e319c6414b3bb61c6704a616/test/e2e/capi_test.go#L110
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1/1618718627345731584
- And sometimes outside of any particular test
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1/1611831354528370688
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1-minus-1/1616480775698386944
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1-minus-1/1615755959446016000
  - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1-minus-1/1615031026914955264

**Reason for failure (if possible):**
The stack trace emitted by Ginkgo when the timeout is hit always points to this line:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f225d0f050eadea3e319c6414b3bb61c6704a616/test/e2e/helpers.go#L484

That `config` is mostly defined here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f225d0f050eadea3e319c6414b3bb61c6704a616/test/e2e/helpers.go#L589-L593

[`ssh.ClientConfig`](https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig) does contain a `Timeout` field that is not currently set, meaning it will never timeout. 

Our tests call the hanging `ssh.NewClientConn` inside of a [`wait.PollImmediate`](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#PollImmediate) which will not check if its timeout has been hit until after the condition is checked once. If the condition hangs forever, then so will `wait.PollImmediate`, which I believe is ultimately causing the suite timeout.

/kind flake
/sig windows

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jackfrancis** [comment]
Great find!

**Comment by nojnhuh** [comment]
/reopen

This same error has started surfacing again, e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1637698433160581120

I wonder if it's worth trying bumping the timeout to collect logs from 1m to something like 5m? https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3153#discussion_r1098943045

**Comment by nojnhuh** [comment]
Eyeballing the history for that job, I'm not sure the fix ever really helped things at all, so it seems like the real issue might be something entirely unrelated.

**Comment by nojnhuh** [comment]
Took one more look at this and made some progress that may or may not be insightful. Most recent run that timed out: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1643679321266589696

Looking deeper into the stack trace, it looks like exactly where things are stuck is here, which seems to indicate that the SSH port is open but the SSH server is not actually running or is at least not responsive: https://github.com/golang/crypto/blob/776e461a4e6d8b372a43c72122c5c28cfc40dca2/ssh/transport.go#L322. And the fix above to add a timeout to the ssh ClientConfig definitely didn't do anything to help this since that timeout is only enforced when making the initial TCP connection.
