### ISSUE TITLE
Reduce the amount of cluster create time

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#313]
/kind feature

CAPZ currently takes ~15 minutes to provision 3 control planes - due to them spinning up serially. It would be great to get cluster creation time lower. :)

**Comment by justaugustus** [comment]
@juan-lee has ideas about this. Will drop some details once he wraps the MachinePool proposal.

**Comment by rbitia** [comment]
Needs definition of done, and a proposal for how to time control plane creation.
