### ISSUE TITLE
Tilt cluster flavor command shows as passed even if it failed

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3135]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
1. Spin up Tilt with `make tilt-up`
2. Modify a flavor's cluster template to fail webhook validation
3. The command shows as passed once calico comes up

**What did you expect to happen:**
The command fails immediately when an error occurs while creating a cluster.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 1.7
- Kubernetes version: (use `kubectl version`): 1.26.1
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/help

the issue is likely due to the fact that commands are separated by `;` instead of `&&`

**Comment by swastik959** [comment]
@CecileRobertMichon hi again can you please tell me the exact location of the file

**Comment by willie-yao** [comment]
@swastik959 thank you for taking a look! Are you still planning on working on this issue? If so, you can assign yourself to the issue.

**Comment by Sajiyah-Salat** [comment]
`` flavor_cmd += "&& until " + kubectl_cmd + " get secret ${CLUSTER_NAME}-kubeconfig > /dev/null 2>&1&& do sleep 5&& done; " + kubectl_cmd + " get secret ${CLUSTER_NAME}-kubeconfig -o jsonpath={.data.value} | base64 --decode > ./${CLUSTER_NAME}.kubeconfig; chmod 600 ./${CLUSTER_NAME}.kubeconfig; until " + kubectl_cmd + " --kubeconfig=./${CLUSTER_NAME}.kubeconfig get nodes > /dev/null 2>&1; do sleep 5; done" ``  I have made changes on the basis of your suggestion. would you like to see this? I will open a  pr on the basis of your suggestions.
