### ISSUE TITLE
BYO Azure VNet

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#314]
/kind feature

A customer provides their own Azure VNet resource id, and CAPZ doesn't provision it's own VNet. Instead it uses the already created Azure VNet.

**Comment by justaugustus** [comment]
Closed as duplicate of #178.
/close

**Comment by justaugustus** [comment]
jk, reopening.
/assign @CecileRobertMichon 
/reopen
/milestone next
/priority important-soon
