### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#318]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Allow creating IPv6 clusters in Azure with cluster-api.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by justaugustus** [comment]
@aojea -- do you have any interest in working on this one?

/help
/priority important-longterm

ref: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1322

**Comment by aojea** [comment]
> @aojea -- do you have any interest in working on this one?
> 

yeah, why not ;) ?

I have to finish the aws one first, will let you know once I have a bit more of free time

**Comment by jsturtevant** [comment]
I can pick this up.

**Comment by lachie83** [comment]
@jsturtevant - Here is an IPv6 cluster def for AKS-Engine which should help you through - https://gist.github.com/aramase/a19fcbf1f309dab99600ee9c0d700fce

**Comment by lachie83** [comment]
Also some prerequisites on your subscription to make this work - https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ipv4-ipv6-dual-stack-cli#prerequisites

**Comment by lachie83** [comment]
@aramase is landing the docs on upstream AKS-Engine soon

**Comment by jsturtevant** [comment]
thanks! Got it started today.  I have also been referencing: 

- https://github.com/Azure/aks-engine/pull/2781
- https://github.com/Azure/aks-engine/tree/master/examples/dualstack
- https://github.com/Azure/aks-engine/pull/1424

**Comment by aojea** [comment]
Yay
