### ISSUE TITLE
Not possible to run CAPZ in AWS along with CAPA

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-azure#3206]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Follow the steps in the [Quick Start to create an AWS cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html)
2. `init` CAPA on the new AWS cluster with:
```
clusterctl init --infrastructure aws
```
3. move the cluster resources
```
clusterctl move --to-kubeconfig capi-quickstart.kubeconfig
```
4. Notice how the Machines get reconciled correctly:
```
➜  kubectl get machines
NAME                                   CLUSTER           NODENAME                                     PROVIDERID                              PHASE     AGE   VERSION
capi-quickstart-control-plane-4h8x2    capi-quickstart   ip-10-0-81-142.us-west-2.compute.internal    aws:///us-west-2a/i-0869147bee79c10ea   Running   20m   v1.26.0
capi-quickstart-md-0-b6b69c88b-8pc6v   capi-quickstart   ip-10-0-126-230.us-west-2.compute.internal   aws:///us-west-2a/i-0703c9136ee0070a8   Running   20m   v1.26.0
capi-quickstart-md-0-b6b69c88b-9hp5l   capi-quickstart   ip-10-0-75-178.us-west-2.compute.internal    aws:///us-west-2a/i-04014fc8056b658b2   Running   20m   v1.26.0
capi-quickstart-md-0-b6b69c88b-fxj9k   capi-quickstart   ip-10-0-98-96.us-west-2.compute.internal     aws:///us-west-2a/i-09c8e9003149b88d9   Running   20m   v1.26.0
```
5. `init` CAPZ on the AWS cluster
```
clusterctl init --infrastructure azure
```
6. Delete the CAPA pod:
```
kubectl delete pods -l cluster.x-k8s.io/provider=infrastructure-aws -n capa-system
```
7. Check the CAPA pod logs and see errors
```
$ kubectl logs -n capa-system -l cluster.x-k8s.io/provider=infrastructure-aws
E0228 01:29:32.215084       1 controller.go:326] "Reconciler error" err="failed to describe instance by id" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="default/capi-quickstart-md-0-9xtth" namespace="default" name="capi-quickstart-md-0-9xtth" reconcileID=640b044e-a92c-4760-a5d6-b48e47c79ce7
```
8. Check the logs of the NMI pod on the Node where CAPA is running (`192.168.98.199` is CAPA pod IP):
```
kubectl logs -n capz-system                         capz-nmi-qkh2k
I0228 01:18:03.794076       1 main.go:90] starting nmi process. Version: v1.8.14. Build date: 2022-12-13-18:34.
I0228 01:18:03.799159       1 main.go:103] features for scale clusters enabled
I0228 01:18:03.907211       1 crd.go:448] CRD lite informers started
I0228 01:18:04.011184       1 main.go:117] running NMI in namespaced mode: true
I0228 01:18:04.011437       1 nmi.go:53] initializing in managed mode
I0228 01:18:04.011599       1 probes.go:41] initialized health probe on port 8085
I0228 01:18:04.011716       1 probes.go:44] started health probe
I0228 01:18:04.011974       1 metrics.go:341] registered views for metric
I0228 01:18:04.012187       1 prometheus_exporter.go:21] starting Prometheus exporter
I0228 01:18:04.012328       1 metrics.go:347] registered and exported metrics on port 9090
I0228 01:18:04.012557       1 server.go:127] listening on 127.0.0.1:2579
W0228 01:18:04.308237       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
E0228 01:18:36.470226       1 server.go:561] metadata header is not specified, req.method=PUT reg.path=/latest/api/token req.remote=192.168.98.199
E0228 01:18:36.478835       1 server.go:561] metadata header is not specified, req.method=PUT reg.path=/latest/api/token req.remote=192.168.98.199
...
```

**What did you expect to happen:**
Deploying CAPZ controller on AWS should not break CAPA.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I see that there are some rules on how NMI pod handles the requests, but looks like it will always fallback to the default handler https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L118, is this expected?

From what I understand https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2924 changes the architecture and this will not be an issue any more? Are there any other workarounds or maybe something that Im missing that could help me now?

**Environment:**

- cluster-api-provider-azure version: 
```
➜  kubectl get provider -A
NAMESPACE                           NAME                    AGE   TYPE                     PROVIDER      VERSION
capa-system                         infrastructure-aws      36m   InfrastructureProvider   aws           v2.0.2
capi-kubeadm-bootstrap-system       bootstrap-kubeadm       36m   BootstrapProvider        kubeadm       v1.3.3
capi-kubeadm-control-plane-system   control-plane-kubeadm   36m   ControlPlaneProvider     kubeadm       v1.3.3
capi-system                         cluster-api             37m   CoreProvider             cluster-api   v1.3.3
capz-system                         infrastructure-azure    28m   InfrastructureProvider   azure         v1.7.2
```
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dkoshkin** [comment]
As soon as I delete the CAPZ infra provider, CAPA works again
```
$ clusterctl delete --infrastructure azure --include-crd
Deleting Provider="infrastructure-azure" Version="" Namespace="capz-system"
$ kubectl delete pods -l cluster.x-k8s.io/provider=infrastructure-aws -n capa-system
pod "capa-controller-manager-86d665c46-g2w9g" deleted
$ kubectl logs -n capa-system -l cluster.x-k8s.io/provider=infrastructure-aws
...
I0228 01:49:56.354015       1 server.go:148] "controller-runtime/webhook: Registering webhook" path="/validate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane"
I0228 01:49:56.354163       1 logr.go:261] "controller-runtime/builder: Conversion webhook enabled" GVK="controlplane.cluster.x-k8s.io/v1beta2, Kind=AWSManagedControlPlane"
I0228 01:49:56.354256       1 logr.go:261] "setup: starting manager" version="v2.0.2"
I0228 01:49:56.354382       1 server.go:216] "controller-runtime/webhook/webhooks: Starting webhook server"
I0228 01:49:56.354469       1 internal.go:362] "Starting server" kind="health probe" addr="[::]:9440"
I0228 01:49:56.354557       1 internal.go:362] "Starting server" path="/metrics" kind="metrics" addr="127.0.0.1:8080"
I0228 01:49:56.365142       1 logr.go:261] "controller-runtime/certwatcher: Updated current TLS certificate"
I0228 01:49:56.365295       1 logr.go:261] "controller-runtime/webhook: Serving webhook server" host="" port=9443
I0228 01:49:56.365465       1 logr.go:261] "controller-runtime/certwatcher: Starting certificate watcher"
I0228 01:49:56.455690       1 leaderelection.go:248] attempting to acquire leader lease capa-system/controller-leader-elect-capa...
I0228 01:50:14.556353       1 leaderelection.go:258] successfully acquired lease capa-system/controller-leader-elect-capa
...
I0228 01:50:14.696725       1 logger.go:68] "Reconciling AWSCluster" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" aWSCluster="default/capi-quickstart" namespace="default" name="capi-quickstart" reconcileID=fabc555c-63d8-48dd-b665-67117a4898d9 cluster="default/capi-quickstart"
I0228 01:50:14.771191       1 controller.go:227] "Starting workers" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" worker count=5
I0228 01:50:18.080685       1 logger.go:68] "Reconciling subnets" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" aWSCluster="default/capi-quickstart" namespace="default" name="capi-quickstart" reconcileID=fabc555c-63d8-48dd-b665-67117a4898d9 cluster="default/capi-quickstart"
I0228 01:50:18.977868       1 logger.go:68] "Reconciling AWSCluster" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" aWSCluster="default/capi-quickstart" namespace="default" name="capi-quickstart" reconcileID=4a40ebb6-7e9a-4d46-b3f7-18c8c044affb cluster="default/capi-quickstart"
I0228 01:50:19.163881       1 logger.go:68] "Reconciling subnets" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" aWSCluster="default/capi-quickstart" namespace="default" name="capi-quickstart" reconcileID=4a40ebb6-7e9a-4d46-b3f7-18c8c044affb cluster="default/capi-quickstart"

**Comment by aramase** [comment]
> From what I understand https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2924 changes the architecture and this will not be an issue any more? Are there any other workarounds or maybe something that Im missing that could help me now?

that's right! CAPZ is moving to use Azure Workload Identity (WI) and when that's available, this should no longer be a problem. There are NMI like components in WI.

> I see that there are some rules on how NMI pod handles the requests, but looks like it will always fallback to the default handler https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L118, is this expected?

That is the expected behavior. However I think we can relax the [metadata header required check](https://github.com/Azure/aad-pod-identity/blob/master/pkg/nmi/server/server.go#L560) in the default path handler and just forward the request without any validation. That'll prevent such issues in the future. 


> From what I understand https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2924 changes the architecture and this will not be an issue any more? Are there any other workarounds or maybe something that Im missing that could help me now?

For the time being, you can set `--metadata-header-required=false` in the NMI args [here](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L483). That should skip the validation and forward the request to IMDS irrespective of running on Azure/AWS.

**Comment by CecileRobertMichon** [comment]
> For the time being, you can set --metadata-header-required=false in the NMI args [here](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L483). That should skip the validation and forward the request to IMDS irrespective of running on Azure/AWS.

@aramase is this something we should set for all CAPZ users?

**Comment by dkoshkin** [comment]
> For the time being, you can set --metadata-header-required=false in the NMI args [here](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L483). That should skip the validation and forward the request to IMDS irrespective of running on Azure/AWS.

Thank you, let me try that. I will report back.

**Comment by dlipovetsky** [comment]
If I understand correctly, NMI intercepts all requests to the metadata service on the machine where it runs. The above flag may allow NMI to process requests from a CAPZ process that runs on an EC2 instance.

However, what will happen to requests destined not for Azure, but for the EC2 metadata service, made by other processes running on the machine? :thinking:

**Comment by dkoshkin** [comment]
Ok I think I understand some more [aramase](https://github.com/aramase) after rereading your response.


>E0228 01:18:36.478835       1 server.go:561] metadata header is not specified, req.method=PUT reg.path=/latest/api/token req.remote=192.168.98.199

The error I was seeing in the NMI pod is from
[this code](https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L560-L564) because the AWS metadata requests do not have this header. (I thought this was something that the Azure API was returning.)

Please correct me if I'm misunderstanding but: 

1. setting `--metadata-header-required=false` disables this check in the NMI pod. **Is it safe to disable the check, I _think_ the Azure API will still deny this request?**
2. the requests to AWS metadata API gets still proxied by the NMI pod without any changes so the request can succeed and is handled in [here](https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L559). This works because the [AWS metadata API](https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L573-L576) is the same host and port. **What happens to non metadata requests, are they still proxied?**

**Comment by dkoshkin** [comment]
Also wanted to report that with the suggested flag `--metadata-header-required=false` I was able to have a management cluster running in AWS with both CAPZ and CAPA working to provision new workload clusters 🎉 .

It would still be great to get some clarification on my previous questions 😄

**Comment by aramase** [comment]
> If I understand correctly, NMI intercepts all requests to the metadata service on the machine where it runs. The above flag may allow NMI to process requests from a CAPZ process that runs on an EC2 instance.

NMI intercepts all requests to IMDS (`169.254.169.254`). If the request is for a token, decides to forward/deny the request based on validation. For any other request, it'll just forward the request to IMDS as is. The flag in question here is to check if the `Metadata: true` header is set as part of the request. Azure IMDS performs this check too but we want to fail early and hence the flag. Disabling/enabling is not specific to CAPZ process.

> setting --metadata-header-required=false disables this check in the NMI pod. Is it safe to disable the check, I think the Azure API will still deny this request?

That's correct! For token requests, if `Metadata: true` is not set, the SDK used in NMI will set the header as part of the new request. For any other request, NMI will forward the request as is and IMDS will perform the header enforcement.

> the requests to AWS metadata API gets still proxied by the NMI pod without any changes so the request can succeed and is handled in [here](https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L559). This works because the [AWS metadata API](https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/nmi/server/server.go#L573-L576) is the same host and port. What happens to non metadata requests, are they still proxied?

Any request that doesn't match the token URI will be proxied.

Apologies for the delay! I was caught up with the Kubernetes `v1.27` code freeze. If you do need any further clarifications, let me know!

**Comment by aramase** [comment]
> > For the time being, you can set --metadata-header-required=false in the NMI args [here](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L483). That should skip the validation and forward the request to IMDS irrespective of running on Azure/AWS.
> 
> @aramase is this something we should set for all CAPZ users?

If the NMI installed by CAPZ is used solely with CAPZ + service principal, setting the flag to false by default would be fine as we're not really talking to IMDS. If we think users consume the NMI installed with MSI when running on Azure environments, I would recommend we still keep it set to `true`.

**Comment by dlipovetsky** [comment]
> NMI intercepts all requests to IMDS (169.254.169.254). If the request is for a token, decides to forward/deny the request based on validation.

I _think_ this is not the correct order. It sounds like the correct order is: "NMI intercepts all requests, validates them, then forwards requests for a token," because the [default path handler performs validation](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3206#issuecomment-1453919508).

(We can work around this by disabling the metadata header check when running NMI outside of Azure, but enabling it inside of Azure)

**Comment by CecileRobertMichon** [comment]
Not planning on fixing as there was a workaround provided and we are actively migrating away from NMI altogether as part of AAD Pod Identity deprecation (in favor of Workload Identity)

/close
