### ISSUE TITLE
Tilt warning about port mapping

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3219]
/kind bug

**What steps did you take and what happened:**

Follow the [tilt developer instructions](https://capz.sigs.k8s.io/developers/development.html#tilt-for-dev-in-capz) and run `make tilt-up`. See that the `metrics: prometheus-operator` component under the "observability" tab reports this warning:

```
k8s_resource(name='metrics: prometheus-operator', port_forwards='9090') currently maps localhost:9090 to port 8080 in your container.
A future version of Tilt will change this default and will map localhost:9090 to port 9090 in your container.
To keep your project working, change your Tiltfile to k8s_resource(name='metrics: prometheus-operator', port_forwards='9090:8080')
```

It seems to require a simple change in the `Tiltfile` at the root of this project, as described in the warning above.

**What did you expect to happen:**

The component should start up without this warning.

**Anything else you would like to add:**

**Environment:**

- tilt version: v0.31.2
- cluster-api-provider-azure version: main

**Comment by Sajiyah-Salat** [comment]
Ihave never worked on cluster api in real world and I am a beginner can you locate me to the file which requires a change.

**Comment by mboersma** [comment]
The file that needs to change is `Tiltfile` in the root of the project, probably at [line 169](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/Tiltfile#L169).

Here is the reference for how to specify the `port_forwards` statement: https://docs.tilt.dev/tiltfile_concepts.html#configuring-kubernetes-resources We're using the last of those four methods, so probably we just need to add `8080` as the second argument, before `name = "View metrics"`.

You can test that your changes work by running `make tilt-up` as described in the [developer docs](https://capz.sigs.k8s.io/developers/development.html#tilt-for-dev-in-capz) and clicking through to the Prometheus metrics component, as described at the end of the observability [README.md](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/hack/observability#observability).

**Comment by Sajiyah-Salat** [comment]
It should be ``port_forwards = [port_forward(9090, 8080, name = "View metrics")]`` right?

**Comment by mboersma** [comment]
@Sajiyah-Salat yes, I think that's correct. 👍🏻

**Comment by Sajiyah-Salat** [comment]
Ohk, I will start a pr shortly.

**Comment by mboersma** [comment]
> Do you think the second step requires me to clone this on my local pc and run `make tilt-up` to test my changes?

In general, yes. That way you can see the problem and verify that you've fixed it. For #3230 it's very simple and I verified that it makes the warning disappear–thank you! For #3231, you should probably get up to speed with the `tilt` developer setup as described in our docs, so you can test your changes.

**Comment by mboersma** [comment]
In this case, I was wrong: I read the warning message and assumed it was correct about us needing to map container port 8080. It turns out that prometheus initially does open port 8080, but then uses port 9090 for its web interface.

Sorry about that! If you can update the port, it should work.

(This is indeed a case where manual testing is necessary: we don't have automated tests for `make tilt-up` and may never have them.)

**Comment by Sajiyah-Salat** [comment]
port_forwards = [port_forward(9090, 8080, name = "View metrics")] right?

**Comment by mboersma** [comment]
No, `port_forward(9090, 9090, name = "View metrics")`, but it looks like you figured that out in the PR. 👍🏻
