### ISSUE TITLE
Windows pod error: failed to setup network for sandbox

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#3227]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Our VMSS tests include a step to validate a LoadBalancer that sits in front of a Windows pod. Those tests occasionally fail because that pod reports:

```
  Warning  FailedCreatePodSandBox  24m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6587e3b5ab2f01bbc40aef99de40539a4b7c77e9579efcdec323a404ce7baafc": plugin type="calico" failed (add): global strict affinity should not be false for Windows node
  Warning  FailedCreatePodSandBox  63s (x103 over 24m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1794612b2e974afa3866f41153f7e104c0fbc9bfd16951c00ac77fd8c703e9a2": plugin type="calico" failed (add): global strict affinity should not be false for Windows node
```

Node metadata for the Windows node that the pod was scheduled onto does not report anything that suggests root cause:

https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1631536507762249728/artifacts/clusters/capz-e2e-0wup7c-vmss/nodes/win-p-win000001/node-describe.txt

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by marosset** [comment]
@mikezappa87

**Comment by MikeZappa87** [comment]
We should involve someone from Tigera to look at this.

**Comment by jackfrancis** [comment]
Would calico logs from any particular pods be helpful?

**Comment by jackfrancis** [comment]
Another repro: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3213/pull-cluster-api-provider-azure-e2e/1632900919190360064

**Comment by jsturtevant** [comment]
This looks like a calico issue.  Can we get an issue opened up over there?

**Comment by jackfrancis** [comment]
Another repro: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3233/pull-cluster-api-provider-azure-e2e/1633158733745885184

**Comment by jackfrancis** [comment]
Another repro: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3237/pull-cluster-api-provider-azure-e2e/1633238845682094080

**Comment by jsturtevant** [comment]
We saw a similar in the upstream tests, slightly different reason for the pod error https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-2022/1634644207173898240

**Comment by CecileRobertMichon** [comment]
@marosset @MikeZappa87 is the next step to open an issue in the Calico repo?

**Comment by MikeZappa87** [comment]
That seems reasonable. This doesn't happen often correct? Should we slow down the tests to ensure the cluster is formed and actually ready as something we can do in parallel?

**Comment by jackfrancis** [comment]
FWIW this flake *does* happen often. We see it on multiple PR flows daily (haven't run a concrete study to measure flake rate but it has definitely risen to the level of negatively impacting project velocity).

I'm not sure slowing down the tests will help, but perhaps I don't understand the suggestion entirely.

**Comment by MikeZappa87** [comment]
Looking at some of the failure it looks like the CNI binaries or network configuration is not present. That should be the calico daemonset placing those in the respective directories. However I'm not sure if they are downloading them and it's taking longer than expected? I have in the past made a script that waits for those files to be present and the nodes marked as ready before running tests.

**Comment by jackfrancis** [comment]
@MikeZappa87 we do actually wait for the Windows daemonset pods to be running. In [this](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3213/pull-cluster-api-provider-azure-e2e/1632900919190360064/build-log.txt) repro log output you can see these statements:

```
  [1mSTEP:[0m waiting for 2 daemonset calico-system/calico-node-windows pods to be Running [38;5;243m@ 03/07/23 00:48:55.447[0m
  [1mSTEP:[0m waiting for 2 daemonset calico-system/calico-node-windows pods to be Running [38;5;243m@ 03/07/23 00:49:05.558[0m
  [1mSTEP:[0m waiting for 2 daemonset calico-system/calico-node-windows pods to be Running [38;5;243m@ 03/07/23 00:49:15.671[0m
  Mar  7 00:49:15.671: INFO: 2 daemonset calico-system/calico-node-windows pods are running, took 20.333968655s
```

We do that check during initial cluster bootstrapping, so any future test scenarios that run (e.g., the ILB test in this case) will always run after those calico-system pods are verified as running.

**Comment by CecileRobertMichon** [comment]
Here is the data: https://storage.googleapis.com/k8s-triage/index.html?text=%2Fhome%2Fprow%2Fgo%2Fsrc%2Fsigs.k8s.io%2Fcluster-api-provider-azure%2Ftest%2Fe2e%2Fhelpers.go%3A121

21 occurrences since 3/3

**Comment by CecileRobertMichon** [comment]
It's get hard to merge a PR... wondering if we should temporarily disable that check until we can figure it out.

**Comment by marosset** [comment]
Can we see if https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3311 fixes anything?
If it doesn't I'm in favor of removing the Windows node pools from the VMSS tests until we sort the issue out.

**Comment by CecileRobertMichon** [comment]
Based on timing alone, the start of this flake seems to be related to the PR that switched templates to use the out-of-tree cloud-provider:

<img width="1261" alt="Screenshot 2023-03-17 at 11 16 58 AM" src="https://user-images.githubusercontent.com/8650424/225986630-7a7ff0ab-75c3-42cb-8162-e720ffe0fd5a.png">
![Screenshot 2023-03-15 at 11 37 24 AM](https://user-images.githubusercontent.com/8650424/225986633-32b8e11a-81aa-4d80-a777-f4034da3167a.png)

**Comment by marosset** [comment]
I'm going to set up some different periodic jobs to compare stability of in-tree vs out-of-tree cloud-provider for Windows. 
If it is the case that this is related to out-of-tree cloud-provider (which I also suspect it is) we can use those jobs as a signal out-of-tree cloud-provider stability too.

**Comment by mweibel** [comment]
If it's related to out-of-tree cloud-provider and not always happening (i.e. could be a timing issue), I have the strong suspicion that the cause is what I mentioned in #2591:

> I just installed the latest helm chart version and it generally seems to work, however sometimes the cloud node manager still fails to start up
>  In those cases it seems that the replace in powershell: [...]
> is working but the kubeconfig is overwritten right afterwards. We verified this by sshing to a node which failed and checked the file which didn't have the path rewritten. When we executed it again manually, it also switched back again to the original value.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2591#issuecomment-1453717172

I suggest to give this change a try (and or find the root cause why it's overwriting).

**Comment by CecileRobertMichon** [comment]
I pushed those changes to my fork of cloud-provider-azure [here](https://github.com/CecileRobertMichon/cloud-provider-azure/commit/f6ad27ea956b8bdc9ee26c0fff0c6520d6a7520d) and trying to test these changes in our PR e2e test: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3330

**Comment by jackfrancis** [comment]
Some observed data on a repro:

- `Sending VTEP update node`... log messages are missing for windows nodes (messages are present for control plane and linux nodes
- `2023-03-17 21:10:14.030 [WARNING][4844] felix/win_dataplane.go 348: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*` error is not present in the success case, but is present in the repro case

**Comment by CecileRobertMichon** [comment]
> I pushed those changes to my fork of cloud-provider-azure [here](https://github.com/CecileRobertMichon/cloud-provider-azure/commit/f6ad27ea956b8bdc9ee26c0fff0c6520d6a7520d) and trying to test these changes in our PR e2e test: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3330

So far the job is passing on the PR but the repro @jackfrancis observed above was with my branch so it looks like this doesn't fix it

**Comment by jsturtevant** [comment]
We are seeing this in 1.24 and 1.25 release jobs as well: 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-1-24/1638210865394094080
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-containerd-windows-1-25/1638209355281076224

```
0321 16:29:31.491318    3940 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-2-4vrss_img-puller-561(ca2daa6e-31e5-4518-b525-e86b6f04d41d)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-2-4vrss_img-puller-561(ca2daa6e-31e5-4518-b525-e86b6f04d41d)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"89e46200c905d908f3da0ceb71f3147302b15a5d0faa5a9baad38d54d6294c17\\\": plugin type=\\\"calico\\\" failed (add): global strict affinity should not be false for Windows node\"" pod="img-puller-561/img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-2-4vrss" podUID=ca2daa6e-31e5-4518-b525-e86b6f04d41d
```
