### ISSUE TITLE
non-determinate test result: FuzzTestFunc

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#3247]
**Which jobs are failing:**

See here for a repro:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3238/pull-cluster-api-provider-azure-test/1633551693771706368

**Which tests are failing:**

**Since when has it been failing:**

**Testgrid link:**

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by nojnhuh** [comment]
This test no longer exists, and I'm guessing it was part of the conversion webhooks that were removed when v1alpha3 and v1alpha4 were removed from CAPZ.

/close

**Comment by nojnhuh** [comment]
@CecileRobertMichon @dtzar Seems odd that the bot didn't close this already since it seems there hasn't been any activity for over 6 months:

> * After 30d of inactivity since `lifecycle/rotten` was applied, the issue is closed
