### ISSUE TITLE
Exclude E2E tests for documentation-only PRs

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#3248]
/kind feature

**Describe the solution you'd like**
When there are only documentation changes in a PR, ignore / do not run any of the E2E tests since this is a waste of time and money.

Some example PRs:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3116
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3161

**Comment by CecileRobertMichon** [comment]
This is our current regex: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-main.yaml#L60

Looks like the first one didn't run the e2e job, as expected. The second did, I believe because the .codespellignore file changed. We could exclude that too.

**Comment by dtzar** [comment]
@mboersma Did you have another job to provide as an example which unnecessarily ran e2e tests for just docs?

**Comment by CecileRobertMichon** [comment]
Another PR type that shouldn't be running e2e tests but does: OWNER file updates https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3208

**Comment by mboersma** [comment]
#3268 only changes a markdown file, but ran all the tests.

**Comment by mboersma** [comment]
#3266 is another markdown-only change that spawned all the tests.

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3368 successfully didn't run e2e tests 🎉

**Comment by mboersma** [comment]
@CecileRobertMichon I also created #3366 and #3367 yesterday just to test that this is working. Looks good! Thank you for fixing this.
