### ISSUE TITLE
pull-cluster-api-provider-azure-e2e failing

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#3251]
**Which jobs are failing:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Which tests are failing:**
```
capz-e2e: [It] Workload cluster creation Creating a highly available cluster [REQUIRED] With 3 control-plane nodes and 2 Linux and 2 Windows worker nodes expand_less
capz-e2e: [It] Workload cluster creation Creating a VMSS cluster [REQUIRED] with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes expand_less
```

**Since when has it been failing:**
Last successful run was Mar 08 18:16:04. 

**Testgrid link:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Reason for failure (if possible):**
```
  Mar  9 14:50:51.270: INFO: Error starting logs stream for pod kube-system/kube-proxy-windows-j29wv, container kube-proxy: container "kube-proxy" in pod "kube-proxy-windows-j29wv" is waiting to start: trying and failing to pull image
```

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by mweibel** [comment]
latest run failed now with not being able to pull `k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine`.

**Comment by marosset** [comment]
I'm not sure how e2e-test images get published to k8sprow.azurecr.io but `registry.k8s.io/e2e-test-images/https:2.4.39-alpine` exists

> regctl tag ls registry.k8s.io/e2e-test-images/httpd
2.4.38-1
2.4.38-2
2.4.38-4
2.4.38-alpine
2.4.39-1
2.4.39-2
2.4.39-4
2.4.39-alpine

**Comment by marosset** [comment]
It also looks like we've never pushed a httpd image to `k8sprow.azurecr.io`

> $ regctl repo list k8sprow.azurecr.io                                                                                                                                        
time="2023-03-09T14:05:10-08:00" level=warning msg="Changing credential host for registry" host=docker.io new=docker.io/mrosse3 orig="https://index.docker.io/v1/"           
azdiskschedulerextender-csi                                                                                                                                                  
azure-cloud-controller-manager-arm64                                                                                                                                         
azuredisk-csi                                                                                                                                                                
azurefile-csi                                                                                                                                                                
blob-csi                                                                                                                                                                     
driver                                                                                                                                                                       
driver-crds                                                                                                                                                                  
kube-apiserver-amd64                                                                                                                                                         
kube-controller-manager-amd64                                                                                                                                                
kube-proxy-amd64                                                                                                                                                             
kube-scheduler-amd64                                                                                                                                                         
kubernetes-e2e-test-images/jessie-dnsutils                                                                                                                                   
kubernetes-e2e-test-images/k8s-directx-device-plugin                                                                                                                         
kubernetes-e2e-test-images/pause                                                                                                                                             
kubernetes-e2e-test-images/port-forward-tester                                                                                                                               
kubernetes-e2e-test-images/webhook                                                                                                                                           
nfsplugin                                                                                                                                                                    
rg-cleanup      

Did some config for this job relating the image repos used by e2e jobs change recently?
@jackfrancis @CecileRobertMichon ?

**Comment by Jont828** [comment]
I noticed this is failing in several periodic jobs as well, figured I'd link them here instead of opening a new issue

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-6/1633833959483772928
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-7/1633834715536429056
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1633892345621516288

**Comment by CecileRobertMichon** [comment]
> Did some config for this job relating the image repos used by e2e jobs change recently?

Not that I know. And what's strange is that we're setting the registry variable as:

```
      - name: REGISTRY
        value: capzci.azurecr.io
```

so unclear where the `k8sprow.azurecr.io` reference is coming from

**Comment by mweibel** [comment]
looking for 'k8sprow.azurecr' in the repo yields the following result:
https://github.com/search?q=repo%3Akubernetes-sigs%2Fcluster-api-provider-azure%20k8sprow.azurecr&type=code

not sure about all instances but this one in particular seems relevant:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0f497f833a710ad2ad720124f2dd3003da9326e8/test/e2e/kubernetes/windows/windows.go#L53-L62
