### ISSUE TITLE
Failed to get controller-runtime client in release 1.6 e2e test

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#3253]
**Which jobs are failing:** periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-6

**Which tests are failing:** Running the Cluster API E2E tests Running the MachineDeployment rollout spec Should successfully upgrade Machines upon changes in relevant MachineDeployment fields

**Since when has it been failing:** 2/25, 2/28, 3/6, and 3/9 (periodic job)

**Testgrid link:** https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-6/1633800237560631296

**Reason for failure (if possible):** Failed to get controller runtime, connection refused error. I'm not sure if it's a flake but it seems to have failed a few tiems

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
@Jont828 was this only seen in release-1.6 jobs? If so we can probably close this since 1.6 is no longer being tested since 1.8 is out.

**Comment by jackfrancis** [comment]
Closing as we no longer test release-1.6 branch
