### ISSUE TITLE
Add support for Confidential VMs and Trusted launch for VMs

### ISSUE THREAD

**Issue by mresvanis** [kubernetes-sigs/cluster-api-provider-azure#3264]
/kind feature

**Describe the solution you'd like**
I would like to be able to spawn [Azure Confidential VMs](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-vm-overview) and to enabled [Trusted launch for VMs](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch). 

Confidential VMs provide protection to data-in-use by encryption the VM memory with keys that Azure doesn't have access to. Those VMs can also be [attested](https://learn.microsoft.com/en-us/azure/attestation/overview) by the user. 

See [Azure Confidential Computing](https://learn.microsoft.com/en-us/azure/confidential-computing/overview) for more details. 

Trusted launch for VMs provide [SecureBoot](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot) and [vTPM](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#vtpm) attestation.

**Anything else you would like to add:**
Confidential VMs require specific [OS images](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-vm-overview#os-support).
Trusted launch for VMs include [these limitations](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#limitations).

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
/assign @mresvanis 

Assigning this since you've started working on this in the PR. Thanks!
