### ISSUE TITLE
Links in PR template are not very useful

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-azure#3266]
/kind bug

Right now PR template contains the following:
```
 <!-- If this is your first PR, welcome! Please make sure you read the [contributing guidelines](../CONTRIBUTING.md). -->
```

However, link to `CONTRIBUTING.md` is not being expanded, which creates rather clunky UX.

Can we make this link absolute perhaps so it can be copy-pasted into browser tab for example?

**Comment by Sajiyah-Salat** [comment]
I am happy to work on this. /assign
