### ISSUE TITLE
Custom CCM CI build flows don't work on macos

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#3292]
The `export CCM_IMG_ARGS` part of `ci-entrypoint.sh` doesn't work on macos. Let's decompose the helm args in a way that works all common bash environments.

One way would be to use local values.yaml files, e.g.:

```bash
cat <<EOF > "${CLOUD_PROVIDER_HELM_VALUES_CUSTOM_BUILD}"
 cloudControllerManager:
   imageRepository: "${IMAGE_REGISTRY}"
   imageName: "${CCM_IMAGE_NAME}"
   imageTag: "${IMAGE_TAG}"
 cloudNodeManager:
   imageRepository: "${IMAGE_REGISTRY}"
   imageName: "${CNM_IMAGE_NAME}"
   imageTag: "${IMAGE_TAG}"
 EOF
```

except do the above using kustomize, not inline in ci-entrypoint

There are lots of references in this stackoverflow thread:

- https://stackoverflow.com/questions/5564418/exporting-an-array-in-bash-script

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
@jackfrancis are you working on this?
