### ISSUE TITLE
Test CAPI with release 1.4 RC 

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3297]
Release candidate for v1.4.0 release of CAPI is out: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0-rc.0

We should bump the version of CAPI in CAPZ and run all the tests with it to help validate the new release and ensure there are no regressions.

See [the Cluster-API book](https://main.cluster-api.sigs.k8s.io/developer/providers/v1.3-to-v1.4.html) for an overview of relevant changes between Cluster API v1.3 and v1.4 that may need changes in CAPZ.

**Comment by nawazkh** [comment]
Ah, I didn't realize that the `"` would be added. Sorry for Creating the churn. 
/retitle Update CAPI to 1.4.1
