### ISSUE TITLE
Skip AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host and AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port validation while cluster is paused/moved

### ISSUE THREAD

**Issue by tapojit047** [kubernetes-sigs/cluster-api-provider-azure#3303]
/kind bug

**What steps did you take and what happened:**
- Create a local kind cluster.
- Set `EXP_MACHINE_POOL=true` and `EXP_AKS=true`.
- `clusterctl init` with `--infrastructure azure`.
- `clusterctl generate cluster` with `--flavor aks`.
- Init the target cluster (same as 3).
- `clusterctl move` from local `kind` to target AKS.
- Notice the error below:
```azure
clusterctl move --to-kubeconfig=$AZURE_KUBECONFIG
Performing move...
Discovering Cluster API objects
Moving Cluster API objects Clusters=1
Moving Cluster API objects ClusterClasses=0
Creating objects in the target cluster
Error: action failed after 10 attempts: error creating "infrastructure.cluster.x-k8s.io/v1beta1, Kind=AzureManagedControlPlane" default/new-cluster5: admission webhook "validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io" denied the request: Spec.ControlPlaneEndpoint.Host: Forbidden: can not be set by the user, will be set automatically by AKS after the cluster is Ready
```

**What did you expect to happen:**

I expect `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host` and  `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port` can be assigned while performing `clusterctl move`. 

**Anything else you would like to add:**
- The error is raised [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcontrolplane_webhook.go#L119).
- I expect that `clusterctl move` operation to be executed successfully.
- For that, maybe the webhook can check whether the `cluster` object of the `AzureManagedControlPlane` has the `spec.paused` set to `true` and `skip` the two aforementioned conditions of `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host` and `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port`.
- Or maybe `clusterctl move` should annotate the objects it is `moving` and then webhooks would honour that.

**Environment:**

- cluster-api-provider-azure version: `v1.8.0`
- Kubernetes version: (use `kubectl version`): `v1.26.2`

**Comment by CecileRobertMichon** [comment]
cc @jackfrancis

**Comment by tarlov** [comment]
+1 
Is there any workaround for this exception?

**Comment by CecileRobertMichon** [comment]
@jackfrancis @nojnhuh is either of you able to take a look at this one?

**Comment by jackfrancis** [comment]
@CecileRobertMichon I think something like this should take care of AzureManagedControlPlane:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3341

We're also validating this same situation for `AzureManagedCluster`, and I assume we'll have to fix that as well. One observation: we aren't setting up the `AzureManagedCluster` webhook in the same way we're setting up others; we're just adding validate methods onto the `AzureManagedCluster` type struct:

-  https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcluster_webhook.go#L45-L46

Compare to:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcontrolplane_webhook.go#L52-L67

Cursory research suggests that the `AzureManagedCluster` variety is the outlier. Do we want to maybe refactor that as a separate, prerequisite change before we fix this?

**Comment by CecileRobertMichon** [comment]
@jackfrancis should we also add an e2e test for AKS? It's not the first bug we fix for ManagedClusters move would be good to add a test for it (maybe a self-hosted AKS cluster test)

**Comment by tarlov** [comment]
@CecileRobertMichon when could we expect this fix to be released?
