### ISSUE TITLE
clusterclass test spec fails often

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3313]
**Which jobs are failing:**

pull-cluster-api-provider-azure-e2e-optional
periodic-cluster-api-provider-azure-e2e-main

**Which tests are failing:**

"Creating clusters using clusterclass [OPTIONAL]"

**Since when has it been failing:**

Unclear, but at least for the last 2-3 days in PRs.

**Testgrid link:**

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3256/pull-cluster-api-provider-azure-e2e-optional/1636391586499661824
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1636248867903115264

**Reason for failure (if possible):**

"KubeadmControlPlane object capz-e2e-yadda-yadda was not initialized in time"

**Anything else we need to know:**

/kind failing-test

/area bootstrap

**Comment by CecileRobertMichon** [comment]
In logs I see

```
  - lastTransitionTime: "2023-03-16T17:53:48Z"
    message: 'admission webhook "default.azuremachine.infrastructure.cluster.x-k8s.io"
      denied the request: failed to fetch subscription ID for AzureMachine capz-e2e-jnl161/capz-e2e-jnl161-cc-control-plane-tknc2-49pdq:
      failed to find owner cluster for capz-e2e-jnl161/capz-e2e-jnl161-cc: AzureCluster.infrastructure.cluster.x-k8s.io
      "capz-e2e-jnl161-cc" not found'
    reason: InfrastructureTemplateCloningFailed
    severity: Error
    status: "False"
    type: MachinesCreated
 ```

@willie-yao this might be a race condition from #2965 that specifically occurs more often for clusterclass due to the order of operations?

**Comment by willie-yao** [comment]
Yup this is definitely a bug and I'll take a look. I'm not sure if it's a race condition if the AzureCluster name is incorrect, but I do remember having an issue where the names didn't match somewhere.. My memory is a bit fuzzy but I'll investigate further. Thanks for pointing this out!
/assign
