### ISSUE TITLE
MachinePool scale up causes CAPZ to make redundant PATCH requests on the VMSS

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3339]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

Reported by @zmyzheng:

My understanding is CAPZ first sets the target instance count, then in every round of loop, it compares the available instance count with the target count and sends a new put/patch request if it discovers available instance count does not match target count yet.

operationName | count_
-- | --
VirtualMachineScaleSets.ResourceOperation.PATCH | 1159
VirtualMachineScaleSets.ResourceOperation.PUT | 1

<p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><i><span style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: black !important;"> </span></i></p>

<p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><i><span style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;">Below shows the call to create the VMSS Flex</span></i><i><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;"></span></i></p><div class="R1UVb" has-hovered="true" style="border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, &quot;system-ui&quot;, Roboto, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(36, 36, 36); overflow: hidden; position: relative; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 59px; width: 547.578px;"><div class="qF8_5" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; opacity: 0; position: absolute; z-index: -1;"><button type="button" class="ms-Button ms-Button--icon wD8TJ root-370" title="Show original size" aria-label="Show original size" data-is-focusable="true" style="border: none; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: controlIcons !important; margin: 0px; padding: 8px; vertical-align: baseline; color: var(--white); outline: transparent; position: absolute; -webkit-font-smoothing: antialiased; border-radius: 2px; box-sizing: border-box; cursor: pointer; display: inline-block; text-decoration: none; text-align: center; width: 32px; height: 32px; background: var(--neutralPrimary); user-select: none; box-shadow: 0 0 5px var(--neutralSecondary); left: 5px; top: 5px; z-index: 1;"><span class="ms-Button-flexContainer flexContainer-164" data-automationid="splitbuttonprimary" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; display: flex; height: 16px; flex-wrap: nowrap; justify-content: center; align-items: center;"><i data-icon-name="FullScreen" aria-hidden="true" class="ms-Icon root-90 css-315 ms-Button-icon icon-291" style="display: inline-block; font-size: 16px; margin: 0px 4px; height: 16px; line-height: 16px; text-align: center; flex-shrink: 0; -webkit-font-smoothing: antialiased; font-style: normal; font-weight: normal; speak: none; font-family: controlIcons;"></i></span></button></div>

PreciseTimeStamp | operationName | httpStatusCode | e2EDurationInMilliseconds
-- | -- | -- | --
2023-03-05 12:18:01.8408654 | VirtualMachineScaleSets.ResourceOperation.PUT | 201 | 740603

</div><p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><i><span style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;"> </span></i><i><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;"></span></i></p><p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><i><span style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;"> </span></i><i><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 10pt; line-height: inherit; font-family: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;"></span></i></p><p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"><i><span style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(33, 33, 33) !important;">After the above patch call, there are 1158 calls for increasing the capacity to 200 which seems to be rebundant. Ideally, the client should wait for the scale up to finish.</span></i></p>

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@Jont828 I believe this is due to the fact that we are not checking for existing async operations before proceeding to patch the VMSS and should be fixed by #2719.

**Comment by Jont828** [comment]
I tried reproducing this on the main branch with VMSS flex using the cluster-template-prow-machine-pool-flex.yaml template. I was unable to reproduce the number of PATCH requests -- when scaling up to 200 replicas in one operation we had 2 PATCH requests as expected. I did, however, see 2082 PUT requests coming from the VMSS VMs, VM extensions, and other resources.

| operationName | count|
| -|-|
| PUT	| 2082|
| PATCH	| 2| 

I also looked into the query producing the 1700 PATCH requests and saw that they were all 200 status codes. I think a next step would be to try to repro on v1.7.0 of CAPZ in case something changed in main.

**Comment by CecileRobertMichon** [comment]
I tried to repro with v1.7.0 and I'm seeing the same results.

**Comment by CecileRobertMichon** [comment]
/close

Not able to reproduce
