### ISSUE TITLE
Image versioning / SKU naming

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#336]
Currently, the Azure Marketplace images published for capz follow this naming:

```
Offer        Publisher      Sku                     Urn                                                          Version
-----------  -------------  ----------------------  -----------------------------------------------------------  ----------
capi         cncf-upstream  k8s-1dot16-ubuntu-1804  cncf-upstream:capi:k8s-1dot16-ubuntu-1804:2019.11.04         2019.11.04
```

Then, the code fetches the `latest` version for the SKU matching the desired k8s version: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/328
https://github.com/Azure/cluster-api-provider-azure/blob/master/cloud/defaults.go#L152

The issue with this is that there is no way to distinguish between patch versions of Kubernetes. So if a user wants to create a cluster with e.g. `1.16.1` but the latest image in the 1.16 SKU is `1.16.2`, then the default image picked will be `1.16.2` and the cluster will come up with `1.16.2`.

We have the following constraints: 
- SKU ID must consist only of lowercase, alphanumeric characters, dashes or underscores. Cannot be modified once published. Max 50 characters.
- The number of versions per SKU is limited.
- version has to be in <number>.<number>.<number> format and has to be unique per SKU

We should consider the following info for image naming:
K8s version, OS type/distro, OS SKU, CNI (CNI version?), date published

Right now we only have a k8s `1.16` image published. Once we agree on the image naming format I will proceed and publish all the missing images.

**Comment by CecileRobertMichon** [comment]
cc @justaugustus @devigned @alexeldeib @serbrech

**Comment by devigned** [comment]
I think adding the full version of k8s to image SKU would make sense. So, we'd have `k8s-1dotXXdotXX` (15 chars) + OS type/distro (35 chars max?). 

I'm not so sure about CNI. Do you think it's really needed?

**Comment by CecileRobertMichon** [comment]
I've decided to go with @devigned's suggestion so the new SKU naming format will be:

k8s-1dotXXdotXX-OS-distro

eg. `k8s-1dot16dot4-ubuntu-1804`

We can always change this later, none of it is set in stone, but need to get the images out there for the release.
