### ISSUE TITLE
Support for AKS

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-azure#337]
/kind feature

**Describe the solution you'd like**
I'd like to see the ability to create/manage AKS clusters using Cluster API.  

**Anything else you would like to add:**

**This comes up a lot in discussions on capi with customers**. There was a mention in the capz call on 2019-12-05 and it was thought this type of functionality would be included in the current Azure provider. Be good to discuss the various options.

Relates to [cluster-api - 980](https://github.com/kubernetes-sigs/cluster-api/issues/980)

**Comment by juan-lee** [comment]
@richardcase can you elaborate on what customer expectations are around capi and AKS?

**Comment by StianOvrevage** [comment]
I'm one of the potential users of capi who kind of expected that to be supported already. We use managed K8s exclusively (AKS). I believe that will be the most common usage-pattern as well going forward across all K8s users.

**Comment by juan-lee** [comment]
@alexeldeib should we close this since it's done?

**Comment by alexeldeib** [comment]
/close 

follow-ups in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues?q=is%3Aissue+is%3Aopen+%5Bmanagedcluster%5D
