### ISSUE TITLE
Add missing test coverage for azuremachine_default.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3372]
/kind cleanup

**Describe the solution you'd like**
Currently, `azuremachine_default.go` is missing unit tests in the following areas:

- [SetIdentityDefaults()](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_default.go#L93): 
    - Test the case where both the deprecated field and the new `SystemAssignedIdentityRole.Name` field is set.
    - Ensure that no defaults are being set.    
    - Add this test case to the existing [TestAzureMachineSpec_SetIdentityDefaults](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_default_test.go#L56) function.
- [SetSpotEvictionPolicyDefaults()](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_default.go#L122) Add a new test for `SetSpotEvictionPolicyDefaults()` with cases covering the following inputs: 
    - nil SpotVMOptions
    - nil SpotVMOptions and non-nil SpotVMOptions.EvictionPolicy
    - non-nil SpotVMOptions and nil SpotVMOptions.EvictionPolicy
        - nil OSDisk.DiffDiskSettings
        - non-nil OSDisk.DiffDiskSettings and OSDisk.DiffDiskSettings.Option != "Local"
        - non-nil OSDisk.DiffDiskSettings and OSDisk.DiffDiskSettings.Option == "Local"

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nawazkh** [comment]
Awesome for picking it up @mhamdisemah 🚀 ! Let us know over slack in case you need any help driving this!

**Comment by willie-yao** [comment]
Hi @ashutosh887. This issue is already assigned to someone. I will let you know if it gets unassigned!

**Comment by aniruddha2000** [comment]
I can work on this too 😺, if no one is really working on it

/assign

Thanks!
