### ISSUE TITLE
Add missing test coverage for azuremachine_webhook.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3373]
/kind cleanup

**Describe the solution you'd like**
Currently, `azuremachine_webhook.go` is missing unit tests in the following areas:

- [ValidateUpdate()](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_webhook.go#L192)
    - Add test case to [TestAzureMachine_ValidateUpdate](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_webhook_test.go#L166) where the old `subnetName` is left blank and the current `subnetName` is populated

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by willie-yao** [comment]
@ashutosh887 Thanks for your interest in working on this issue! @Jim-Walk is already assigned and is working on this issue. If you would like to pick up an issue, please look for ones that are not already assigned to someone.

**Comment by aniruddha2000** [comment]
I want to take this if no one is working on it :)

**Comment by willie-yao** [comment]
@aniruddha2000 Sure I think @Jim-Walk is no longer working on this as the PR has been stale.

/unassign @Jim-Walk 
/assign @aniruddha2000

**Comment by aniruddha2000** [comment]
Do you know if we expect an error in this case? because I see -
```text
AzureMachine.infrastructure.cluster.x-k8s.io "" is invalid: spec.networkInterfaces: Invalid value: []v1beta1.NetworkInterface{v1beta1.NetworkInterface{SubnetName:"subnet1", PrivateIPConfigs:0, AcceleratedNetworking:(*bool)(nil)}}: field is immutable
```

```go
{
			name: "validTest: Spec.NetworkInterfaces.SubnetName will get populated on the first interface",
			oldMachine: &AzureMachine{
				Spec: AzureMachineSpec{
					NetworkInterfaces: []NetworkInterface{{SubnetName: ""}},
				},
			},
			newMachine: &AzureMachine{
				Spec: AzureMachineSpec{
					NetworkInterfaces: []NetworkInterface{{SubnetName: "subnet1"}},
				},
			},
			wantErr: false,
		},
```

here I am unsure how these new fields are getting populated - 

```text
PrivateIPConfigs:0, AcceleratedNetworking:(*bool)(nil)
```

@willie-yao could you give me some idea?

**Comment by willie-yao** [comment]
@aniruddha2000 The `AcceleratedNetworking` field is set on this line: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_webhook.go#L193

I'm not quite sure why it's detecting a diff though. I think this can be fixed by setting the `AcceleratedNetworking` field inside `s.NetworkInterfaces` in both the `oldMachine` and `newMachine`
