### ISSUE TITLE
securityRules should support source address in plural

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cluster-api-provider-azure#3377]
/kind feature

**Describe the solution you'd like**

As a _User_ i want to group multiple network sources into one `securityRule`. At the moment i have to specify for each source one `securityRule`.

**Anything else you would like to add:**

In theory it should be an easy one to extend the `securityRule` struct by a new field called `Sources` and do the conversion to [`SourceAddressPrefixes`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-08-01/network#SecurityRulePropertiesFormat) in [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/79c47714bfd637d9d979494af08310e712c855cf/azure/converters/rules.go#L26-L38).

But maybe it's also worth the discussion to keep the existing `Source` field and convert it directly to `SourceAddressPrefixes` as at least in theory, on Azure side nothing will (should) change.

**Environment:**

- cluster-api-provider-azure version: `1.9.0`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nawazkh** [comment]
This is still on my radar.

**Comment by nawazkh** [comment]
Started taking a look at this now, will update as I make progress.
