### ISSUE TITLE
some issues with getting-started.md

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#338]
/kind bug

**What steps did you take and what happened:**

Was trying to follow the steps in the `getting-started.md` and got the following issues:
 - In the `Install release binaries` section, there is a link to `release of clusterctl` but it links to the releases of the azure provider and doesn't explain how to get the clusterctl
 - In the `Customizing the cluster deployment` section, 
    - `./azure/generate-yaml.sh` file is mentioned, but I could not find it
    - there is not default value set for `AZURE_LOCATION`
 - In `Creating a cluster` section, there is not mention that the user needs to deploy the azure-provider controller first before creating a cluster

**Comment by rbitia** [comment]
Hey what's the status on doc fixes? I'm finding inconsistencies too and I'd love to make a PR
