### ISSUE TITLE
"feature gate 'WindowsHostProcessContainers' is not enabled" fails capz-periodic-apiversion-upgrade-main

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3380]
**Which jobs are failing:**

capz-periodic-apiversion-upgrade-main

**Which tests are failing:**

capz-e2e: [It] Running the Cluster API E2E tests API Version Upgrade upgrade from v1alpha4 to v1beta1, and scale workload clusters created in v1alpha4 Should create a management cluster and then upgrade all the providers

**Since when has it been failing:**

3/27/2023, presumably when #3301 merged.

**Testgrid link:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-apiversion-upgrade-main

**Reason for failure (if possible):**

`DaemonSet.apps "cloud-node-manager-windows" is invalid: spec.template.spec.securityContext.windowsOptions.hostProcess: Forbidden: not allowed when feature gate 'WindowsHostProcessContainers' is not enabled`

**Anything else we need to know:**

/kind failing-test

cc: @marosset @jsturtevant

**Comment by CecileRobertMichon** [comment]
@mboersma I believe that's because we're creating the cluster on an older version of k8s for v1alpha4 -> v1beta1 upgrade, due to newer versions not being supported with v1alpha4 (I don't remember the exact reason why)

**Comment by CecileRobertMichon** [comment]
yep:

https://prow.k8s.io/prowjob?prowjob=f3365ae5-cfe0-11ed-95ad-1e43d58f4b8b

```
      - name: KUBERNETES_VERSION
        value: v1.22.9
 ```

**Comment by marosset** [comment]
If we can't update the starting cluster to v1.23.x or drop the v1alpha4 -> v1beta1 upgrade test can we drop the Windows nodes from this particular test?

**Comment by CecileRobertMichon** [comment]
@marosset we can, by putting https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3301/files#diff-8b91713d32e4c8ded5ab1750a28ff56606d6e293536e2229e0e38784796fbc90R59 back into an if bock

Both `1.23.x` and `v1alpha4` tests should be dropped very soon (and are already EOL).
