### ISSUE TITLE
Add missing test coverage for azuremanagedcontrolplane_default.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3431]
/kind cleanup

**Describe the solution you'd like**
Currently, `azuremanagedcontrolplane_default.go` is missing unit tests in the following areas:

- [setDefaultAutoScalerProfile()](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcontrolplane_default.go#L87): Add unit test to ensure that the default auto scaler profile is set if all fields are nil.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by samyakjain10** [comment]
@willie-yao I have added the missing test. Please review
