### ISSUE TITLE
[e2e] Consume CAPI's e2e framework

### ISSUE THREAD

**Issue by jadarsie** [kubernetes-sigs/cluster-api-provider-azure#345]
**Describe the solution you'd like**

Consume CAPI's e2e framework and remove copied package `test/e2e/framework` from CAPZ's code base.

https://github.com/kubernetes-sigs/cluster-api/tree/master/test/framework

**Anything else you would like to add:**

Challenges at the time were:

1. Module has a redirect to a local file system directory
2. References to v1alpha3 types

> The first item got revolved recently by this: https://github.com/kubernetes-sigs/cluster-api/pull/1900.

Related work: #339

**Comment by cpanato** [comment]
/assign
will try
