### ISSUE TITLE
[e2e] Parameterize e2e tests

### ISSUE THREAD

**Issue by jadarsie** [kubernetes-sigs/cluster-api-provider-azure#346]
**Describe the solution you'd like**

Let's removed hard-coded values from the e2e test suite. Potential candidates are: location, vmSize, namespace, k8sVersion, imageOffer, imagePublisher, imageSKU, imageVersion.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1567581fffdc2daa272aac227b5b6c6a3961e191/test/e2e/azure_suite_test.go#L65-L73

**Comment by cpanato** [comment]
This will be environment variables? 
I can take that

@jadarsie

**Comment by justaugustus** [comment]
Hey @cpanato, are you still interested in this one?

**Comment by cpanato** [comment]
@justaugustus yes, just need to understand how we will input those values, as environment variables?

and where should i configure those values?

thx :)
