### ISSUE TITLE
[e2e] e2e and example load CAPI/CABPK versions from the same location

### ISSUE THREAD

**Issue by jadarsie** [kubernetes-sigs/cluster-api-provider-azure#347]
**Describe the solution you'd like**

Ensure that the examples gen script and the e2e test suite always deploy the same CAPI/CABPK versions.

Related to #346

**Comment by nader-ziada** [comment]
I think can be closed now @rbitia

**Comment by nader-ziada** [comment]
This is now fixed as part of the new e2e framework and refactoring.
