### ISSUE TITLE
[e2e] Ensure all Azure resources are deleted

### ISSUE THREAD

**Issue by jadarsie** [kubernetes-sigs/cluster-api-provider-azure#348]
**Describe the solution you'd like**

Make sure `scripts/ci-e2e.sh` cleans after itself and all Azure resources created by the e2e are deleted.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/scripts/ci-e2e.sh#L39-L44

**Anything else you would like to add:**

This may require loading `AZURE_CREDENTIALS` from `ci-e2e.sh` instead of test suite itself.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/azure_suite_test.go#L79-L84

**Comment by cpanato** [comment]
@jadarsie I would like to work on that
The clean up will be done in the ci-e2e.sh script? or part of the test?

how can i "test" that?

**Comment by CecileRobertMichon** [comment]
@cpanato I think this should be done as part of the test. Feel free to assign yourself if you're still interested.

**Comment by cpanato** [comment]
/remove-help
/assign

I will ping you in the chat @CecileRobertMichon to talk a bit more about this
