### ISSUE TITLE
Support AKS cluster with HTTP Proxy mode 

### ISSUE THREAD

**Issue by mjnovice** [kubernetes-sigs/cluster-api-provider-azure#3485]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Ability to create AKS clusters with http_proxy support https://learn.microsoft.com/en-us/azure/aks/http-proxy

***Non-Goals/Future Work***
1. Non-Goal 1
1. Non-Goal 2

**User Story**

As a [developer/user/operator] I would like to be able to create a Azure managed `Cluster` ( with `AzureManagedControlPlane`/`AzureManagedMachinePool` ) using the HTTP_PROXY mode.

**Detailed Description**

`AzureManagedControlPlane` can have a field `httpProxyConfig` akin to 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/3083824/234593187-db3e330a-315b-48d2-bfa1-1a49107ba888.png">
allowing us to create the cluster with proxy mode.

/kind proposal

**Comment by nojnhuh** [comment]
Looks good, thanks! I think this is small enough that we can classify this as a regular feature request instead of a proposal. No need to change the description though.

/remove-kind proposal
/kind feature

**Comment by mjnovice** [comment]
@nojnhuh I would be willing to work on this, just curious, can we go with making changes with `autorest` client for now, or do we have a guidance for new features ? Any help would be great

**Comment by nojnhuh** [comment]
I don't think adding this feature will require any new use of `autorest` so I think following the existing pattern is a good place to start. If you run into any specific cases feel free to ask then or we can address those once you have a PR open.

Thanks for picking this up!

/assign @mjnovice
