### ISSUE TITLE
Assess scalability of CAPZ using ASO vs. Azure SDK

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3547]
At a high level, we should ensure CAPZ's current scalability limits do not drop below what's acceptable once we start using ASO. Scalability in this case refers to the total volume of clusters (in number and in size) that CAPZ can manage.

Limits to look out for include:
- CPU/memory usage (of both CAPZ and ASO)
- Azure API rate limits

```[tasklist]
### Dependencies
- [ ] #3524
```

**Comment by dtzar** [comment]
@mtougeron - could you please share what progress you might have made in the performance testing of CAPZ space?  I'm starting to get more requests from people in this space in general.

**Comment by mboersma** [comment]
We should establish a performance bsaeline here, such as "what's the smallest management cluster that can support a large number of worker clusters?" etc.

**Comment by jackfrancis** [comment]
Closing to focus on general performance measurements
