### ISSUE TITLE
Automate release branch and tag creation

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3555]
/kind feature

**Describe the solution you'd like**
Several members of the CAPZ community has expressed interest in participating in the release process but are unable to follow the current release guidelines unless they have write permissions on the CAPZ repo. Here are the current release steps: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/developers/releasing.md

A possible idea for this is to use a GitHub Action for creating and pushing the tag. One way to trigger this action would be upon merge of a release notes file. This would also add a review process to our release notes, which used to only be edited by an approver right before a release. 

**Anything else you would like to add:**
A similar issue is raised in CAPI in regards to their release process and team: https://github.com/kubernetes-sigs/cluster-api/issues/7128

**Comment by CecileRobertMichon** [comment]
This is done in #4366 

/close
