### ISSUE TITLE
Cluster with NSG in separate RG fails to expose service

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#356]
/kind bug

Because of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/281, we are currently unable to specify a `securityGroupResourceGroup` in `azure.json` and the cloud-provider expects the NSG to be in the same RG as the cluster RG. Once the issue above is fixed, we should add `securityGroupResourceGroup` to all `azure.json` examples.

/assign

**Comment by CecileRobertMichon** [comment]
Add `securityGroupResourceGroup` field in cluster template Azure json so this supported starting with 1.18+ 

https://github.com/kubernetes/kubernetes/pull/87035

/unassign
/help
/good-first-issue

**Comment by CecileRobertMichon** [comment]
@aramase are you still working on this?

**Comment by aramase** [comment]
@CecileRobertMichon yeah, I'll raise the PR for it soon.

**Comment by CecileRobertMichon** [comment]
@aramase I'm going to unassign you for now to give to opportunity to someone else to pick this up, feel free to assign yourself again if/when you're able to get to it

/unassign @aramase

**Comment by Deeps-1989** [comment]
@CecileRobertMichon I can help make this change. Do I need to make change under templates/cluster-template-*.yaml. Will it be a top level field or under which field this new field be nested to?

**Comment by CecileRobertMichon** [comment]
Hi @Deeps-1989, I'm actually going to assign @alexeldeib on this one since he's already working on #773 and they are closely related. 

/assign @alexeldeib 

Feel free to pick up any of the other good first issues https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 and comment `/assign` to assign yourself

**Comment by alexeldeib** [comment]
/remove-help

Should be easy to add this on top of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/802

**Comment by CecileRobertMichon** [comment]
This would also require adding NSG RG to the AzureCluster Spec since the nsg can be in its own RG as well

**Comment by dbsanfte** [comment]
I've recently run into this trying to set up a hybrid k8s deployment in Azure. 

The state of this issue is a bit confusing: the code seems to be merged, but it isn't released?

Is this feature released to the 0.4.x Azure Cloud Provider yet? Apologies if I'm asking in the wrong place.

**Comment by CecileRobertMichon** [comment]
@dbsanfte this issue is still open so it hasn't been fixed yet. It was fixed in the Kubernetes cloud provider for k8s 1.18+ but we need to consume it in CAPZ and that is what this issue is for. This should be a pretty easy fix so if you'd like to assign yourself to the issue and contribute a fix feel free to do so. Otherwise I'll make sure we get to it before the next milestone.

/milestone v0.4.11
