### ISSUE TITLE
GPU test failing

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3561]
**Which jobs are flaky:**

Any job involving the GPU spec, for example:

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main

**Which tests are flaky:**

**Testgrid link:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main

**Reason for failure (if possible):**

**Anything else we need to know:**
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/kind flake

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
@nojnhuh @mboersma can this issue be closed?

**Comment by nojnhuh** [comment]
Yep, that test is green!

/close
