### ISSUE TITLE
Add Services unit tests

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#359]
This is an easy one because the ground work is already done, just needs iteration :) 

Following examples in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/virtualnetworks/virtualnetworks_test.go and https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/virtualmachines/virtualmachines_test.go, we should add a unit test suite for the other `services/` packages.

- [x] (@noamran) availabilityzones
- [x] (@cpanato) disks
- [x] (@cpanato) groups
- [x] (@noamran) internalloadbalancers
- [x] (@asatish) networkinterfaces
- [x] (@cpanato) publicips
- [x] (@cpanato) publicloadbalancers
- [x] (@cpanato) routetables
- [x] (@nader-ziada) securitygroups
- [x] (@nader-ziada) subnets
- [x] (@cpanato) virtualmachineextensions
- [x] virtualmachines ~(partially done)~
- [x] virtualnetworks

/help

**Comment by CecileRobertMichon** [comment]
@noamran is going to look into `availabilityzones` and `internalloadbalancers`

**Comment by nader-ziada** [comment]
i'll take the `securitygroups` and `subnets` as a start

**Comment by asatish** [comment]
I can help with networkinterfaces and publicips

**Comment by cpanato** [comment]
@CecileRobertMichon can i try `publicloadbalancers` ?

**Comment by justaugustus** [comment]
@cpanato -- Go for it! :)

**Comment by cpanato** [comment]
@asatish are you working in the publicips tests?

**Comment by cpanato** [comment]
@CecileRobertMichon i will try disks as well

**Comment by asatish** [comment]
> @asatish are you working in the publicips tests?

you can take it if you like, since I haven't got to it so far. Thanks..

**Comment by cpanato** [comment]
will take care groups

**Comment by cpanato** [comment]
will take care `routetables`

**Comment by cpanato** [comment]
will take care `virtualmachineextensions`

**Comment by cpanato** [comment]
Will check what is missing for `virtualmachines`

**Comment by cpanato** [comment]
@asatish are you working in the `networkinterfaces` tests?

**Comment by CecileRobertMichon** [comment]
@asatish any updates on network interfaces?

**Comment by cpanato** [comment]
@asatish @CecileRobertMichon I can work on that if you don't have time

**Comment by asatish** [comment]
Hi Carlos, sure you can go ahead and work on that, I haven't gotten to this
as yet.

Thanks,
Satish
