### ISSUE TITLE
convert all ci jobs to use workload identity. 

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#3590]
/kind feature

**Describe the solution you'd like**
All the CI jobs in capz should start using workload identity. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Umbrella Issue: #2205 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
We might want to wait for https://github.com/Azure/azure-workload-identity/pull/1209 to do this work

/milestone next

**Comment by dtzar** [comment]
@jackfrancis - Isn't this already covered by #4763 ?

**Comment by jackfrancis** [comment]
Ya, good call
