### ISSUE TITLE
Cluster update hangs after some -Azure RBAC related- control plane parameters are changed

### ISSUE THREAD

**Issue by raftAtGit** [kubernetes-sigs/cluster-api-provider-azure#3592]
/kind bug

**What steps did you take and what happened:**
1. A cluster is provisioned and was functional.
2. `KubeadmControlPlane` is edited as described [here](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/azure-rbac?tabs=AzureCLI%2Ckubernetes-latest#enable-azure-rbac-on-the-cluster)
a. added `files` from `azure-arc-guard-manifests` Secret
b. added `extraVolumes` to `apiServer`
c. added `extraArgs` to `apiServer`
3. Changes accepted but cluster update is stuck at  `WaitingForBootstrapData` state. In the logs, I can see `Bootstrap data secret reference is not yet available`. State didn't change for more than 6 hours.

**What did you expect to happen:**
Cluster is updated.

**Anything else you would like to add:**
Attached are `controller-manager` logs and output of `clusterctl describe` and `kubectl get/describe kcp` commands:

[clusterctl-describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/11553023/clusterctl-describe.txt)
[controller-manager-logs.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/11553024/controller-manager-logs.txt)
[kcp-describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/11553025/kcp-describe.txt)
[kcp-get.txt](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/11553026/kcp-get.txt)

**Environment:**

- cluster-api-provider-azure version: 
```
Image:         registry.k8s.io/cluster-api-azure/cluster-api-azure-controller:v1.9.2
```
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"dc2f9dc64421983f0f7839da8ab4ab6d4673daad", GitTreeState:"clean", BuildDate:"2023-04-08T13:29:19Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
`Ubuntu 20.04.4 LTS` on WSL2

**Comment by CecileRobertMichon** [comment]
@raftAtGit did you also keep the azure.json file https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template.yaml#L82 in the KubeadmControlPlane files? The azure.json file contains Azure credential information to be used by cloud-provider-azure for Azure auth.

**Comment by raftAtGit** [comment]
@CecileRobertMichon no, I don't have that file, sorry

**Comment by CecileRobertMichon** [comment]
@raftAtGit that's likely what is causing the issue

**Comment by raftAtGit** [comment]
@CecileRobertMichon sorry, I was thinking you asked if I kept that file for debugging this issue.
But, I guess you are saying I need to keep that file for the process, correct?

If so, how should I do that?

**Comment by CecileRobertMichon** [comment]
@raftAtGit I meant does the resulting KubeadmControlPlane object after you add it have both `files` (but it sounds like yes because you just added a new file to the list).

Could you please share kubeadm-control-plane controller logs from the CAPI management cluster?

In the KCP describe you shared above I see `DataSecretGenerationFailed @ /cluster1-control-plane-cv9r2` so it looks like something went wrong with custom data secret generation

**Comment by raftAtGit** [comment]
> @raftAtGit I meant does the resulting KubeadmControlPlane object after you add it have both files (but it sounds like yes because you just added a new file to the list).

Ah, okay, true. I didn't remove any files.

> Could you please share kubeadm-control-plane controller logs from the CAPI management cluster?

Sorry, I deleted the cluster. But you can easily re-create the issue. It was happening all the time

**Comment by raftAtGit** [comment]
@CecileRobertMichon it turned out to be my bad. I somehow didn't provide the management cluster the secret which is used in workload cluster's bootstrap process.

sorry for the inconvenience. I'm closing the issue.
