### ISSUE TITLE
azure cluster delete - CLI context close

### ISSUE THREAD

**Issue by asatish** [kubernetes-sigs/cluster-api-provider-azure#360]
/kind bug

**What steps did you take and what happened:**
Normally kubectl delete -f cluster.yaml should return after basic validation, but in the azurecluster case, until the operation completes, the CLI context is not closed, so that CLI session is hung until operation is completed. This can be in in the order of minutes for a successful completion. 

**What did you expect to happen:**
The CLI context session should be closed after basic validation

**Environment:**

- cluster-api-provider-azure version: v0.3.0-alpha.1
- Kubernetes version: (use `kubectl version`):  1.16.3
- OS (e.g. from `/etc/os-release`):  Darwin Kernel Version 16.7.0

**Comment by vincepri** [comment]
`kubectl delete -f cluster.yaml --wait=false` solves this issue

**Comment by CecileRobertMichon** [comment]
Verified that @vincepri's suggestion above does the trick. 

/close
