### ISSUE TITLE
Proposal to integrate Kamino Style VM image caching with CAPZ

### ISSUE THREAD

**Issue by bennycortese** [kubernetes-sigs/cluster-api-provider-azure#3607]
***Goals***
1. A solution using the Node Prototype pattern which cache’s nodes’ OS image on a regular interval and replaces it as a new Machine or MachinePool template VM image
1. Faster horizontal scale outs of applications
1. Prevent security breaking issues on node bootup from security updates being required immediately

***Future Work***
1. Extend the functionality to Windows nodes
1. Optimization for efficiency and scalability
1. A more complicated method of selecting a good candidate node such as incorporating manual forced prototype creation, which would perform better but take research to find the optimal method
1. Optimization of the default time interval into a specific, best general default which would have to be researched
1. Automatic bad snapshot rollbacks since it will be hard to generically determine when a snapshot is bad currently
1. Annotating the timestamp on each node of when it was updated with automatic security updates
1. Allow the feature to be enabled for any type of image (marketplace or custom with ID)

**User Story**

As a operator I would like to be able to have my node’s OS image cache for the ability to avoid security alerts, cache security updates and patches and avoid having to create warm nodes to have faster horizontal scaling

**Detailed Description**

A controller will be added to CAPZ which caches the Nodes’ Linux OS image on a regular interval and updates the model to use that image for future scale outs. An operator will be able to decide to turn the feature on or off with a flag on creation of a cluster, and then can alter the YAML file to customize how long they want the caching interval to be. 

**Contract changes [optional]**

We don’t expect any contract changes

**Data model changes [optional]**

AzureMachine with AzureMachineTemplate and AzureMachinePool changes are likely and the changes we expect will be purely additive and nonbreaking. 

/kind proposal

**Comment by jackfrancis** [comment]
Great start!

To be clear are we updating the VMSS model (in the description section) or are we updating the AzureMachineTemplate's Spec.Image data w/ the newly built image?

**Comment by bennycortese** [comment]
The AzureMachineTemplate's Spec.Image data w/ the newly built image, thanks for the comment, I'll edit that in the proposal

**Comment by bennycortese** [comment]
Design document done/basic functionality outside of node cleanup done, just need to integrate everything into the codebase in the next month

**Comment by bennycortese** [comment]
Node cleanup now works but it is not node orchestration agnostic, it requires kubeadm reset to properly cleanup certain uniquely identifying information on the node. As a result, I've moved the target end date back a month on this for that to be addressed in some way.

**Comment by bennycortese** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3737

Issue that will be used to monitor migration of these problems, also explains the node cleanup issue on it and has linked pull requests
