### ISSUE TITLE
ci-conformance.sh not clean up resource group in the end

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#3620]
**Which jobs are failing:**
After jobs running `ci-conformance.sh` finished, the script doesn't clean up the resource group in the end. And I can still see the resource group existing: capz-conf-s2u6gm
e.g. capz-conformance
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/capz-conformance-master/1668022774355988480

I checked the script, unlike `ci-entrypoint.sh`, I failed to find the logic to clean up. Is it by design?

**Which tests are failing:**

**Since when has it been failing:**

**Testgrid link:**
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/capz-conformance-master/1668022774355988480

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
@lzhecheng I do see the cleanup happening in the logs but looks like deleting the cluster timed out:

```
  STEP: Deleting cluster capz-conf-s2u6gm @ 06/12/23 00:49:31.032
  INFO: Waiting for the Cluster capz-conf-s2u6gm/capz-conf-s2u6gm to be deleted
  STEP: Waiting for cluster capz-conf-s2u6gm to be deleted @ 06/12/23 00:49:31.048
  STEP: Redacting sensitive information from logs @ 06/12/23 01:19:31.049
  [FAILED] in [AfterEach] - /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.2/framework/cluster_helpers.go:176 @ 06/12/23 01:20:44.033
• [FAILED] [9411.603 seconds]
```

Here is an example of a successful run with cleanup: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-conformance-main/1668560574193078272

```
  STEP: Deleting cluster capz-conf-f62vdj @ 06/13/23 12:26:26.784
  INFO: Waiting for the Cluster capz-conf-f62vdj/capz-conf-f62vdj to be deleted
  STEP: Waiting for cluster capz-conf-f62vdj to be deleted @ 06/13/23 12:26:26.804
  Jun 13 12:33:07.014: INFO: Deleting namespace used for hosting the "conformance-tests" test spec
  INFO: Deleting namespace capz-conf-f62vdj
  Jun 13 12:33:07.027: INFO: Checking if any resources are left over in Azure for spec "conformance-tests"
  STEP: Redacting sensitive information from logs @ 06/13/23 12:33:07.565
  ```

**Comment by lzhecheng** [comment]
@CecileRobertMichon Thank you. Then it is transient. Closing
/close
