### ISSUE TITLE
Testgrid reports success on some jobs when some tests failed

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3635]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1669595355953500160

<img width="1672" alt="Screenshot 2023-06-16 at 10 21 26 AM" src="https://github.com/kubernetes-sigs/cluster-api-provider-azure/assets/8650424/a0f0912f-d551-441a-9905-8e3d513492a7">

The overall job should fail if one or more tests failed

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
wut
