### ISSUE TITLE
Add missing test coverage for azureimage_validation.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3652]
/kind cleanup

**Describe the solution you'd like**
Currently, `azureimage_validation.go` is missing unit tests in the following areas:

- [validateSingleDetailsOnly](https://app.codecov.io/github/kubernetes-sigs/cluster-api-provider-azure/blob/main/api%2Fv1beta1%2Fazureimage_validation.go#L50):
  - Test case if image.Marketplace != nil and image details are not found
  - Test case if image.Marketplace == nil, image.ComputeGallery != nil, and image details are not found
  - Test case if image.Marketplace == nil, image.ComputeGallery == nil, and image details are not found
  - Ensure an error is returned for all of these cases

**Comment by nawazkh** [comment]
Hey @Nilesh-chaudhary 👋🏼 , Are you still working on this issue ?

**Comment by aniruddha2000** [comment]
If not can I work on this? @willie-yao @nawazkh

**Comment by Nilesh-chaudhary** [comment]
Hello @nawazkh , I want to apologize for the delay in addressing this issue. As I approach the end of my degree, I've been focused on a job hunt, which temporarily took my attention away from this issue. The good news is that I've successfully secured a job opportunity, and I'm now in a position to dedicate my time to resolving this issue. I appreciate your understanding and patience. Thank you for your understanding!!!

**Comment by nawazkh** [comment]
Hey @Nilesh-chaudhary, no worries at all! Just checking in. Also, congrats!
Feel free to continue with this issue. :)
