### ISSUE TITLE
When using capz for Presubmits in kubernetes if the k8s job name is too long it fails

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#3673]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

If a k8s job is name is long such as `pull-kubernetes-e2e-capz-windows-alpha-feature-vertical-pod-autoscaler` you will get an error like:

```
using K8s KUBE_IMAGE_TAG=v1.28.0-alpha.3.118_34ac88a4e45892
ERROR: The specified resource name length is not within the permissible limits.
RequestId:ab4e3a19-d01e-0021-3517-a9fec5000000
Time:2023-06-27T16:48:32.8172364Z
ErrorCode:OutOfRangeInput
````

The error is in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c35fda9c75d4e6028f3d13203744c68ab5cb7873/scripts/ci-build-kubernetes.sh#L84-L88 

**What did you expect to happen:**

maybe we should truncate the job name?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

shortening the jobname fixes the issue as a work around. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
looking at the script more closely, I don't know if it even makes sense to use the job name as the storage container name in the first place. If we are trying to reuse artifacts as optimally as possible, shouldn't we reuse the same k8s build across jobs? i.e. if Job A creates a build of k8s for commit 1234 and Job B wants to test something else from commit 1234, is there any issue with Job B using the artifact built by Job A?

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c35fda9c75d4e6028f3d13203744c68ab5cb7873/scripts/ci-build-kubernetes.sh#L142
