### ISSUE TITLE
Add support for Azure CNI Overlay on AKS managed clusters

### ISSUE THREAD

**Issue by illrill** [kubernetes-sigs/cluster-api-provider-azure#3678]
/kind feature

**Describe the solution you'd like**
Add support for [Azure CNI Overlay](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay) on AKS managed clusters.

**Anything else you would like to add:**
Microsoft.ContainerService/managedClusters API implements this with:

[`networkProfile.networkPluginMode: overlay`](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get?tabs=HTTP#networkpluginmode)
[`networkProfile.podCidr: <cidr>`](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get?tabs=HTTP#containerservicenetworkprofile)

**Comment by CecileRobertMichon** [comment]
/help

A PR to introduce this change would be welcome!

**Comment by felfa01** [comment]
This is sought-after feature for my usecase. Any updates?

**Comment by CecileRobertMichon** [comment]
@felfa01 I added it to the high-priority list of missing AKS features we're tracking https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3446

If anyone would like to pick up this work and open a PR, help is welcome

cc @dtzar

**Comment by nojnhuh** [comment]
@illrill @felfa01 I just opened #3988 which implements this. If you are able to build from source and offer feedback if that's sufficient for you that would be very helpful!

**Comment by illrill** [comment]
Many thanks @felfa01 and @nojnhuh!
