### ISSUE TITLE
Failed to get v1.9.4

### ISSUE THREAD

**Issue by ionutleca** [kubernetes-sigs/cluster-api-provider-azure#3679]
/kind bug

**What steps did you take and what happened:**
Running `clusterctl init --infrastructure azure` or `clusterctl upgrade plan` will fail when it tries to fetch the latest release (v1.9.4)

```
Error: failed to get provider components for the "azure" provider: failed to read "infrastructure-components.yaml" from provider's repository "infrastructure-azure": failed to get GitHub release v1.9.4: failed to read release "v1.9.4": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-azure/releases/tags/v1.9.4: 404 Not Found []
```

**What did you expect to happen:**
Fetch and install the latest CAPZ version.

**Anything else you would like to add:**
Might be caused by the fact that there is a **v1.9.4** tag published while the latest release seems to be still **v1.9.3** 

**Environment:**

- cluster-api-provider-azure version: N/A
- Kubernetes version: 1.25.2
- OS: MacOs Ventura: 13.3.1

**Comment by ffais** [comment]
I've just upgrade to the latest version, but looks like that the image is not present in the repository.

`Back-off pulling image "registry.k8s.io/cluster-api-azure/cluster-api-azure-controller:v1.9.4"`

**Comment by akum78** [comment]
same issue faced just now. time - 17:29 CET image not found.

**Comment by CecileRobertMichon** [comment]
The v1.9.4 release is now published so this issue should be mitigated.

Discussion for why this happened in the first place and why clusterctl tries to fetch releases for tags before the release is published is happening here: https://github.com/kubernetes-sigs/cluster-api/issues/8966
