### ISSUE TITLE
When cluster is stuck in provisioning due to error, cannot delete/force delete azurecluster

### ISSUE THREAD

**Issue by asatish** [kubernetes-sigs/cluster-api-provider-azure#371]
/kind bug

**What steps did you take and what happened:**
 When azureclusters is stuck in provisioning state, there is no way to delete the azurecluster using kubectl. Unless until, I go backdoor and delete the azure resource group and then I have to delete the management cluster to stop azure controller from going in an infinite loop deleting target cluster

For ex, I was using 0.3.0 with older control_plane_machine.yaml which had a reference to this
"image:
  offer: capi
  publisher: cncf-upstream
  sku: k8s-1dot16-ubuntu-1804
  version: latest"

and this error was seen. 

E0127 23:02:22.597598    1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachine VM: failed to create vm capi-quickstart-azure-controlplane-0 : failed to create or get machine: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code=\"PlatformImageNotFound\" Message=\"The platform image 'cncf-upstream:capi:k8s-1dot16-ubuntu-1804:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile\" Target=\"imageReference\"" "controller"="azuremachine" "request"={"Namespace":"default","Name":"capi-quickstart-azure-controlplane-0"}

BTW, I even tried "--grace-period=0 --force" in kubectl, that also doesn't help. 

I have seen this error in 2 other instances, another example:
ssh key was incorrect for some reason, so the creation was failing, When I tried to delete the cluster, it was hung even after 3 hours. 

E0118 17:18:14.405915       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachine VM: failed to create vm capi-quickstart-azure-controlplane-0 : failed to decode ssh public key: illegal base64 data at input byte 0"  "controller"="azuremachine" "request"={"Namespace":"default","Name":"capi-quickstart-azure-controlplane-0"}

I0118 17:22:56.350198       1 azurecluster_controller.go:142] controllers/AzureCluster "msg"="Reconciling AzureCluster delete" "azureCluster"="capi-quickstart-azure" "cluster"="capi-quickstart-azure" "namespace"="default"
I0118 17:22:56.362657       1 azuremachine_controller.go:194] controllers/AzureMachine "msg"="Reconciling AzureMachine" "azureCluster"="capi-quickstart-azure" "azureMachine"="capi-quickstart-azure-controlplane-0" "cluster"="capi-quickstart-azure" "machine"="capi-quickstart-azure-controlplane-0" "namespace"="default"
E0118 17:22:57.758838       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachine VM: failed to create nic capi-quickstart-azure-controlplane-0-nic for machine capi-quickstart-azure-controlplane-0: unable to create VM network interface: load balancer capi-quickstart-azure-public-lb not found: network.LoadBalancersClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"NotFound\" Message=\"Resource /subscriptions/f8ffe977-ca2a-49b2-8019-794623830a89/resourceGroups/capi-quickstart-azure/providers/Microsoft.Network/loadBalancers/capi-quickstart-azure-public-lb not found.\" Details=[]"  "controller"="azuremachine" "request"={"Namespace":"default","Name":"capi-quickstart-azure-controlplane-0"}
I0118 17:22:57.759384       1 azuremachine_controller.go:297] controllers/AzureMachine "msg"="Handling deleted AzureMachine" "azureCluster"="capi-quickstart-azure" "azureMachine"="capi-quickstart-azure-controlplane-0" "cluster"="capi-quickstart-azure" "machine"="capi-quickstart-azure-controlplane-0" "namespace"="default"
E0118 17:23:10.440905       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/capi-quickstart-azure: failed to delete load balancer: failed to internal load balancer capi-quickstart-azure-internal-lb for cluster capi-quickstart-azure: cannot create, future response: Code=\"OperationNotAllowed\" Message=\"Operation 'startTenantUpdate' is not allowed on VM 'capi-quickstart-azure-controlplane-0' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete).\" Details=[]"  "controller"="azurecluster" "request"={"Namespace":"default","Name":"capi-quickstart-azure"}
I0118 17:23:10.446493       1 azurecluster_controller.go:142] controllers/AzureCluster "msg"="Reconciling AzureCluster delete" "azureCluster"="capi-quickstart-azure" "cluster"="capi-quickstart-azure" "namespace"="default"

E0120 20:52:29.998256       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/capi-quickstart-azure: failed to delete subnets: failed to delete capi-quickstart-azure-node-subnet subnet for cluster capi-quickstart-azure: failed to delete subnet capi-quickstart-azure-node-subnet in resource group capi-quickstart-azure: network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code=\"InUseSubnetCannotBeDeleted\" Message=\"Subnet capi-quickstart-azure-node-subnet is in use by /subscriptions/f8ffe977-ca2a-49b2-8019-794623830a89/resourceGroups/capi-quickstart-azure/providers/Microsoft.Network/networkInterfaces/capi-quickstart-azure-node-5s5q9-nic/ipConfigurations/pipConfig and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\" Details=[]"  "controller"="azurecluster" "request"={"Namespace":"default","Name":"capi-quickstart-azure"}
I0120 20:54:20.159559       1 azurecluster_controller.go:142] controllers/AzureCluster "msg"="Reconciling AzureCluster delete" "azureCluster"="capi-quickstart-azure" "cluster"="capi-quickstart-azure" "namespace"="default"
E0120 20:54:22.407910       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/capi-quickstart-azure: failed to delete subnets: failed to delete capi-quickstart-azure-node-subnet subnet for cluster capi-quickstart-azure: failed to delete subnet capi-quickstart-azure-node-subnet in resource group capi-quickstart-azure: network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code=\"InUseSubnetCannotBeDeleted\" Message=\"Subnet capi-quickstart-azure-node-subnet is in use by /subscriptions/f8ffe977-ca2a-49b2-8019-794623830a89/resourceGroups/capi-quickstart-azure/providers/Microsoft.Network/networkInterfaces/capi-quickstart-azure-node-5s5q9-nic/ipConfigurations/pipConfig and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\" Details=[]"  "controller"="azurecluster" "request"={"Namespace":"default","Name":"capi-quickstart-azure"}

**What did you expect to happen:**
Need a mechanism to delete target cluster in azure, from the management cluster, when there are persistent errors during deletion phase. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: v0.3.0
- Kubernetes version: (use `kubectl version`): 1.16.3
- OS (e.g. from `/etc/os-release`):

**Comment by FranBarrera** [comment]
I've been testing this issue trying to replicate it with the same problems, wrong image and ssh but using the latest master code and I couldn't replicate it, if I delete the cluster with kubectl, it will delete everything without issues.

**Comment by asatish** [comment]
With v1alapha3 release 0.4.1, I don't see this issue anymore, the cluster gets deleted, closing this. Thanks for fixing this.
