### ISSUE TITLE
Definition of PriorityClass for capz-nmi

### ISSUE THREAD

**Issue by esierra-stratio** [kubernetes-sigs/cluster-api-provider-azure#3716]
/kind feature

**Describe the solution you'd like**
Include the option to assign a PriorityClass to `capz-nmi` since it is a critical component of the cluster.

**Anything else you would like to add:**
Given the low priority, the `capz-nmi` component may be susceptible to being preempted by another service with a higher priority value and a preemptionPolicy set to a value other than Never.

**Environment:**

- cluster-api-provider-azure version: v1.9.3 
- Kubernetes version: (use `kubectl version`):  1.26.3
- OS (e.g. from `/etc/os-release`):  
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by CecileRobertMichon** [comment]
Let's set it in the CAPZ manifest https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/config/capz/aad-pod-identity-deployment.yaml#L244 to `system-node-critical` since CAPZ needs it

/help

**Comment by esierra-stratio** [comment]
Can I lend a hand in any way with this?
