### ISSUE TITLE
Use CAAPH to install Helm charts in e2e tests

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-azure#3736]
/kind feature

**Describe the solution you'd like**

Cluster API v1.5 brings support for installing add-on providers using clusterctl. This allows us to use CAAPH in the e2e tests to install cloud-provider-azure, calico, and azuredisk-csi-driver rather than a manual Helm install.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
re-opening since only Calico is done
