### ISSUE TITLE
Feature Request: Support for Integration with Azure's Application Security Groups (ASGs)

### ISSUE THREAD

**Issue by yashwanth-mannem** [kubernetes-sigs/cluster-api-provider-azure#3745]
/kind feature

**Describe the solution you'd like**
We are using Cluster API Provider Azure (CAPZ) to manage our Kubernetes clusters on Azure. Currently, we also use Azure's Application Security Groups (ASGs) to manage network security at the level of network interfaces (NICs) across VMs. I propose adding support to CAPZ for associating Azure's ASGs with the NICs of VMs that are created and managed by it. This functionality would greatly enhance network security management for users of CAPZ.

**Anything else you would like to add:**
No

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): v1.22.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.6 LTS

**Comment by nawazkh** [comment]
Would the API docs be of help? 
- https://learn.microsoft.com/en-us/rest/api/virtualnetwork/application-security-groups/create-or-update?tabs=HTTP
- https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?tabs=HTTP#applicationsecuritygroup

**Comment by yashwanth-mannem** [comment]
@nawazkh Thank you for pointing me to the API documentation. I'm currently reviewing it to understand the implementation details better.  Could I take this on as my first contribution to the project?

**Comment by nawazkh** [comment]
> @nawazkh Thank you for pointing me to the API documentation. I'm currently reviewing it to understand the implementation details better. Could I take this on as my first contribution to the project?

Yes, feel free! Please join our office hours or ping us on slack to get more info on this if needed.
