### ISSUE TITLE
Upgrade to Go 1.13

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/cluster-api-provider-azure#376]
/kind feature

**Describe the solution you'd like**
similar update make in the AWS provider: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1430
Any blockers that make this upgrade not possible?

**Anything else you would like to add:**
I can work on that

**Comment by CecileRobertMichon** [comment]
@cpanato no blockers, feel free to submit a PR!

/assign @cpanato
