### ISSUE TITLE
AKS autoscaler e2e test is failing

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3763]
**Which jobs are failing:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-aks-main

**Which tests are failing:**

```
{Timed out after 2316.131s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/aks_autoscaler.go:117 with:
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 2316.131s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/aks_autoscaler.go:117 with:
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/aks_autoscaler.go:118 @ 07/24/23 15:44:05.172
}
```

**Since when has it been failing:**

07/25

**Testgrid link:**

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-aks-main/1684093305685544960

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by nojnhuh** [comment]
Not sure why this is only happening now, but for me locally disabling autoscaling for an AzureManagedMachinePool puts the controller in one of our familiar forever-reconcile loops with this diff:
```diff
  containerservice.AgentPool{
  	Response: {},
  	ManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{
  		... // 9 identical fields
  		OsType:            "",
  		OsSKU:             "",
- 		MaxCount:          nil,
+ 		MaxCount:          &2,
- 		MinCount:          nil,
+ 		MinCount:          &1,
- 		EnableAutoScaling: nil,
+ 		EnableAutoScaling: &true,
  		ScaleDownMode:     "Delete",
  		Type:              "",
  		... // 23 identical fields
  	},
  	ID:   nil,
  	Name: nil,
  	Type: nil,
  }
```

I don't see any similar log messages in the e2e test though. My read of the code still suggests this may be the problem, though now I'm trying to understand how this ever worked in the first place.

**Comment by mtougeron** [comment]
I'll see if I can help take a look after my block of meetings this afternoon are done.

**Comment by CecileRobertMichon** [comment]
Confirmed this was a change in AKS... turns out we had been previously relying on a "bug" of setting the autoscaler settings to nil resulting in disabling it. AKS will no longer reset the user settings when it's nil so we'll need to set it to "false" to disable it. Release [v20230723](https://github.com/Azure/AKS/releases/tag/2023-07-23) is currently rolling out (https://releases.aks.azure.com/webpage/index.html) which explains why we're still seeing some tests pass - although at this point it should be in pretty much every region.

#3766 should fix it, test failed on a different reason on the first run though so I just ran a retest. 

/assign @nojnhuh
