### ISSUE TITLE
Codecov job failing with token error

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3779]
**Which jobs are failing:**

Codecov

**Which tests are failing:**

**Since when has it been failing:**

At least since 7/31.

**Testgrid link:**

https://github.com/kubernetes-sigs/cluster-api-provider-azure/actions/runs/5715317747/job/15486532385?pr=3775

**Reason for failure (if possible):**
```
[2023-07-31T14:41:09.329Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/eaaf4bedf32dbdc6b720b6[30](https://github.com/kubernetes-sigs/cluster-api-provider-azure/actions/runs/5715317747/job/15486532385?pr=3775#step:7:31)67d99c4d77d6047d/dist/codecov' failed with exit code 255
```
**Anything else we need to know:**

/kind failing-test

**Comment by CecileRobertMichon** [comment]
@willie-yao since we're using the codecov github app integration now do we still need the github action? If not should it be removed?

**Comment by willie-yao** [comment]
> @willie-yao since we're using the codecov github app integration now do we still need the github action? If not should it be removed?

Yes we will still need the GitHub action as the codecov app still needs the data from a code coverage report.

**Comment by CecileRobertMichon** [comment]
https://github.com/codecov/codecov-action#usage

> For public repositories, no token is needed

**Comment by willie-yao** [comment]
Hmm that's interesting... I don't see any mention of a token in our codecov action https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/cover.yaml

Looks like this is an issue with codecov-action 3.1.4? Another user on a public repo posted about the same issue: https://github.com/codecov/codecov-action/issues/1035

**Comment by willie-yao** [comment]
Update: the job passed when I reverted to codecov-action v3.1.3

https://github.com/kubernetes-sigs/cluster-api-provider-azure/actions/runs/5720469281/job/15500461417?pr=3786

**Comment by CecileRobertMichon** [comment]
@willie-yao I think this is an ongoing transient known issue, see https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Comment by willie-yao** [comment]
Oh I see. Looks like the best course of action would be to add a codecov upload token since it is a GitHub rate-limiting issue.

**Comment by CecileRobertMichon** [comment]
@willie-yao we won't be able to make the upload token a secret as secrets are not available to forks in github actions

> Public repositories that rely on PRs via forks will find that they cannot effectively use Codecov if the token is stored as a GitHub secret

That means making the upload token publically visible :( 

> A malicious actor would be able to upload incorrect or misleading coverage reports to a specific repository if they have access to your upload token, but would not be able to pull down source code or make any code changes.

**Comment by willie-yao** [comment]
Oof.. Looks like there's no way around this then. The only other way I can think of is using the codecov uploader, but that also requires a codecov token https://docs.codecov.com/docs/codecov-uploader

**Comment by willie-yao** [comment]
Another way I could think of is automatically retrying the step if it fails with a set max_retry using the "Retry Step" GitHub action. @CecileRobertMichon @mboersma what do you think?

https://github.com/marketplace/actions/retry-step

**Comment by CecileRobertMichon** [comment]
+1 to adding a retry, let's see if we're able to get rid of most of the failures that way

If not, we can reevaluate using a token

**Comment by willie-yao** [comment]
Added the [retry action](https://github.com/marketplace/actions/retry-action) to my PR and it seemed to succeed although it did so on the first try. I may need someone with write permissions to try and get it to fail to test the retry: https://github.com/kubernetes-sigs/cluster-api-provider-azure/actions/runs/5730295627/job/15528785539
