### ISSUE TITLE
Flaky e2e tests: Windows nodes not joining cluster

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3842]
**Which jobs are flaky:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-e2e-main

**Which tests are flaky:**

clusters Windows nodes

**Testgrid link:**

[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/bootstrap/resources/capz-e2e-c6bd60/Machine/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-bv7cw.yaml](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/bootstrap/resources/capz-e2e-c6bd60/Machine/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-bv7cw.yaml)

**Reason for failure (if possible):**

1 or 2 of the Windows nodes are not joining the cluster, Machine stays stuck in "Provisioned" state

**Anything else we need to know:**
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/kind flake

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
Looking at one example repro in particular: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e/1691226971670843392

> Timed out waiting for 2 nodes to be created for MachineDeployment capz-e2e-c6bd60/capz-e2e-c6bd60-ha-md-win

CAPI reports 1 out of 2 Machines Available in the [MachineDeployment](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/bootstrap/resources/capz-e2e-c6bd60/MachineDeployment/capz-e2e-c6bd60-ha-md-win.yaml) and it times out at `00:02:31.818`.

```
  [1mSTEP:[0m Waiting for the workload nodes to exist [38;5;243m@ 08/14/23 23:37:31.817[0m
  [38;5;9m[FAILED][0m in [It] - /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.0/framework/machinedeployment_helpers.go:127 [38;5;243m@ 08/15/23 00:02:31.818[0m
  Aug 15 00:02:31.819: INFO: FAILED!
```
[One of the two windows Machines ](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/bootstrap/resources/capz-e2e-c6bd60/Machine/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-bv7cw.yaml) is in `Provisioned` state, with `NodeHealthy` condition false: 

```
  - lastTransitionTime: "2023-08-14T23:34:41Z"
    reason: NodeProvisioning
    severity: Warning
    status: "False"
    type: NodeHealthy
```


However, the node became ready at `23:34:59.517934`

> I0814 23:34:59.517934       1 machine_controller_noderef.go:95] "Infrastructure provider reporting spec.providerID, Kubernetes node is now available" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="capz-e2e-c6bd60/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-xh4xq" namespace="capz-e2e-c6bd60" name="capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-xh4xq" reconcileID=f41b94c3-95e3-49b7-86a4-4497040c2db7 MachineSet="capz-e2e-c6bd60/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq" MachineDeployment="capz-e2e-c6bd60/capz-e2e-c6bd60-ha-md-win" Cluster="capz-e2e-c6bd60/capz-e2e-c6bd60-ha" AzureMachine="capz-e2e-c6bd60/capz-e2e-c6bd60-ha-md-win-gj72t" providerID="azure:///subscriptions/===REDACTED===/resourceGroups/capz-e2e-c6bd60-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-gj72t" node="capz-e2e-gj72t"

The `Node` itself also looks healthy and has a `ProviderID`: https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/capz-e2e-c6bd60-ha/nodes/capz-e2e-fq2sp/node-describe.txt](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/capz-e2e-c6bd60-ha/nodes/capz-e2e-fq2sp/node-describe.txt)

I do see a bunch of errors in [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/capz-e2e-c6bd60-ha/machines/capz-e2e-c6bd60-ha-md-win-74d985d79cx9djbq-bv7cw/kubelet.log) for that node around `cloud-node-manager-windows` pods which are not present in the healthy node's kubelet logs:

> E0814 23:45:04.240258     580 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"cloud-node-manager\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=cloud-node-manager pod=cloud-node-manager-windows-pvqnj_kube-system(851a4374-f2d8-430f-8a92-4efd419c8155)\"" pod="kube-system/cloud-node-manager-windows-pvqnj" podUID=851a4374-f2d8-430f-8a92-4efd419c8155

**Comment by nojnhuh** [comment]
I hit what I think is the same thing in the CAPI MachinePool test: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3723/pull-cluster-api-provider-azure-capi-e2e/1691533729240977408

**Comment by jsturtevant** [comment]
Interestingly, the pod logs for that container report success:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3798/pull-cluster-api-provider-azure-e2e/1691226971670843392/artifacts/clusters/capz-e2e-c6bd60-ha/kube-system/cloud-node-manager-windows-pvqnj/cloud-node-manager.log

```
I0815 00:07:15.512646    5860 nodemanager.go:104] Version: v1.25.17
I0815 00:07:15.512646    5860 nodemanager.go:105] NodeName: capz-e2e-fq2sp
I0815 00:07:15.519770    5860 nodemanager.go:139] Starting cloud-node-manager...
I0815 00:07:15.528373    5860 azure.go:573] Azure cloud provider is starting without credentials
I0815 00:07:15.530141    5860 nodemanager.go:146] Sending events to api server.
I0815 00:07:15.530674    5860 nodemanager.go:156] Started cloud-node-manager
I0815 00:07:15.597091    5860 nodemanager.go:363] Initializing node capz-e2e-fq2sp with cloud provider
I0815 00:07:15.628550    5860 nodemanager.go:473] Adding node label from cloud provider: beta.kubernetes.io/instance-type=Standard_B2s
I0815 00:07:15.628550    5860 nodemanager.go:474] Adding node label from cloud provider: node.kubernetes.io/instance-type=Standard_B2s
I0815 00:07:15.628550    5860 nodemanager.go:489] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=0
I0815 00:07:15.628550    5860 nodemanager.go:490] Adding node label from cloud provider: topology.kubernetes.io/zone=0
I0815 00:07:15.628550    5860 nodemanager.go:500] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=westus2
I0815 00:07:15.628550    5860 nodemanager.go:501] Adding node label from cloud provider: topology.kubernetes.io/region=westus2
I0815 00:07:15.648736    5860 nodemanager.go:426] Successfully initialized node capz-e2e-fq2sp with cloud provider
```

**Comment by jsturtevant** [comment]
In kubelet the logs for the failed restart show it failing up until 

```
0815 00:03:42.233492     580 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"cloud-node-manager\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=cloud-node-manager pod=cloud-node-manager-windows-pvqnj_kube-system(851a4374-f2d8-430f-8a92-4efd419c8155)\"" pod="kube-system/cloud-node-manager-windows-pvqnj" podUID=851a4374-f2d8-430f-8a92-4efd419c8155
```

**Comment by jsturtevant** [comment]
The warning back off was ~4 mins off `Warning  BackOff    4m42s`

**Comment by jsturtevant** [comment]
The containerd logs confirm this was retried several times: 

```
[53] {"Timestamp":"2023-08-15T00:02:07.2295372+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2408,"TraceEventProcessName":"","Message":"CreateContainer within sandbox \"2a1b5be5c415bc9493379842bfb90bd6ec597e8dd57b9ff1fa9be934de61a1e5\" for container &ContainerMetadata{Name:cloud-node-manager,Attempt:10,}","Time":"2023-08-15T00:02:07.2408421+00:00"}}
```

And getting an error when it starts up:

```
[53] {"Timestamp":"2023-08-15T00:02:07.2295372+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2408,"TraceEventProcessName":"","Message":"CreateContainer within sandbox \"2a1b5be5c415bc9493379842bfb90bd6ec597e8dd57b9ff1fa9be934de61a1e5\" for container &ContainerMetadata{Name:cloud-node-manager,Attempt:10,}","Time":"2023-08-15T00:02:07.2408421+00:00"}}
[54] {"Timestamp":"2023-08-15T00:02:08.4290226+00:00","ProviderName":"Microsoft.Virtualization.RunHCS","Level":2,"Keywords":0,"Payload":{"ID":21,"EventName":"LogrusEntry","TraceEventProcessID":1804,"TraceEventProcessName":"","Message":"Span","Time":"2023-08-15T00:02:08.436298+00:00","duration":"4.4443ms","endTime":"2023-08-15T00:02:08.4407423+00:00","name":"HcsOpenComputeSystem","parentSpanID":"e0980bb5874e4e2b","spanID":"9bf49b50acf6481e","startTime":"2023-08-15T00:02:08.436298+00:00","traceID":"acb515d2de1ba0de2b41d4118ff6b996","error":"A virtual machine or container with the specified identifier does not exist."}}
[54] {"Timestamp":"2023-08-15T00:02:08.4544042+00:00","ProviderName":"Microsoft.Virtualization.RunHCS","Level":4,"Keywords":0,"Payload":{"ID":2,"EventName":"LogrusEntry","TraceEventProcessID":1804,"TraceEventProcessName":"","Message":"Span","Time":"2023-08-15T00:02:08.4357875+00:00","duration":"30.0575ms","endTime":"2023-08-15T00:02:08.465845+00:00","name":"delete","parentSpanID":"0000000000000000","spanID":"e0980bb5874e4e2b","startTime":"2023-08-15T00:02:08.4357875+00:00","traceID":"acb515d2de1ba0de2b41d4118ff6b996"}}
```

**Comment by CecileRobertMichon** [comment]
I tried to get a local repro, I definitely do see some of the cloud-node-manager-windows pods crashing and restarting several times when they first come up:

```
kube-system        cloud-node-manager-windows-7gfbp                        1/1     Running   3 (77s ago)    2m35s   10.1.0.13         win-24893-b2xk6                 <none>           <none>
kube-system        cloud-node-manager-windows-gglrb                        1/1     Running   2 (86s ago)    2m29s   10.1.0.10         win-24893-98wlk                 <none>           <none>
kube-system        cloud-node-manager-windows-gqwxt                        1/1     Running   3 (74s ago)    2m36s   10.1.0.12         win-24893-74gnd                 <none>           <none>
kube-system        cloud-node-manager-windows-k7957                        1/1     Running   2 (100s ago)   2m37s   10.1.0.11         win-24893-xplk7                 <none>           <none>
kube-system        cloud-node-manager-windows-mf6xd                        1/1     Running   0              2m39s   10.1.0.9          win-24893-6g7pg                 <none>           <none>
```

**Comment by CecileRobertMichon** [comment]
https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%202

shows 4 clusters of 24 failures (1 in last day) out of 128247 builds from 8/2/2023, 5:00:05 PM to 8/17/2023, 3:51:09 AM.

8/2 happens to be the first day we have data for (2 weeks ago) so nothing special about that date AFAIK

**Comment by CecileRobertMichon** [comment]
@jsturtevant @lzhecheng here are the logs from one failed CNM pod: 

https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3847/pull-cluster-api-provider-azure-e2e/1691851182969982976/artifacts/clusters/capz-e2e-w8l8ng-vmss/kube-system/cloud-node-manager-windows-r6p75/cloud-node-manager.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3847/pull-cluster-api-provider-azure-e2e/1691851182969982976/artifacts/clusters/capz-e2e-w8l8ng-vmss/kube-system/cloud-node-manager-windows-r6p75/cloud-node-manager.log)

```
invalid configuration: unable to read certificate-authority C:\C\67768a87412fd1f062f47d35b680b7866a5a1d2a28a5aeb90264faf5390441a0\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt for default due to open C:\C\67768a87412fd1f062f47d35b680b7866a5a1d2a28a5aeb90264faf5390441a0\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt: The system cannot find the path specified.
```

**Comment by lzhecheng** [comment]
Hello @CecileRobertMichon. Thank you for the information and I think I found the root cause.

The problem is in the `start.ps1` script of `cloud-provider-azure-scripts`. 
```
  start.ps1: |
    $cm = "$env:CONTAINER_SANDBOX_MOUNT_POINT/cloud-node-manager.exe"

    ((Get-Content -path $env:CONTAINER_SANDBOX_MOUNT_POINT/var/lib/cpaw/kubeconfig.conf -Raw) -replace '/var',"$($env:CONTAINER_SANDBOX_MOUNT_POINT)/var") | Set-Content -Path $env:CONTAINER_SANDBOX_MOUNT_POINT/var/lib/cpaw/kubeconfig.conf

    $argList = @()

    foreach ($var in @("LOG_VERBOSITY", "CLOUD_CONFIG", "KUBE_API_BURST", "KUBE_API_CONTENT_TYPE", "KUBE_API_QPS", "MASTER", "MIN_RESYNC_PERIOD", "NODE_STATUS_UPDATE_FREQUENCY", "WAIT_ROUTES")) {
      if ([System.Environment]::GetEnvironmentVariable($var) -NE $null) {
        $argList += [System.Environment]::GetEnvironmentVariable($var)
      }
    }

    Write-Host "Running $cm $argList --node-name=$env:NODE_NAME --use-instance-metadata=true --kubeconfig=$env:CONTAINER_SANDBOX_MOUNT_POINT/var/lib/cpaw/kubeconfig.conf"
    Invoke-Expression "$cm $argList --node-name=$env:NODE_NAME --use-instance-metadata=true --kubeconfig=$env:CONTAINER_SANDBOX_MOUNT_POINT/var/lib/cpaw/kubeconfig.conf"
```
`$env:CONTAINER_SANDBOX_MOUNT_POINT/var/lib/cpaw/kubeconfig.conf` is mounted from kube-proxy ConfigMap but it should not be modified and reused for CNM.exe. Instead, a new copy should be used. Otherwise, the file will be reset by mount behavior.

Then the reason for "flaky" CNM Pod is that if mount reset happens between modifying kubeconfig.conf and CNM.exe run, CNM fails. If CNM.exe run is before mount reset, CNM runs.

Fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4465
