### ISSUE TITLE
Documentation: developement doc Mock Section need update

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/cluster-api-provider-azure#385]
/kind bug

**What steps did you take and what happened:**
The Section `mock` (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/development.md#mocks) in the development.md documentation has a link that does not exist and a make command that doesn't exist as well

**What did you expect to happen:**
How to generate the mocks and work with that.

**Anything else you would like to add:**
I can help with the update, just need to know what is the steps.

**Comment by CecileRobertMichon** [comment]
whoops didn't know that existed, we need to remove it since it's outdated thanks for reporting.

For now you can just run `make generate` to generate mocks.

**Comment by CecileRobertMichon** [comment]
see https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/9bb84dd15a4fc7d86d2f32f149dfd8dc1c7476fa for reference
