### ISSUE TITLE
kubelet uses --config to set some parameters

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#3873]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It seems capz is not using `--config` for kubelet parameters currently. Is it in the roadmap?
```
Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag
```

https://[storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-master-capz/1694016826222055424/artifacts/clusters/capz-v66bu4/machines/capz-v66bu4-control-plane-77lrz/kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-master-capz/1694016826222055424/artifacts/clusters/capz-v66bu4/machines/capz-v66bu4-control-plane-77lrz/kubelet.log)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
> @lzhecheng this might be a better question for the kubeadm folks. CAPZ is not configuring kubelet, only using `kubeadm init` and `kubeadm join` to join the nodes.
> 
> is `container-runtime-endpoint` getting set as an extra kubelet arg in the template you're using in this context?

No, this job is using standard capz cluster [template](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L849-L901). So args should be only `azure-container-registry-config` and `cloud-provider`. I don't know where this arg comes from...

**Comment by CecileRobertMichon** [comment]
It gets set by kubeadm https://github.com/kubernetes/kubernetes/blob/714e77595c8b19b693925bda2a96ab80c307d38f/cmd/kubeadm/app/phases/kubelet/flags.go#L79

looks like this is already tracked in https://github.com/kubernetes/kubeadm/issues/2902

/close
