### ISSUE TITLE
MachinePool upgrade test is failing

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#3875]
**Which jobs are failing:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-24-1-25
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-25-1-26
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-26-1-27

**Which tests are failing:**

MachinePool k8s version upgrade

```
Timed out waiting for all MachinePool k8s-upgrade-and-conformance-iy6m0j/k8s-upgrade-and-conformance-o9rfwj-mp-0 instances to be upgraded to Kubernetes version v1.27.
```

**Since when has it been failing:**

8/17

**Testgrid link:**

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-26-1-27-main/1694130206484205568

**Reason for failure (if possible):**

possibly related to https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/373518e3c79e76d0edd8ddd84679203fd5548f01

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by willie-yao** [comment]
From the `AzureMachine` `events.log`, the failed upgrade seems to be related to this:
```
message: failed to reconcile AzureMachine: failed to reconcile AzureMachine service inboundnatrules: failed to get existing NAT rules: could not list inbound NAT rules for load balancer k8s-upgrade-and-conformance-3cjm3p-public-lb: network.InboundNatRulesClient#List: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```
