### ISSUE TITLE
Azure VM unable to come in service

### ISSUE THREAD

**Issue by saurabrana** [kubernetes-sigs/cluster-api-provider-azure#3903]
/kind bug

[yes, we have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[We are trying to launch an Azure VM, but eventually, it fails to come into service due to failure in the CAPz extensions .]

**What did you expect to happen:**
VM should be launched successfully and able to connect to the cluster always.

**Anything else you would like to add:**
[cloudbase-init.log](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/12461099/cloudbase-init.log)
[Logs.zip](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/12461100/Logs.zip)

**Environment:**

- cluster-api-provider-azure version: v1.8.0
- Kubernetes version: 1.25.7 
- OS : windows build - 10.0.20348

**Comment by hermesimi** [comment]
We are facing a similar issue. Did you find any solution?

**Comment by CecileRobertMichon** [comment]
Hi @saurabrana, have you tried with a newer version of CAPZ? could you please share repro steps (what do your cluster, machines look like)

@hermesimi the VM extension failing just means that k8s node join failed, it could be for a variety of reasons. Are you also seeing this on windows? what k8s version? what CAPZ version?

**Comment by CecileRobertMichon** [comment]
Are those VMs getting created as part of the original cluster creation or is this a scaling event outside of CAPZ by any chance (autoscaler, Azure portal, etc)?

Can you please share repro steps? 

> error execution phase preflight: couldn't validate the identity of the API Server: could not find a JWS signature in the cluster-info ConfigMap for token ID "e9xgm3"

seems like the bootstrap token isn't valid
