### ISSUE TITLE
AAD Pod Identity resources do not get cleaned up

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3905]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
- Deploy any cluster with an AzureClusterIdentity with any `spec.type` that involves creating an AzureIdentity and AzureIdentityBinding, i.e. `ServicePrincipal`, `ServicePrincipalCertificate`, or `UserAssignedMSI`. This applies to both AzureCluster and AzureManagedControlPlane.
- Delete the cluster.
- The AzureIdentity and AzureIdentityBinding remain for at least several hours.

**What did you expect to happen:**
- The Pod Identity resources are deleted shortly after the cluster is deleted

**Anything else you would like to add:**

The controller in controllers/azureidentity_controller.go is responsible for cleaning up those resources. It looks like the reason it's not doing that is because it first tries to get the owning AzureCluster or AzureManagedControlPlane to determine which type owns the resources. Only when the owner is found does the reconciliation continue to delete the necessary resources. But when the AzureCluster or AzureManagedControlPlane is deleted, that get will return a "not found" error and short-circuit reconciliation without deleting the resources.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dtzar** [comment]
Should we still do this since pod identity is now removed in 1.13?

**Comment by nojnhuh** [comment]
I could see marginal benefit in still doing this to prune old Pod Identity resources that still happen to exist, but that doesn't seem worth doing to me at this point. 

/close
