### ISSUE TITLE
[Windows] Stale kubelet log (0720) should not exist

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#3909]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

It is not impacting anything but it looks confusing.

If I created a cluster with Windows Node, I will see some kubelet log says:
```
Get-Content : Cannot find path 'C:\var\lib\kubelet\kubeadm-flags.env' because it does not exist.
At C:\k\StartKubelet.ps1:16 char:16
+ $FileContent = Get-Content -Path "/var/lib/kubelet/kubeadm-flags.env"
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\var\lib\kubelet\kubeadm-flags.env:String) [Get-Content], ItemNotFoun 
   dException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
You cannot call a method on a null-valued expression.
At C:\k\StartKubelet.ps1:17 char:1
+ $kubeAdmArgs = $FileContent.TrimStart('KUBELET_KUBEADM_ARGS=').Trim(' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
https://[storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-ccm-windows-capz/1696553307436224512/artifacts/clusters/capz-yxfhfn/machines/capz-yxfhfn-md-win-5546fbbc8xfslf9-8jwrv/kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-ccm-windows-capz/1696553307436224512/artifacts/clusters/capz-yxfhfn/machines/capz-yxfhfn-md-win-5546fbbc8xfslf9-8jwrv/kubelet.log)

It is actually from `kubelet.err-20230720T203118.471.log` which I believe comes from the Windows image instead of something generated when the cluster is created. However, this log is confusing and hope it can be removed in the image.

**What did you expect to happen:**
No such stale log

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@jsturtevant @marosset
