### ISSUE TITLE
Update loadbalancers service to SDK v2

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#3917]
part of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3409

**Comment by mboersma** [comment]
My approach to these has basically been:
- Change the `import` line to reference the new SDK v2 package
- Replace `network.` with `armnetwork.` (for example) in the loadbalancers.go file
- Fix the resulting compilation errors according to SDK v2 changes
- Repeat the above three steps for the remaining files in the package
- Update the client.go file following the pattern of other SDK v2 PRs
- Run `make generate-go lint go-test`
- Fix errors and repeat

That should do most of it, but in this case there's some special behavior to replicate. The current client adds the `If-Match` header when the loadbalancer has an ETag set.

We don't have direct access to the request or its "preparer" in SDK v2, so we have to add a custom `Policy` class whose behavior can be controller from within the `CreateOrUpdateAsync` func. The [`CustomPutPatchHeaderPolicy`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/managedclusters/client.go#L43) is one example of a custom policy.

**Comment by nojnhuh** [comment]
> That should do most of it, but in this case there's some special behavior to replicate. The current client adds the `If-Match` header when the loadbalancer has an ETag set.

I added something to do this in the second commit of #3938
