### ISSUE TITLE
AKS e2e test flakes in the tags tests with a "not found" error

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3955]
**Which jobs are flaky:**
- pull-cluster-api-provider-azure-e2e-aks

**Which tests are flaky:**
- Workload cluster creation Creating an AKS cluster [Managed Kubernetes] with a single control plane node and 1 node

**Testgrid link:**
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3971/pull-cluster-api-provider-azure-e2e-aks/1704200991722704896
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3975/pull-cluster-api-provider-azure-e2e-aks/1700198722740162560
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3946/pull-cluster-api-provider-azure-e2e-aks/1699032232213090304
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3935/pull-cluster-api-provider-azure-e2e-aks/1697661825484591104
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4094/pull-cluster-api-provider-azure-e2e-aks/1710391381085655040

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind flake

/area managedclusters

**Comment by tapojit047** [comment]
Is this issue resolved? I am facing similar kind of issue in my PR (#3974)[https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3974]

Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3974/pull-cluster-api-provider-azure-e2e-aks/1700477335679012864
