### ISSUE TITLE
Support deploying a cluster using custom k8s build

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#397]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As a Kubernetes developer, I want to use capz to test my build of Kubernetes in the Azure environment.

This is a pre-requisite for being able to run Azure testgrid jobs using capz. For reference, the current setup for testing Kubernetes/Kubernetes on Azure is with [AKS Engine](https://github.com/Azure/aks-engine/blob/master/docs/topics/kubernetes-developers.md).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I think it _might_ be possible to do this right now using an OS image that already has the custom k8s build on it, but I would like to be able to do this without building an image so it can be used in CI. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Going to write down a few notes here from what I've discovered so far:

In order to use a custom k8s build (example k/k master), there are 3 possible ways:

- Build a custom image with image-builder as part of CI and use that image in the cluster
    - pros: can reuse the image for multiple nodes
    - cons: time consuming, building an Azure image with packer takes ~20 minutes
- Use an existing image (possibly with a different k8s version) and in the KubeadmConfig pass in a PreKubeadmCommand script to replace the k8s version with the one we want.
    - pros: doesn't require building an image, faster
    - cons:  we have to do this for every vm, hacky (bash script might be error prone), different from how users are actually building k8s clusters with capz (with images)
- Modify capz/capi to take custom k8s images
     - pros: can be reused more easily by users not familiar with the project and CI (eg. TestGrid w/ kubetest)
    - cons: more work and changes involved.

Existing solutions:

capa does this with 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/hack/ci/e2e-conformance.sh
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/templates/kustomizeversions.yaml#L9

Open questions: 
The above solution only allows a custom k8s version but it does not allow passing in a custom image, for example to build a cluster to test a branch/PR in upstream Kubernetes.

**Comment by nader-ziada** [comment]
I like the `Build a custom image with image-builder as part of CI and use that image in the cluster` option as it gives us. the most flexibility and seems cleaner. is there any way to speed up the packer process? pre-building of anything or things like that?
