### ISSUE TITLE
Audit behavior of managed cluster API fields for consistency

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3990]
/kind cleanup
/area managedclusters

**What needs cleanup:**

There has not historically been much consistency enforced in how fields defined in AzureManagedControlPlane and AzureManagedMachinePool ultimately get represented in API requests to AKS. Some possible opportunities to make things more consistent might include:
- Settling on using pointers or plain values in CAPZ Go API types
- Deciding whether `null` in the CAPZ spec means "zero" or "default" or "whatever already exists in AKS"
- If/how "actual" (vs. "desired") state should be reported

We should take stock of how each field behaves in CAPZ currently to help identify any changes we may want to make.

**Describe the solution you'd like**

The scope of this issue is to identify the current state of affairs and record that in this thread or in some other document linked here, not to decide on any specific approach or make any changes (yet).

**Anything else you would like to add:**

**Comment by dtzar** [comment]
This still applicable @nojnhuh with the new v2 API?

**Comment by nojnhuh** [comment]
No, this was mostly targeting all the fields that the new API inherits straight from ASO. Does that mean we can close this?
