### ISSUE TITLE
"log.SetLogger(...) was never called" in e2e tests

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3999]
/kind bug

**What steps did you take and what happened:**

In at least the ci-entrypoint e2e job, there is an exception and a warning logged near the end:

```go
Sep 12 20:44:59.877: INFO: Collecting boot logs for AzureMachine capz-joz95f-md-0-f6czh
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc00011e800, {0x342ed37, 0x14})
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/log/deleg.go:147 +0x4c
...
```

This suggests we still have some adjustments to make for controller-runtime v1.15.x. See the [CAPI migration guide](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5#notes-about-the-controller-runtime-bump):

> Ensure that the e2e test suite is setting a logger (e.g. via ctrl.SetLogger(klog.Background()) in TestE2E. Otherwise logs are not visible and controller-runtime will print a warning.

**Examples**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3971/pull-cluster-api-provider-azure-ci-entrypoint/1701685446406311936

**Comment by mboersma** [comment]
I think this is confined to the ci-entrypoint job, perhaps because it doesn't use a `TestE2E()` func?

**Comment by Jont828** [comment]
I remember having to set the logger in CAAPH after CAPI v1.5, and there was a similar CAPI PR doing the same. Let me see if I can still find it.
