### ISSUE TITLE
allow networkPolicy to be None for AKS clusters

### ISSUE THREAD

**Issue by zmalik** [kubernetes-sigs/cluster-api-provider-azure#4002]
/kind feature

**Describe the solution you'd like**
The `networkPolicy` parameter in `AzureManagedControlPlaneSpec` allows the configuration of either Azure or Calico network policy managers. However, we have recently identified a limitation with this setup; it is no longer recommended for AKS clusters exceeding 250 nodes, earlier it was for 500 nodes. https://github.com/MicrosoftDocs/azure-docs/commit/365c32b20a97e56d35a09e97fb939f4d08193294 

To address this, I think we CAPZ should allow setting network policy to `None` which explicitly set to `nil` when creating the AKS clusters. 

The property is still immutable so that should still allow backward compatibilty and default behaviour can still continue with `Azure` as default

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Dhairya-Arora01** [comment]
@zmalik @CecileRobertMichon  should we have an if statement inside
[here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/30d08b2a6134420f404205f0d8232a7bf270f425/azure/scope/managedcontrolplane.go#L513C1-L515C3)
to check if the value of network policy is None and if it is set managedClusterSpec.NetworkPolicy to nil

**Comment by CecileRobertMichon** [comment]
@zmalik looking at this more closely, isn't this already possible by leaving the field nil? I don't see any defaulting happening anywhere in the code

> default behaviour can still continue with Azure as default

where do you see this default being set?

**Comment by zmalik** [comment]
you are right this was removed already in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2999 I totally missed it. I should catch up with upstream. 

This issue can be closed! thanks for looking into it still.

**Comment by CecileRobertMichon** [comment]
thank you for confirming!

/close
