### ISSUE TITLE
[Flaky] Node is not ready in CI (maybe related to lease)

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#4010]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I see cluster creation in our CI has failed for several times recently. The problem is that one Node is not ready.

The example is from a dualstack vmss job but it also happened for ipv6 single stack, dualstack standalone. I can see `Failed to get lease: leases.coordination.k8s.io "xxx" not found` in those failed builds and hope it will help.

e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-dualstack-vmss-capz/1702774520093347840

**What did you expect to happen:**

No cluster creation failure

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
cc @feiskyer this accounts for several recent daily CI testgrid job failure.

**Comment by CecileRobertMichon** [comment]
@lzhecheng what k8s version(s) is this with? is it possible it's the same issue as https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3754 ?

**Comment by lzhecheng** [comment]
> @lzhecheng what k8s version(s) is this with? is it possible it's the same issue as #3754 ?

It's k8s v1.27.1.
They seem not related because here Node can not be ready at all.

**Comment by CecileRobertMichon** [comment]
how often is this happening? we haven't seen this flake in capz e2e tests before AFAIK

**Comment by lzhecheng** [comment]
> how often is this happening? we haven't seen this flake in capz e2e tests before AFAIK

I can see it happened on 9/13 9/15 9/16
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-dualstack-vmss-capz/1701687345280978944
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-dualstack-vmss-capz/1702412128368988160
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-dualstack-vmss-capz/1702774520093347840

**Comment by lzhecheng** [comment]
@jackfrancis 
The issue is still happening on ipv6 only with machinedeployment recently. Could you take a look?
The interesting part is that the Node NotReady only happens on one worker Node and the other one is fine.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-ipv6-capz/1753448264994131968
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-ipv6-capz/1751274014896033792

**Comment by lzhecheng** [comment]
The issue has been resolved by updating our templates following the change in CAPZ ones https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4350
/close
