### ISSUE TITLE
Creating an AzureMachinePool with Arm64 node fail with "typeHandlerVersion is invalid"

### ISSUE THREAD

**Issue by arsiesys** [kubernetes-sigs/cluster-api-provider-azure#4022]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
- Create an AzureCluster
- Create an AzureMachinePool using arm nodes/images

```
│ capz-controller-manager-7d5f8f99db-ghs6q E0921 14:11:41.179459       1 controller.go:324]  "msg"="Reconciler error" "error"="failed to reconcile AzureMachinePool service scalesets: failed to create or update resource test/test-arm (service: scalesets): PUT https://mana/ │
│ gement.azure.com/subscriptions/xxxx/resourceGroups/test/providers/Microsoft.Compute/virtualMachineScaleSets/test-arm\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 Bad Request\nERROR  │
│ CODE: InvalidParameter\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"InvalidParameter\",\n    \"message\": \"The value of parameter typeHandlerVersion is invalid.\",\n    \"target\": \"typeHandlerV │
│ ersion\"\n  }\n}\n--------------------------------------------------------------------------------\n" "AzureMachinePool"={"name":"test-arm","namespace":"default"} "controller"="azuremachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="Azur │
│ eMachinePool" "name"="test-arm" "namespace"="default" "reconcileID"="b9eddeeb-ebec-4251-bd81-022da13cc419"
```

**What did you expect to happen:**
The vmss ressource being created

**Anything else you would like to add:**
I rebuilt the controller by changing the extensionVersion used for arm fron 1.1.1 to 1.1 and it fixed the problem:
```
-                       extensionVersion = "1.1.1"
+                       extensionVersion = "1.1"
```

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3dea65e166b9a678c24e1acde5ad4dee2ecbe9fc/azure/defaults.go#L308

It seens that the Azure Api do not accept that we provide the minor version.

With that change, I got my first arm node joining the cluster.

**Environment:**

- cluster-api-provider-azure version: master

**Comment by nojnhuh** [comment]
cc @willie-yao
