### ISSUE TITLE
Codespell unable to list some incorrect spellings

### ISSUE THREAD

**Issue by shiveshabhishek** [kubernetes-sigs/cluster-api-provider-azure#4029]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I tried running `make verify-codespell` with some misspelled words, like `scalibility` but I didn't get the expected suggestion to change it

**What did you expect to happen:**
I should have got a warning to fix the incorrect spelling

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Another word was `Kuebrnetes` which I did not get warning about.

**Environment:**

- cluster-api-provider-azure version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by shiveshabhishek** [comment]
Thank you for the info.  @mboersma 
Do you think it is worth adding some common terms that we use in this repo to the local dictionary?

**Comment by mboersma** [comment]
> Do you think it is worth adding some common terms ... ?

It's not hard to do:
- Create a file named something like `.codespell_dict`
- Populate it with entries in the right [dictionary format](https://github.com/codespell-project/codespell#dictionary-format)
- Change the `verify-codespell` Makefile target to end with
`-D .codespell_dict -D -`
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/03e441bbf30f1f1b00e576fc6209b272d93795c4/Makefile#L278

I think it's only worth doing if we see the same words being misspelled the same way consistently. The way codespell works is by finding specific misspellings that are listed in its dictionary, not by finding mistakes in general.

If you can find misspellings in the codebase that occur more than once, but aren't found by codespell's built-in dictionary, I think it would be worth it.

**Comment by shiveshabhishek** [comment]
Makes sense. I'm closing this issue as I've not found any misspellings as per my findings.
Thanks Matt.
