### ISSUE TITLE
Fix invalid boilerplate

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4038]
/kind cleanup

**What needs cleanup:**

`make verify-boilerplate` has been failing for some time because the script that invokes doesn't fail when the `python` command isn't available, which it's not in the prow environment:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-verify/1706387974339432448#1:build-log.txt%3A21

**Describe the solution you'd like**
The script should be updated to invoke `python3` instead of `python` like CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/4c6e89cf2ca962599856ff8e302894bdd4387bdf/hack/boilerplate/boilerplate.py#L1.

Once that change is made, `make verify-boilerplate` will report errors that should also be fixed.

**Anything else you would like to add:**

**Comment by nojnhuh** [comment]
Thank you @nawazkh for helping find this!

**Comment by jackfrancis** [comment]
Good lord these python 3 land mines are going to outlast my career lifespan.
