### ISSUE TITLE
Reuse Azure Service Operator for IaC

### ISSUE THREAD

**Issue by lieberlois** [kubernetes-sigs/cluster-api-provider-azure#4065]
/kind feature

**Describe the solution you'd like**
I want to be able to reuse the Azure Service Operator deployment that is part of the CAPI Provider Azure for my Azure infrastructure (e.g. Storage Accounts etc.) to prevent the necessity of deploying another solution like Crossplane or even a second ASO. The current implementation appears to deploy the ASO but scoped to a limited set of custom resources (only those that re. 

**Anything else you would like to add:**
--

**Environment:**

- cluster-api-provider-azure version: v1.11.2
- Kubernetes version: 1.25
- OS (e.g. from `/etc/os-release`): Linux

**Comment by CecileRobertMichon** [comment]
cc @dtzar @nojnhuh @matthchr

**Comment by nojnhuh** [comment]
@lieberlois Even though the installation of ASO that comes with CAPZ only comes with a limited number of CRDs currently, it is possible to configure ASO to install and manage more CRDs. Steps to do that are described here: https://capz.sigs.k8s.io/topics/aso#using-aso-for-non-capz-resources. Fair warning that I've only done some light manual testing of that path, so please report any issues if you do try that out.

The inverse of that is described here, where you install ASO however you'd like then install CAPZ later: #3900. I haven't tried that out but I think it's possible.

**Comment by dtzar** [comment]
We discussed this topic today on the CAPZ community call, more specifically:
1. This is now enabling a feature-set (ASO) completely outside of what CAPZ itself is designed to do - should it be included inside clusterctl and/or CAPI Operator or a separate tool?
2. If we are including it inside the purview of CAPZ somehow, would it make sense to only have it enabled via CAPI Operator helm chart and not clusterctl?

IMO - I'd like to see this happen via CAPI Operator helm chart switches.
