### ISSUE TITLE
Add support for Azure Spot VMs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#407]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/spot-vms

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
https://github.com/openshift/enhancements/pull/199

**Comment by CecileRobertMichon** [comment]
capi issue: https://github.com/kubernetes-sigs/cluster-api/issues/1876

**Comment by JoelSpeed** [comment]
I'm trying to answer some questions that were raised around how CAPZ will work with Spot VMs which needs to be properly tested, so I've basically implemented support for this so that I can answer some of these questions. Will assign myself and PR once the CAPI proposal is agreed on

/assign

**Comment by CecileRobertMichon** [comment]
Spot VMs are now GA https://azure.microsoft.com/en-us/updates/azure-spot-virtual-machines-are-now-generally-available
