### ISSUE TITLE
ASO service: virtualmachines

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4072]

**Comment by nojnhuh** [comment]
@willie-yao Sorry for only thinking of this now, but it occurred to me that virtual machines would be the first service that generates one ASO resource per machine which could strain CAPZ/ASO for large clusters. I wonder if it might be better to focus on the one-or-a-few-ish-per-cluster services for now until we have more robust scale testing set up.

If you're reasonably far along on this though I don't think it's worth dropping.

**Comment by willie-yao** [comment]
@nojnhuh No problem. I'm a bit far in but I'm running into a few roadblocks in the implementation. I'll be happy to set it aside for now and circle back to it once we have that figured out. Would that be okay?

**Comment by nojnhuh** [comment]
Yep, no problem.

**Comment by nojnhuh** [comment]
soft-blocked on #3547
