### ISSUE TITLE
ASO service: roleassignments

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4077]

**Comment by nojnhuh** [comment]
I think these are also one per VM.

**Comment by willie-yao** [comment]
Whoops! That makes sense since I had changes for this in the vm PR. Will look elsewhere
/unassign

**Comment by nojnhuh** [comment]
soft-blocked on #3547 (https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4072#issuecomment-1762149705)
