### ISSUE TITLE
USMI is specified in the azuremachine template, but get auth failure on the VM

### ISSUE THREAD

**Issue by zylxjtu** [kubernetes-sigs/cluster-api-provider-azure#4098]
snippet of the azure machinetemplate:
      
identity: UserAssigned
      userAssignedIdentities:
      - providerID: ${MANAGEDIDENTITY_RESOURCE_ID}

in the generated azure.json secret:

    "useManagedIdentityExtension": true,
    "useInstanceMetadata": true,
    "enableVmssFlexNodes": true,
    "userAssignedIdentityID": "/subscrip
    "userAssignedIdentityID": "/subscriptions/1c8c4edc-b188-4199-9580-3173033d75f7/resourcegroups/containerRolling/providers/Microsoft.ManagedIdentity/userAssignedIdentities/containerRollingMI"

The azure vm is booted but not able to join the cluster, by logging to the vm, find the following error:

E1005 16:15:23.456334    7340 kubelet.go:1474] "Kubelet failed to get node info" err="failed to get instance ID from cloud provider: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/1c8c4edc-b188-4199-9580-3173033d75f7/resourceGroups/containerrolling-capz/providers/Microsoft.Compute/virtualMachines?api-version=2019-07-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=%2Fsubscriptions%2F1c8c4edc-b188-4199-9580-3173033d75f7%2Fresourcegroups%2FcontainerRolling%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2FcontainerRollingMI&resource=https%3A%2F%2Fmanagement.core.windows.net%2F"

It looks that the auth is trying to use the specified resource id to get the token, but specify the parameter as "client_id", and hence the token retrieve failure. it should be"mi_res_id" instead

**Comment by CecileRobertMichon** [comment]
this is now fixed in the latest v1.11.3 release

Please reopen if you encounter further issues

/close
