### ISSUE TITLE
Support OOT credential provider for all templates

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cluster-api-provider-azure#4110]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
With latest k8s (1.29+), in-tree credential provider is disabled by default and current capz templates don't support OOT one.

**What did you expect to happen:**
All capz templates support OOT credential provider.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have updated main branch ci-entrypoint to support OOT credential provider. Also for cloud-provider-azure, I have created a template for OOT and it works fine.
https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml

Key change in template:
Scripts to download credential provider binary and config file
```
# linux
        echo "Use OOT credential provider"
        mkdir -p /var/lib/kubelet/credential-provider
        # Update the link below
        curl --retry 10 --retry-delay 5 -Lo /var/lib/kubelet/credential-provider/acr-credential-provider "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${JOB_NAME}/${IMAGE_TAG_ACR_CREDENTIAL_PROVIDER}/azure-acr-credential-provider"
        chmod 755 /var/lib/kubelet/credential-provider/acr-credential-provider

        # Update the link below
        curl --retry 10 --retry-delay 5 -Lo /var/lib/kubelet/credential-provider-config.yaml https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/examples/out-of-tree/credential-provider-config.yaml
        chmod 644 /var/lib/kubelet/credential-provider-config.yaml

# windows
          echo "Use OOT credential provider"
          mkdir C:\var\lib\kubelet\credential-provider
          # Update the link below
          curl.exe --retry 10 --retry-delay 5 -L "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${JOB_NAME}/${IMAGE_TAG_ACR_CREDENTIAL_PROVIDER}/azure-acr-credential-provider.exe" --output C:\var\lib\kubelet\credential-provider\acr-credential-provider.exe
          cp C:\var\lib\kubelet\credential-provider\acr-credential-provider.exe C:\var\lib\kubelet\credential-provider\acr-credential-provider

          # Update the link below
          curl.exe --retry 10 --retry-delay 5 -L https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/examples/out-of-tree/credential-provider-config-win.yaml --output C:\var\lib\kubelet\credential-provider-config.yaml
```

kubelet args:
```
        kubeletExtraArgs:
          image-credential-provider-bin-dir: /var/lib/kubelet/credential-provider
          image-credential-provider-config: /var/lib/kubelet/credential-provider-config.yaml
```

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by lzhecheng** [comment]
@CecileRobertMichon I never update templates in capz repo. Can you show how/example for me or you can help take this issue? I have included all necessary changes in issue description. Thank you.

**Comment by jackfrancis** [comment]
Should the credential provider yaml be downloaded at runtime? Or can we put it into the reference OS image?

**Comment by lzhecheng** [comment]
> Should the credential provider yaml be downloaded at runtime? Or can we put it into the reference OS image?

Yes I think it can be put into the image.

**Comment by jackfrancis** [comment]
cc @mboersma

@lzhecheng Thanks! Does OOT credital provider work with versions of k8s < 1.29? If so can we backport these files into each cloud-provider-azure release branch:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/examples/out-of-tree/credential-provider-config.yaml

As far as I know CAPZ builds OS images for each release, so we'd want to update those CI to pull the release-appropriate yaml file to put into /var/lib/kubelet.

**Comment by lzhecheng** [comment]
@jackfrancis yes, I can do it. Notice, windows config file is different from linux one so its config file is called `credential-provider-config-win.yaml` and should be renamed when put into `/var/lib/kubelet`.

**Comment by lzhecheng** [comment]
> > curl --retry 10 --retry-delay 5 -Lo /var/lib/kubelet/credential-provider/acr-credential-provider "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${JOB_NAME}/${IMAGE_TAG_ACR_CREDENTIAL_PROVIDER}/azure-acr-credential-provider"
> 
> Looks like the template above is building the OOT credential provider binary for the purpose of testing it, how does it work when we don't want to build it ourselves but just use a release? Is that where it would need to be put on the VM OS image? or is there a helm chart for it to install it on k8s clusters? @lzhecheng

My recent change to `ci-entrypoint.sh` doesn't support it. I think it should be done the same way as CCM.
So far no helm chart.

**Comment by CecileRobertMichon** [comment]
/reopen

@lzhecheng #4169 added OOT credential provider to all the k8s CI artifacts templates, however we need a more user friendly way to install it (e.g. Helm chart) before we can add it to all templates.

**Comment by CecileRobertMichon** [comment]
@lzhecheng it seems that the credential provider doesn't work with kubelet 1.25? The tests are failing for k8s 1.25 since this merged, kubelet is crashing with 

```
Nov 04 20:58:31.931758 capz-conf-wmjvfg-control-plane-s64vm kubelet[2684]: E1104 20:58:31.931732    2684 kuberuntime_manager.go:261] "Failed to register CRI auth plugins" err="error decoding config /var/lib/kubelet/credential-provider-config.yaml: no kind \"CredentialProviderConfig\" is registered for version \"kubelet.config.k8s.io/v1\" in scheme \"pkg/credentialprovider/plugin/plugin.go:56\""
```

https://[storage.googleapis.com/kubernetes-jenkins/logs/capz-conformance-dual-stack-1-25/1720896299273818112/artifacts/clusters/capz-conf-wmjvfg/machines/capz-conf-wmjvfg-control-plane-b8zps/kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/capz-conformance-dual-stack-1-25/1720896299273818112/artifacts/clusters/capz-conf-wmjvfg/machines/capz-conf-wmjvfg-control-plane-b8zps/kubelet.log)
https://testgrid.k8s.io/provider-azure-1.25-signal#capz-conformance-dual-stack

**Comment by mboersma** [comment]
@lzhecheng what work items remain to do before we can close this?

**Comment by lzhecheng** [comment]
> @lzhecheng what work items remain to do before we can close this?

Currently all templates have OOT cred provider, and they are working fine.
But Cecile mentioned before that it is better to use the credential provider binary & config directly in the vm image as for non-CI templates. I merged a PR for this into the image-builder repo before and that's the reason.
Do you think it needs to be done? If not, please feel free to close the issue.

**Comment by mboersma** [comment]
/close

Let's open a more specific issue for the refactoring of the cred binaries.
