### ISSUE TITLE
Allow omitting the k8s patch version in `azuremanagedcontrolplanes`

### ISSUE THREAD

**Issue by felfa01** [kubernetes-sigs/cluster-api-provider-azure#4111]
/kind feature

**Describe the solution you'd like**
AKS allows to omit the patch version and thus defaulting to latest patch. When trying to configure this via CAPZ the following error is thrown:
```
Error: admission webhook "validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io" denied the request: must be a valid semantic version
```

Support docs: https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#alias-minor-version

**Comment by nojnhuh** [comment]
I think this would fit better as a change separate from #4069. This might be a bit more complicated than changing a regex since that value is currently shared in the templates between AzureManagedControlPlane `spec.version` and MachinePool `spec.template.spec.version` and I'm not sure if CAPI accepts MAJOR.MINOR versions there.

**Comment by LochanRn** [comment]
@nojnhuh how do we support this if we want ?

Should I raise a support request in CAPI ?

**Comment by nojnhuh** [comment]
I think bringing this up in CAPI makes the most sense to me. That may have already been discussed at some point, so it would be worth a quick look through the CAPI issue queue, Slack, and weekly meeting notes to see if that has been previously brought up.

**Comment by nojnhuh** [comment]
This is possible with the new ASO-based API: https://capz.sigs.k8s.io/topics/aso#experimental-aso-api

The way you would do this is to not specify `spec.template.spec.version` on the MachinePool, then set `spec.orchestratorVersion` to anything allowed by AKS on the ManagedClustersAgentPool definition in `spec.resources` for the AzureASOManagedMachinePool. `orchestratorVersion` would be set under this `spec` in the example template: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/32ebb7709bfd89a0d06c8dd40d25cf1ab39f8ac9/templates/cluster-template-aks-aso.yaml#L91

/close
