### ISSUE TITLE
Support for AKS cluster deployment with Major.Minor version.

### ISSUE THREAD

**Issue by LochanRn** [kubernetes-sigs/cluster-api-provider-azure#4117]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Support deploying AKS clusters using capz, with just major.minor version 
eg version: 1.26.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
Duplicate of #4111?

**Comment by LochanRn** [comment]
@nojnhuh yes.

**Comment by nojnhuh** [comment]
Duplicate of #4111

/close
