### ISSUE TITLE
e2e VMSS spec fails with "no machine has started to drain"

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#4123]
**Which jobs are flaky:**

pull-cluster-api-provider-azure-e2e

**Which tests are flaky:**

`Creating a VMSS cluster [REQUIRED]`

**Testgrid link:**

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4121/pull-cluster-api-provider-azure-e2e/1712247975322849280

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind flake

**Comment by CecileRobertMichon** [comment]
This test is about to be removed in #3998 

cc @Jont828
