### ISSUE TITLE
CAPI v1.6.0-beta.0 has been released and is ready for testing

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#4179]
CAPI v1.6.0-beta.0 has been released and is ready for testing.
Looking forward to your feedback before v1.6.0 release!

## For quick reference

- [CAPI v1.6.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

CAPI v1.6.0 will be released on **Tuesday, 28th November 2023**.

More details of the upcoming schedule can be seen at [CAPI v1.6.0 release timeline](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/releases/release-1.6.md#timeline).

**Comment by willie-yao** [comment]
/unassign
/assign @mboersma 
Sorry, didn't realize you already started working on this!

**Comment by mboersma** [comment]
@willie-yao sorry, I should have `/assign`ed myself. I started the PR but haven't gotten back to it to fix the remaining issues. I'll do so by the end of the week, but if you want to look at sooner please feel free, you're not stepping on my toes. :-)
