### ISSUE TITLE
Use `// +kubebuilder:default` annotations where possible

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4204]
/kind cleanup
/good-first-issue
/help

**What needs cleanup:**

There are several places in the defaulting webhooks where CAPZ defaults a static value that could be replaced with the [`// +kubebuilder:default`](https://book.kubebuilder.io/reference/markers/crd-validation.html) annotation on the API type.

e.g. this code defaults a static value
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremanagedcontrolplane_webhook.go#L75-L78

It should be removed and replaced by the following change to this block:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremanagedcontrolplane_types.go#L118-L123

```diff
diff --git a/api/v1beta1/azuremanagedcontrolplane_types.go b/api/v1beta1/azuremanagedcontrolplane_types.go
index 5d83db207..35adbf3db 100644
--- a/api/v1beta1/azuremanagedcontrolplane_types.go
+++ b/api/v1beta1/azuremanagedcontrolplane_types.go
@@ -126,6 +126,7 @@ type AzureManagedControlPlaneSpec struct {
 	// Allowed values are "azure", "kubenet".
 	// Immutable.
 	// +kubebuilder:validation:Enum=azure;kubenet
+	// +kubebuilder:default:=azure
 	// +optional
 	NetworkPlugin *string `json:"networkPlugin,omitempty"`
```

Tests that verify the removed code should also be removed.

After modifying the annotations, run `make generate-manifests` to encode the new defaults in the CRDs.

**Describe the solution you'd like**
Walk through the webhooks starting at the following places and replace hand-rolled code to default fields with static fields with the kubebuilder annotation:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremachine_webhook.go#L221
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremachinetemplate_webhook.go#L145
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremanagedcontrolplane_webhook.go#L70
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/api/v1beta1/azuremanagedmachinepool_webhook.go#L68
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e2bd59253c859b151ac6f3222ad6c749e2a1ba75/exp/api/v1beta1/azuremachinepool_webhook.go#L59

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by SubhasmitaSw** [comment]
I'd like to work on this, assigning it to myself. 

/assign

**Comment by SubhasmitaSw** [comment]
@nojnhuh I've submitted a [PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4214) the aforementioned cleanup. Kindly review it at your earliest convenience. Thank you!

**Comment by kumarankit999** [comment]
I would like to go with this issue!
If anyone is not working on this issue!

**Comment by nojnhuh** [comment]
Thank you!
/assign @kumarankit999

**Comment by bryan-cox** [comment]
It doesn't look like there has been any new progress on this issue. I can work on this issue if no one is actively working on it.

**Comment by nawazkh** [comment]
Feel free to pick it up @bryan-cox !
/unassign @kumarankit999
