### ISSUE TITLE
Add constants for CAPZ Kind names

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#4223]
/kind cleanup

**What needs cleanup:**
[A clear and concise description of what needs to be cleaned up.]

There are a bunch of hardcoded strings in the codebase for the CRD Kinds (`"AzureCluster"`, `"AzureCluster"`, `"AzureMachinePool"`, `"AzureManagedCluster"`, `"AzureManagedControlPlane"`, `"AzureClusterIdentity"`, etc.). We should add constants for these strings and reuse them throughout the codebase instead of hardcoding them in several places.

**Describe the solution you'd like**
[Description of how you would like the cleanup to be done.]

Files to change: 2

- [ ] File 1
  - Specific lines to cleanup
- [ ] File 2
  - Specific lines to cleanup

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by SD-13** [comment]
Hi @CecileRobertMichon Can I work on this issue?

**Comment by CecileRobertMichon** [comment]
@SD-13 yes please assign yourself to the issue by commenting "/assign"

**Comment by SD-13** [comment]
Hey @CecileRobertMichon I am not sure what would be the correct location to add the constants. Should we add them in `api/v1beta1/consts.go`?
