### ISSUE TITLE
Add unit test coverage for azurecluster_reconciler.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#4227]
Add unit test coverage for azurecluster_reconcilergo. This is a part of a larger effort to improve overall test converage in the controllers package: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3649

**Comment by aniruddha2000** [comment]
@willie-yao I think close this one, as already implemented

**Comment by willie-yao** [comment]
/close

Thanks @aniruddha2000 !
