### ISSUE TITLE
Agent nodes have role of "<none>"

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#423]
/kind bug

**What steps did you take and what happened:**
I provisioned a new cluster-api cluster according to our docs, but it appears the agent nodes don't get labeled as expected:
```console
% kubectl --kubeconfig=./examples/_out/clusterapi.kubeconfig get no
NAME                          STATUS   ROLES    AGE     VERSION
capz-cluster-controlplane-0   Ready    master   6m43s   v1.16.7
capz-cluster-controlplane-1   Ready    master   5m10s   v1.16.7
capz-cluster-controlplane-2   Ready    master   3m51s   v1.16.7
capz-cluster-md-0-xbm55       Ready    <none>   3m41s   v1.16.7
capz-cluster-md-0-xmtz2       Ready    <none>   2m49s   v1.16.7
```

**What did you expect to happen:**
Expected the agent nodes eventually to show up with that role.

**Anything else you would like to add:**
In AKS Engine, we rely on a hacky systemd script to apply the node-role.kubernetes.io and friends labels. I'm not sure what code is successfully applying the label to the masters here--cloud-provider?--but ideally it would also label the agents.

This isn't mission-critical functionality AFAICT. Scheduling isn't usually done via these labels, it's mostly a user convenience.

**Environment:**

- cluster-api-provider-azure version: master
- Kubernetes version: (use `kubectl version`): v1.16.7
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
FWIW I've also noticed that sometimes one or more of the control plane nodes also don't have a label.
Agree this isn't critical, but it would be nice to get it fixed. 

/help

**Comment by detiber** [comment]
My memory is a little fuzzy here, but iirc the idea was that if someone wanted to set the node-role labels that it could be done using a controller that is separate from Cluster API to do so, and that we didn't want to make assumptions on behalf of the user in core Cluster API at the time.

That said, this might be a good use of the new experimental feature/gates and/or APIs and controllers to handle.

The current labeling of control plane nodes is done via kubeadm currently.

**Comment by cpanato** [comment]
What are the directions/decision here? should we fix that or leave as is?

**Comment by CecileRobertMichon** [comment]
@detiber are you saying we should consider implementing this at the capi level?

**Comment by detiber** [comment]
@CecileRobertMichon it's probably worth the discussion again.

**Comment by CecileRobertMichon** [comment]
opened https://github.com/kubernetes-sigs/cluster-api/issues/2596

**Comment by CecileRobertMichon** [comment]
/close

this is already being tracked in the capi issue above
