### ISSUE TITLE
Add unit test coverage for azureidentity_controller.go

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#4267]
Add unit test coverage for azureidentity_controller.go. This is a part of a larger effort to improve overall test coverage in the controllers package: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3649

**Comment by aniruddha2000** [comment]
@troy0820 thanks

**Comment by troy0820** [comment]
Closing because this got merged.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4269
/close
