### ISSUE TITLE
Refactor: use defaulting/validating webhooks for more properties

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#427]
Right now we do a lot of defaulting and validation in azuremachine_reconciler.go and azurecluster_reconciler.go. After #334 merges, we should apply the same default/validation method to other cluster and machine spec properties such as: subnets, vnets, NSGs, etc.

**Comment by richardcase** [comment]
@CecileRobertMichon  -  I can look at this after #334 if you want?

**Comment by CecileRobertMichon** [comment]
@richardcase that'd be great if you can! 

I'll assign you for now so no one else takes it

/assign richardcase

**Comment by CecileRobertMichon** [comment]
@richardcase are you still interested in working on this?

**Comment by richardcase** [comment]
@CecileRobertMichon  - i am and have started. But want to get the failure domains finished first. Shall i unassign for the time being?

**Comment by CecileRobertMichon** [comment]
Sounds good, thanks! No need to unassign yourself since you have already started and intend on working on it later.
