### ISSUE TITLE
2 seconds is too short for azure api call

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/cluster-api-provider-azure#4276]
2 seconds is too short for azure api call. 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/fc261f0df8cfe4f783039d8c182c616d18843685/util/reconciler/defaults.go#L33

NSG subnet route table requests got cancelled because context expired. 

https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/4997/pull-cloud-provider-azure-e2e-capz/1724631304445628416/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-69487dcc9f-4pzvp/manager.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/4997/pull-cloud-provider-azure-e2e-capz/1724631304445628416/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-69487dcc9f-4pzvp/manager.log)

https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/4968/pull-cloud-provider-azure-e2e-capz/1724664448301404160/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-69487dcc9f-z7b5v/manager.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/4968/pull-cloud-provider-azure-e2e-capz/1724664448301404160/artifacts/clusters/bootstrap/controllers/capz-controller-manager/capz-controller-manager-69487dcc9f-z7b5v/manager.log)

**Comment by CecileRobertMichon** [comment]
see also: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/proposals/20210716-async-azure-resource-creation-deletion.md
