### ISSUE TITLE
ArgoCD app sync fails because of ds.meta_data["local_hostname"] in CRD

### ISSUE THREAD

**Issue by dragon119** [kubernetes-sigs/cluster-api-provider-azure#4297]
I'm trying to provision a k8s cluster on Azure using ArgoCD and Cluster API. When I run the clusterctl generate command to provision k8s on Azure, the CRD contains the following line that causes the error at the bottom in syncing app.  I see the same line in KubeadmControlPlane as well. Anybody has faced the same issue? 

This line causes the parse error:
**{{ ds.meta_data["local_hostname"] }}**

apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capiz-workload-007-md-0
  namespace: default
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: worker-node-azure.json
            name: capiz-workload-007-md-0-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            azure-container-registry-config: /etc/kubernetes/azure.json
            cloud-provider: external
          **name: '{{ ds.meta_data["local_hostname"] }}'**
      preKubeadmCommands: []

This is the error message I got when I run argocd app sync command.
 
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template cluster-create --kube-version 1.26 --values <path to cached source>/mgmt/values-c1.yaml <api versions removed> --include-crds` failed exit status 1: Error: parse error at (cluster-config/templates/cluster-api-template.yaml:191): function "ds" not defined Use --debug flag to render out invalid YAML

**Comment by CecileRobertMichon** [comment]
cc @dtzar @nawazkh

**Comment by dragon119** [comment]
This issue is solved by separating it out to value file. I changed the format a little bit as follow.
'"{{ ds.meta_data[\"local_hostname\"] }}"'

**Comment by dtzar** [comment]
Glad you got it figured out!  Sounds like you've got this figured out, so closing.  Let us know if otherwise.
