### ISSUE TITLE
Flatcar e2e tests are failing

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-azure#4317]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

Opening issue for visiblity.

This is caused by https://github.com/kubernetes-sigs/image-builder/issues/1346. We can either patch it on Flatcar template level temporarily to make it work with existing CAPZ images, then e.g. wait new k8s bugfix release to build new images with a fix on image-builder level or even wait for Flatcar itself to possibly provide a fix, depending on how urgent this issue is.

**Comment by nojnhuh** [comment]
Flatcar tests are green again.

/close
