### ISSUE TITLE
Add e2e tests for private endpoints

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#4336]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- With https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4108 landing very soon, we would like to have an e2e test scenario added to test the private endpoint service in CAPZ.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: n/a
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by nojnhuh** [comment]
For context, the tricky part here is determining what the private endpoint in the test can link to. In my testing I've been spinning up an ACR instance (with the premium SKU) and linking to that, but I'm not sure if there's a cheaper option.
