### ISSUE TITLE
etcd state stalls control plane bootstrapping on 2nd node

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#435]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
[etcd] Announced new etcd member joining to the existing etcd cluster
[etcd] Creating static Pod manifest for "etcd"
[etcd] Waiting for the new etcd member to join the cluster. This can take up to 40s
[kubelet-check] Initial timeout of 40s passed.
{"level":"warn","ts":"2020-03-10T17:06:06.640Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://10.0.0.5:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
error execution phase control-plane-join/update-status: error uploading configuration: unable to create ConfigMap: rpc error: code = Unavailable desc = etcdserver: leader changed
To see the stack trace of this error execute with --v=5 or higher
Cloud-init v. 19.4-33-gbb4131a2-0ubuntu1~18.04.1 running 'modules:final' at Tue, 10 Mar 2020 17:05:16 +0000. Up 34.85 seconds.
2020-03-10 17:06:17,866 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2020-03-10 17:06:17,891 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-03-10 17:06:17,901 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 19.4-33-gbb4131a2-0ubuntu1~18.04.1 finished at Tue, 10 Mar 2020 17:06:18 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 96.93 seconds
```

https://github.com/kubernetes-sigs/cluster-api/issues/2591

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by xgao3** [comment]
Running into the same issue in my environment.  2nd control plane node fails to join the cluster:

etcd] Announced new etcd member joining to the existing etcd cluster
[etcd] Creating static Pod manifest for "etcd"
[etcd] Waiting for the new etcd member to join the cluster. This can take up to 40s
{"level":"warn","ts":"2020-03-11T03:51:04.512Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthroug
h:///https://10.174.6.87:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
error execution phase control-plane-join/update-status: error uploading configuration: unable to create ConfigMap: Post https://10.174.6.100:6443/api/v1/
namespaces/kube-system/configmaps?timeout=10s: dial tcp 10.174.6.100:6443: connect: connection refused
To see the stack trace of this error execute with --v=5 or higher
Cloud-init v. 19.4-33-gbb4131a2-0ubuntu1~18.04.1 running 'modules:final' at Wed, 11 Mar 2020 03:50:23 +0000. Up 10.35 seconds.
2020-03-11 03:51:04,575 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2020-03-11 03:51:04,578 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-03-11 03:51:04,578 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/
cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 19.4-33-gbb4131a2-0ubuntu1~18.04.1 finished at Wed, 11 Mar 2020 03:51:04 +0000. Datasource DataSourceVMwareGuestInfo.  Up 51.53 seconds
root@xgao-cluster-pwgmf:/var/log# exi

**Comment by CecileRobertMichon** [comment]
@xgao3 I believe this might have gotten fixed with #438, could you please try again from the latest master and let me know if you can still repro?

**Comment by CecileRobertMichon** [comment]
going to close this for now since I'm not seeing it anymore on latest master, please reopen if it is still happening.

/close

**Comment by CecileRobertMichon** [comment]
I just got a repro on latest master so it looks like this is still happening intermittently.

**Comment by CecileRobertMichon** [comment]
After doing a lot of investigation with @devigned, we reached the conclusion that this is most likely due to the disk being too small. Currently etcd is running on the OS Disk and the example template has a 30GB size. The short term fix is to up that size to at least 128GB, per the recommendation on https://etcd.io/docs/v3.3.12/op-guide/hardware/. As a more long term solution, I am looking creating a data disk for etcd.
