### ISSUE TITLE
Add test that upgrades CAPZ from latest release branch to HEAD

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4359]
/kind cleanup

Currently, the only test that CAPZ runs which upgrades from an older version of CAPZ upgrades from v1.0 of CAPZ. A new test should be added which upgrades from the most recent stable version of CAPZ.

This would likely more accurately reflect the upgrade scenarios that users encounter and help catch issues like the one fixed by #4308 which affects upgrades only from newer versions of CAPZ.

**Comment by CecileRobertMichon** [comment]
This is partially solved by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4433 

it doesn't upgrade from the latest release but from the older supported release (n-2). We could easily add a second cluster test that uses the latest release.
