### ISSUE TITLE
Add Kubebuilder `printcolumns` to CAPZ resources 

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#4376]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- This ask is evolving out of the comment at https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4371#issuecomment-1853191449.

- We should be adding more `print columns` to `azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io` to display the resource's state. As of now, we only display the resource name and its age.
```
❯ kg azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
NAME        AGE
aks-24401   3m49s
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- There are many other resource types in CAPZ that need more printcolumns added to them. We can either make this issue an epic or have individual issues connected to it. Either works.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by SD-13** [comment]
I would like to work on this.

/assign

**Comment by prashantrewar** [comment]
hey @nawazkh I created a PR for this issue, could you please take a look?
