### ISSUE TITLE
Support failure domains

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#439]
"An infrastructure provider may or may not implement the failure domains feature. Failure domains gives Cluster API just enough information to spread machines out reducing the risk of a target cluster failing due to a domain outage. This is particularly useful for Control Plane providers. They are now able to put control plane nodes in different domains.

An infrastructure provider can implement this by setting the InfraCluster.Status.FailureDomains field with a map of unique keys to failureDomainSpecs as well as respecting a set Machine.Spec.FailureDomain field when creating instances.

To support migration from failure domains that were previously specified through provider-specific resources, the Machine controller will support updating Machine.Spec.FailureDomain field if Spec.FailureDomain is present and defined on the provider-defined infrastructure resource.

Please see the cluster and machine infrastructure provider specifications for more detail."

https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#optional-support-failure-domains

**Comment by CecileRobertMichon** [comment]
Failure domains should map to Azure availability zones, eg. https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1420/files

/help

**Comment by richardcase** [comment]
@CecileRobertMichon - shall i deprecate the `AvailabilityZone` field like they have in the AWS provider? Or shall we just provide a conversion function between v1alpha2(AvailabilityZone) and v1alpha3(FailureDomain)?

I think i prefer the conversion approach as it doesn't require the support of both fields and the removal of `AvailabilityZone` in the future.

**Comment by CecileRobertMichon** [comment]
@detiber do you have any guidance here?

**Comment by detiber** [comment]
I think things are a bit complicated by the existence of a v1alpha3 release, I don't think doing the conversion from v1alpha2 -> v1alpha3 is feasible considering it would break the v1alpha3 api that was already published.

If backward compatibility is desired, I think you can probably do the following:
- Deprecate the existing AvailabilityZone field
- Add a new FailureDomain field
- AzureMachine controller can populate FailureDomain with the value from AvailabilityZone if available
- AzureMachine controller can prioritize Machine.Spec.FailureDomain, over AzureMachine.Spec.FailureDomain, over AzureMachine.Spec.AvailabilityZone
- conversion webhook to restore AzureMachine.Spec.FailureDomain from annotation 

This should handle v1alpha2 -> v1alpha3 conversions, migrating the value from the deprecated field to the new field, and support the upstream migration to Machine.Spec.FailureDomain

It's not overly pretty, but it should accomplish the goal with only additive API type changes and not require bumping to v1alpha4 yet.

**Comment by richardcase** [comment]
Sounds like a plan to me. Thanks @detiber and @CecileRobertMichon

**Comment by cpanato** [comment]
/remove-help 

since @richardcase is working on

**Comment by CecileRobertMichon** [comment]
/close

fixed in #572
