### ISSUE TITLE
Does CAPZ supports workload cluster with nodes located in different regions?

### ISSUE THREAD

**Issue by DonadoJuan** [kubernetes-sigs/cluster-api-provider-azure#4395]
That's pretty much it. I would like to know if it is possible to create a workload cluster where nodes can be located in different azure locations. It seems that by default worker nodes are created within the same location as the control plane nodes.

**Comment by dtzar** [comment]
Yes, you just use the spec - location field for the resources you are deploying. e.g.

```
spec:
  location: southcentralus
```

**Comment by DonadoJuan** [comment]
@dtzar thanks for the feedback! my think question was a bit confusing:
I'm trying to create a cluster with 2 worker nodes that must be located in different azure locations (e.g. North europe and US east). This would be considered as a multi-region cluster. I don't see a _location_ property in AzureMachineTemplate.
 Is that possible or do I have to create a cluster for each region?

**Comment by dtzar** [comment]
You just would have two different AzureMachineTemplate resources, each with different location values.

**Comment by DonadoJuan** [comment]
@dtzar There's no **location** field defined for CDR AzureMachineTemplate (v1beta1). The location seems to be inherited from the **location** field in **AzureCluster**. How can I achieve what you describe without defining an AzureCluster per region?

**Comment by dtzar** [comment]
Yes, you would need an AzureCluster for each region.  If you want everything identical and it's just a matter of DRY, then you could utilize tooling like a helm chart or kustomize to templatize the YAML.  This would be the same challenge with any infrastructure as code (e.g. Do I really have to create another definition file for a different cluster which exists in a new region?).
