### ISSUE TITLE
Implement --feature-gates flag in main.go

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#440]
"Cluster API now ships with a new experimental package that lives under exp/ containing both API types and controllers.
Controller and types should always live behind a gate defined under the feature/ package.
If you’re planning to support experimental features or API types in your provider or codebase, you can add feature.MutableGates.AddFlag(fs) to your main.go when initializing command line flags. For a full example, you can refer to the main.go in Cluster API or under bootstrap/kubeadm/."

https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#optional-implement---feature-gates-flag-in-maingo

**Comment by cpanato** [comment]
I will try this one

/assign
/help cancel

**Comment by cpanato** [comment]
I will try this one

/assign
/remove-help
