### ISSUE TITLE
Releasing docs need some updates

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#4479]
/kind documentation

In executing the v1.13.0, v1.12.2, and v1.11.8 CAPZ releases with new tooling, the team ran into a few issues and things that could be clarified. This issue tries to summarize our findings so we can improve the documentation and fix bugs that we found.

Please add to this list by adding more comments!

**Comment by mboersma** [comment]
- make promote-images assumes https, not ssh, and sets USER_FORK wrongly
- should clarify that there are two metadata.yaml files
- bug in release-notes tool that generates bad links
- clarify that PRs are created against the `main` branch
- update "1.5" to to "1.13" (or current) in paragraph beginning "Additionally, we need to update the..."
- clarify that creating a new milestone must be done by a maintainer
- clarify that the release notes PR should contain a single file
- clarify that `make promote-images` is still using ${RELEASE_TAG} set earlier

**Comment by mboersma** [comment]
- point out that a maintainer must publish the draft release

**Comment by nawazkh** [comment]
- Emphasize that the Release should only be published once the k8s.io - image promotion PR gets merges.

**Comment by nawazkh** [comment]
I have some idea on the changes I need to do to improve the documentation. I will take a stab at this. 
/assign

**Comment by mboersma** [comment]
@nawazkh I already created #4483--sorry, didn't mean to step on your toes! Please feel free to copy from it, push more commits to it, or close it.

**Comment by nawazkh** [comment]
Sorry, The UI probably didn't update at my end and looked unassigned. Unassigning myself. 
/unassign

**Comment by mboersma** [comment]
> - bug in release-notes tool that generates (some) bad links

See kubernetes/release#3424 to track this.
