### ISSUE TITLE
Re-evaluate putting etcd in a data disk

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#448]
Related to #435 

Currently etcd is running on the OS Disk and the example template has a 30GB size. The short term fix is to up that size to at least 128GB (#445), per the recommendation on https://etcd.io/docs/v3.3.12/op-guide/hardware/. As a more long term solution, I would like to look into creating a data disk for etcd.

**Comment by CecileRobertMichon** [comment]
WIP doc is [here](https://docs.google.com/document/d/12eYcQrlZdkojHY3atUCCIS9YGPQ1LSQvT4gdg6JWroc/edit?usp=sharing)

**Comment by CecileRobertMichon** [comment]
@detiber @alexeldeib @devigned would love any feedback on the general direction of https://docs.google.com/document/d/12eYcQrlZdkojHY3atUCCIS9YGPQ1LSQvT4gdg6JWroc/edit?usp=sharing before I polish it and share it with the wider CAPI community. There are still some rough edges (like what should the `ClusterConfiguration.Etcd.LocalEtcd.MountOptions` API look like) but 
I want to make sure doing this in the first place even makes sense first (ie. do we even need a new API?).

**Comment by devigned** [comment]
Read through the doc. Though I don't have a ton of depth in the bootstrap provider, it does seem like the right place to add the mount config. Using pre and post scripts does strike me as the way this should be implemented.

**Comment by CecileRobertMichon** [comment]
I updated the proposal to propose adding a generic way to specify disk partitions and mounts in cloud init as part of KubeadmConfigSpec instead of making the change etcd specific. I'll share the proposal at the capz office hours tomorrow (5/1) and at the capi office hours next week (5/6).

**Comment by CecileRobertMichon** [comment]
Also look into https://github.com/Azure/aks-engine/issues/3285 and https://github.com/Azure/aks-engine/issues/3286
