### ISSUE TITLE
Review prow plugins required for project

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#45]
FIrst crack at parity with other cluster-api projects here: https://github.com/kubernetes/test-infra/pull/10670
There's still some work to be done to assess the appropriate plugins for the project.

/assign

**Comment by soggiest** [comment]
We've added milestone integration as of last night. From the contents of the `plugins.yaml` this project has more plugins associated with it than most.

**Comment by justaugustus** [comment]
Closing this. I think we have what we need here.
/kind feature
/priority critical-urgent
/close

**Comment by justaugustus** [comment]
For reference, the prow plugins currently enabled for the repo are:
```
  kubernetes-sigs/cluster-api-provider-azure:
  - milestone
  - milestonestatus
  - release-note
  - require-matching-label
  - welcome
  - trigger
```

and for k-sigs/*:
```
  kubernetes-sigs:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks
```
