### ISSUE TITLE
Verify that Tilt works as expected with capz and add capz section to capi book tilt docs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#450]
https://cluster-api.sigs.k8s.io/developer/tilt.html#prerequisites 

1) Follow the instructions above for Tilt to make sure it works will with the current `tilt-provider.json`  in the capz master branch. 
2) Add a capz section in the book (capi docs)

**Comment by jsturtevant** [comment]
I am working on this

**Comment by CecileRobertMichon** [comment]
/close 

fixed in https://github.com/kubernetes-sigs/cluster-api/pull/2333

**Comment by jsturtevant** [comment]
I confirmed it is hot re-loading the azure manager container with the current tilt-provider.json 👍
