### ISSUE TITLE
Upgrade to 1.13 failing with ClientAssertionCredential errors

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#4521]
/kind bug

**What steps did you take and what happened:**
Upgraded my existing functioning management cluster from 1.12.1 to 1.13.0.  Bumped the version of K8s in my CAPZ YAML definition to upgrade the cluster.  For awhile, nothing got upgraded but eventually the controlplane upgraded and ONE of the node pools upgraded.  The additional node pool is still stuck trying to upgrade.

**What did you expect to happen:**
The upgrade just worked without any errors.

**Anything else you would like to add:**
Error logs from CAPZ management controller.  #'s changed for security reasons.

```
E0130 20:21:44.879946       1 controller.go:329] "Reconciler error" err="error creating AzureManagedControlPlane default/ascapz: failed to reconcile kubeconfig secret: failed to construct cluster-info: failed to reconcile certificate authority data secret for cluster: failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get \"https://asc###.hcp.westus3.azmk8s.io:443/api/v1?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" controller="azuremanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureManagedControlPlane" AzureManagedControlPlane="default/ascapz" namespace="default" name="ascapz" reconcileID="2082cb5a-9bc8-4485-a09a-669f8023a776"

error creating AzureManagedMachinePool default/pool0: failed to list vmss in resource group MC_asc###_asc###_westus3: could not iterate scalesets: ClientAssertionCredential: unable to resolve an endpoint: server response error:

Get "https://login.microsoftonline.com/a290a5d3-a356-464f-ae27-####/v2.0/.well-known/openid-configuration": dial tcp: lookup login.microsoftonline.com on 10.96.0.10:53: server misbehaving      
 > controller="azuremanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureManagedMachinePool" AzureManagedMachinePool="default/pool0" namespace="default" name="pool0" reconcileID="22d5ecbd-ac26-42f5-a211-d8ba073e1dfa"
```

Possible somehow the secret(s)/cert(s) changed or were removed?

**Environment:**
Management cluster:
- cluster-api-provider-azure version: 1.13.0
- Kubernetes version: (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): kind with workload identity enabled

**Comment by nojnhuh** [comment]
`server misbehaving` doesn't sound like something that would be caused by CAPZ. Are your workload ID creds working outside of CAPZ?

**Comment by dtzar** [comment]
No idea how things got resolved, but the cluster is fully upgraded now and even though I'm still getting some of these error logs theoretically everything is functioning.
