### ISSUE TITLE
CAPZ v1.13.0 fails to reconcile tags when Azure Policies are used to alter them

### ISSUE THREAD

**Issue by ionutleca** [kubernetes-sigs/cluster-api-provider-azure#4525]
/kind bug

**What steps did you take and what happened:**
Trying to deploy an **AzureManagedControlPlane** resource. 

The initial logs indicate that every reconcile loop stops at:
```
E0130 11:31:04.458354       1 managedcontrolplane.go:427] "Unable to determine if ManagedControlPlaneScope VNET is managed by capz, assuming unmanaged" err="VirtualNetwork.network.azure.com \"***\" not found" logger="scope.ManagedControlPlaneScope.IsVnetManaged" x-ms-correlation-request-id="db13a137-5b7f-4c2c-8573-9524e1830b02" AzureManagedCluster="***"
```

After increasing the verbosity (-v=6), it shows that it's actually stuck at the ResourceGroup reconciliation:
```
I0130 11:31:04.459647       1 azuremanagedcontrolplane_controller.go:264] "requeuing due to transient failure" logger="controllers.AzureManagedControlPlaneReconciler.reconcileNormal" controller="azuremanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureManagedControlPlane" AzureManagedControlPlane="***" namespace="***" name="***" reconcileID="6e68e6e7-290c-4b24-a055-d4a8dabe62e6" x-ms-correlation-request-id="81423de5-eba6-4bb0-8344-46f412fc15a5" name="***" namespace="***" error="failed to reconcile AzureManagedControlPlane service group: failed to reconcile tags: operation type ASOCreateOrUpdate on Azure resource *** is not done. Object will be requeued after 20s"
```

Looking at the code added to 1.13.0, I suspect [this change](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/5b358164342796160ce80a2f4a9ac57c0daf88d4) doesn't work when there is an active Azure Policy that alters the tags for any create/update request for resource groups. (In our case, there is such a policy that appends 2 tags)

**What did you expect to happen:**
Work as before  1.13.0 and not be blocked by the policy added tags.

**Anything else you would like to add:**
As a quick fix, I just added the tags (the policy was going to add) to **AzureManagedControlPlane.spec.additionalTags** and it seems to get past the `reflect.DeepEqual(t.GetDesiredTags(existing), existingTags)` condition.

**Environment:**

- cluster-api-provider-azure version: v1.13.0
- Kubernetes version: (use `kubectl version`): v1.26.6
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS

**Comment by nojnhuh** [comment]
#4531 fixes this AFAICT. @ionutleca If you are able to confirm that this fixes your issue that would be very helpful!

**Comment by ionutleca** [comment]
Thanks, @nojnhuh. Do you know if the 1.13.1 release is already scheduled?

**Comment by nojnhuh** [comment]
Yep! I'm planning to cut that today.
