### ISSUE TITLE
Deploying more than topology based on the default AKS ClusterClass only results in one successfully deployed cluster

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#4556]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**

- Deployed the default `aks-clusterclass` template
- Deployed three of the `aks-topology` template
- Only one cluster is successfully created

I lost a handle on the exact error, but the error was while creating the managed cluster resource and was indicating that the vnet could not be found. The ASO vnet's default name is the name of the AzureManagedControlPlaneTemplate which is shared among all instances of the template, so subsequent topologies also try to share the same ASO vnet instead of creating their own in their respective resource groups.

**What did you expect to happen:**

Three clusters are deployed successfully.

**Anything else you would like to add:**

This is the smallest change I need to make to get things to work the way I expect:
```diff
diff --git a/api/v1beta1/azuremanagedcontrolplanetemplate_default.go b/api/v1beta1/azuremanagedcontrolplanetemplate_default.go
index fce6a8182..de87e97af 100644
--- a/api/v1beta1/azuremanagedcontrolplanetemplate_default.go
+++ b/api/v1beta1/azuremanagedcontrolplanetemplate_default.go
@@ -38,9 +38,9 @@ func (mcp *AzureManagedControlPlaneTemplate) setDefaults() {
 
 // setDefaultVirtualNetwork sets the default VirtualNetwork for an AzureManagedControlPlaneTemplate.
 func (mcp *AzureManagedControlPlaneTemplate) setDefaultVirtualNetwork() {
-	if mcp.Spec.Template.Spec.VirtualNetwork.Name == "" {
-		mcp.Spec.Template.Spec.VirtualNetwork.Name = mcp.Name
-	}
 	if mcp.Spec.Template.Spec.VirtualNetwork.CIDRBlock == "" {
 		mcp.Spec.Template.Spec.VirtualNetwork.CIDRBlock = defaultAKSVnetCIDR
 	}
```

This raises the question though of how much defaulting we should do on template types when the same defaulting is already being applied to the non-template type.

An alternative approach is to add extra API fields to the resources which define the names of the ASO resources separately from the names of the resources as they exist in Azure. Or to include the resource group name in the names of all ASO resources, but I'm not sure how easily that might hit name length limits or how easily we could maintain backwards compatibility with that.

**Environment:**

- cluster-api-provider-azure version: 40f3dfb2d7bf128a267b33976c7e0e37f9f530eb
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nojnhuh** [comment]
fyi @willie-yao

**Comment by willie-yao** [comment]
Okay so actually this is a huge bug. The vnet name should not be in the template type for the AMCP as it cannot be shared across clusters. Opening a PR to move the name field out of the template type.
