### ISSUE TITLE
CAPZ stays stuck in deleting mode when resources are all actually gone

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#4570]
/kind bug

**What steps did you take and what happened:**
Ran the command to delete an existing deployed cluster and it stayed permanently stuck in the deleting state.  I then manually deleted the cluster resources created by CAPZ and CAPZ still stayed stuck in the deleting state.

**What did you expect to happen:**
CAPZ would detect that the resources it were trying to delete were already removed and get rid of the definition present which was trying to delete what is clearly already gone.

**Environment:**
management cluster
- cluster-api-provider-azure version: 1.13.1
- Kubernetes version: (use `kubectl version`): 1.29.1 
- OS (e.g. from `/etc/os-release`): wsl ubuntu 22.04 docker desktop K8s

**Comment by nojnhuh** [comment]
I'd be surprised if this were a general problem since I don't remember seeing this ever in e2e. Can you provide any more details about what the cluster template looked like or if you were doing anything to it around the time it was being deleted? It would also be helpful to know what the capz-controller-manager was logging for the CAPZ resources while they were stuck and what the full YAML of the resources was then.

**Comment by dtzar** [comment]
Unfortunately, I can't reproduce the problem right now - but will circle back when/if I do.

**Comment by nojnhuh** [comment]
It almost seems like there's something wonky in your Workload ID setup or your sub or something. I've never seen this kind of error in e2e or locally for me.

**Comment by dtzar** [comment]
I have a live repo of this now.  I'm pretty sure you can reproduce this by doing the following:
1. Let CAPZ create a cluster
2. Power off the CAPZ management cluster
3. Delete the resource
4. Bring back online the CAPZ management cluster

Here's my logs I have right now from ASO (using 1.14.0 release also).

```
I0314 21:49:12.626378       1 recorder.go:104] "msg"="Reason: ResourceNotFound, Severity: Warning, RetryClassification: RetrySlow, Cause: The Resource 'Microsoft.ContainerService/managedClusters/argocluster' under resource group 'argocluster' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix: PUT https://management.azure.com/subscriptions/####/resourceGroups/argocluster/providers/Microsoft.ContainerService/managedClusters/argocluster/agentPools/pool1\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 Not Found\nERROR CODE: ResourceNotFound\n
```

**Comment by nawazkh** [comment]
#4609 May or may not be connected to this issue. But since both of these issues are around deletion, I am mentioning the other issue as well in here.

**Comment by dtzar** [comment]
Yes, we did start the delete before powering the cluster off.  So [between step 1 and 2](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4570#issuecomment-1998543894) should be added "delete the cluster object" (don't let it finish).  Either case should be handled in some way though.  If you don't initiate delete the CAPZ cluster object and manually delete the cluster while the management cluster is off, CAPZ should re-create the cluster as it has in its definition when it powers back on...

**Comment by willie-yao** [comment]
Just confirmed that the cluster does delete after powering off and on the management cluster, even in the case where the replicas is set to 0. The cluster deletion just takes a while (~25 minutes). This can be tracked in #4339 

/close
