### ISSUE TITLE
Allow no k8s version for ManagedClusters

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#4610]
/kind feature

**Describe the solution you'd like**
As a cluster operator, I'd like to manage my AKS cluster kubernetes version upgrades via Azure directly (e.g. via Azure Fleet Manager), but provision my clusters using CAPZ.  

**Anything else you would like to add:**
Not only will we need to not require the K8s version to be specified for the controlplane and machinepools, we would need to ensure that CAPZ is not auto-populating and trying to re-inforce the version/upgrades when set in this manner.  

Potentially relevant to consider a general feature in which a user could initially specify a value, but then have CAPZ not enforce it.  e.g. this could be useful for things like machinepool worker node SKU sizes (which change with karpenter, autoscaling, etc).

This apparently can be done today with Terraform (no AKS version specified in their HCL IaC), so relevant to dig into how they're using the Go SDK to make it happen.

Related to #4111

**Comment by jackfrancis** [comment]
There is a already a pattern in place here for external autoscaler, but the kubernetes version is such an integral contract w/ CAPI that this is not going to be a trivial change. jFYI

**Comment by nojnhuh** [comment]
For the ASO API, these fields can simply be omitted and won't be defaulted or enforced by CAPZ. I think ClusterClass requires that `spec.topology.version` is set on each Cluster, which CAPZ does ultimately enforce, but that would require a CAPI change. Non-ClusterClass Clusters wouldn't be affected by that.

/close
