### ISSUE TITLE
Support disabling bastion host

### ISSUE THREAD

**Issue by simonklb** [kubernetes-sigs/cluster-api-provider-azure#4648]
/kind feature

**Describe the solution you'd like**

Currently, disabling a bastion host is not allowed after it has been enabled. Instead you have to tear down the entire cluster to remove it. I would like to be able to disable the bastion host while keeping the cluster alive.

**Anything else you would like to add:**

Support for enabling a bastion host was added in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1300. There it was decided that disabling the bastion once it had been enabled would not be allowed due to the lack of support for garbage collecting it. However a follow-up ticket was proposed to implement this in this [Slack thread](https://kubernetes.slack.com/archives/CEX9HENG7/p1617905312189800?thread_ts=1617883958.183000&cid=CEX9HENG7) but I've not been able to find it when searching the issues here. Please close this as a duplicate if it already exist!

**Comment by dtzar** [comment]
This is not a duplicate, but this isn't on our priority list as you're the first person I know of to ask for it (aside from that slack request 3 years ago).  PRs are welcome!

**Comment by rarescosma** [comment]
Meanwhile, this is the dance we had to perform to delete Azure bastions manually:

- Identify the index of the validating webhook that rejects cluster definitions when their `bastionSpec` is removed:

  ```bash
  WH_INDEX=$(kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io capz-validating-webhook-configuration -o json | jq '.webhooks | map(.name) | index("validation.azurecluster.infrastructure.cluster.x-k8s.io")')
  ```

- Patch it to remove the `UPDATE` from its `operations` field, essentially disabling the webhook:

  ```bash
  kubectl patch validatingwebhookconfigurations.admissionregistration.k8s.io capz-validating-webhook-configuration --type='json' -p="[{\"op\": \"replace\", \"path\": \"/webhooks/$WH_INDEX/rules/0/operations\", \"value\": [\"CREATE\"]}]"
  ```

- Remove the `bastionSpec` from your `azureclusters.infrastructure.cluster.x-k8s.io` resource and apply it.

- Delete the `bastionhosts.network.azure.com` resource manually.

- Finally, restore the CAPZ webhook to its former glory:

  ```bash
  kubectl patch validatingwebhookconfigurations.admissionregistration.k8s.io capz-validating-webhook-configuration --type='json' -p="[{\"op\": \"replace\", \"path\": \"/webhooks/$WH_INDEX/rules/0/operations\", \"value\": [\"CREATE\", \"UPDATE\"]}]"
  ```
