### ISSUE TITLE
Support setting routeTables to virtualnetworkssubnets for AKS managed clusters

### ISSUE THREAD

**Issue by staerion** [kubernetes-sigs/cluster-api-provider-azure#4665]
/kind feature

**Describe the solution you'd like**
This feature request applies to AKS managed clusters.

The capi azure provider can create virtualnetworks and subnets for AKS managed clusters. They can be configured under the field
AzureManagedControlPlane.spec.virtualNetwork.subnet. From this object you can configure the cidrBlock, name and optionally privateEndpoints and serviceEndpoints. In our use case we'd also like to configure a routeTable for the subnet. Currently this option is not support by capi azure provider. 

**Anything else you would like to add:**
The aso controller itself does already have support for this option: https://azure.github.io/azure-service-operator/reference/network/v1api20201101/#network.azure.com/v1api20201101.VirtualNetworksSubnet

**Environment:**

- cluster-api-provider-azure version: v1.14.0
- Kubernetes version: (use `kubectl version`): 1.27.7
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.4 LTS

**Comment by jackfrancis** [comment]
cc @nojnhuh if you want to sanity check this scenario as available in your ASO AKS prototype

**Comment by nojnhuh** [comment]
@jackfrancis Yes, this kind of thing is possible with my prototype. Sorry @staerion I don't have anything to show for that yet, but keep your eyes on Slack and the PR queue in the coming weeks.

**Comment by staerion** [comment]
Great, thanksk for the heads up! We'll make sure to keep track of the slack channel and new releases.

**Comment by dtzar** [comment]
How would this work with CAPZ new ASO v2 API? @nojnhuh @nawazkh

**Comment by nojnhuh** [comment]
> > How would this work with CAPZ new ASO v2 API? @nojnhuh @nawazkh
> 
> You could add vnet and subnet resources to `spec.resources` of the AzureASOManagedCluster alongside the ResourceGroup and define them however you want:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/afde2c8f64f300790863bab32c210a10797669e5/templates/cluster-template-aks-aso.yaml#L48

This would be the particular kind of change to apply to the flavor template to achieve this:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/21479a9a4c640b43e0bef028487c522c55605d06/templates/cluster-template-aks-aso.yaml
```diff
diff --git a/templates/cluster-template-aks-aso.yaml b/templates/cluster-template-aks-aso.yaml
index 29f77594e..1fb00a94e 100644
--- a/templates/cluster-template-aks-aso.yaml
+++ b/templates/cluster-template-aks-aso.yaml
@@ -54,6 +54,44 @@ spec:
       name: ${CLUSTER_NAME}
     spec:
       location: ${AZURE_LOCATION}
+  - apiVersion: network.azure.com/v1api20201101
+    kind: VirtualNetwork
+    metadata:
+      name: ${CLUSTER_NAME}
+    spec:
+      location: ${AZURE_LOCATION}
+      owner:
+        name: ${CLUSTER_NAME}
+      addressSpace:
+        addressPrefixes:
+          - 10.0.0.0/16
+  - apiVersion: network.azure.com/v1api20201101
+    kind: VirtualNetworksSubnet
+    metadata:
+      name: ${CLUSTER_NAME}-nodes
+    spec:
+      owner:
+        name: ${CLUSTER_NAME}
+      addressPrefix: 10.0.0.0/24
+  - apiVersion: network.azure.com/v1api20201101
+    kind: RouteTable
+    metadata:
+      name: ${CLUSTER_NAME}-nodes
+    spec:
+      location: ${AZURE_LOCATION}
+      owner:
+        name: ${CLUSTER_NAME}
+      disableBgpRoutePropagation: true
+  - apiVersion: network.azure.com/v1api20201101
+    kind: RouteTablesRoute
+    metadata:
+      name: ${CLUSTER_NAME}-route
+    spec:
+      owner:
+        name: ${CLUSTER_NAME}-nodes
+      addressPrefix: cab:cab::/96
+      nextHopType: VirtualAppliance
+      nextHopIpAddress: ace:cab:deca:f00d::1
 ---
 apiVersion: cluster.x-k8s.io/v1beta1
 kind: MachinePool
@@ -95,6 +133,10 @@ spec:
         name: ${CLUSTER_NAME}
       type: VirtualMachineScaleSets
       vmSize: ${AZURE_NODE_MACHINE_TYPE}
+      vnetSubnetReference:
+        group: network.azure.com
+        kind: VirtualNetworksSubnet
+        name: ${CLUSTER_NAME}-nodes
 ---
 apiVersion: cluster.x-k8s.io/v1beta1
 kind: MachinePool
@@ -136,3 +178,7 @@ spec:
         name: ${CLUSTER_NAME}
       type: VirtualMachineScaleSets
       vmSize: ${AZURE_NODE_MACHINE_TYPE}
+      vnetSubnetReference:
+        group: network.azure.com
+        kind: VirtualNetworksSubnet
+        name: ${CLUSTER_NAME}-nodes
```

Not that you'll have to set the `ADDITIONAL_ASO_CRDS` environment variable when you install CAPZ to a valid value for the `--crd-pattern` ASO command line flag as described here: https://azure.github.io/azure-service-operator/guide/crd-management/. You could set it to `network.azure.com/*` or more granularly depending on what you need.

https://azure.github.io/azure-service-operator/guide/crd-management/

These changes are mostly taken from the examples in the ASO docs, so tweak the parameters as-needed, but this should get you most of the way there.

All of the ASO resources' schemas are defined here: https://azure.github.io/azure-service-operator/reference/

/close
