### ISSUE TITLE
Support Azure client request to other Azure Clouds (eg. Sovereign clouds)

### ISSUE THREAD

**Issue by gaulzhw** [kubernetes-sigs/cluster-api-provider-azure#469]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We use cluster api to create k8s cluster in China. But this project uses cloudapp.azure.com as a default DNS zone, and sends client request to management.azure.com for default.
Is it ok to add an option to support other datacenter?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
Great idea!

**Comment by CecileRobertMichon** [comment]
@gaulzhw that's definitely something that should be on the roadmap, thanks for opening the issue. If you'd like to help and contribute this feature feel free to assign yourself!

**Comment by alexeldeib** [comment]
n.b.: this must not be hardcoded to the existing Go SDK environments. Azure Stack is the obvious exception, but we should enable free form support for anything that can supply the endpoints at runtime (e.g., airgapped environments, gov't cloud).

**Comment by gaulzhw** [comment]
We just hardcoded to support azure-cn. The project github.com/Azure/azure-sdk-for-go may be out of date about some client URI. We have no idea to support in an elegant manner.

See our commit on https://github.com/q8s-io/cluster-api-provider-azure/commit/6f529b25b0adb44c76d6fdd8bb63b5000f071755

**Comment by CecileRobertMichon** [comment]
Thanks for sharing @gaulzhw, this gives a good idea of what changes are required for anyone who wants to pick this up and implement a more generic solution.

**Comment by jseely** [comment]
@devigned, @CecileRobertMichon and I discussed this. These are the following points we've agreed on for implementation:
* Cloud Instance selection should happen at the Controller level
* Optional `AZURE_ENVIRONMENT` environment variable parsed by `azure.EnvironmentFromName(string)` in `go-autorest` enabling environment endpoints from file
* All clients must be created using the endpoints from the `AZURE_ENVIRONMENT`

**Comment by jseely** [comment]
@devigned also brought up that if an ARM endpoint has been provided that you can look up the rest of the endpoints from there. 

After looking through the code between `cluster-api-provider-azure` and `go-autorest` it seems that that functionality should live in `go-autorest` to replace the `environments` map from `EnvironmentName` to `Environment`.

Does that work for you @devigned?

**Comment by devigned** [comment]
I thought go-autorest provided a few way to load metadata (I cheated and looked at the code).

1) [Load from ARM metadata endpoint](https://github.com/Azure/go-autorest/blob/9132adfc9db3007653dccb091b6a6c8e09b74ef5/autorest/azure/metadata_environment.go#L96)
2) [Load from well-known name](https://github.com/Azure/go-autorest/blob/9132adfc9db3007653dccb091b6a6c8e09b74ef5/autorest/azure/environments.go#L212)
3) [Load from file](https://github.com/Azure/go-autorest/blob/9132adfc9db3007653dccb091b6a6c8e09b74ef5/autorest/azure/environments.go#L235)

I intentionally ordered them in such a way b/c I think they are the order of most intuitive. 1) should enable both custom clouds where the metadata values are not known ahead of time (Azure Stack, other sovereign clouds not in the SDK, etc) as well as any of the well-known clouds. 2) is relatively easy if you know the names. 3) is all the knobs and buttons in case the others don't work for the user.

### Here's the ARM metadata endpoint:
``` script
$ curl https://management.azure.com/metadata/endpoints?api-version=2020-05-01 | jq
```
```json
  {
    "portal": "https://portal.azure.com",
    "authentication": {
      "loginEndpoint": "https://login.windows.net/",
      "audiences": [
        "https://management.core.windows.net/",
        "https://management.azure.com/"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.azure.net",
    "graphAudience": "https://graph.windows.net/",
    "graph": "https://graph.windows.net/",
    "name": "AzureCloud",
    "suffixes": {
      "azureDataLakeStoreFileSystem": "azuredatalakestore.net",
      "acrLoginServer": "azurecr.io",
      "sqlServerHostname": "database.windows.net",
      "azureDataLakeAnalyticsCatalogAndJob": "azuredatalakeanalytics.net",
      "keyVaultDns": "vault.azure.net",
      "storage": "core.windows.net",
      "azureFrontDoorEndpointSuffix": "azurefd.net"
    },
    "batch": "https://batch.core.windows.net/",
    "resourceManager": "https://management.azure.com/",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "activeDirectoryDataLake": "https://datalake.azure.net/",
    "sqlManagement": "https://management.core.windows.net:8443/",
    "gallery": "https://gallery.azure.com/"
  },
  {
    "portal": "https://portal.azure.cn",
    "authentication": {
      "loginEndpoint": "https://login.chinacloudapi.cn",
      "audiences": [
        "https://management.core.chinacloudapi.cn",
        "https://management.chinacloudapi.cn"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.chinacloudapi.cn",
    "graphAudience": "https://graph.chinacloudapi.cn",
    "graph": "https://graph.chinacloudapi.cn",
    "name": "AzureChinaCloud",
    "suffixes": {
      "acrLoginServer": "azurecr.cn",
      "sqlServerHostname": "database.chinacloudapi.cn",
      "keyVaultDns": "vault.azure.cn",
      "storage": "core.chinacloudapi.cn",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.chinacloudapi.cn",
    "resourceManager": "https://management.chinacloudapi.cn",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.chinacloudapi.cn:8443",
    "gallery": "https://gallery.chinacloudapi.cn"
  },
  {
    "portal": "https://portal.azure.us",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.us",
      "audiences": [
        "https://management.core.usgovcloudapi.net",
        "https://management.usgovcloudapi.net"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.usgovcloudapi.net",
    "graphAudience": "https://graph.windows.net",
    "graph": "https://graph.windows.net",
    "name": "AzureUSGovernment",
    "suffixes": {
      "acrLoginServer": "azurecr.us",
      "sqlServerHostname": "database.usgovcloudapi.net",
      "keyVaultDns": "vault.usgovcloudapi.net",
      "storage": "core.usgovcloudapi.net",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.core.usgovcloudapi.net",
    "resourceManager": "https://management.usgovcloudapi.net",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.usgovcloudapi.net:8443",
    "gallery": "https://gallery.usgovcloudapi.net"
  },
  {
    "portal": "https://portal.microsoftazure.de",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.de",
      "audiences": [
        "https://management.core.cloudapi.de",
        "https://management.microsoftazure.de"
      ],
      "tenant": "common",
      "identityProvider": "AAD"
    },
    "media": "https://rest.media.cloudapi.de",
    "graphAudience": "https://graph.cloudapi.de",
    "graph": "https://graph.cloudapi.de",
    "name": "AzureGermanCloud",
    "suffixes": {
      "sqlServerHostname": "database.cloudapi.de",
      "keyVaultDns": "vault.microsoftazure.de",
      "storage": "core.cloudapi.de",
      "azureFrontDoorEndpointSuffix": ""
    },
    "batch": "https://batch.cloudapi.de",
    "resourceManager": "https://management.microsoftazure.de",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json",
    "sqlManagement": "https://management.core.cloudapi.de:8443",
    "gallery": "https://gallery.cloudapi.de"
  }
]
```

**Comment by alexeldeib** [comment]
Overall 👍🏻 Sovereign clouds are a mix of 1/3, btw.

I don’t think this code should live in go-autorest. We should make helpers in capz and drop down to go-autorest internals/AAD as necessary.

**Comment by voor** [comment]
If possible, this PR could also include something to update the `KubeadmConfigTemplate` and `KubeadmControlPlane` to recognize the cluster is being deployed in another cloud environment, since that's currently expecting `AzurePublicCloud`

**Comment by jseely** [comment]
@voor I agree that would be nice, I'd love to see all of the duplicated values in from the `KubeadmControlPlane` config be managed by the `AzureCluster` scope context. ie. have AzureCluster provide the values to generate the config file. That said I don't think that should be part of this PR.

**Comment by nader-ziada** [comment]
@devigned are you saying that the code should make a call to the arm endpoint to get the settings? or use all three methods?

**Comment by devigned** [comment]
I'm open to proposals.

What do you think about the following:
1. Have a top level setting for either a well known cloud name or `"CustomCloud"`
    1. if well known cloud name, fetch configuration settings from well known cloud name from go-autorest
    2. if `"CustomCloud"`, require settings file or metadata endpoint to be set
2. Check if metadata endpoint is set, if so, override settings with metadata settings
3. Check for a settings file to load. If settings file is available, override settings from file

**Comment by nader-ziada** [comment]
in that case would `metadata endpoint` and `settings file path` be other environment variables? and what happens if you set both?

**Comment by devigned** [comment]
With the numeric ordering in my previous comment, I was implying an order of operations applying settings in a cascading order. What do you think?

**Comment by nader-ziada** [comment]
yeah makes sense but from your previous comment above in the issue I thought the metadata endpoint should have preference over the file, but here seems the file overrides the endpoint

**Comment by devigned** [comment]
I think the metadata endpoint is the more transparent to the user, but I think the well known cloud name will be easier for users. I've vacillated between the order of operations, and feel like I might be too close to the subject represent a user.

Also, didn't want to edit the previous comment since there were references to it in the thread.

**Comment by nader-ziada** [comment]
ok, sounds good, I'll update the PR and we can get more feedback there! thanks

**Comment by devigned** [comment]
Awesome! Thank you, @nader-ziada. 

Also, if anyone else has an opinion, please speak up.

**Comment by CecileRobertMichon** [comment]
+1 on allowing users to provide a well known cloud name and fetching the settings from that as the first "choice", I think having the flexibility of passing in a metadata endpoint is great but it's not as user friendly.  The ordering @devigned mentions above sounds good to me.
