### ISSUE TITLE
CAPZ upgrade - cluster-api-provider-azure failed to reconcile with worker cluster with existing vnet/subnet

### ISSUE THREAD

**Issue by itodorova1** [kubernetes-sigs/cluster-api-provider-azure#4704]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

After Cluster API upgrade, manager cluster is unable to reconcile with worker cluster, with the following error:
```
E0407 17:06:24.620918 1 controller.go:329] "Reconciler error" err="error creating AzureManagedControlPlane aks***/aks-***: failed to reconcile AzureManagedControlPlane service subnets:
failed to create resource aks-***/vnet-***-aks_system (service: subnets): 
VirtualNetworksSubnet.network.azure.com \"vnet-***-aks_system\" is invalid: 
metadata.name: Invalid value: \"vnet-***-aks_system\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" controller="azuremanagedcontrolplane"
controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureManagedControlPlane" 
```
We have the following configurationin our AzureManagedControlPlane , where we are referencing pre-existing virtual network and subnet (configured with terraform):

```
virtualNetwork:
    name: vnet-***
    cidrBlock: 172.18.0.0/16
    subnet:
      cidrBlock: 172.18.0.0/22
      name: aks_system
```
This configuration was working fine until cluster-api-provider-azure version 1.11.4 

As possible solution, we would like to be able to set azureName in the  AzureManagedControlPlane.

**What did you expect to happen:**

Successfully reconcile the manager cluster with the worker clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

According to the documentation, there is a change in the  crds:
https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-azure/network.azure.com/VirtualNetwork/v1api20201101storage@v1.14.0
https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-azure/network.azure.com/VirtualNetworksSubnet/v1api20201101storage@v1.14.0

 That did not exist in the previous versions, which is preventing the clutsers from reconcile.

**Environment:**

- cluster-api-provider-azure version: v1.14.1
- Kubernetes version: (use `kubectl version`): 1.28.3
- OS (e.g. from `/etc/os-release`): Ubuntu 

The following issue seems to be similar - #4699

**Comment by willie-yao** [comment]
I think the change in #4606 should fix this as it introduced this line: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/managedcontrolplane.go#L284

It should normalize the kubernetes name which allows it to conform to RFC 1123. @itodorova1 can you confirm this fixes your issue?

**Comment by itodorova1** [comment]
Hi,
Not sure exactly if this is our case - isn't that change for the existing resource gropus? Our case is with the subnet specifically:
```
virtualNetwork:
    name: vnet-prod-nl-weu
    subnet:
      name: aks_system
```

**Comment by willie-yao** [comment]
The main focus of the PR is to fix existing resource groups, but it also adds a line that normalizes the name of the vnet to avoid the issue with RFC 1123 subdomain, so it should fix your issue with the name being in the wrong format.

We'll work on backporting this fix into the next patch release so you can give it a try!

**Comment by itodorova1** [comment]
Today we performed the upgrade to the latest patch release. Unfortunately we still have same the issue with the existing subnet that has underscore:
```
subnet:
      name: aks_system
```

```
Last Transition Time:  2024-05-02T11:35:06Z
Message:               subnets failed to create or update. err: failed to create resource test-nl-prod/vnet-test-nl-weu-aks_system 
(service: subnets): VirtualNetworksSubnet.network.azure.com "vnet-test-nl-weu-aks_system" is invalid: 
metadata.name: Invalid value: "vnet-test-nl-weu-aks_system": a lowercase RFC 1123 subdomain must consist of 
lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character 
(e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Can we expect that **AzureName** to be added in  the AzureManagedControlPlane in future releases, or this is not something that will be considered?

**Comment by willie-yao** [comment]
> Can we expect that AzureName to be added in the AzureManagedControlPlane in future releases, or this is not something that will be considered?

I don't think it would be necessary once #4725 merges as it will automatically convert the name to be kubernetes-compliant. I can understand if there is need for a different AzureName. Is there a reason you need it besides making it a valid name for kubernetes?

**Comment by itodorova1** [comment]
I confirm, that now the issue is resolved after upgradeing to the latest version. Thank you very much for your help!

**Comment by willie-yao** [comment]
No problem, thanks for finding this issue!

/close
