### ISSUE TITLE
Diagnostic script for log collection

### ISSUE THREAD

**Issue by ksubrmnn** [kubernetes-sigs/cluster-api-provider-azure#474]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
An easy to use script that will collect logs for kubernetes, iptables, instance metadata, etc.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ksubrmnn** [comment]
@CecileRobertMichon can you please assign this to me?

**Comment by CecileRobertMichon** [comment]
@ksubrmnn one consideration for this: some of the pod logs and CRDs contain sensitive information at the moment (will be fixed by switching to MSI) so we need to either 1) not use the collect-logs script in any CI for now and add a clear warning in any documentation referencing the script, or 2) find a way to redact service principals from output logs (might be more involved but if we find an easy way to do this would be ideal).

**Comment by chewong** [comment]
@ksubrmnn I can help out if you don't have any bandwidth.

/assign

**Comment by ksubrmnn** [comment]
@chewong Can you take a look at https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/534? I just messed up my original cluster which stopped me from continuing with the script but it's mostly done! Just needs validation.

**Comment by chewong** [comment]
Left a comment in the PR - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/534#discussion_r433497639. In short, I think we should re-evaluate how we collect logs from the workload cluster. Log collecting for management cluster looks good to me.

**Comment by CecileRobertMichon** [comment]
@chewong, I think @ksubrmnn doesn't have time to keep working on this right now so I suggest we close the existing PR and you open a new PR with her previous commit (that way she's co-author) and push your changes on top of it. How does that sound to everyone?

**Comment by chewong** [comment]
Sounds good to me

**Comment by ksubrmnn** [comment]
works for me, thanks so much!
