### ISSUE TITLE
AAD support

### ISSUE THREAD

**Issue by weinong** [kubernetes-sigs/cluster-api-provider-azure#481]
/kind feature

**Describe the solution you'd like**
Use AAD to authenticate with k8s clusters
should be similar or equivalent to these existing products/projects
https://github.com/Azure/aks-engine/blob/master/docs/topics/aad.md
https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration
https://docs.microsoft.com/en-us/azure/aks/azure-ad-v2

**Anything else you would like to add:**
In addition, when implementing AAD feature, please consider to use exec plugin (https://github.com/Azure/kubelogin out-of-tree) instead of azure (in-tree) plugin

References: 
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/314
https://github.com/Azure/kubelogin

**Comment by weinong** [comment]
do you have any requirements from customers? does capz have any oidc support already?

**Comment by CecileRobertMichon** [comment]
/assign

Writing some docs on this as everything should already be possible today. oidc flags can be passed into apiserver via extra args.
