### ISSUE TITLE
Support Multiple Placement Groups in VMSS

### ISSUE THREAD

**Issue by jseely** [kubernetes-sigs/cluster-api-provider-azure#484]
/kind feature

**Describe the solution you'd like**
Many large customers, when they scale out their applications, run into the 100 VM limit in VMSS. There is a flag in VMSS to support scaling out across multiple Placement Groups to support up to 1000 VMs. I have run into this issue with customers on existing platforms and therefore believe it should go in before we hit it in the field.

**Anything else you would like to add:**
[Azure Docs - Working with large virtual machine scale sets](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-placement-groups)

ARM Template flag (`"singlePlacementGroup": false`):
```
{
  "type": "Microsoft.Compute/virtualMachineScaleSets",
  "location": "australiaeast",
  "name": "bigvmss",
  "sku": {
    "name": "Standard_DS1_v2",
    "tier": "Standard",
    "capacity": 1000
  },
  "properties": {
    "singlePlacementGroup": false,
    "upgradePolicy": {
      "mode": "Automatic"
    }
```

**Comment by CecileRobertMichon** [comment]
This depends on #472
