### ISSUE TITLE
Uses of field.NewPath should use camel case

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#4862]
/kind cleanup

**What needs cleanup:**
[A clear and concise description of what needs to be cleaned up.]

Uses of `field.NewPath()` should use camel case as pointed out here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4792#discussion_r1603009257

Incorrect use of field.NewPath(): https://github.com/willie-yao/cluster-api-provider-azure/blob/37702d1053c3c3802a1f8c40b0d8f98e56eb41ae/api/v1beta1/azuremachine_webhook.go#L184

Correct use of field.NewPath(): https://github.com/willie-yao/cluster-api-provider-azure/blob/add-mp-ci-ipv6/api/v1beta1/azuremachine_webhook.go#L210

**Describe the solution you'd like**
[Description of how you would like the cleanup to be done.]
Fix all uses of field.NewPath() that don't follow camel case.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by lakshkeswani** [comment]
@willie-yao could you please assign this to me? i can fix this issue
