### ISSUE TITLE
Overhaul Quickstart UX using AzureASOManagedCluster

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#4866]
/kind documentation

**Describe the solution you'd like**
As a user of CAPZ, I would like to understand how to easily provision any available [ASO ManagedCluster* features](https://azure.github.io/azure-service-operator/reference/containerservice/) listed from the in the [new experimental ASO API](https://capz.sigs.k8s.io/topics/aso.html#experimental-aso-api).

The existing documentation and [reference API doc ](https://capz.sigs.k8s.io/reference/v1alpha1-api.html) 
 and example template do not make it easy to understand how to accomplish this.  

Aside from improving documentation to make this clearer, it would also be great to have [the helm chart implementation ](https://github.com/mboersma/cluster-api-charts/tree/main/charts/azure-aks-aso) be a way to make this experience better/more understandable.

Related issues:

- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1755
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4665
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4414
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4281
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3573
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4568

**Comment by dtzar** [comment]
It would be great if we could re-write the [CAPZ getting started ](https://capz.sigs.k8s.io/getting-started) for this scenario (CAPI-Operator install + ASO Managed cluster helm chart to create a cluster). If people want to create a self-managed cluster, they could go to the existing [CAPI quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html) with Azure tabs.

**Comment by nojnhuh** [comment]
Here are some places where I try to explain how to do things in the new API:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/5214#issuecomment-2440608312
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4665#issuecomment-2223476976
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4414#issuecomment-2223488762

I think a goal for the docs should be to describe this generally enough that users
1. know what's possible, and
2. can figure out how to do what they want without fully spec'd out examples for every use case.

**Comment by jackfrancis** [comment]
I think a better scope for helping users would be to re-organize the AKS documentation to emphasize "here is how to create an AKS cluster" with the particulars of the API (AzureASOManagedCluster) being a necessary level of detail, but without all of the "AzureManagedCluster vs AzureASOManagedCluster" content.

To the comment about the "Getting Started" section, I agree that the section as-is has more info than needed. I don't think it's obvious that we would want to put "How to create an AKS cluster" type content there, but we should be open to streamlining some of that content.
