### ISSUE TITLE
SGX-enabled VMs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#488]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

[Intel&reg; Secure Guard Extension](https://software.intel.com/en-us/sgx) (Intel&reg; SGX) is an architecture extension designed to increase the security of application code and data.
Developers may choose [Intel&reg; SGX SDK](https://software.intel.com/en-us/sgx-sdk) or [Open Enclave SDK](https://github.com/Microsoft/openenclave/) to create applications that leverage this technology.

Azure supports provisioning of SGX-enabled VMs under the umbrella of Azure Confidential Compute (ACC).
reference: https://github.com/Azure/aks-engine/blob/master/docs/topics/sgx.md

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
/remove-lifecycle rotten
/lifecycle frozen

I guess the TL;DR of what's needed here is "copy AKS-Engine", per the [above link](https://github.com/Azure/aks-engine/blob/master/docs/topics/sgx.md)?

**Comment by CecileRobertMichon** [comment]
@mresvanis does https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3265 fix this?

**Comment by mresvanis** [comment]
> @mresvanis does #3265 fix this?

If I'm not mistaken, this fix is not required. There should already be support for SGX-enabled VMs in CAPZ. If I understand correctly, the requirements for a successful cluster creation with SGX-enabled VMs are:
-  gen2 VM image, e.g. creating an gen2 image via [image-builder](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/Makefile#L621) `make build-azure-sig-ubuntu-2204-gen2` and using this in the `AzureMachineTemplate` spec
- a supported VM size, e.g. `Standard_DC4s_v2`

PS. I was able to successfully create a test cluster with control-plane and worker nodes with VM size `Standard_DC4s_v2`.
