### ISSUE TITLE
Test and enable VMSS overprovisioning

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#489]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Test compatibility of cluster-api/kubeadm with VMSS overprovisioning and enable overprovisioning if it compatible as overprovisioning can improve provisioning success, especially when deploying large numbers of instances at once.

> While overprovisioning does improve provisioning success rates, it can cause confusing behavior for an application that is not designed to handle extra VMs appearing and then disappearing

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning

Depends on #472 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by alexeldeib** [comment]
Note, I think we want to be careful here. IIRC AKS engine did not run CSE on overprovisioned VMs. There’s no separation between cloud init and extensions here, so that route isn’t workable unless we switch to CSE (which is its own can of worms).

**Comment by CecileRobertMichon** [comment]
@alexeldeib @devigned so apparently overprovisioning is on by default now... Couldn't find it in official docs anywhere except in this FAQ though https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#why-are-there-gaps-between-my-virtual-machine-scale-set-vm-machine-names-and-vm-ids-for-example-0-1-3 😕 

Which means... since we aren't specifying a value... it's actually already turned on. I have not seen any issues with nodes joining the cluster and then getting deleted but it's worth investigating.

For example, this cluster had 4 instances created and only the first 2 were kept:
```
kubectl --kubeconfig=./kubeconfig get nodes
NAME                              STATUS   ROLES    AGE     VERSION
capz-vmss-6-control-plane-8r9gq   Ready    master   13m     v1.17.5
capz-vmss-6-control-plane-bhtcs   Ready    master   16m     v1.17.5
capz-vmss-6-control-plane-t967c   Ready    master   18m     v1.17.5
capz-vmss-6-mp-0000001            Ready    <none>   2m32s   v1.17.5
capz-vmss-6-mp-0000003            Ready    <none>   2m44s   v1.17.5
```

**Comment by CecileRobertMichon** [comment]
I lied it says the default is `true` in https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning

**Comment by alexeldeib** [comment]
Interesting...Wonder if cloud provider is properly handling clean up for us?

**Comment by CecileRobertMichon** [comment]
we're already doing this so I'm going to close the issue, nothing to do here

/close
