### ISSUE TITLE
Update ASO dep to 2.8.0

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#4957]
/kind feature

**Describe the solution you'd like**
Bump [ASO to 2.8.0 ](https://github.com/Azure/azure-service-operator/releases/tag/v2.8.0) dep so we can use all the latest AKS preview features such as AKS automatic.

**Comment by nojnhuh** [comment]
This is blocked on the controller-runtime bump we will eventually inherit from CAPI 1.8. https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4954
