### ISSUE TITLE
Add validations for AzureCluster Updates

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#497]
Some fields (eg. Azure location) are immutable and we should fail when they are updated.

To get started, you can look at how we implemented validation for AzureMachines here: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/azuremachine_webhook.go#L46

and add to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/azurecluster_webhook.go

You can also look at this PR in CAPA which achieves something similar: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1677/files

**Comment by jackfrancis** [comment]
@CecileRobertMichon should we re-scope this issue to just the `location` property? If so, then #522 will close this. If not, then I'll note in #522 that we've made progress, but we'll keep this issue open.

**Comment by CecileRobertMichon** [comment]
@jackfrancis let's keep this one open and once #522 merges we can make a list of the other properties that should be validated as immutable in this issue for someone else to pick up.

**Comment by surajrana93** [comment]
@CecileRobertMichon  do you need help in this?

**Comment by furkatgofurov7** [comment]
@surajrana93 have you picked this up already? if not I would like to work on this.

**Comment by CecileRobertMichon** [comment]
@furkatgofurov7 go for it, I believe @surajrana93 is already working on #1075

**Comment by CecileRobertMichon** [comment]
Fields that we should allow updates on:

- AdditionalTags
- ControlPlaneEndpoint (this should be moving to status in v1alpha4 but we need to keep it updatable so the controllers can update it when the LB is provisioned)
- NetworkSpec.APIServerLB (this is to allow backcompat backfill)

Everything else should not be updated.

/cc @devigned
