### ISSUE TITLE
Better error message for not setting identity field for UserAssignedIdentity

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#4990]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Users are able to specify `userAssignedIdentities` for an AzureMachineTemplate without setting `identity: UserAssigned`, resulting in the identity not being applied to the machine.

**What did you expect to happen:**
When specifying `userAssignedIdentities` for an AzureMachineTemplate, if the user forgets to set `identity: UserAssigned`, there should be a webhook error and a better error message.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by bryan-cox** [comment]
@willie-yao - I overlooked this issue was assigned to you and put a local patch together 🤦🏻 . If you are not working this, I can post my patch ([here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/main...bryan-cox:cluster-api-provider-azure:4990?expand=1)) in a PR if you would like.

**Comment by willie-yao** [comment]
@bryan-cox No worries at all! I haven't started working on this and it would be great if you could open a PR. Thanks so much for working on a fix!

/unassign
/assign @bryan-cox

**Comment by bryan-cox** [comment]
Thanks Willie! I posted the PR now.
