### ISSUE TITLE
ASO API - AKS Automatic Authentication Failure

### ISSUE THREAD

**Issue by ljtill** [kubernetes-sigs/cluster-api-provider-azure#5017]
/kind bug

**What steps did you take and what happened:**
When integrating the new ASO API with an AKS Automatic resource, I discovered that the reconciler cannot authenticate with the newly provisioned cluster. By default, AKS Automatic uses Entra ID with Azure RBAC integration. This setup causes the reconciler to fail authentication, preventing reconciliation completion.

[Cluster authentication and authorization](https://learn.microsoft.com/azure/aks/intro-aks-automatic#security-and-policies)

**What did you expect to happen:**
The reconciler successfully authenticates with the cluster using Azure RBAC. Maybe similar to how the AzureClusterIdentity object is used. 

**Anything else you would like to add:**
Management cluster is using AKS Automatic with the Cluster API Operator and Workload Identity to authenticate.

**Environment:**

- cluster-api-provider-azure version: v1.16.0
- Kubernetes version:  1.29.6

**Comment by nojnhuh** [comment]
I think I have a decent handle on this.

/triage accepted
/assign

**Comment by nojnhuh** [comment]
I've been working on this in the background and have it mostly working, but don't want to rush anything for the release next week.

/milesone next
