### ISSUE TITLE
Bump golangci-lint to v1.60.2

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#5110]
Taking inspiration from CAPI https://github.com/kubernetes-sigs/cluster-api/issues/11075
Let's also bump CAPZ's golangci-lint to latest `v1.60.2` release.

/help

**Comment by bryan-cox** [comment]
I can take it 👍🏻 
/assign

**Comment by bryan-cox** [comment]
Hey @nawazkh 👋🏻 - I didn't realize you were planning to work this and assigned it to myself 😄 

I'll remove myself and close the draft PR I had opened.

**Comment by nawazkh** [comment]
Chatted with Bryan offline (sorry about the confusion!) I will try finishing this issue in this week. 
/assign
