### ISSUE TITLE
Drop deprecated Azure API `2023-02-02-preview`

### ISSUE THREAD

**Issue by AndreiBarbuOz** [kubernetes-sigs/cluster-api-provider-azure#5141]
/kind cleanup

**What needs cleanup:**
- Remove use of deprecated API as announced [here](https://learn.microsoft.com/en-us/answers/questions/1655206/azure-retirement-azure-kubernetes-service-2023-02)

**Describe the solution you'd like**

Files to change: 1

- [ ] `main.go`
  - Line https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9eaaadc83de27d85a8ca887a919a4e23afd2cb18/main.go#L29

**Anything else you would like to add:**

Importing both ASO 2.9.0 and Cluster API provider for Azure (which uses ASO 2.8.0) leads to errors, because the `"github.com/Azure/azure-service-operator/v2/api/containerservice/v1api20230202preview"` import is no longer available, being deprecated (as seen [here](https://github.com/Azure/azure-service-operator/releases/tag/v2.8.0))

**Comment by nojnhuh** [comment]
We've bumped to ASO v2.9.0 in #5170 and have removed usage of that API version.

/close
