### ISSUE TITLE
BYO nodepool AKS test is referring to a Kubernetes version for which we don't have images published

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#5145]
**Which jobs are failing:**

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=aks_byo_node.go

**Which tests are failing:**

**Since when has it been failing:**

**Testgrid link:**

**Reason for failure (if possible):**

The latest available k8s version in AKS has now reached v1.30.4 within the last week or so, so we've been creating AKS clusters with that version in e2e tests. The BYO nodepool e2e tests involve creating a MachinePool whose `spec.template.spec.version` is inherited from that latest AKS version. We only have reference images published for up to v1.30.3, so creating the BYO nodepool fails because no image is available. (This is kind of a guess since the logs in the e2e artifacts are cut off before this point in the tests)

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by nojnhuh** [comment]
FYI @mboersma, one more side effect of being blocked from publishing new images

**Comment by mboersma** [comment]
We don't currently have a way to publish new Marketplace images while we transition to shared image galleries by default. I think for now, we should cap the AKS version at v1.30.3 (or whatever is also supported by CAPZ), or skip the test case.
