### ISSUE TITLE
python 3+ dependency

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#515]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Dev docs describe using python 2.7 as a requirement. Just as a concrete example on my mac:

```
$ python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.
```

The above follows the general pattern of encouraging projects to remove 2.x dependencies. This is a tracking issue request to remove the 2.7 dependencies from capz.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by devigned** [comment]
I don't think that is a real requirement anymore.

**Comment by CecileRobertMichon** [comment]
Is this a documentation update only?

**Comment by jackfrancis** [comment]
I think it started out as an actual work item to fix the fact that capz depends upon <= python 3. But as @devigned pointed out, that documented dependency is not real, so yeah, I think this is now a documentation task.

**Comment by CecileRobertMichon** [comment]
/kind documentation
/good-first-issue

to summarize: the ask is to change the line in development.md that says python 2.7 is a requirement and make the requirement python (either 2.7+ or 3) since the project already works with python 3. @jackfrancis does that sound correct?

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/development.md#L57
