### ISSUE TITLE
Enable AKS BYO nodepool test spec

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#5153]
/kind cleanup

**What needs cleanup:**

The `AKSBYONodeSpec` was temporarily disabled in #5151, but should be restored when CAPZ reference image publishing catches up with AKS.

**Describe the solution you'd like**
[Description of how you would like the cleanup to be done.]

Files to change: 1

- [ ] test/e2e/azure_test.go
  - 856-866

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by nojnhuh** [comment]
This will involve reverting #5151 and its backports to release branches, so these three PRs in total:
- #5151
- #5152 
- #5154

**Comment by nojnhuh** [comment]
This is fixed on main by #5167.

For the release branches, I'll make a change to the test to refer to the new images.

**Comment by nojnhuh** [comment]
This should be fixed on the release branches by #5230 and its ensuing cherry-pick.

**Comment by nojnhuh** [comment]
> Hey @nojnhuh and @mboersma , should this issue be closed now ?

Yep, thanks!

/close
