### ISSUE TITLE
docs: troubleshooting

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#520]
/kind documentation

We need a troubleshooting doc similar to https://github.com/Azure/aks-engine/blob/master/docs/howto/troubleshooting.md to walk through what to check, and in what order when things go wrong.

Some things to consider including:

- How to ssh on a VM and check cloud init logs
- How to check capz controller logs

**Comment by CecileRobertMichon** [comment]
+1

Let's also remove https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/development.md#debugging-cluster-creation and put it in the new troubleshooting doc

**Comment by alexeldeib** [comment]
/unassign 

troubleshooting some networking issues...

**Comment by CecileRobertMichon** [comment]
/close 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/troubleshooting.md
