### ISSUE TITLE
docs: service principals

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#521]
We need a doc similar to https://github.com/Azure/aks-engine/blob/master/docs/topics/service-principals.md#creating-a-service-principal that explains to use and create a service principal for CAPZ.

**Comment by rbitia** [comment]
The doc that we link in the quick-start isn't enough or would a specific doc in CAPZ help?

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/getting-started.md#setting-up-your-azure-environment is a good start but https://github.com/Azure/aks-engine/blob/master/docs/topics/service-principals.md#creating-a-service-principal is more complete, what do you think?

**Comment by nader-ziada** [comment]
I think this should should have been closed with #616 PR 

@CecileRobertMichon
