### ISSUE TITLE
CAPZ upgrade test is failing since migration to Compute Gallery default images

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#5229]
**Which jobs are failing:**

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-apiversion-upgrade-main

**Which tests are failing:**

**Since when has it been failing:**

**Testgrid link:**

**Reason for failure (if possible):**

Likely caused by #5167

It seems like the machines are using the default image implicitly, and the upgrade is changing the implicit default and therefore the images on those existing machines, causing them to re-roll nodes, which the test is verifying doesn't occur.

Is this failure isolated to Machines owned by MachinePools?

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by nojnhuh** [comment]
Some prior discussion in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4575#issuecomment-2450898339

/assign @willie-yao

**Comment by willie-yao** [comment]
It looks like there's some trouble upgrading nodes from 22.04 to 24.04. Seems like it works but the node gets replaced after the cluster is ready. This might be something we can manually fix in the upgrade template so it also upgrades the Ubuntu version.

I'm testing upgrading to 22.04 first to see if that's the problem in #5228

**Comment by willie-yao** [comment]
Okay I think the fix is to publish 24.04 marketplace images for the older CAPI versions. Is that something that can be done? @mboersma

**Comment by mboersma** [comment]
No, we can no longer publish to the Azure Marketplace, only the community gallery.

**Comment by willie-yao** [comment]
Gotcha. I'm not super familiar with how the image publishing process works so correct me if I'm wrong, but is the upgrade test going to be stuck on 22.04? And if so, do we create 22.04 images for the newer CAPI versions?

**Comment by nojnhuh** [comment]
Are we sure Ubuntu version is the only thing triggering the rollout? Based on my read of this, it seems like any migration from a reference to a Marketplace image to a Community Gallery one will cause CAPZ to rollout changes, even if the images are functionally identical:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/bcca2e2c01804769a46ce57075a8ee8c29d6bae3/azure/types.go#L125-L132

> Is this failure isolated to Machines owned by MachinePools?

Have we figured this out yet? I'm wondering why we wouldn't have hit this when we've modified the default image before, like in #2807. Maybe we need to add back some of the logic from before to say "if you're using k8s 1.30.3, you get a Marketplace image. If you're using 1.30.5, you get a Community Gallery image"?

**Comment by mboersma** [comment]
Based on what's actually available in the Marketplace offers, I think we could restore some logic in the `GetDefaultXXXImage` funcs that would return a Marketplace offer for windows-2019 or ubuntu-2204 in this range:

```go
// Use the Azure Marketplace for specific older versions, to keep clusterctl upgrade from rolling new machines.
 marketplaceVersionRange := semver.MustParseRange("1.27.16 || >=1.28.1 <=1.28.12 || >=1.29.1 <=1.29.7 || >=1.30.0 <=1.30.3")
if marketplaceVersionRange(v) {
	return &infrav1.Image{
		Marketplace: &infrav1.AzureMarketplaceImage{
			ImagePlan: infrav1.ImagePlan{
				Publisher: publisher,
				Offer:     offer,
				SKU:       skuID,
			},
			Version: version,
	}, nil
}
// otherwise return default community gallery image spec
```
