### ISSUE TITLE
Setup Azure Bastion in default installations

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-azure#528]
/kind feature

**Describe the solution you'd like**
[Azure Bastion](https://aka.ms/AboutBastion) is a neat feature that allows secure connections to the individual VMs without exposing their SSH ports to the internet.  The default configuration should add in the necessary address space, `AzureBastionSubnet`, and vnet-bastion setup to allow for this to work without any additional configuration.  Documentation should be updated to reflect this is a more secure and preferable way to connect to hosts instead of exposing them to the internet.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@voor this is already tracked in #165, @cpanato and I were just chatting about it this morning as he's interested in working on it. Going to close this one to avoid duplicates, feel free to add any comments you have on the other issue! Thanks.

/close

**Comment by voor** [comment]
Perfect, thanks!
