### ISSUE TITLE
docs: custom images

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#530]
We should expand the documentation in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/getting-started.md#using-images and move it to its own file. The new docs should describe how to use the different types of supported image types: shared image gallery, Azure Marketplace, image ID. It should also explain any requirements for the image. Expected OS, required components installed, etc. 

Refer to implementation here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/types.go#L392-L407

**Comment by CecileRobertMichon** [comment]
Should also link to Shared Image Gallery replication recommendations: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries#scaling

**Comment by CecileRobertMichon** [comment]
@mboersma would you like to take this one? If not no worries, I can take it.

**Comment by mboersma** [comment]
/assign

@CecileRobertMichon sure, I'd be happy to.
