### ISSUE TITLE
Proposal: use host based time sync instead of systemd-timesyncd by default

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#539]
Follow up from #535, we should look into replacing systemd-timesyncd time sync with host based.

References:
https://help.ubuntu.com/lts/serverguide/NTP.html
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync
https://github.com/Azure/aks-engine/issues/2552

We can also consider enabling [chrony](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#chrony).

These changes will most likely live in the [image-builder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi/packer/azure) but tracking here since the image would be consumed by capz.

**Comment by CecileRobertMichon** [comment]
from @ericsuhong's comment in the aks-engine issue above, "I found out that disabling NTP is not enough for enabling host-only sync mode. If you disable NTP, VMs till only sync from host on when VM is paused or reboot (got a confirmation from Azure Linux team). Chrony is the only way to sync time from host using PTP source."

**Comment by randomvariable** [comment]
Maybe for most complete coverage, and this would also cover vSphere environments where PTP might be enabled:

* In image builder, we default to time services being disabled in systemd
* We expose ntp options in CLuster API, defaulting to
```
ntp:
  enabled: true
```
This should then enable and start the appropriate NTP-based daemon for the distribution.

* We additionally install and enable by default ptp4l as per
Enable the ptp4l service https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/servers/Configuring_PTP_Using_ptp4l/ for all images, such that if PTP is available in the environment, it would be automatically used. If it is not available in the environment, it will do nothing.

* For Azure, we provide templates with `ntp.enabled` set to false in kubeadm configs.

**Comment by randomvariable** [comment]
Chatting @nader-ziada , I hadn't realised Ubuntu switched to chrony in 18.04, so I think we're good to go with chrony for the major distros.

**Comment by nader-ziada** [comment]
Had a chat with @randomvariable to understand his comment more, he was worried about whether ubuntu supports chrony, and since we found that it does since 18.04, seems like its an appropriate solution.

**Comment by nader-ziada** [comment]
created PR in image builder repo https://github.com/kubernetes-sigs/image-builder/pull/240

**Comment by nader-ziada** [comment]
PR in image-builder repo merged

**Comment by ericsuhong** [comment]
@nader-ziada Does this change mean that all default 18.04 Azure Ubuntu VMs will come with chrony enabled by default? I am wondering what would it take for us to start using this feature.

**Comment by nader-ziada** [comment]
yes, the capi 18.04 Azure Ubuntu VM will come with chrony enabled by default, but I believe we have not yet published such an image to the Azure Marketplace

**Comment by nader-ziada** [comment]
the linked PR ads chrony to the image, closing this

/close
