### ISSUE TITLE
Add warnings when a user selects a VM instance type that could lead to potential throttling issues based on the storage configuration

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-azure#550]
/kind feature

**Describe the solution you'd like**
Azure has a tiered set of i/o and bandwidth limits that can lead to difficult to debug throttling behavior. We should likely attempt to warn the user if the VM type they choose could cause VM-level limits to throttle before individual storage-level limits are hit.

**Anything else you would like to add:**
This will likely require either mapping (or potentially determining through api introspection) the vm-level limits based on the instance type selected to the aggregated limits for individual disks for the given instance to determine if the vm-level limits are lower than the aggregated individual disk limits.

**Comment by devigned** [comment]
kind of related: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/448

Also related, @CecileRobertMichon and I have talked about this a few times and have increased the default disk storage capacity as disk storage capacity is also related to i/o 😜.

What do you think about this going into a warning event on the AzureMachine resource?

**Comment by detiber** [comment]
I think a Warning event on the AzureMachine resource is a great idea. Only downside is that events are not long lived. It might also be good to replicate it as a Condition on the AzureMachine once we go down the path of supporting Conditions :)

**Comment by CecileRobertMichon** [comment]
/good-first-issues

conditions are now supported for AzureMachines, we should use those.

**Comment by jackfrancis** [comment]
My 2¢: these types of warnings should be integrated into the UX flow of building/configuring clusters and/or machines. Putting them in an event stream of the resource itself is sort of too late.

**Comment by alexeldeib** [comment]
> My 2¢: these types of warnings should be integrated into the UX flow of building/configuring clusters and/or machines. Putting them in an event stream of the resource itself is sort of too late.

do I hear webhook warnings?

**Comment by alexeldeib** [comment]
I will say...calculating what the limits even are can be super annoying. Here's my [hacked up version](https://github.com/alexeldeib/throttled/blob/master/src/resource.rs#L25-L28) -- it's not totally accurate, but gives you a rough idea of what's involved.

If you decide to pick this up and aren't  _**very**_ familiar with Azure disk performance limits, please ping me for specifics.
