### ISSUE TITLE
Consider disabling the instance ephemeral storage by default

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-azure#551]
/kind feature

**Describe the solution you'd like**
Since we are not reliant on the instance ephemeral storage, we should likely disable it be default.

**Anything else you would like to add:**
Instance-level ephemeral storage can consume part of the vm-level cached iops/bandwidth limits, so to avoid potential for this to be an issue we should likely disable the ephemeral storage by default. 

It wasn't overly clear to me if configured but unused ephemeral storage would have an impact on performance of other cached storage devices based on https://docs.microsoft.com/en-us/archive/blogs/xiangwu/azure-vm-storage-performance-and-throttling-demystify, but removing the chance that the ephemeral storage becomes used and causing issues would still be a good reason to consider disabling by default.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
sort of related to #487 (maybe?)

Thanks for opening this, agreed we should disable it if not using it.

/help

**Comment by alexeldeib** [comment]
What are our feelings about where the docker data disk should live? 🙂

**Comment by alexeldeib** [comment]
I'd like us to move toward a model where the OS is isolated fully on ephemeral disk. Docker IOPS can hog the OS disk so I'd like to suggest moving docker (like etcd) off the OS disk. If we do that, the natural destinations are either managed disk or tmp disk. Managed disk means users need both an etcd and docker data disk, or etcd and docker compete for resources.

We should also consider our preferred failure modes.

When the VM is at its SKU limits, it's toast. You can't do anything and many operations will be stuck in IO wait, including core functionality. This is bad. On the other hand, with docker on a managed disk, it's possible for the user workload to get throttled with performance impact. That's also bad. Worse than the VM going down? Debatable...

When using ephemeral OS disk, two effectively have two ephemeral disks capable of reaching max VM throughput, but they're still separate disks. From testing with fio configured for deep queues and random write heavy workloads, you can see the difference in r/w disk latencies between offloading docker to tmp disk.

FWIW, in AKS we've discussed this a lot and the likely outcome looks like defaulting ephemeral OS disk, move docker data dir to tmp disk by default, and potentially let users configure docker on a managed disk if they prefer (you can avoid docker taking down the VM this way by buffering between docker disk capacity and VM SKU capacity).

Some links as ref from my investigation with Jesse:
- his issue: https://github.com/Azure/AKS/issues/1373
- some docs on how I measured: https://github.com/alexeldeib/bpf-demo/blob/master/docs/disk_io.md
- basics guidelines on "am I throttled" with iostat: https://docs.microsoft.com/en-us/azure/aks/troubleshoot-linux#iostat
- how we're doing this in AKS-Engine: https://github.com/Azure/aks-engine/pull/3072

**Comment by detiber** [comment]
The main downsides that I see to leveraging ephemeral disk for OS/container storage is that the VM instances that we are using would no longer be able to handle "maintenance" operations including migrations.

I don't necessarily think that is a bad thing, but is there a way to flag an instance as not supporting those features so that we can figure out a way to safely handle those conditions (possibly using MachineHealthCheck and remediation)?

**Comment by alexeldeib** [comment]
I'm happy to say the best practice is allocating docker and etcd each a managed disk, btw. I think the key point is there are valid reasons for several potential combinations, we probably can't get away with picking one that's "good enough". I'd love to see us support the full range of features, even if some of those have constraints attached on possible configurations.
