### ISSUE TITLE
Add validation for Storage Profile parameters

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#557]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As part of the AzureMachine webhook, we should validate any spec passed in as part of `OSDisk` to make sure that it is valid and that it won't cause an error when creating the VM storage profile.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Working on this one.
