### ISSUE TITLE
Print controller versions on startup

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#561]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Would be great to to see the controller version in the logs, makes debugging issues for end users much simpler.

Suggested implementation: Add `"version", version.Get().String()` in the main.go `starting manager` log.

/good-first-issue
/help

**Comment by srm09** [comment]
@CecileRobertMichon IIUTC, at this time the version info does not get included in the binary anywhere. And the changes required are to push version information into the binary and have them show up in the startup log?
