### ISSUE TITLE
Add events for Azure Cluster services errors

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#562]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Building on what was described in #519 described, we should leverage k8s resource events to bubble up Azure cloud errors to the user. For example, if a network interface fails to create, the error message is currently printed in the capz manager logs but we should also add an event in the azurecluster resource.

/good-first-issue
/help

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/737 added events for AzureMachines, this is to add the same thing for AzureCluster errors.

/good-first-issue

**Comment by varunpurohit76** [comment]
hi @CecileRobertMichon can i take this up?

**Comment by CecileRobertMichon** [comment]
@varunpurohit76 go for it!
