### ISSUE TITLE
LoadBalancer service is not accessible

### ISSUE THREAD

**Issue by jzhoucliqr** [kubernetes-sigs/cluster-api-provider-azure#578]
/kind bug

**What steps did you take and what happened:**
Create a LoadBalancer service, public IP is allocated, but the service is not accessible through public IP.

**Anything else you would like to add:**
kube-controller-manager is adding correct inbound security rules to node-nsg with destination to be the allocated public IP. But capz securitygroup reconcile reset the rules to default and remove those rules.

**Environment:**

- cluster-api-provider-azure version: v0.4.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@jzhoucliqr I discussed with @aramase, we should do something similar to what the Azure cloud provider is doing: when reconciling the NSG, first get the existing NSG if it is already created and get the existing rules. Then, only add the rules we need for the CAPZ cluster to be functional if they do not already exist but preserve all the additional existing rules. 

We should also use ETAGs to make sure we do not update the NSG while something else (eg. Azure Cloud Provider) is updating it. If we don't, that could cause a race condition where we fetch the existing rules [a, b, c] and in the meantime something else deletes b but CAPZ updates the rules to [a, b, c, d] and thus we undo the rule deletion.

This is where Azure Load Balancer updates the NSG and checks the ETAG to make sure its version of the NSG is still current: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_backoff.go#L149-L175
    
And this is where Azure Load Balancer determines what rules to apply: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L1112-L1307

Let me know if any of this doesn't make sense.

**Comment by jzhoucliqr** [comment]
Thanks @CecileRobertMichon for sharing this. Make sense to me.

**Comment by snehala27** [comment]
I went through the changes required for this issue. As suggested,
azure-cloud-provider uses its own client https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go#L44  to communicate with Azure resources which has the provision to specify ETAG Headers: 
```
WithHeader("If-Match", autorest.String(etag))
```
azure-cluster-api-provider uses client from `azure-sdk-for-go` which does not have this provision. To add support for Headers would hardly be a 3-line change but in https://github.com/Azure/azure-sdk-for-go repository

So to have ETAG provision there are three options:
1. Import armClient from legacy-cloud-provider(Is this import allowed. It’s not used anywhere in the code)
2. Make changes to azure-sdk-for-go client
3. Create a new client for the this repo(Too much of work to do. Feasibility?)

@CecileRobertMichon Can you please suggest which option would be better? Or is there any other way to proceed.

**Comment by aramase** [comment]
@snehala27 The older versions (< 1.18) of azure-cloud-provider uses the `azure-sdk-for-go`. We have etag checks in those releases for security groups - https://github.com/kubernetes/kubernetes/blob/release-1.16/staging/src/k8s.io/legacy-cloud-providers/azure/azure_backoff.go#L184-L215. We should be able to do the same here.

**Comment by snehala27** [comment]
Thanks @aramase I got your point
