### ISSUE TITLE
Multi-tenancy within one manager instance

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#586]
/kind feature

**Describe the solution you'd like**
Provide multi-tenancy within the same instance of a CAPZ controller, rather than one instance per credential set.

CAPA issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1552
CAPA multitenancy proposal: https://docs.google.com/document/d/1vwjvWc-RIZfwDXb-3tW4gKBOaPCKhripfhXshOmB5z4/edit#heading=h.13bi7vgop9tn

TODOs:
- [x] discuss in upcoming CAPZ meeting (5/1/2020)
- [ ] create proposal
- [ ] break down features

**Comment by CecileRobertMichon** [comment]
related to #583

**Comment by randomvariable** [comment]
Hi, we're chatting about the AWS proposal today at 17:30 UTC. Ping me on slack [at]naadir if you want the invite with the Zoom ID & password.

**Comment by richardcase** [comment]
This is really interesting, especially for highly regulated environments like banks (as the CAPA proposal mentions) and to companies offering an internal platform/self service for their engineering teams to use.

Banks are an interesting one, as even sharing a management cluster may not be allowed....depending in what era the security controls still reside in.

**Comment by CecileRobertMichon** [comment]
/reopen

this isn't actually implemented yet
