### ISSUE TITLE
cluster/machine controller need to pause in v1alpha3 with annotation present

### ISSUE THREAD

**Issue by asatish** [kubernetes-sigs/cluster-api-provider-azure#601]
/kind bug

**What steps did you take and what happened:**
As specified in cluster API alpha2 to alpha3, providers need to check for pause annotation in cluster/machine controller which is used by clusterctl during a move. This is not present in azure provider.

https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#support-the-clusterx-k8siopaused-annotation-and-clusterspecpaused-field
https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html

**What did you expect to happen:**
Presence of pause annotation to stop reconcilation

**Environment:**

- cluster-api-provider-azure version: v0.4.1
- Kubernetes version: (use `kubectl version`):  1.16.8
- OS (e.g. from `/etc/os-release`): centos

**Comment by CecileRobertMichon** [comment]
Thanks @asatish, looks like we missed this.
/help
/milestone v0.5

**Comment by asatish** [comment]
I have a fix for this, I can send a PR for this, thanks..

**Comment by CecileRobertMichon** [comment]
@asatish are you still working on this?
