### ISSUE TITLE
Bootstrap failure detection

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-azure#603]
/kind feature

**Describe the solution you'd like**
If bootstrapping doesn't succeed, set AzureMachine.Status.FailureReason and FailureMessage to indicate there was an error. 

**Anything else you would like to add:**
More information in https://github.com/kubernetes-sigs/cluster-api/issues/2554.

We may need to amend the bootstrap provider contract to require them to write a sentinel file indicating success to a specific location because not all bootstrap providers will necessarily use cloud-init and have that as a consistent means for checking success/failure. I will probably write up a separate proposal for that.

**Comment by ncdc** [comment]
We will need a way for the CAPZ controller to be able to determine the status for a given AzureMachine. Does Azure have any services where the bootstrap logic in the VM could send an update to an Azure service (such as a message queue) to indicate bootstrap success? Or maybe some way to label or tag the Azure VM? This would need to be properly secured, presumably.

**Comment by alexeldeib** [comment]
I **think** the credentials in azure.json (or MSI) should do the trick for worker authentication, assuming we setup RBAC correctly.

There's an existing boot diagnostics option on VMs that streams cloud init + boot time logs into a plain text file in a storage account. Uploading a sentinel file that way or tagging a VM would probably be doable.

If you're thinking more like a message queue (perhaps to build on later?), Service Bus is a pretty traditional pub/sub message broker and Event Grid is a more loosely coupled event source/sink model with handlers.

**Comment by nader-ziada** [comment]
azure also supports the option to [add a tag](https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdateatscope) to the VM

**Comment by ncdc** [comment]
Whatever we do, we need to make sure that the information is available for inspection any time, and that CAPZ doesn't have to be running to receive a notification. I want to avoid a situation where bootstrapping fails, but CAPZ crashes/goes offline for whatever reason, and because it's down, we miss the notification that bootstrapping failed. It sounds like the options you suggested are all feasible, as long as messages are persisted until consumption.

**Comment by CecileRobertMichon** [comment]
@nader-ziada the tags are only visible to the Azure user, that might be one downside of using tags (ie. if we wanted to ever gather data on percentage of bootstrap failures/success).

**Comment by CecileRobertMichon** [comment]
/assign @jackfrancis
/assign

Jack and I are going to start putting together a CAPZ proposal / design doc for different ways we can implement this in Azure. Will drop a link to a doc here for collaboration once it exists.

**Comment by jackfrancis** [comment]
@CecileRobertMichon and I have written up our investigation and conclusions here:

https://docs.google.com/document/d/1U0GxvO6ltgIINMjpQz96UD4bExlN2h21wyyn-3ENezc

I think next steps are to produce a concrete proposal for implemeting a capz-specific, named Azure VM Extension to include with capz-provisioned AzureMachine vms.

**Comment by devigned** [comment]
@CecileRobertMichon is this still open?

**Comment by CecileRobertMichon** [comment]
yes, the last part is to add the script in the extension that checks for the sentinel file and set conditions.
