### ISSUE TITLE
enable vm bootdiagnostics

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#606]
/kind feature

**Describe the solution you'd like**

Azure VM and VMSS support a boot diagnostics feature which streams cloud init logs and boot time output into a storage account. This is incredibly useful for debugging bootstrapping failures when using cloud init, as all the logs get exfiltrated for the machine. 

Consider enabling this for AzureMachine and AzureMachinePool.

https://godoc.org/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute#DiagnosticsProfile

/help-wanted
/good-first-issue

**Comment by CecileRobertMichon** [comment]
related to #603
