### ISSUE TITLE
Refactor: Services should not return interfaces

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#609]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

**Detailed Description**

_Follow up on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/482#discussion_r421789468_

We should be returning SDK types for Azure resources in services/ instead of interface{}.

Also, we should remove unused service mocks (we mock the Azure Clients and those are the ones used in tests):
- remove unused https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/fake_interfaces.go
- remove unused https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/mocks/service_mock.go#L31

related to #110 

**Contract changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

**Data model changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

/kind proposal

**Comment by CecileRobertMichon** [comment]
@juan-lee are you still interested in helping with this?

**Comment by CecileRobertMichon** [comment]
cc @alexeldeib @justaugustus @devigned

**Comment by devigned** [comment]
I'd caution from returning SDK types from the services. Having dependencies on AzSDK for Go types beyond the service layer implies a tighter coupling to the SDK.

Perhaps, we should consider the services layer returns a spec + status type (maybe not a `runtime.Object`, but something with all the info needed by callers).

**Comment by CecileRobertMichon** [comment]
What if the `Get()` functions were never called from outside `services`? The way I see this working is you would only have `Ensure()`/`Reconcile()` and `Delete()` be public and be called from the controllers (see #110). Reconcile and Delete should both only return `error`, the SDK type return would only be for intermediate `Get`s.

**Comment by devigned** [comment]
What do you think about `Get()` being `get()`?

**Comment by CecileRobertMichon** [comment]
@devigned I almost wrote `get()` but I realized that might not work if you need to get another resource type since each service is in its own package right now, eg. you need to get the subnet ID from the network interface package... https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/networkinterfaces/networkinterfaces.go#L71

Ways to go around this off the top of my head: 
- put all the Azure resource types in one `services` package (or maybe `azure` package)
- have public functions just to get the ID or whatever info we need, so `GetSubnetID()` would return a string and call `get()` which would return the `network.subnet`.

**Comment by CecileRobertMichon** [comment]
/close 

in favor of #757
