### ISSUE TITLE
[managedcluster] e2e tests

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#611]
/kind feature

**Describe the solution you'd like**
We should add e2e tests similar to the existing tests for Azure, particularly being sure to validate the options we provide to AKS match the result we get.

**Comment by alexeldeib** [comment]
couple observations from spiking on this.

The capi test framework is a bit tightly coupled. The machine portion is fairly well abstracted but the control plane tests hardcode a KubeadmControlPlane struct as part of the test context [0], [1]. Besides the fact that it uses KCP directly instead of the CAPI control plane contract, it also relies on a control plane provider using machines for the underlying implementation, which is not necessarily true. A control plane could be pod based or in the case of AKS/EKS/GKE fully managed/externalized. 

It would be nice to decouple the pieces of the capi e2e framework to allow it to run against arbitrary control plane implementations like used for AzureManagedControlPlane. That seems like it might take a good chunk of work. A shorter term approach could be a simple pipeline which does the following:
- create AzureManagedCluster with clusterctl
- wait for all objects to reach status.ready = true
- validate control plane connectivity, ensure all nodes ready
- delete crds, ensure all objects get deleted (maybe verify against azure CLI at the end or something?)

[0]: https://github.com/kubernetes-sigs/cluster-api/blob/72ee11af1bec2e9dcd3fb22cba3f718839658d89/test/framework/clusterctl/clusterctl_helpers.go#L240
[1]: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/controlplane_helpers.go#L233

**Comment by alexeldeib** [comment]
this should be unblocked thanks to @shysank's upstream work, at least using v0.4.0-beta.0 or later of CAPI 🎉

**Comment by CecileRobertMichon** [comment]
@shysank is actually working on this in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1386

**Comment by alexeldeib** [comment]
/assign @shysank 

We can definitely add more configurations on top of the work in #1386, but marking as assigned since I feel that's enough to close the general issue for adding e2e. Let's open specific issues for desired testing scenarios after that gets merged.

**Comment by nader-ziada** [comment]
/close 

fixed with e2e added as part of #1386 🚀
