### ISSUE TITLE
[managedcluster] validating webhook for DNS IP

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#612]
/kind feature

**Describe the solution you'd like**
In AKS users can provider the service CIDR but also can individually provide a DNS IP. We should ensure the DNS IP is inside the service CIDR inside a validating webhook to avoid footguns.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by CecileRobertMichon** [comment]
@jroden are you working on this one?

**Comment by jroden** [comment]
@CecileRobertMichon My apologies for the delay!  Yes, I'm working on this as a joint effort with #615 .  I have the validating and mutating hooks created, just working through adding service account permissions so the amcp validating hook can extract the serviceCIDR field from the associated cluster resource.  I actually haven't worked on capz in a couple weeks (been pushing to get csapro cert hopefully this week).  Was planning on picking up the work again starting next week, but can make some time this week if you want!  Just lmk 😄

**Comment by CecileRobertMichon** [comment]
@jroden no worries! Was just doing some issue triage, feel free to work on it whenever you can. Will mark you as assigned so no one else works on it at the same time.

/assign @jroden

**Comment by jroden** [comment]
cleared the exam :tada: so I'm back!

Currently working on the rbac permissions for the amcp validating webhook.  Researching if I can assign a custom serviceAccount to the amcp webhooks since system:serviceaccount:capi-webhook-system:default doesn't have permissions to list cluster objects.

Once I have that sorted I should be ready to submit a PR for these!

**Comment by jroden** [comment]
Hope everyone is having a good week!  I've done a little digging and am hoping to get some feedback.  A quick background on the challenge I'm working through is-- the validating webhook for amcp needs to list the owner cluster resource (to get the serviceCIDR field for validating the amcp DNSServiceIP).  The capz webhooks are served from the capz-controller-manager deployment in the capi-webhook-system namespace.  However, the default serviceAccount for that namespace doesn't have permissions to list cluster resources.  I'm wondering what the thoughts are on associating that deployment with a new capz serviceAccount that has permissions to list cluster resources?  Thanks for the help! :smile: 

@alexeldeib @CecileRobertMichon

**Comment by devigned** [comment]
We have avoided using a client from webhooks up to this point. Perhaps, this deserves stronger consideration than we have provided it in the past. It appears this will be a reoccurring issue in infrastructure providers, which need information about their related CAPI resources.

**Comment by alexeldeib** [comment]
seems reasonable to me to generate a separate serviceaccount/role for our webhook deployment? @vincepri @detiber any thoughts on this (kubeclient in webhooks, multiple webhook serviceaccounts) from CAPI perspective?

**Comment by detiber** [comment]
I believe we've mostly avoided it until now because of the multi-tenancy model we are operating under (being namespace-based). Once things have adopted native multi-tenancy, then I think it'll be a lot easier to do these types of things.

**Comment by alexeldeib** [comment]
hmm, I'm not sure I totally follow. I was thinking we'd add some controller-gen rbac markers and deploy a Role + RoleBinding + ServiceAccount into the existing capi-webhook-system namespace, but they would be specific to capz. Are you talking about some way to isolate the existing set up of managers/webhooks more cleanly?

**Comment by detiber** [comment]
The main reason why we separated out the webhooks from the controller deployment was because multi-tenancy is currently done via separate controller manager deployments watching different namespaces. Since there is only a single deployment of webhooks, it would require the webhook "controller manager" to have broader permissions across the cluster than the associated controller "controller manager".

With the webhook controller having broader permissions, it crosses the existing multi-tenancy boundaries, which might be okay, but could also create interesting vulnerability vectors depending on what permissions we are talking about and what the exact actions the webhook implementations look like.

**Comment by alexeldeib** [comment]
Does that imply we shouldn't use ClusterRoles in CAPI upstream and infra/bootstrap providers downstream? Seems that would go against the security model, we use them a bit liberally at the moment.

**Comment by detiber** [comment]
> Does that imply we shouldn't use ClusterRoles in CAPI upstream and infra/bootstrap providers downstream? Seems that would go against the security model, we use them a bit liberally at the moment.

Probably, but I think that would also require changes to `clusterctl` to support.

**Comment by alexeldeib** [comment]
@jroden i guess we may want to park this one for a bit, I’m not sure the trade off here makes sense at the moment. If we’re not doing so already, maybe we can just make an invalid IP record an event and terminal condition in the customer resource instead.

**Comment by vincepri** [comment]
Apart from what Jason mentioned, having a client in webhooks can turn into error prone behavior pretty easily. You can get into situations where object A requires object B which requires object A, then webhooks would cause an infinite loop.

We'll need to find a good solution for this, we're also re-evaluating the webhook approach we take today in controller runtime.
