### ISSUE TITLE
[managed cluster] documentation

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#613]
/kind documentation

**Describe the solution you'd like**
Users should understand how to use managed clusters in CAPZ from our documentation 🙃 We should have example templates as well as markdown around how to deploy a cluster.

**Comment by CecileRobertMichon** [comment]
Note: we should make sure this includes the feature flags needed for the feature (both AKS and MachinePool).

**Comment by rbitia** [comment]
Please add documentation, I'd love to try this feature out but I need a little guidance.
Happy to help write it too, if someone can guide me in the right direction :D
