### ISSUE TITLE
[multitenancy/managedcluster] enable reading Azure credentials from secret

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#614]
/kind feature

**Describe the solution you'd like**
For multitenancy and least-privilege access, it should be possible to inject a different set of credentials from those running in the manager for use inside the cluster.

**Comment by alexeldeib** [comment]
/assign @devigned 

for now at least, ref https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/809 which addresses references to credentials

**Comment by CecileRobertMichon** [comment]
work for non-managed clusters has started in #977

**Comment by CecileRobertMichon** [comment]
Once #977 merges, the same changes can be adopted in managedcluster to enable this.

/help

**Comment by CecileRobertMichon** [comment]
duplicate of #1153 

/close
