### ISSUE TITLE
defaulting + templates for marketplace images

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#623]
/kind feature

**Describe the solution you'd like**
The current template doesn't have any image in it. This may be tricky due to date/version, but we could at least do defaulting for the user. That may still required network calls to determine the most suitable image offer, but we should try.

Thoughts?

**Comment by CecileRobertMichon** [comment]
So I looked into doing this a while back and I ran into two main problems:

1) The `Image` field is in `AzureMachine` and it depends on `Version` which is in `AzureCluster`, which makes it hard to default with a webhook without opening up the door for race conditions
2) If we default it, we also have to make sure it gets updated during upgrades (ie. When `Version` is changed). But then that also means we need to only change it if it's not a user-provided custom image so we need a mechanism for that. That one is more solvable but it's worth the call out.

**Comment by alexeldeib** [comment]
1. Can we not use https://github.com/kubernetes-sigs/cluster-api/blob/703111b822505e836236541ac51795bb38928a60/api/v1alpha3/machine_types.go#L58-L61 from the owner machine? The defaulting also doesn't have to be in webhook, note that I didn't mention it in the issue because I wanted to leave the door open to not forcing validation in webhook and letting the controller handle lookup on the CAPI Cluster/Machine.

2. We already can't validate custom images in these scenarios. We could validate that if you used a capi-cncf offer, it's compatible with the desired k8s version and then punt on defaulting during upgrade. Alternatively, if we can do the semver <=> image mapping reasonably in the controller, I don't see why it's a problem. I guess that's what you're alluding to in terms of being solvable?

**Comment by CecileRobertMichon** [comment]
> The defaulting also doesn't have to be in webhook, note that I didn't mention it in the issue because I wanted to leave the door open to not forcing validation in webhook and letting the controller handle lookup on the CAPI Cluster/Machine.

Agreed, but if that's the case then we can't enforce the field in the validating webhook (which is what it's currently doing)

**Comment by alexeldeib** [comment]
can you clarify the race condition you're seeing?

I see the one being that AzureMachine tries to default before version is set on AzureCluster. That's fine, come back later. This is expected behavior already using e.g. kubectl. 

I don't really understand the case for a race where AzureCluster has a version that's removed after AzureMachine uses it.

**Comment by alexeldeib** [comment]
FWIW, personally, I kind of feel "runtime-y" validation should be done in the controller. The things I would want to do in a webhook are often covered today by structural schema. So I don't really think that's the end of the world. 

I don't like the runtime behavior of webhooks in terms of latency, especially when you're issuing lots of client calls from inside the webhook context. It's bad UX because the user expects to apply the object immediately and let async reconciliation happen. We should also do validation as early as possible, but I think when a user is already expecting potentially long-running reconciliation (read: azure vm provisioning), it's reasonable to punt runtime validation and let them check the status.

/opinion

My preferred use case for validating webhooks today is cross-field validation that's difficult to express in OpenAPI specs alone.

**Comment by CecileRobertMichon** [comment]
@alexeldeib currently the defaulting already happens in the controller for AzureMachine.

My comment about race conditions only applies if we move that defaulting in the webhook, which is what I thought your original issue was (read too fast and missed that you actually left out webhooks on purpose).

**Comment by alexeldeib** [comment]
Not sure I follow how the webhook makes it a race condition?

**Comment by CecileRobertMichon** [comment]
It was a few months back that I started a branch trying to make the default for Image happen in the AzureMachine webhook so I don't remember exactly but I had talked to @devigned about it so maybe he has better recollection. I think it was something to do with the fact that if you default a field in one object's defaulting webhook that depends on another object's spec then you introduce some concurrency. Ie. If you get the Machine spec Version and then the Machine gets updated, your might have a wrong version used for the image default. Not sure if all of this is true btw but I think that's what stopped me at the time. Very open to revisiting.

**Comment by CecileRobertMichon** [comment]
This is where the image is currently getting defaulted: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azuremachine_reconciler.go#L380

**Comment by alexeldeib** [comment]
The blurb above was just for context -- I think we do the right thing now which is why I'm not concerned. Also I see what you're saying about the webhook behavior.

For the sake of the templates, I think you fixed this by removing the webhook validation so the defaulting actually runs and the templates work without user-specified images (that's why I opened the issue).

For upgrade, we can probably say something like
- we default marketplace images to the latest image for the corresponding k8s version (equivalent to create)
- we attempt to create if the user provides a custom image, but can't do any validation (equivalent to existing behavior with custom images).

I think the only action item there might be to handle the upgrade case? I didn't see that covered, but if that's already done we can close this issue (or else repurpose).

**Comment by alexeldeib** [comment]
CAPI doesn't do mutable upgrades
