### ISSUE TITLE
Easily enabling Azure Monitoring on CAPZ created clusters

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#624]
/kind feature

**Describe the solution you'd like**
I'd like to easily enable azure container monitoring on my management k8s cluster (if needed) and k8s clusters created from there. Ideally we would utilize the outcome of the Cluster Resource Set proposal here: https://github.com/kubernetes-sigs/cluster-api/pull/3050

**Comment by juan-lee** [comment]
Shouldn't this go in an azure monitor repo? This does seem like a core concern of cluster lifecycle.
