### ISSUE TITLE
Flatcar support for CAPZ

### ISSUE THREAD

**Issue by rbitia** [kubernetes-sigs/cluster-api-provider-azure#629]
/kind feature

**Describe the solution you'd like**
Support users that have a dependency on CoreOS by supporting Flatcar containers in CAPZ.

**Comment by detiber** [comment]
I suspect this will need additional support from the kubeadm bootstrap provider and image-builder support as well (https://github.com/kubernetes-sigs/cluster-api/issues/1582), since Flatcar is managed quite a bit differently than the currently supported OSs.

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/248

**Comment by CecileRobertMichon** [comment]
I'm going to close this one since it doesn't require any changes to the infra provider AFAIK and it's already being tackled from an image perspective in kubernetes-sigs/image-builder#248 and for bootstrapping in https://github.com/kubernetes-sigs/cluster-api/pull/3437

/close

**Comment by vbatts** [comment]
@CecileRobertMichon I think it may require infra-provider updates, it just that the image-builder work has been a huge thing for review and feedback.

**Comment by vbatts** [comment]
I guess I was mis-remembering. Looking through the code it doesn't seem to have particular things jump out as blockers. There is a good chance we need a change to incorporate the ignition-bootstrap-provider, rather than just kubeadm-bootstrap-provider.
The big this is for us to work through the providers and get testing on this.

**Comment by CecileRobertMichon** [comment]
reopening to track testing / integration

/remove-lifecycle rotten
/reopen

**Comment by vbatts** [comment]
@CecileRobertMichon nice. This is on our roadmap and I'm looking forward to making it happen.

**Comment by vbatts** [comment]
cc @invidian

**Comment by invidian** [comment]
/remove-lifecycle rotten

Small update. We've got image-builder to build CAPI Azure images, but there is still some thing which needs to be resolved before we open the PR.

Changes proposed in https://github.com/kubernetes-sigs/cluster-api/pull/4172 works out of the box with CAPZ, except new cluster configuration template needs to be submitted including some minor differences in node configuration. Mentioned here: https://github.com/kubernetes-sigs/cluster-api/pull/4172#issuecomment-802771490.

**Comment by invidian** [comment]
CABPK PR kubernetes-sigs/cluster-api#4172 has been merged and will be part of v1.1 release, so we're getting closer getting this resolved :tada:

**Comment by mboersma** [comment]
@invidian is this still ongoing? We have it tagged for the next release, but can change that if it's not going to land.

**Comment by invidian** [comment]
Thanks for the ping @mboersma. I'll try to push things forward again, as we're only missing some final conversation around https://github.com/flatcar-linux/Flatcar/issues/734. Hopefully this could happen by the end of this month, but please don't wait for this with the release.

**Comment by jackfrancis** [comment]
@invidian should we consider the progress of flatcar + capz blocked on https://github.com/flatcar-linux/Flatcar/issues/734 ?

**Comment by invidian** [comment]
>@invidian should we consider the progress of flatcar + capz blocked on https://github.com/flatcar-linux/Flatcar/issues/734 ?

Definitely.

**Comment by invidian** [comment]
It's almost done in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2890.

**Comment by invidian** [comment]
/close

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2890 is now merged.
