### ISSUE TITLE
Skip Deletion of vnet in Unmanaged Mode

### ISSUE THREAD

**Issue by bagnaram** [kubernetes-sigs/cluster-api-provider-azure#631]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Specify `AZURE_VNET_NAME` to an already existing vnet and deploy the cluster. When deleting the cluster, CAPZ attempts to delete the vnet.

**What did you expect to happen:**
CAPZ should not attempt to remove vnet resources in unmanaged mode.

**Anything else you would like to add:**
```text
E0519 20:36:16.478877       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/capz-mbagnara: failed to delete virtual network mbagnara-vnet for cluster capz-mbagnara: failed to delete vnet mbagnara-vnet in resource group mbagnara: network.VirtualNetworksClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code=\"InUseSubnetCannotBeDeleted\" Message=\"Subnet default is in use by /subscriptions/3b511ccd-979b-40b6-b8fe-08a6d1a75d78/resourceGroups/mbagnara/providers/Microsoft.Network/networkInterfaces/server2019208/ipConfigurations/ipconfig1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\" Details=[]"  "controller"="azurecluster" "request"={"Namespace":"default","Name":"capz-mbagnara"}

```

**Environment:**

- cluster-api-provider-azure version: v0.4.4
- Kubernetes version: (use `kubectl version`): 1.18.2
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@bagnaram was the vnet created by another capz cluster?

**Comment by CecileRobertMichon** [comment]
vnet deletion is skipped when the vnet is not owned by the clsuter (ie. it does not have the owned tag with value clusterName): https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/virtualnetworks/virtualnetworks.go#L122

**Comment by bagnaram** [comment]
> @bagnaram was the vnet created by another capz cluster?

No it was previously created manually. I will have to dig deeper into the codebase and determine what occurred.

**Comment by bagnaram** [comment]
Steps to reproduce:
1. Provision CAPZ cluster on already existing vnet `mbagnara-vnet`. `capz-test.yaml`
2. CAPZ controller will fail to provision AzureCluster because target vnet's subnet doesn't exist.
3. Delete `capz-test` `kubectl delete -f capz-test.yaml`
4. AzureCluster status will be hung
```text
archlinux% kubectl get azurecluster
capz-test       capz-test       
``` 
Viewing the logs shows that the controller is attempting to delete the vnet `mbagnara-vnet` but failing because I have existing resources running.
```text
kubectl logs -n capz-system capz-controller-manager-5cb8467499-c9j6l manager -f
```text
I0520 14:13:45.325161       1 azurecluster_controller.go:145] controllers/AzureCluster "msg"="Reconciling AzureCluster delete" "AzureCluster"="capz-test" "cluster"="capz-test" "namespace"="default" 
E0520 14:13:47.905677       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting AzureCluster default/capz-test: failed to delete virtual network mbagnara-vnet for cluster capz-test: failed to delete vnet mbagnara-vnet in resource group mbagnara: network.VirtualNetworksClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code=\"InUseSubnetCannotBeDeleted\" Message=\"Subnet default is in use by /subscriptions/3b511ccd-979b-40b6-b8fe-08a6d1a75d78/resourceGroups/mbagnara/providers/Microsoft.Network/networkInterfaces/server2019208/ipConfigurations/ipconfig1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\" Details=[]"  "controller"="azurecluster" "request"={"Namespace":"default","Name":"capz-test"}
```

**Comment by CecileRobertMichon** [comment]
I was able to repro, it looks like the problem is that vnet.ID is empty which is causing `isManaged` to return true. It shouldn't be empty because it should be getting set by https://github.com/sozercan/cluster-api-provider-azure/blob/master/cloud/services/virtualnetworks/virtualnetworks.go#L92, not sure why that's not happening yet. It does get set for managed vnets which is interesting...

**Comment by CecileRobertMichon** [comment]
there's also a passing unit test that validates that this works as expected so I'm a little puzzled: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/virtualnetworks/virtualnetworks_test.go#L99-L100

**Comment by CecileRobertMichon** [comment]
update: this actually only happens if the subnets are not provided, confirmed it works as expected if the subnets exists. Still a bug but this helps reduce the scenario quite a bit.

**Comment by CecileRobertMichon** [comment]
I think I found the root cause: it's a regression due to the newly introduced webhook validation which is failing the AzureCluster object update. Will send a PR shortly.

**Comment by CecileRobertMichon** [comment]
the other thing I realized is that if you are passing in an existing vnet, it is expected that you'll also provide the RG name of where that vnet is located. If you do, the webhook validation would prevent you from even creating that cluster without specifying subnets. It is [documented](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/topics/custom-vnet.md) but unfortunately not enforced by webhook validation since you could also provide a custom name for the vnet to be created and there is no way to distinguish between these two cases.
