### ISSUE TITLE
Templates for clusters are only partially namespaced

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#641]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When running `make create-workload-cluster` while `kubeconfig` is pointing at a namespace other than `default` for most 'flavor' and parts of the templates will end up in default namespace and other parts will end up in current namespace.  This causes only parts of the cluster to be provisioned as CAPI components can't find the `AzureMachineTemplates` or similiar CRD's.

**What did you expect to happen:**
All components to be deployed to same namespace regardless of what namespace I am in now.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Kustomize 3.5.4

- cluster-api-provider-azure version: master branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/close

fixed by #642
