### ISSUE TITLE
Enable VMSS for Control Plane Nodes

### ISSUE THREAD

**Issue by jseely** [kubernetes-sigs/cluster-api-provider-azure#644]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

Currently CAPZ has, in experimental, the ability to deploy worker nodes as VMSS via the CAPI `MachinePool` and CAPZ `AzureMachinePool` resources. This issue is to discuss how we can enable VMSS support for Control Plane nodes.

***Goals***
1. Enable deployment of Control Plane (Master) nodes via VMSS

***Non-Goals/Future Work***
1. Upgrade cluster
1. Upgrade path for VMSS VM types

**User Story**

As an operator I would like highly available control plane nodes in regions that do not support availability zones so that my cluster is available when I need it.

**Detailed Description**
Currently we only have support for VMSS for worker nodes. This work enables control plane nodes to be managed by a VMSS and thus enables HA via its underlying Availability Sets.

**Contract changes [optional]**

This may impact how KubeadmControlPlane functions as each VM in the VMSS must share the same userdata for initialization. It also may break some of the lifecycle management of the control plane.

**Data model changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

/kind proposal

**Comment by alexeldeib** [comment]
If we can generalize the quirks of VMSS (e.g. no ordering guarantees) in a way that makes sense upstream, I think that's a big win. One viable but maybe suboptimal solution would be a provider-specific control plane implementation for vmss.

**Comment by CecileRobertMichon** [comment]
The scope of this issue has grown quite a bit since KCP was introduced in CAPI so now it's no longer about supporting MachinePools with a "control-plane" label, we would have to either add some glue between KCP and MachinePools to make KCP work with MachinePools or create an equivalent MachinePool Control Plane CRD to KCP (similar to how KCP manages machines).
