### ISSUE TITLE
MachinePool and KubeAdmControlPlane disagree on k8s version validation

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#669]
/kind bug

**What steps did you take and what happened:**

Generate a machinepool-flavored cluster manifest:

```clusterctl config cluster capz-machinepool -f machinepool --worker-machine-count 1 --kubernetes-version 1.18.3 > capz-machinepool.yaml```

Then apply the manifest and get a validation error on the "version" field:

```shell
% k apply -f capz-machinepool.yaml 
cluster.cluster.x-k8s.io/capz-machinepool unchanged
azurecluster.infrastructure.cluster.x-k8s.io/capz-machinepool unchanged
azuremachinetemplate.infrastructure.cluster.x-k8s.io/capz-machinepool-control-plane created
machinepool.exp.cluster.x-k8s.io/capz-machinepool-mp-0 unchanged
azuremachinepool.exp.infrastructure.cluster.x-k8s.io/capz-machinepool-mp-0 unchanged
kubeadmconfig.bootstrap.cluster.x-k8s.io/capz-machinepool-mp-0 created
The KubeadmControlPlane "capz-machinepool-control-plane" is invalid: spec.version: Invalid value: "": spec.version in body should match '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([-0-9a-zA-Z_\.+]*)?$'
```

Adding a `v` prefix to `v1.18.3` in the manifest fixes it, but note that:
- This worked fine until recently
- the `MachinePool` in the same manifest is happy with either `1.18.3` or `v1.18.3` AFAICT

**What did you expect to happen:**

I expected that CAPZ and `clusterctl` would create a valid manifest without built-in validation errors.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: master, post v0.4.4
- clusterctl version: v0.3.6
- Kubernetes version: (use `kubectl version`): v1.18.3
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@mboersma I think this is a CAPI issue, k8s version is not part of Azure types. Validation was added in https://github.com/kubernetes-sigs/cluster-api/pull/2691 but was not added for `MachinePool`. Can you please file the issue in https://github.com/kubernetes-sigs/cluster-api/issues and close this one?

**Comment by mboersma** [comment]
Closing in favor of kubernetes-sigs/cluster-api#3128
