### ISSUE TITLE
AZURE_CLIENT_SECRET with quotes causes cluster failure.

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-azure#672]
/kind bug

Creating an Azure Service Principal where the randomly generated secret contains a `"`.

This secret then goes into `AZURE_CLIENT_SECRET` and creates issues, because the output into `/etc/kubernetes/azure.json` will not properly escape the `"`, resulting in kubelet failures:
```
Jun 03 00:03:26 capi-quickstart-control-plane-pvzh4 kubelet[76379]: F0603 00:03:26.581514   76379 server.go:274] failed to run Kubelet: could not init cloud provider "azure": error converting YAML to JSON: yaml: line 5: did not find expected ',' or '}'
```

**What did you expect to happen:**

There should be some sort of logic to escape the quotes prior to them going into `/etc/kubernetes/azure.json` or Azure should stop using `"` in its randomly generated passwords.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
> There should be some sort of logic to escape the quotes prior to them going into /etc/kubernetes/azure.json or Azure should stop using " in its randomly generated passwords.

We won't be able to make "Azure should stop using " in its randomly generated passwords" happen so let's focus on ways we can document escaping special quotes in the CAPZ documentation about SPs or even better, automate escaping special chars. 

/help

**Comment by alexeldeib** [comment]
> We won't be able to make "Azure should stop using " in its randomly generated passwords" happen

https://github.com/Azure/azure-cli/issues/13625#issuecomment-632667687
https://github.com/Azure/azure-cli/pull/13643

it's fixed in new CLI versions

**Comment by alexeldeib** [comment]
It's reasonable to escape these, but IMO the CLI team messed up on this

**Comment by CecileRobertMichon** [comment]
Awesome, I think we can close this then. For anyone running into this, please update to the latest Azure CLI.

/close
