### ISSUE TITLE
Look into making LB outbound rule IdleTimeoutInMinutes configurable and increase default

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#676]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

From https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/674#discussion_r434848567

> // DefaultOutboundRuleIdleTimeoutInMinutes determines the aks-engine provided default for IdleTimeoutInMinutes of the OutboundRule of the agent loadbalancer
// This value is set greater than the default Linux idle timeout (15.4 min): https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html

We should:

1) Determine what is a sane default for this value. Should it be the same default for different LB roles? The Azure default is 4 minutes. AKS Engine sets it to 30 minutes, and points to that being greater than the default Linux timeout which is 15.4 minutes. It's possible that there is no action to be taken if 4 is already the right default.

2) Consider making this value user configurable. Before doing this, we need to answer the following questions: is there a user story for configuring this value? What is the best way to represent this in the AzureCluster Spec? Do we expect to expose other options for Load Balancers in the future? Currently, there is no Load Balancer configuration so this might involve creating a new struct to store Load Balancer Spec(s). Keep in mind that CAPZ currently manages the lifecycle of 3 different load balancers per cluster: 1 internal LB, 1 public apiserver LB (control planes in the backend pool), and 1 "node outbound" LB (nodes in the backend pool), which is also the same LB used by cloud provider to define LB rules for services.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
"Let's enable a convenient user-override for the cluster LoadBalancer outbound rule timeout, which governs how long to keep idle connections open. Certain applications may be idle by design for longer than 4 minutes (the default), and we want to accommodate that. Conversely, certain clusters may not have any such applications, but will expect a lot of aggregate outbound connections, in which case they will want to more aggressively close connections to better protect against SNAT port exhaustion." - @jackfrancis

**Comment by yangl900** [comment]
Seems cannot be configured yet, should we still track this in backlog?
