### ISSUE TITLE
When enabling route creation in the cloud provider routes can not be created

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#682]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If you turn on `--configure-cloud-routes` in the [cloud provider](https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/#options) for a CNI that requires route tables such as kubenet or when using [calico with UDRs](https://docs.projectcalico.org/reference/public-cloud/azure#azure-user-defined-routes) there will be 2 reconciliation loops running on the route table object in azure which for the cloud provider is causing the following issue when trying to update add the routes for each node:

```
E0604 17:11:05.255586       1 azure_routes.go:345] CreateRoute failed for node "capz-cluster-0-control-plane-q7mgs" with error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: {
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch"
        "message": "Etag provided in if-match header W/\"8aea0627-0483e-ba38-ebd11e488\" does not match etag W/\"a96fd6fb-1bcb-4824-94306b551d5f5\" of resource /subscriptions/b9436a-0c7/resourceGroups/capz-cluster-0/providers/Microsoft.Network/routeTables/capz-cluster-0-node-routetable in NRP data store."
      }
    ]
  }
}
```
**What did you expect to happen:**
The work load cluster can update routes if required by the cni.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I tracked it down in cloud provider and turned off capz controller and things worked as expected on the cloud provider side.

NSG has this code in place to handle etags and should be able to mimic: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/ff37e097b6cdad039e1df89d8887eb67436e8b32/cloud/services/securitygroups/securitygroups.go#L117

**Environment:**

- cluster-api-provider-azure version: k8s.gcr.io/kube-controller-manager:v1.18.2
- Kubernetes version: (use `kubectl version`): 1.18.2
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@jsturtevant are you working on this or is it okay to mark it as help wanted?

**Comment by jsturtevant** [comment]
This will be tricky to test since we don't have other CNI that requires the route creation behavior currently.  I can take this and test it against the #646
