### ISSUE TITLE
Add code coverage as part of PR status

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#692]
This is important to developers submitting PRs to analyze how many tests are being introduced into the code base and/or removed and the quality of the tests as well.
This will also enable reviewers to assist in improving the test code base as well.
This is important for the long-term reliability of the project and the overall confidence.

https://github.com/kubernetes/test-infra/blob/master/robots/coverage/docs/design.md

see also https://github.com/kubernetes-sigs/cluster-api/issues/2918

/help

**Comment by cpanato** [comment]
I'm going to check this one and learn some new things :)

/assign
/remove-help

**Comment by CecileRobertMichon** [comment]
related to https://github.com/kubernetes-sigs/cluster-api/pull/3310

**Comment by cpanato** [comment]
some update: https://github.com/kubernetes-sigs/cluster-api/pull/3310#issuecomment-655952591
