### ISSUE TITLE
[e2e] cluster should apply network policies

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#704]
**Describe the solution you'd like**
An e2e test that validates network policies got applied as expected 

test from aks-engine: https://github.com/Azure/aks-engine/blob/master/test/e2e/kubernetes/kubernetes_test.go#L1637

**Comment by cpanato** [comment]
I would like to work on this. Is that possible or there is anyone already working on this?

**Comment by nader-ziada** [comment]
@cpanato please go ahead, nobody is working on it as far as I know. Thanks

**Comment by cpanato** [comment]
@nader-ziada cool, thanks, i will write some questions in the chat

**Comment by CecileRobertMichon** [comment]
/close

fixed in #721
