### ISSUE TITLE
Does not currently handle creating seperate route tables for node and contorl plane

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#718]
/kind bug

**What steps did you take and what happened:**
It is possible to set the the route table name on [control nodes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/api/v1alpha3/azurecluster_default.go#L76) and [nodes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/api/v1alpha3/azurecluster_default.go#L89) but only [the node route table ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/controllers/azurecluster_reconciler.go#L113) is created:

```golang
	rtSpec := &routetables.Spec{
		Name: r.scope.NodeSubnet().RouteTable.Name,
	}
	if err := r.routeTableSvc.Reconcile(ctx, rtSpec); err != nil {
		return errors.Wrapf(err, "failed to reconcile route table %s for cluster %s", r.scope.NodeSubnet().RouteTable.Name, r.scope.Name())
	}
```

If someone set both of these to something other than default they would run into issue on the control plane subnet reconciliation since the [subnet assumes route table is already created](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/cloud/services/subnets/subnets.go#L106).

**What did you expect to happen:**
Should reconcile the both route tables if this is possible or provide appropriate error messages/defaulting if over loading the defaults

**Anything else you would like to add:**
I am not 100% sure it makes sense to have two different route tables.  Need to look into it more.

**Environment:**

- cluster-api-provider-azure version: main branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
If we only want to allow one route table for now we could also add webhook validation that fails if route table is specified for a control plane subnet.

**Comment by nader-ziada** [comment]
> I am not 100% sure it makes sense to have two different route tables. Need to look into it more.

@jsturtevant I kind of changes to address this, should I go ahead and submit a PR for this? you mentioned you wanted to check if its needed, thanks

**Comment by jsturtevant** [comment]
Yes go for it. I have not had an opportunity to look into it
