### ISSUE TITLE
Remove usage of deprecated NewFakeClient in tests

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#726]
/kind bug

Some tests use `fake.NewFakeClient()` (eg. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/networkinterfaces/networkinterfaces_test.go#L584) which is deprecated:  `Deprecated: use NewFakeClientWithScheme. You should always be passing an explicit Scheme.`

This issue is to replace all occurrences of:

```
	client := fake.NewFakeClient(cluster)
```

in the codebase with:

```
	client := fake.NewFakeClientWithScheme(scheme.Scheme, cluster)
```

See https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/services/scalesets/vmss_test.go#L56 for an example of this being done.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vinu2003** [comment]
@CecileRobertMichon I can pick this up as part of my learning task and help.

**Comment by nader-ziada** [comment]
/close 
since the PR merged

**Comment by vinu2003** [comment]
@nader-ziada thanks for closing this.
