### ISSUE TITLE
Document and test use of ExternalDNS

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes-sigs/cluster-api-provider-azure#731]
/kind feature

**Describe the solution you'd like**
It should be documented, easy and tested to use [ExternalDNS on Azure](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md)

**Anything else you would like to add:**

**Environment:**

**Comment by CecileRobertMichon** [comment]
@craiglpeters would it be more appropriate to update the doc at https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md to be compatible with CAPZ (assuming no changes are required in CAPZ for compatibility)?
