### ISSUE TITLE
Add Events data for AzureMachineTemplate/AzureMachine resources

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#737]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When introspecting an `AzureMachineTemplate` resource type, underlying reconciliation events aren't bubbled up to the `AzureMachineTemplate` or `AzureMachine` resources. For example: 

```
$ k describe AzureMachineTemplate/francis-capz-control-plane | grep Events:
Events:                          <none>
```

and

```
$ k describe AzureMachine/francis-capz-md-0-7xfq7 | grep Events
Events:                      <none>
```

The example resource `francis-capz-control-plane` above has a non-working `vmSize` + `storageAccountType` combination. 

However, if you inspect the capz controller logs, we can see that there is an invalid VM spec and the machine will never successfully reconcile:

```
$ k logs capz-controller-manager-84bfdf8664-b4478 -n capz-system -c manager | grep StatusCode=400 | tail -n 1
E0626 21:10:29.831269       7 controller.go:247] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create VM francis-capz-control-plane-hjq4z : failed to reconcile virtual machine: cannot create VM: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidParameter\" Message=\"Requested operation cannot be performed because the VM size Standard_D2_v3 does not support the storage account type Premium_LRS of disk 'francis-capz-control-plane-hjq4z_OSDisk'. Consider updating the VM to a size that supports Premium storage.\" Target=\"osDisk.managedDisk.storageAccountType\""  "controller"="azuremachine" "request"={"Namespace":"default","Name":"francis-capz-control-plane-hjq4z"}
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
is this a duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/562?

**Comment by jackfrancis** [comment]
It's a more specific version of it, yeah. Do we want to make #562 an epic, and then do per-resource event bubbling in discrete issues?

**Comment by CecileRobertMichon** [comment]
Sure let's do that/ I'll mark this as help wanted since the description is more specific.

/good-first-issue
/help

**Comment by jroden** [comment]
Cool if I work on this issue? :smile:

**Comment by CecileRobertMichon** [comment]
@jroden go for it! Let us know if you need any pointers.

**Comment by jroden** [comment]
Thanks Cecile!

qq for anyone who may be able to clarify. I'm not sure if it makes sense to publish azureMachine events back to a template object.  The template could be used for multiple machines, so we would need to filter azureMachine reconcile errors based on if the root cause was due to a template misconfiguration.  Maybe my understanding is off? :smile: 

Thanks for the help!

**Comment by devigned** [comment]
@jroden, I think you are right on not publishing events back to the `AzureMachineTemplate`. I think you are right to say reconcile events should go on the `AzureMachine` resources.

If we do find there is an error in the template, then those errors should be added to the `AzureMachineTemplate`.
