### ISSUE TITLE
Add license header checks to the make check target

### ISSUE THREAD

**Issue by tariq1890** [kubernetes-sigs/cluster-api-provider-azure#75]
A check that validates that every go file has a license header.

For reference check : https://github.com/prometheus/prometheus/blob/7f7b21104734fd1c7a5d2b3bc812da96cd7c35a3/Makefile.common#L110

/good-first-issue

**Comment by Avni-Sharma** [comment]
I would like to work on this

**Comment by justaugustus** [comment]
Let's hold on this until I discover if there's already a canonical way for handling this.

**Comment by nikhita** [comment]
We have a script in k/k that can do this: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-boilerplate.sh.

I've added the script to cluster-api-provider-digital-ocean https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/111, so I can confirm this can be re-used in other repos too. :)

**Comment by justaugustus** [comment]
I'll pick this up
/assign

**Comment by justaugustus** [comment]
Prow, you crazy
/remove-help
/remove-good-first-issue
