### ISSUE TITLE
[help wanted] refactor remaining services following established pattern

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#757]
Following the pattern established in #716, we should refactor each service to follow the same pattern. Each service should have its own refactor PR to make reviewing easier. For example, network interfaces was already done in #742.

- [x] disks (@cpanato)

- [x] groups (@cpanato)

- [x] exp/managedclusters

- [ ] exp/agentpools

- [x]  public IPs (@CecileRobertMichon)

- [x] network interfaces (@CecileRobertMichon)

- [x] load balancers  (@CecileRobertMichon)

- [x] subnets (@cpanato)

- [x] virtual networks (@cpanato)

- [x] route tables (@nader-ziada)

- [x] inbound nat rules (@CecileRobertMichon)

- [x] role assignments (@CecileRobertMichon)

- [x]  resource skus (@alexeldeib)

- [x] securitygroups (@CecileRobertMichon)

- [x] exp/scalesets (@CecileRobertMichon)

- [x] virtualmachines (@CecileRobertMichon)

Let me know if you want to help with one of these in comments and I'll add your username next to it!

/help

**Comment by cpanato** [comment]
Can I take disks?

**Comment by cpanato** [comment]
Can I take `groups` ?

**Comment by cpanato** [comment]
@CecileRobertMichon can I take subnets?

**Comment by devigned** [comment]
@cpanato, go for it! I don't think anyone is working on it right now.

**Comment by cpanato** [comment]
ok, after the subnet i will take the virtual networks if that is fine

**Comment by cpanato** [comment]
going to work on `virtual networks`

**Comment by nader-ziada** [comment]
route tables is the last one without a name, I'll take that one

**Comment by CecileRobertMichon** [comment]
@alexeldeib changed resource skus to you since you have #783 open

**Comment by nader-ziada** [comment]
I can take that one after the existing "refactoring PRs" get merged

**Comment by nprokopic** [comment]
I can take exp/managedclusters.

**Comment by nader-ziada** [comment]
thanks @nprokopic

**Comment by nprokopic** [comment]
FYI I finally got to start with AKS refactoring (managed cluster and agent pools), started working on it this week.

**Comment by nprokopic** [comment]
FYI I started working on the final part of the refactoring - exp/agentpools.

**Comment by nprokopic** [comment]
We can also tick off exp/managedclusters.
