### ISSUE TITLE
Skip End to End tests if KUBECONFIG env variables are not specified

### ISSUE THREAD

**Issue by tariq1890** [kubernetes-sigs/cluster-api-provider-azure#76]
We need to skip e2e tests when the KUBECONFIG env var is not present. Please use `t.Skip()` for this.

This is the test that needs skipping: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/235e8beaacc05954ec3f25480c58e5f7756d0cab/test/e2e/e2e_test.go#L41

**Comment by himani93** [comment]
I would like to work on this if no one else is working on this. Thanks

**Comment by Avni-Sharma** [comment]
Hi there, PTAL https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/81

**Comment by Avni-Sharma** [comment]
I guess this issue needs to be closed since it has been merged now

**Comment by tariq1890** [comment]
Yes. Thank you!
