### ISSUE TITLE
[e2e] Collect cloud init logs for E2E workload clusters

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#761]
There have been quite a few E2E flakes lately but those are hard to investigate because most of them are due to a timeout waiting for control planes to join the cluster and there are no errors in controller logs.

Right now we only collect logs from the bootstrap cluster (that is what the CAPI test framework collects). We should also collect workload cluster logs.

For conformance tests, we have https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/hack/log/log-dump.sh#L88 to get the logs directly from VMs. An easy way to fix this would be to run the same thing in E2E.

Note: the CAPI test framework might be the best place to implement this.

**Comment by CecileRobertMichon** [comment]
cc @chewong @fabriziopandini

**Comment by fabriziopandini** [comment]
I'm definitely +1 to get this in the CAPI test framework

**Comment by nader-ziada** [comment]
This feature is coming from the CAPI e2e test framework

/close

**Comment by randomvariable** [comment]
0.3.10 has an interface to implement that you can pass to the test framework and it will gather logs for you https://github.com/kubernetes-sigs/cluster-api/blob/59faa7b1c63ba301cb780836891e7b10098fce34/test/framework/cluster_proxy.go#L81

Docker example in https://github.com/kubernetes-sigs/cluster-api/blob/7d0deb18b44305a993783b50d7e2ee458615ff3e/test/framework/docker_logcollector.go which is based on what CAPA is doing https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/test/e2e/common.go#L78

**Comment by mboersma** [comment]
Yep, I have that all scaffolded and working in CAPZ, just trying to figure out SSH proxy details to nodes. Hopefully I'll have a PR tomorrow.
