### ISSUE TITLE
Cluster teardown doesn't delete azure resources

### ISSUE THREAD

**Issue by dklyle** [kubernetes-sigs/cluster-api-provider-azure#775]
/kind bug

**What steps did you take and what happened:**
When tearing down a cluster, kubectl delete -f cluster.yaml does not properly bring down the cluster in azure. The move to clusterctl which combines all the base cluster config into one yaml file makes teardown not work. The separate yaml files for controlplane.yaml and cluster.yaml worked better. What **happens** instead is the controlplane nodes remain up and indeterminate amounts of the load balancer, etc get **deleted.**

Updating, even splitting the yaml file into cluster and controlplane components does not delete the controlplane nodes in Azure.

**What did you expect to happen:**
kubectl delete -f cluster.yaml should clean up the azure resources. Better yet is to have the controlplane and cluster definition in separate yaml files.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.4.3
- Kubernetes version: (use `kubectl version`): 1.17.4
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4

**Comment by CecileRobertMichon** [comment]
Will look into this. What error are you getting?

In the meantime, `kubectl delete cluster --all --wait=false` gets the job done (or `kubectl delete cluster <cluster-name> --wait=false` to delete a specific cluster)

**Comment by dklyle** [comment]
In the past, I've always used the yaml file for deleting, I will try `kubectl delete cluster`. Thanks
