### ISSUE TITLE
[e2e] Add more CAPI e2e test specs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#780]
Currently we are only running a few of the specs in https://github.com/kubernetes-sigs/cluster-api/tree/master/test/e2e as part of the CAPZ spec (see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/capi_test.go).

We should add as many of the test specs as possible and make sure they run successfully on CAPZ (some might need fixing some stuff before they can run).

note: to test in PR CI, use `/test pull-cluster-api-provider-azure-capi-e2e` and  set `GINKGO_FOCUS` to `Cluster API E2E tests` when testing locally.

**Comment by CecileRobertMichon** [comment]
@nader-ziada just fyi @devigned already enabled the self-hosted one in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/843/files#diff-cf63d4849f8ccd526cbe6e442ed9c72cR94, so you can focus on the others

**Comment by nader-ziada** [comment]
> @nader-ziada just fyi @devigned already enabled the self-hosted one in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/843/files#diff-cf63d4849f8ccd526cbe6e442ed9c72cR94, so you can focus on the others

I think its more involved than enabling it, the cluster on azure can't find the generated image and fails, but anyways will work on the other tests

**Comment by devigned** [comment]
@nader-ziada, as you point out, the pivot clusters fail b/c they run into an image backoff error due to the fact we are only pushing images into kind, and not to a remote repository. I'm taking a look at that right now.

**Comment by devigned** [comment]
@nader-ziada see #852
