### ISSUE TITLE
duplication of template between azure machine/machinepool

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#812]
/kind cleanup

**What steps did you take and what happened:**
Machine Pool has an Azure Machine Template which is nearly identical to the same templatized version provided by Azure Machine. The difference in fields is mostly things at the top level for the resource. We should try to consolidate and reuse this, it will also probably have a nice side effect of definable the "cloneable" portions of machine/machinepool.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/exp/api/v1alpha3/azuremachinepool_types.go#L27-L53

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/azuremachine_types.go#L33

**Comment by alexeldeib** [comment]
@devigned machine pool also doesn't have any fields for identity

**Comment by devigned** [comment]
@CecileRobertMichon correct me if memory fails me, but we were hoping to make this change with the next API version we cut, right?

The idea was to show how we'd like to break out the template with MachinePool and then port it back while adding identity to AzureMachine.

**Comment by CecileRobertMichon** [comment]
I think in the initial stages of implementing machine pool there was a choice that was made that vmss would have different capabilities as vms and so it made sense to have a different template? I added this issue to #618 so we can revisit as part of v1alpha4.

**Comment by CecileRobertMichon** [comment]
/remove-lifecycle stale

Not sure if we still want to do this?
