### ISSUE TITLE
expose cloud provider rate limiting configuration

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#815]
/kind feature

**Describe the solution you'd like**
The Azure cloud provider exposes a wide number of configuration fields: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#cloud-provider-config

Most of these can be derived from infrastructure specs in CAPZ. The significant outliers all are around the rate limiting configuration for the cloud provider. We should surface these to users in a reasonable way without requiring them to set the entire file.

One approach would be to allow the subset of the CloudProviderConfig struct relevant to rate limiting to be defined in a config map. We would merge any user provided values there over our own defaults when we build the configuration.

**Anything else you would like to add:**
Follow up to #802

**Comment by alexeldeib** [comment]
@marwanad any thoughts on this? would it be reasonable to just expose a config map for the rate limiting config?

**Comment by marwanad** [comment]
I'd say a configmap and merge with defaults is probably reasonable - yeah

**Comment by alexeldeib** [comment]
For comparison sake, we could also embed it directly into the spec as e.g. map[string]string{}

**Comment by nader-ziada** [comment]
would we want to expose all these values? https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/#per-client-rate-limiting

**Comment by CecileRobertMichon** [comment]
We could make this a 1.18+ feature only and support per-client rate limiting to avoid having to implement the old way of having global rate limit settings.

**Comment by dr0pdb** [comment]
busy for few weeks.

/unassign
