### ISSUE TITLE
Add cluster and machine actuators tests

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#82]
I did a bad thing in #68 and commented out the cluster and machine actuator tests, because the associated code had been fully refactored and the current code doesn't fit the old tests.

We've got to rewrite new tests ASAP.
/help
/priority critical-urgent
/cc @tariq1890 @soggiest

**Comment by awesomenix** [comment]
/assign @awesomenix

Already added cluster actuator test, working on machine actuator tests
