### ISSUE TITLE
Kubectl delete cluster keeps running indefinitely

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-azure#821]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

# kubectl delete clusters capi-quickstart --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
cluster.cluster.x-k8s.io "capi-quickstart" force deleted

Also running the original kubectl delete-f capi-quickstart.yaml does not delete the cluster for a long time

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
`kubectl delete -f cluster.yaml --wait=false` solves this issue

The reason it takes a long time is that it deletes the resources in Azure before returning success which could take a while. In the future, we have plans to move the Azure API calls to a separate infra controller and not block on long running operations (see https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/416), but we won't fix this for now.

/close
