### ISSUE TITLE
add network describer interface

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#824]
/kind cleanup

**Describe the solution you'd like**
This is a convenient way to allow for multiple infrastructure types to implement the necessary interfaces (ClusterDescriber and NetworkDescriber) to describe all required Azure infrastructure and secrets.

It's a stepping stone to removing AzureCluster from MachineScope, so MachineScope can use different Cluster/ControlPlane providers

**Anything else you would like to add:**
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/822#discussion_r459598656

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
/assign @alexeldeib 
/assign

Just assigning us for now so no one else starts working on it while we figure out how to minimize merge conflicts. If you don't open a PR for it, I can after I finish with VMs.
