### ISSUE TITLE
version for managed control plane should be normalized in webhook

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes-sigs/cluster-api-provider-azure#836]
/kind feature

**Describe the solution you'd like**

AzureManagedControlPlane should have the version normalized to handle https://github.com/kubernetes-sigs/cluster-api/pull/3147. 

We should add a defaulting webhook similar to machine to handle the normalization: https://github.com/CecileRobertMichon/cluster-api/blob/9aaae9f9b5152ed4dc8ce8f2fe6e51f8c6395a37/api/v1alpha3/machine_webhook.go#L60-L63

**Anything else you would like to add:**

We need to do something similar for MachinePool, but upstream in CAPI.

**Comment by alexeldeib** [comment]
ref https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/818 which is the current implementation of the same thing, but we should put this in a webhook

**Comment by CecileRobertMichon** [comment]
/help
/good-first-issue

webhook for managed control plane was added in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/862

**Comment by cpanato** [comment]
will take this
/assign
/remove-help
