### ISSUE TITLE
AzureMachine reconciler error patching condition

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#871]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Seeing intermittent error in capz controller logs:

```
E0811 16:54:30.919241       8 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error patching conditions: The condition \"Ready\" was modified by a different process and this caused a merge/ChangeCondition conflict:   \u0026v1alpha3.Condition{\n  \tType:               \"Ready\",\n- \tStatus:             \"Unknown\",\n+ \tStatus:             \"True\",\n  \tSeverity:           \"\",\n- \tLastTransitionTime: v1.Time{Time: s\"2020-08-11 16:54:18 +0000 UTC\"},\n+ \tLastTransitionTime: v1.Time{Time: s\"2020-08-11 16:54:30 +0000 UTC\"},\n  \tReason:             \"\",\n  \tMessage:            \"\",\n  }\n" "controller"="azuremachine" "name"="vmss-md-0-control-plane-8ztgd" "namespace"="default"
```

We should find out what are the two processes competing to update the ready condition.

**What did you expect to happen:**

No error in reconciler.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@nader-ziada any ideas?

**Comment by nader-ziada** [comment]
looking into it

/assign
