### ISSUE TITLE
Document installing OOT storage drivers

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#897]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
This [doc](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/book/src/topics/external-cloud-provider.md) already documents using the out of tree cloud provider. It should also document and provide an example template to install https://github.com/kubernetes-sigs/azurefile-csi-driver and https://github.com/kubernetes-sigs/azuredisk-csi-driver.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by cpanato** [comment]
I will try, but maybe will need some help from more experienced persons :) 
/assign
/remove-help
