### ISSUE TITLE
long wait in logs during reconcile

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-azure#902]
/kind bug

**What steps did you take and what happened:**

Seems like theres an unnaturally log silent phase during reconcile, 
```I0827 14:07:15.191566       1 azurecluster_controller.go:154] controllers/AzureCluster "msg"="Reconciling AzureCluster" "AzureCluster"="tkg-mgmt-azure" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
I0827 14:08:27.646433       1 azurecluster_controller.go:154] controllers/AzureCluster "msg"="Reconciling AzureCluster" "AzureCluster"="tkg-mgmt-azure" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
I0827 14:08:32.447450       1 azurecluster_controller.go:154] controllers/AzureCluster "msg"="Reconciling AzureCluster" "AzureCluster"="tkg-mgmt-azure" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
```
Which picks back up again  about 20 minutes later.. .

```
I0827 14:26:51.608396       1 helpers.go:281] controllers/AzureJSONTemplate "msg"="returning early from json reconcile, user provided secret already exists" "AzureMachineTemplate"="tkg-mgmt-azure-md-0" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
I0827 14:26:51.608682       1 helpers.go:281] controllers/AzureJSONTemplate "msg"="returning early from json reconcile, user provided secret already exists" "AzureMachineTemplate"="tkg-mgmt-azure-control-plane" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
I0827 14:27:46.054020       1 azurecluster_controller.go:154] controllers/AzureCluster "msg"="Reconciling AzureCluster" "AzureCluster"="tkg-mgmt-azure" "cluster"="tkg-mgmt-azure" "namespace"="tkg-system"
```

**What did you expect to happen:**

Probably some kind of status would print out at least every minute or so during creation of a management cluster from capz-controller-manager 

**Anything else you would like to add:**

This is relatively minor and i assume can be fixed just by adding a log statement somewhere in the control loop 

**Environment:**

- cluster-api-provider-azure version: 0.4.7

**Comment by ncdc** [comment]
The manager does a full resync every 10 minutes. If nothing is changing in etcd during those 10 minutes, you won't see anything logged, as the manager doesn't have any work to do. I'd suggest closing this.

**Comment by jayunit100** [comment]
hmmm ok, don;t know enough to debate this :) , typically w/ capa clusters im not used to seeing this kind of lag in log feedback, but will close anyways.

**Comment by devigned** [comment]
If nothing is changing and the logs keep spewing, that could be an indication of unnecessary work being done by the controller. CAPZ has suffered from inefficient watches and event cycles in the past, which are pernicious little bugs. 

If anyone notices continuous logs from controllers with nothing changing in the cluster, please open an issue.
