### ISSUE TITLE
Change AzureManagedCluster LoadBalancerSKU values to Uppercase

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#908]
/kind bug

To be consistent with Azure naming of Load Balancer SKUs (https://docs.microsoft.com/en-us/azure/load-balancer/skus, https://docs.microsoft.com/en-us/rest/api/load-balancer/loadbalancers/createorupdate#create-load-balancer-with-standard-sku) and with CAPZ AzureClusters, Load Balancer SKU values should be "Standard" and "Basic" (right now they are "standard" and "basic").

This is a breaking change and we should mark it as so but it's okay to make a breaking change at this point since AzureManagedCluster is still an experimental feature.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Evalle** [comment]
I think I can take care of it
/assign
