### ISSUE TITLE
Generate SSH key in AzureMachinePool and AzureManagedControlPlane defaulting webhook

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#909]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We should default `SSHPublicKey` for AzureMachinePool and AzureManagedControlPlane, like we do for AzureMachine: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/f8ca63979c28b5bc4d2d53c7a2cffd4d7edcbda4/api/v1alpha3/azuremachine_default.go#L29.

This should also include unit tests to validate the default functionality.

Then, change `sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64}` to `sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}` in the templates to make the value optional.

/help
/good-first-issue

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by cpanato** [comment]
I will take this since no one claims it :)

/assign
/remove-help

**Comment by cpanato** [comment]
off-topic question:
when we generate the ssh keys, should we store somewhere the private key?

**Comment by CecileRobertMichon** [comment]
> when we generate the ssh keys, should we store somewhere the private key?

right now the behavior for AzureMachines is to not store the private key since we don't know if the environment the cluster is being created from is shared/public. If the user would like to store the key, they should create their own and set it, or alternatively they can easily reset the key from the Azure Portal or Azure CLI after the VM is created. The defaulting is mostly provided as a convenience for users who do not want to set a key to make the key optional and set a random one on the vm.
