### ISSUE TITLE
Auto detect available flavors in Tilt

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#935]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, using cluster flavors as Tilt resources requires adding them to tile_config.json as described in https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/templates/flavors#from-tilt-config. Furthermore, this requires developers to remember adding new flavors to the config whenever a new template is added. 

Desired solution: By default, flavors are automatically fetched from the templates/flavors directory and added as tilt resources. If and only if `worker-flavors` is defined in tilt_config.json, then use that list as tilt resources (to allow overriding default flavors if you want a subset only).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
@CecileRobertMichon Just to understand the ask here, the Tiltfile uses the `templates/flavors` directory to add all the flavors as resources by default. And if the `worker-flavors` is provided instead, only flavors present in that list are added as tilt resources.

Another query that I have is, what is the significance of `templates-to-run`? I do not see any docs around it either.

**Comment by CecileRobertMichon** [comment]
@srm09 apologies I just saw your comment now when I was looking for the issue for #1040... There is also https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/937 which is similar if you want to work on that one

/assign
