### ISSUE TITLE
Update mdbook to v0.4.3

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#940]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
See https://github.com/kubernetes-sigs/cluster-api/pull/3659

/help
/good-first-issue

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
Hey 👀

**Comment by varunpurohit76** [comment]
can i take this up @CecileRobertMichon ?

**Comment by CecileRobertMichon** [comment]
@varunpurohit76 go for it! Thanks 🙂 

/assign @varunpurohit76
