### ISSUE TITLE
Support dynamic kubelet configuration

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes-sigs/cluster-api-provider-azure#944]
/kind feature

**Describe the solution you'd like**
Enable a cluster operator to dynamically change the kubelet configuration for a cluster https://kubernetes.io/blog/2018/07/11/dynamic-kubelet-configuration/

**Comment by craiglpeters** [comment]
The caveat - SIG Node is evaluating the fate of this feature

**Comment by CecileRobertMichon** [comment]
@craiglpeters this is probably a better issue for kubeadm

**Comment by CecileRobertMichon** [comment]
As far as I can tell it has been there for a while https://github.com/kubernetes/kubernetes/pull/65576

/close
