### ISSUE TITLE
DNS name conflict for cluster with same name across different subscriptions 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-azure#958]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- created a cluster with name `cluster1` in subscription 1234....
- a pubic ip with the name `pip-cluster1-node-outbound` is generated and has a dns record
- I create another cluster with the same name in a different subscription
- get an error
```
E0923 17:37:15.979213       1 controller.go:248] controller-runtime/controller “msg”=“Reconciler error” “error”=“failed to reconcile cluster services: failed to reconcile public IP: cannot create public IP: network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\“DnsRecordInUse\” Message=\“DNS record pip-cluster1-node-outbound.eastus.cloudapp.azure.com is already used by another public IP.\” Details=[]” “controller”=“azurecluster” “name”=“cluster1” “namespace”=“default”
I0923 17:37:15.979904       1 azurecluster_controller.go:154] controllers/AzureCluster “msg”=“Reconciling AzureCluster” “AzureCluster”=“cluster1” “cluster”=“cluster1” “namespace”=“default”
```

**What did you expect to happen:**
- expected clusters with the same name to work across different subscriptions 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: master as of `cd8f5e7ee5f8abf4b4923409e3f74f1bcbe078e2`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
Indeed, the DNS name must be unique within the Azure location you create the name in (across all subscriptions and all customers) - https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-public-ip-address

[We're not setting a DNS name](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/scope/cluster.go#L110) for the outbound IP so I think a fix would be to define it as a hash sum just like we do for the API Server IP: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azurecluster_reconciler.go#L148

The main issue is that this name needs to be defined once and then stay the same during the cluster's lifetime so it either needs to be a deterministic hash that is unique enough (combination of cluster name, subID, resource group maybe?) or we need to store the value in the Status like we do for the API server IP and only set it if it's unset.
