### ISSUE TITLE
Add support for managed identity with AzureMachinePool

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#960]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/312 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/616 added support for Azure Managed identities for AzureMachines. We should port the changes to AzureMachinePool to allow VMSS using MSI.

This will become especially useful if/when we add support for VMSS control planes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shysank** [comment]
@CecileRobertMichon Is someone working on this? If not, can I take this one?

**Comment by CecileRobertMichon** [comment]
@shysank nope, go for it! You can comment `/assign` to assign yourself.

Let @nader-ziada or I know if you need any guidance.
