### ISSUE TITLE
Create v1alpha4 API types

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api-provider-azure#961]
Tracking issue to generate v1alpha4 Cluster API types.

- change imports to use v1alpha4
- set storage version to v1alpha4 types
- remove old v1alpha2 types and conversion webhooks if necessary.

For reference: https://github.com/kubernetes-sigs/cluster-api/issues/3428

/kind api-change
/area provider/azure
/cc @nader-ziada

**Comment by nader-ziada** [comment]
I will start working on this in a branch so we are ready!

/assign
