### ISSUE TITLE
Document versioning and release process

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#97]
ref: #92
/milestone baseline 
/assign

**Comment by chuckha** [comment]
Awesome, we have a doc in aws: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/releasing.md and an open issue in cluster-api: https://github.com/kubernetes-sigs/cluster-api/pull/768#pullrequestreview-209793027. There is also this document that I'm hoping will get us closer to a uniformish release process across providers: https://docs.google.com/document/d/17tY88ysZPDH2rZ9BkewPxETViqivdWDJPrVl_P1TpLg/edit would love y'alls feedback on this!

**Comment by justaugustus** [comment]
Thanks for the deets, @chuckha! I'm watching the capi issue and will provide some feedback on the Google Doc when I have a moment.

We're happy to follow the capa release process and I've created a PR to document that: #117
