### ISSUE TITLE
Document the different Azure identities, rights and use cases 

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/cluster-api-provider-azure#992]
/kind feature

**Describe the solution you'd like**
Cluster API Provider Azure has a complex set of identities, rights and use cases which are not easily understood by the naive observer. Perhaps, we could start by documenting the following:
- **CAPZ controller:** the identity used to provision infrastructure in Azure
  - Env config
    - Service Principal
  - Multi-tenant config
    - AAD Pod Identity using Service Principals and Managed Identities
- **Azure Host Identity:** the identity assigned to the Azure host which in the control plane provides the identity to Azure Cloud Provider, and can be used on all nodes to provide access to Azure services during cloud-init, etc.
  - Service Principal
  - System Assigned Identity
  - User Assigned Identity
- **Pod Identity:** identity used by pods running within the workload cluster to provide access to Azure services during runtime. For example, to access blobs stored in Azure Storage or to access Azure database services.
  - AAD Pod Identity: Service Principals and Managed Identities

cc @jackfrancis

**Comment by jsturtevant** [comment]
@paulbouwer You've been looking to some of these different identities, do you have any relevant documentation that you might be able to help out with?

**Comment by paulbouwer** [comment]
@jsturtevant - we don't have anything in a state that is ready to share at the moment. But happy to contribute to the docs with positioning and guidance we've been working on.
