### ISSUE TITLE
Update kind to more recent version

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#994]
/kind cleanup

**Describe the solution you'd like**

In development.md, we recommend installing "kind 0.7.0," and we have a specific SHA of sigs.k8s.io/kind vendored in at 0.7.1. Those versions are both pretty old, but may be pinned by a transitive dependency through CAPI.

We should investigate whether we can update `kind` to a more recent version (currently 0.9.0 is the latest). See [this comment](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/976#issuecomment-708033180) for more context.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nader-ziada** [comment]
had to update the kind version as part of the v1alpha4 types PR #1144 

/assign

**Comment by nader-ziada** [comment]
kind updated to v0.9.0 as part of v1alpha4 PR #1144 

closing
