### ISSUE TITLE
Add Azure boot diagnostics as an e2e log collection strategy

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#997]
/kind feature

**Describe the solution you'd like**

While the implementation of the CAPI e2e test framework `ClusterLogCollector` in #976 is working, it relies on SSH connectivity. Sometimes that [fails](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/988/pull-cluster-api-provider-azure-e2e/1316355750150279168), which is unfortunate because those cases are more likely to have logs of interest.

Perhaps the e2e log collector could have a fallback strategy that does the equivalent of `az vm boot-diagnostics get-boot-log`, or maybe even use the serial console to collect the expected set of logs.

Failing that, it might be worth adding retry code around the `Dial` calls in the test helper func `execOnHost`.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
On recent runs (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/974/pull-cluster-api-provider-azure-e2e/1321918203156238336) I've noticed it doesn't get logs successfully for vmss nodes or when the cluster provisioning timed out (eg 2 out of 3 nodes up after 1200s).

**Comment by mboersma** [comment]
The e2e framework doesn't handle MachinePools yet, so that explains the VMSS node issue. (We should add that.)
